### ISSUE TITLE
[Uno] A referenced assembly was compiled with a newer .NET version

### ISSUE THREAD

**Issue by morning4coffe-dev** [beto-rodriguez/LiveCharts2#1002]
**Describe the bug**

When using the most recent version of LiveCharts and Default Uno .NET 7 template I get this error: `error NETSDK1148: A referenced assembly was compiled using a newer version of Microsoft.Windows.SDK.NET.dll. Please update to a newer .NET SDK in order to reference this assembly.`

**To Reproduce**
1. Create new Uno Project
2. Use the Default template
3. Add LiveCharts
4. Run the project

**Package Versions**
.NET 7.0.203
LiveChartsCore.SkiaSharpView.Uno.WinUI 2.0.0-beta.703
Microsoft.WindowsAppSDK 1.2.230313.1
Uno.WinUI 4.8.33

**Comment by beto-rodriguez** [comment]
Hi! I am not sure what causes this issue but notice that on the Uno template has a workaround for this issue.

Notice I also faced this issue while building the latest package and was able to fix it by following the Uno guide.

Just go to *.Windows project and look for the workaround there, your project will also contains [this](https://github.com/beto-rodriguez/LiveCharts2/blob/master/samples/UnoPlatformSample/UnoPlatformSample.Windows/UnoPlatformSample.Windows.csproj#L51) message.

**Comment by morning4coffe-dev** [comment]
Thanks for the quick reply! I forgot to mention, I have already tried this workaround yesterday. While it does successfully build the Windows target, unfortunately, the other targets still fail to build for me.

**Comment by morning4coffe-dev** [comment]
Update: After updating to v2.0.0-beta.710 and our latest Uno Extension, creating a new project and uncommenting the mentioned lines in both `*.Windows.csproj` and the class library `*.csproj` it works!

**Comment by beto-rodriguez** [comment]
Than
