### ISSUE TITLE
Update Nuget

### ISSUE THREAD

**Issue by gktval** [beto-rodriguez/LiveCharts2#1004]
I am following the instructions for downloading the Nuget for .Net Maui. I have tried 

```dotnet add package LiveChartsCore.SkiaSharpView.Maui --version 2.0.0-beta.710```

according to the Nuget website and also tried searching for ```LiveChartsCore.SkiaSharpView.Maui``` without success.

Can you kindly point me in the right direction?
Thanks

**Comment by beto-rodriguez** [comment]
Hi, currently the latest version of LiveCharts is beta, so you must use the `–prerelease` option. 

I did not tested it but I think that this should work:

`dotnet add package LiveChartsCore.SkiaSharpView.Maui --version 2.0.0-beta.710 –prerelease`
