### ISSUE TITLE
The X-axis and Y-axis coordinates of LiveCharts2 can be displayed normally under Windows, but the X-axis and Y-axis is not displayed under Linux. How can I solve this problem

### ISSUE THREAD

**Issue by liliangsen** [beto-rodriguez/LiveCharts2#1013]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by beto-rodriguez** [comment]
Hi, which framework are you using? is it aAvalonia? Uno? ETO?

**Comment by liliangsen** [comment]
> 嗨，您使用的是哪个框架？是阿瓦洛尼亚吗？乌诺？环氧乙烷？

I am using Avalonia and I have resolved this issue. Thank you for your reply

**Comment by liliangsen** [comment]
> > 嗨，您使用的是哪个框架？是阿瓦洛尼亚吗？乌诺？环氧乙烷？
> 
> 我正在使用阿瓦隆尼亚，我已经解决了这个问题。感谢您的回复

I also want to ask if the line color of line chart can be changed dynamically in Avalonia

**Comment by beto-rodriguez** [comment]
Hello, yes, the colors can be changed, please check out the docs and let me know if something is not clear or you face a new issue.

**Comment by SummerCSharp** [comment]
你是如何解决这个问题的  我也遇到这个问题了
