### ISSUE TITLE
Get Mouse click Item 

### ISSUE THREAD

**Issue by xtz0602** [beto-rodriguez/LiveCharts2#1014]
![1](https://github.com/beto-rodriguez/LiveCharts2/assets/106213402/56e0fb3b-341c-4ef1-8cdc-2750b42b2b95)
I have a barCharts and DataGrid . How can I know mouse click which one(C1,C2,C3)?
 I want to get like datagrid selectItem function and I can in viewModel bind selectItem 
 The table changes with mouse selection
I English is so bad, im so sorry   

My xaml 
<UserControl x:Class="iManager_wpf.View.Control.BarChartControl"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" 
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008" 
             xmlns:local="clr-namespace:iManager_wpf.View.Control" 
             xmlns:model="clr-namespace:iManager_wpf.ViewModel.Control"
       
  

             xmlns:prism="http://prismlibrary.com/"
             prism:ViewModelLocator.AutoWireViewModel="True"
             
           xmlns:oxy="http://oxyplot.org/wpf" xmlns:lvc="clr-namespace:LiveChartsCore.SkiaSharpView.WPF;assembly=LiveChartsCore.SkiaSharpView.WPF"
             mc:Ignorable="d" 
             d:DesignHeight="1030" d:DesignWidth="1920">

    <Grid>
        <Grid.RowDefinitions>
            <RowDefinition Height="100"/>
            <RowDefinition />
            <RowDefinition />
            <RowDefinition />

        </Grid.RowDefinitions>
        
        <Label>Bar Chart Test</Label>

        <lvc:CartesianChart Grid.Row="1"
                             
        Series="{Binding BarSeries}"
        XAxes="{Binding BarXAxes}"
                           
        LegendPosition="Right">
        </lvc:CartesianChart>

        <DataGrid Grid.Row="2"                   
             AlternatingRowBackground="#b8c7cf"
                                AutoGenerateColumns="False"
                                Background="Transparent"
                                BorderBrush="#61648A93"
                                BorderThickness="0"
                                CanUserAddRows="False"
                                ColumnHeaderHeight="36"
                                FontSize="18" 
                                VerticalScrollBarVisibility="Auto"
                                Foreground="Black"
                                GridLinesVisibility="Vertical"
                                IsReadOnly="True"
                               
                                CanUserSortColumns="true"   
                                SelectionMode="Extended"
                                SelectionUnit="Cell"
             ItemsSource="{Binding DataGrid}"
             
                  >
            <DataGrid.ColumnHeaderStyle>
                <Style TargetType="DataGridColumnHeader">
                    <Setter Property="HorizontalContentAlignment" Value="center" />
                    <Setter Property="BorderBrush" Value="#80A4AB" />
                    <Setter Property="BorderThickness" Value="0,0,0,3" />
                </Style>
            </DataGrid.ColumnHeaderStyle>

            <DataGrid.Columns>

                <DataGridTemplateColumn Width="*" Header="Name">
                    <DataGridTemplateColumn.CellTemplate>
                        <DataTemplate>
                            <Label
                                HorizontalContentAlignment="Center"
                                VerticalContentAlignment="Center"
                                Content="{Binding Name}"
                                FontSize="20"
                                Foreground="#D1000000" />
                        </DataTemplate>
                    </DataGridTemplateColumn.CellTemplate>
                </DataGridTemplateColumn>

                <DataGridTemplateColumn Width="*" Header="ErrorInfo">
                    <DataGridTemplateColumn.CellTemplate>
                        <DataTemplate>
                            <Label
                                HorizontalContentAlignment="Center"
                                VerticalContentAlignment="Center"
                                Content="{Binding ErrorInfo}"
                                FontSize="20"
                                Foreground="#D1000000" />
                        </DataTemplate>
                    </DataGridTemplateColumn.CellTemplate>
                </DataGridTemplateColumn>

            </DataGrid.Columns>
        </DataGrid>
        
        

    </Grid>
</UserControl>

My ViewModel

using LiveChartsCore;
using LiveChartsCore.Measure;
using LiveChartsCore.SkiaSharpView;
using LiveChartsCore.SkiaSharpView.Painting;
using Prism.Commands;
using Prism.Mvvm;
using SkiaSharp;
using SqlSugar;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Diagnostics;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace iManager_wpf.ViewModel.Control
{
    public class BarChartControlViewModel : BindableBase
    {
        private ObservableCollection<ISeries> _barSeries;
        public ObservableCollection<ISeries> BarSeries
        {
            get { return _barSeries; }
            set { _barSeries = value; RaisePropertyChanged(); }
        }

        private ObservableCollection<Axis> _barXAxes;
        public ObservableCollection<Axis> BarXAxes
        {
            get { return _barXAxes; }
            set { _barXAxes = value; RaisePropertyChanged(); }
        }

        public BarChartControlViewModel()
        {
            BarSeries = new ObservableCollection<ISeries>();
            BarXAxes = new ObservableCollection<Axis>();
            DataGrid = new ObservableCollection<TestInfo>();
            InitCharts();
            InitDataGrid();

        }

        private void InitDataGrid()
        {

            DataGrid.Add(new TestInfo() { Name = "C1", ErrorInfo = "AAA" });
            DataGrid.Add(new TestInfo() { Name = "C1", ErrorInfo = "AAB" });
            DataGrid.Add(new TestInfo() { Name = "C1", ErrorInfo = "AAC" });
        }

        private ObservableCollection<TestInfo> dataGrid;
        public ObservableCollection<TestInfo> DataGrid
        {
            get { return dataGrid; }
            set { dataGrid = value; RaisePropertyChanged(); }
        }

        private void InitCharts()
        {
            var temp = new ISeries[] {

                     new ColumnSeries<double>
                    {
                        Name="success",
                        Values = new double[] { 2, 5, 4 },
                        DataLabelsPosition = DataLabelsPosition.Top,
                        DataLabelsSize = 14,
                        DataLabelsPaint = new SolidColorPaint(new SKColor(50, 50, 50)),

                    },
                      new ColumnSeries<double>
                    {

                        Name="Error",
                        Values = new double[] { 3, 1, 6 },
                        DataLabelsPosition = DataLabelsPosition.Top,
                        DataLabelsSize = 14,
                        DataLabelsPaint = new SolidColorPaint(new SKColor(50, 50, 50)),

                    }
                };
            BarSeries.AddRange(temp);

            var tempAxis = new Axis[] {
                new Axis {
                    UnitWidth= 0.7,
                        Labels =new string[] { "C1", "C2", "C3" },
                        LabelsPaint = new SolidColorPaint
                        {
                            Color = new SKColor(50, 50, 50),
                            SKTypeface = SKTypeface.FromFamilyName("Microsoft YaHei")
                        },

                    }
                };

            BarXAxes.AddRange(tempAxis);
        }
    }

    public class TestInfo : BindableBase
    {
        private string name;
        public string Name
        {
            get { return name; }
            set { name = value; RaisePropertyChanged(); }
        }
        private string errorInfo;
        public string ErrorInfo
        {
            get { return errorInfo; }
            set { errorInfo = value; RaisePropertyChanged(); }
        }
    }
}

**Comment by xtz0602** [comment]
I use to wpf  
.netFramework4.7.2 
prism

**Comment by beto-rodriguez** [comment]
Hello, there are multiple ways to do this.

1. using the events defined in the library: https://lvcharts.com/docs/WPF/2.0.0-beta.710/samples.events.cartesian
2. using the events defined in WPF (or any other framework) and then using the chart function to get the element that was clicked: https://github.com/beto-rodriguez/LiveCharts2/issues/423#issuecomment-1575639884

Please give it a try to one alternative ald feel free to open a new issue if you find something that is not working as documented.
