### ISSUE TITLE
Please tell me how to Fix XAxes in realTime 

### ISSUE THREAD

**Issue by hancheong** [beto-rodriguez/LiveCharts2#1016]
I Set MinLimit, MaxLimit, MinStep but XAxes Slide for left.

`  Setting XAxes
 public  Axis[] XAxes { get; set; } =
           
        {
            new Axis
            {
                Labeler = value => value.ToString("F0"),

                MinStep = 1,
                MaxLimit = 5,
                ForceStepToMin = true,
                MinLimit = 0,
                UnitWidth = 1,
                EasingFunction = EasingFunctions.ElasticInOut,
                SeparatorsPaint = new SolidColorPaint(SKColors.LightSlateGray) { StrokeThickness = 1  },
                AnimationsSpeed = TimeSpan.FromMilliseconds(0)
            }
        }; 
`

`Limit Method
public void SetLimit(Double diff)
        {
          
            if (diff > 100)
            {
              
                XAxes[0].MaxLimit = diff;
                XAxes[0].MinStep = (100) / 5;
                XAxes[0].MinLimit = diff-100;
   
            }
            else if (diff > 6)
            {
          
                XAxes[0].MaxLimit = diff;
                XAxes[0].MinStep = diff / 5;
            }
        }
`
I want to this 
https://raw.githubusercontent.com/Live-Charts/WebSiteDocs/master/v1/Resources/constant.gif

but My result this
https://youtu.be/LIeGVyRS3M8

**Comment by beto-rodriguez** [comment]
This is already supported in the latest NuGet version, here is an example (it will be added to the website):

https://github.com/beto-rodriguez/LiveCharts2/blob/dev/samples/ViewModelsSamples/General/RealTime/ViewModel.cs

![realtime](https://github.com/beto-rodriguez/LiveCharts2/assets/10853349/90b0d7c9-b809-4e8c-b8a0-89f427abb599)
