### ISSUE TITLE
Unable to display emojis in charts

### ISSUE THREAD

**Issue by Bebz0r** [beto-rodriguez/LiveCharts2#1022]
I'm trying to display a pie chart for the most emojis used in a WhatsApp conversation, but the emojis are not displayed.

To Reproduce :
```
    protected override void OnAppearing()
    {
        base.OnAppearing();

        // Pie Chart Series
        ObservableCollection<ISeries> SeriesChart = new ObservableCollection<ISeries>();

        PieSeries<double?> aSeries;

        aSeries = new PieSeries<double?> { Values = new List<double?> { 10 }, Name = "Value 1" };
        SeriesChart.Add(aSeries);

        aSeries = new PieSeries<double?> { Values = new List<double?> { 5 }, Name = "Value 2" };
        SeriesChart.Add(aSeries);

        aSeries = new PieSeries<double?> { Values = new List<double?> { 5 }, Name = "Emoji 😉 (Not Working)" };
        SeriesChart.Add(aSeries);

        // UI : Bind the chart
        crtPieEmojisSent.Series = SeriesChart;
    }
```

Expected behavior : 
Emoji should be shown, but it's displayed as a little box

I guess it may be something to the font used (just like the chinese / japanese 'issues' I read about on the repo), but it wasn't clear to me how to change the font and/or if it was the same thing.

**Comment by beto-rodriguez** [comment]
Hi, you need to find a font that supports emojis. this needs better docs.

**Comment by Bebz0r** [comment]
Thanks for your reply @beto-rodriguez !
I read the docs but wasn't able to find how to change fonts for various elements of the graphs (datalabel and axis), do you have the code to do that ?
Cheers !
Beb

**Comment by beto-rodriguez** [comment]
From the SkiaSharp repo, this should work:

https://github.com/mono/SkiaSharp/issues/232

**Comment by Bebz0r** [comment]
Thanks, it worked !
Working code below :
Two drawbacks I found :
- I'm stuck with a specific font, If I want to have emojis with a comic sans, I don't know how to do that
- Oddly enough, if I used the same SolidColorPaint variable for legend and tooltip, when I hover my mouse on the tooltip, the legend goes blank. I have to define two SolidColorPaint, hence the two variables tooltipFont and legendFont

```
    protected override void OnAppearing()
    {
        base.OnAppearing();

        // Pie Chart Series
        ObservableCollection<ISeries> SeriesChart = new ObservableCollection<ISeries>();

        PieSeries<double?> aSeries;

        aSeries = new PieSeries<double?> { Values = new List<double?> { 10 }, Name = "Value 1" };
        SeriesChart.Add(aSeries);

        aSeries = new PieSeries<double?> { Values = new List<double?> { 5 }, Name = "Value 2" };
        SeriesChart.Add(aSeries);

        aSeries = new PieSeries<double?> { Values = new List<double?> { 5 }, Name = "Emoji 😍 (Not Working)" };
        SeriesChart.Add(aSeries);

        // EMOJI SUPPORT
        SolidColorPaint legendFont = new SolidColorPaint
        {
            Color = new SKColor(0, 0, 0),
            // from https://github.com/beto-rodriguez/LiveCharts2/issues/1022
            // Search for a font that support an emoji - here, rocket 0x1F680
            SKTypeface = SKFontManager.Default.MatchCharacter(0x1F680)
        };

        SolidColorPaint tooltipFont = new SolidColorPaint
        {
            Color = new SKColor(0, 0, 0),
            SKTypeface = SKFontManager.Default.MatchCharacter(0x1F680)
        };

        crtPieEmojisSent.TooltipTextPaint = tooltipFont;
        crtPieEmojisSent.LegendTextPaint = legendFont;

        // UI : Bind the chart
        crtPieEmojisSent.Series = SeriesChart;
    }
```

**Comment by jawinchen** [comment]
Hello,

I'm using uno wasm and livecharts2 for my new project. I use SKFontManager.Default.MatchCharacter("") to show some chinese text. But it seems fail and show one square block. Anyone can help? Plz.
