### ISSUE TITLE
Include VisualElements in SKCartesianChart by default

### ISSUE THREAD

**Issue by SailDev** [beto-rodriguez/LiveCharts2#1029]
**Is your feature request related to a problem? Please describe.**
When generating an image from a chart, i could not see any VisualElements.

**Describe the solution you'd like**
I would like to see any Visuals in the generated image by default.

```
    public SKCartesianChart(ICartesianChartView<SkiaSharpDrawingContext> view) : this()
    {
        XAxes = view.XAxes;
        YAxes = view.YAxes;
        Series = view.Series;
        Sections = view.Sections;
        DrawMarginFrame = view.DrawMarginFrame;
        LegendPosition = view.LegendPosition;
        Title = view.Title;

        // Change
        VisualElements = view.VisualElements;
    }
```
**Workaround**
```
var skChart = new SKCartesianChart(chart) 
{
    Width = 2000,
    Height = 1000,
    VisualElements = chart.VisualElements
};
```

**MANY THANKS FOR THIS AWESOME LIBRARY!**

**Comment by beto-rodriguez** [comment]
Thanks for the report, the referenced commit fixes that and will be included in the next version of the library.
