### ISSUE TITLE
labeler format incorrectly formatting for date time input

### ISSUE THREAD

**Issue by AaranGicquel** [beto-rodriguez/LiveCharts2#1030]
**Date Time labels are producing labels with impossible times and years.**

![Screenshot_20230530-130137](https://github.com/beto-rodriguez/LiveCharts2/assets/38384011/119b7c68-2432-42fe-aaa1-55f22d4e3fe6)

` [RelayCommand]
    public async Task ChartSensorDataPointsAsync()
    {
        if (IsBusy) return;

        try
        {
            IsBusy = true;

            var seriesValues = new List<ObservablePoint>();
            

            foreach (var dataPoint in SensorData)
            {
                if (dataPoint.DateTime > DateTime.Now - SelectedTime.Value)
                {
                    var _date = dataPoint.DateTime.ToOADate();
                    double sensorValue = dataPoint.SensorValue;
                    seriesValues.Add(new ObservablePoint(_date, sensorValue));
                }
            }

            _series.Values = seriesValues;
            _series.Name = Sensor.DisplayChannelName;
           _series.TooltipLabelFormatter = point => $"{point.SecondaryValue.ToString(DateTime.FromOADate(point.SecondaryValue).ToString("g"))} - {point.PrimaryValue.ToString("0.##")}:{Sensor.Uom}";
            
            SensorDataISeries = new ISeries[]
                {
                    _series
                };
        }
        catch (Exception ex)
        {
            Console.WriteLine(ex);
        }
        finally { IsBusy = false; }
        
    }

 [ObservableProperty]
    public List<Axis> xAxes = new List<Axis>{
        new Axis
        {
            NameTextSize = 40,
            TextSize = 30,
            Name = "Sensor Reading Time",
            Labeler = (Value) => Value.ToString(DateTime.FromOADate(Value).ToString("g")),
            LabelsRotation = 60,
            UnitWidth = TimeSpan.FromDays(1).Ticks,
        }
    }; `

Values for sensor Dates is coming from my api as a datetime value like this.
![image](https://github.com/beto-rodriguez/LiveCharts2/assets/38384011/6a9378fd-c3a1-4547-a65d-5939d76b42e0)

**Desktop **
 -.net maui, visual studio 22
 - Android 12.0 Samsung

**Comment by beto-rodriguez** [comment]
Hi, it seems that `FromOADate` is not the same as `DateTime.Ticks` this is why you are getting this error. The library internally uses `DateTime.Ticks` if you need/require to use OADate you must register a custom tipe.

**Comment by AaranGicquel** [comment]
> Hi, it seems that `FromOADate` is not the same as `DateTime.Ticks` this is why you are getting this error. The library internally uses `DateTime.Ticks` if you need/require to use OADate you must register a custom tipe.

Thanks for the info, Any suggestions on using DateTime.Ticks?

**Comment by AaranGicquel** [comment]
Thanks for the information, Managed to change to Ticks and works as intended



` foreach (var dataPoint in SensorData)
            {
                if (dataPoint.DateTime > DateTime.Now - SelectedTime.Value)
                {
                    var _date = dataPoint.DateTime.Ticks;
                    double senV = dataPoint.SensorValue;
                    seriesValues.Add(new ObservablePoint(_date, senV));
                }
            }


            _series.Values = seriesValues;
            _series.Name = Sensor.DisplayChannelName;
           _series.TooltipLabelFormatter = point => $"{new DateTime((long)point.SecondaryValue).ToString("g")} - {point.PrimaryValue.ToString("0.##")}:{Sensor.Uom}";`

**Comment by AaranGicquel** [comment]
Thanks Again
