### ISSUE TITLE
The Name of the Series does not support Chinese and displays garbled code

### ISSUE THREAD

**Issue by 285984303** [beto-rodriguez/LiveCharts2#1035]
**Describe the bug**
The Name of the Series does not support Chinese and displays garbled code

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
The Name of the Series does not support Chinese and displays garbled code

**Comment by beto-rodriguez** [comment]
Please take a look at #931, there you can find a solution for the issue, this will also have better docs/support in a future.

**Comment by 285984303** [comment]
OK
