### ISSUE TITLE
How do livecharts disable mouse scrolling and scaling events?

### ISSUE THREAD

**Issue by 285984303** [beto-rodriguez/LiveCharts2#1038]
How do livecharts disable mouse scrolling and scaling events?

**Comment by beto-rodriguez** [comment]
Hi, do you mean the [zooming and panning](https://lvcharts.com/docs/WPF/2.0.0-beta.710/samples.lines.zoom) features?

**Comment by 285984303** [comment]
Yes

**Comment by beto-rodriguez** [comment]
There is a zooming option that disables zooming, please take a look at the docs and let me know if something is not working as the docs state:

https://lvcharts.com/docs/WPF/2.0.0-beta.710/CartesianChart.Cartesian%20chart%20control#zooming-and-panning
