### ISSUE TITLE
 Chart point with the closest x value to that of the mouse pointer

### ISSUE THREAD

**Issue by ts-research7** [beto-rodriguez/LiveCharts2#1042]
I created a line series. When the mouse pointer moves horizontally on the Cartesian chart, I want to obtain the chart point with the closest x value to that of the mouse pointer because I need to draw the cross-hair lines and the tangent line that pass through the point. In addition, I need to display the x, y values of the chart point.
To achieve this, I tried choosing CompareOnlyXTakeClosest for TooltipFindingStrategy and utilizing the ChartPointPointerHover event. However, it didn't work. When the mouse pointer is at (4, 2), (3.7, 5.4) is highlighted as shown, not (4, 6.1) because 
the former is the closest to (4, 2).
Is there an easy way to achieve this? Or do I have to use UIElement.MouseMove event, scale the mousepointer point in pixels to the chart data scale, and then search for the point with the closest x value to that of the mouse pointer on the line series?
![lineSeries](https://github.com/beto-rodriguez/LiveCharts2/assets/66772163/c9e8767c-903f-4070-b83d-1f4f9c5d8e88)

**Comment by beto-rodriguez** [comment]
Hi, this is an interesting example.

> To achieve this, I tried choosing CompareOnlyXTakeClosest for TooltipFindingStrategy and utilizing the ChartPointPointerHover event

This makes a lot of sense for me, I think that what you tried makes sense, if the `TooltipFindingStrategy ` is called `CompareOnlyXTakeClosest`, then it must only compare the X axis, it is currently calculation the hypotenuse to the points but that seems wrong IMO, in this option in must only use the X coordinate.

Finally the alternative you mentioned is a good way to go, but I think that the library could do more for you here, I will mark this as a bug for now.

**Comment by beto-rodriguez** [comment]
After a second think..  I am afraid that this should be implemented on your side, that method is used internally to get the points for the tooltips, you can use the chart mouse move event to get the coordinate.

This is an untested method that I think that could work for you:

```c#
var closestOnX = mySeries.Fetch(chart)
    .Select(x => new
    {
        distance = Math.Abs(x.Coordinate.SecondaryValue - pointerPosition.X),
        point = x
    })
    .OrderBy(x => x.distance)
    .SelectFirst(x => x.point);
```
