### ISSUE TITLE
Local Mappers do not work for null values / IChartEntity is undocumented

### ISSUE THREAD

**Issue by mark-monteiro** [beto-rodriguez/LiveCharts2#1043]
**Describe the bug**
Consider this custom model used for a series on a cartesian chart. Notice that the value is nullable (for adding null points to the chart).

```cs
public record StaticDateTimePoint(DateTime DateTime, double? Value); 
```

Previously you could add a mapper like this to handle this model:

```cs
    public static LiveChartsSettings AddMappers(this LiveChartsSettings config) 
    { 
        return config.HasMap<StaticDateTimePoint>((model, point) => { 
            if (model.Value is null) { 
                point.IsNull = true; 
                return; 
            } 
 
            point.IsNull = false; 
            point.PrimaryValue = model.Value.Value; 
            point.SecondaryValue = model.DateTime.Ticks; 
        }); 
    } 
```

However, in version 2.0.0-beta.361 the `IsNull` property has become read-only, and any other approach to setting the point to empty also appear to be read-only (i.e. `point.IsEmpty`, `point.Context.Entity.Coordinate`, `point.Context.Entity.Coordinate.IsEmpty` are all read-only).

In order to work around this, I've updated my custom model to implement `IChartEntity` which works fine. However this interface isn't included in the documentation anywhere so I wasn't sure if that was the new recommended approach.

**To Reproduce**
See example above

**Expected behavior**
The documentation for Mappers (https://lvcharts.com/docs/WPF/2.0.0-beta.710/Overview.Mappers) should be updated to include an example of mapping null values for custom models. Documentation for `IChartEntity` should be added to this page if that is the recommended approach.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: N/A
 - Version: 2.0.0-beta.710

**Smartphone (please complete the following information):**
N/A

**Additional context**
None

**Comment by beto-rodriguez** [comment]
Implementing `IChartEntity` is the way, this was changed for performance reasons, implementing this allows the chart to run much faster than the previous approach.

You are right the docs are missing, I will keep this issue open as a reminder to write that.

**Comment by beto-rodriguez** [comment]
This is already documented, thanks for the report again!

https://lvcharts.com/docs/WPF/2.0.0-beta.800/Overview.Mappers

**Comment by mark-monteiro** [comment]
Unless I'm missing something there still doesn't appear to be any documentation on using null values with custom types. The Mappers page would probably benefit from a small additional section or paragraph showing how to use `Coordinate.Empty` to achieve this

**Comment by beto-rodriguez** [comment]
There are now better docs in the latest version:

https://lvcharts.com/docs/WPF/2.0.0-beta.850/Overview.Mappers

Feel free to re-open if the docs are not clear or you think it requires more info.
