### ISSUE TITLE
After clicking on the linserises, the data display is abnormal

### ISSUE THREAD

**Issue by lindadamama** [beto-rodriguez/LiveCharts2#1045]
**Describe the bug**

**To Reproduce**
2. Click on '...linserises.'
After clicking on the linserises, the data display is abnormal
https://github.com/beto-rodriguez/LiveCharts2/assets/48863486/18ad5e5d-c37f-48ff-981f-f88a6f66f806
Fixed display of 100 sets of data in the program
4. Scroll down to '....'
5. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by beto-rodriguez** [comment]
Hello

This is an intended behavior. When you clicked on the chart, you actually moved it (panning) and because you moved the chart view port, then it stays at that range.

Disabling zooming and panning could be a solution in your case.

Also resetting the limits of the axes to null could help
