### ISSUE TITLE
When wpf runs any chart to change the form size, the mask size of the mouse hover is not uniform

### ISSUE THREAD

**Issue by 1234567hp** [beto-rodriguez/LiveCharts2#1046]
![iiOJUELOR1](https://github.com/beto-rodriguez/LiveCharts2/assets/72642652/532b9331-ca4f-4115-a1e3-27d5d1a30e5f)

When wpf runs any chart to change the form size, the mask size of the mouse hover is not uniform,Including pie charts, bar charts, line charts

**Comment by beto-rodriguez** [comment]
Thanks for the report, this should be fixed and will be included in the next version of the library..
