### ISSUE TITLE
PieChart missing TooltipFindingStrategy - 1 label hover on series

### ISSUE THREAD

**Issue by SCLD-JMcCoard** [beto-rodriguez/LiveCharts2#1047]
**Describe the bug**
Documentation https://lvcharts.com/docs/WPF/2.0.0-beta.710/PieChart.Pie%20chart%20control#tooltips, states that it uses the CartesianChart tool tips https://lvcharts.com/docs/wpf/2.0.0-beta.710/CartesianChart.Tooltips which includes the TooltipFindingStrategy.  

When I use tooltips on the pie chart I get some strange results where it shows both series but switch the unhovered value to 0, which technically is incorrect.  So I figured this is where TooltipFindingStrategy would come into play, but it is not available on the PieChart in 710.

**To Reproduce**
Have code like: 
```
         <lvc:PieChart Grid.Row="1"
				                  Margin="4"
				                  Height="200"
				                  Width="200"
				                  TooltipPosition="Bottom"
				                  Series="{Binding Series}"
				                  TooltipFindingStrategy="CompareAll"
				                  Total="{Binding PieChartTotal}"
				                  InitialRotation="-90"/>
```
The series generator
```
private PieSeries<int> CreatePieSeries(string p_name, int[] p_values, SolidColorPaint p_color, bool p_isInnerDonut = false)
    {
        return new PieSeries<int>
               {
                   Name                 = p_name,
                   Values               = p_values,
                   InnerRadius          = 20,
                   MaxRadialColumnWidth = p_isInnerDonut ? 10 : 35,
                   Fill                 = p_color,
                   HoverPushout         = 0,
                   TooltipLabelFormatter = p_point => $"{p_name}: {p_point.PrimaryValue}",
               };
    }
```

**Actual behavior**
Failes to build there is no property for TooltipFindingStrategy in 710.

It also seems to be ignoring my TooltipPosition of Bottom, it is always fixed to the top center. 

**Expected behavior**
Hoping it will only show the hovered pie area's name and value.

**Screenshots**
Here are the screen shots without hover, hovering over the green one, then hovering over the red series.
![image](https://github.com/beto-rodriguez/LiveCharts2/assets/70153610/8814c044-8b24-4f04-9ef7-165cc24177b2)
![image](https://github.com/beto-rodriguez/LiveCharts2/assets/70153610/52f72b0e-855b-4192-92d0-2b56477fe37d)
![image](https://github.com/beto-rodriguez/LiveCharts2/assets/70153610/c28f27a5-6add-432c-bd3b-32b25c27b4e3)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] - Windows (Desktop Application with Avalonia)
 - Browser [e.g. chrome, safari] - None
 - Nuget Version [e.g. 22] - 2.0.0-beta-710

**Additional context**

**Comment by beto-rodriguez** [comment]
I see multiple issues reported here.

> Hoping it will only show the hovered pie area's name and value.

This should be already working properly in beta.800, can you please try it?

> It also seems to be ignoring my TooltipPosition of Bottom, it is always fixed to the top center.

Same, it should be working properly now in the latest version.

> So I figured this is where TooltipFindingStrategy would come into play, but it is not available on the PieChart in 710.

This property is not available in PieCharts, it is by design.
