### ISSUE TITLE
Crash with LiveChartsCore.SkiaSharpView.Avalonia 2.0.0-beta.700-11.0.0-rc1.1 causes by GetTooltipLocation()

### ISSUE THREAD

**Issue by Developer-Alexander** [beto-rodriguez/LiveCharts2#1048]
**Describe the bug**
I get an exception **location not supported** in my Avalonia App using `LiveChartsCore.SkiaSharpView.Avalonia 2.0.0-beta.700-11.0.0-rc1.1`. It is probably caused by a tooltip with a custom text created with Labeler. The same Labeler is used for tooltips and for XAxis labels.

The entire app crashes. There is no way for me to catch the exception.

The version of Avalonia I use is 11.0.0-rc1.1.

```
System.Exception
  HResult=0x80131500
  Nachricht = location not supported
  Quelle = LiveChartsCore
  Stapelüberwachung:
   bei LiveChartsCore.Kernel.Extensions.GetTooltipLocation[TDrawingContext](IEnumerable`1 foundPoints, LvcSize tooltipSize, Chart`1 chart)
   bei LiveChartsCore.SkiaSharpView.SKCharts.SKDefaultTooltip.Show(IEnumerable`1 foundPoints, Chart`1 chart)
   bei LiveChartsCore.Chart`1.<TooltipThrottlerUnlocked>b__151_1()
   bei Avalonia.Threading.DispatcherOperation.InvokeCore()
   bei Avalonia.Threading.DispatcherOperation.Execute()
   bei Avalonia.Threading.Dispatcher.ExecuteJob(DispatcherOperation job)
   bei Avalonia.Threading.Dispatcher.ExecuteJobsCore()
   bei Avalonia.Threading.Dispatcher.Signaled()
   bei Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   bei Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   bei Avalonia.Win32.Win32DispatcherImpl.RunLoop(CancellationToken cancellationToken)
   bei Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl impl)
   bei Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   bei Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   bei Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   bei Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, ShutdownMode shutdownMode)
   ...
```

**To Reproduce**
Unfortunately I don't know exactly how to reproduce. It happens when the values of the chart are updated via an ObservableCollection in the background.

**Expected behavior**
No crash

**Desktop (please complete the following information):**
 - OS: Windows 11

**Comment by beto-rodriguez** [comment]
Hello.

Hi and thanks for the report.

Are you updating your data from multiple threads? that error could happen in that scenario. Please take a look https://github.com/beto-rodriguez/LiveCharts2/issues/225#issuecomment-1012488255 there you can find a way to fix that.

**Comment by Developer-Alexander** [comment]
Thank you. That's helpful.
