### ISSUE TITLE
how to use linear notation in legends instead hollow circle

### ISSUE THREAD

**Issue by Fotrey** [beto-rodriguez/LiveCharts2#1053]
![image](https://github.com/beto-rodriguez/LiveCharts2/assets/59856346/30c075d3-8094-4f00-875b-9a03b6b0a505)
like this

**Comment by Fotrey** [comment]
series type is LineSeries

**Comment by beto-rodriguez** [comment]
Hello, the website was updated with a sample based on this case.

To achieve that you will need to create a default legend that uses a rectangle geometry, here is an example that uses the `SVGVisual` to draw a start, but you could also use the but you could instead use the `GeometryVisual<RectangleGeometry>` and draw a rectangle there.

https://lvcharts.com/docs/WPF/2.0.0-beta.800/samples.general.customLegends#customlegend.cs
