### ISSUE TITLE
How can I to draw a markLine to LineSeries Like to Echarts markLine

### ISSUE THREAD

**Issue by xtz0602** [beto-rodriguez/LiveCharts2#1059]
Now I draw a LineChart like this 
![image](https://github.com/beto-rodriguez/LiveCharts2/assets/106213402/6d520918-ad58-4546-a700-f6b503512edd)
My viewModel is 
   public class TestPageViewMode : BindableBase
    {
    

        public TestPageViewMode()
        {
            var strokeThickness = 10;
            var strokeDashArray = new float[] { 3 * strokeThickness, 2 * strokeThickness };
            var effect = new DashEffect(strokeDashArray);

            Series = new ISeries[]
            {
            new LineSeries<int>
            {
                Name="value",
                Values = new [] { 4, 2, 8, 5, 3 ,7,1},
                LineSmoothness = 1,
                GeometrySize = 22,
                Stroke = new SolidColorPaint
                {
                    Color = SKColors.CornflowerBlue,
                    StrokeCap = SKStrokeCap.Round,
                    StrokeThickness = strokeThickness,
                    PathEffect = effect
                },
                Fill = null
            },
             new LineSeries<double>
                {
                 Name="+3sd",
                    Values = new double[] { 5, 5, 5, 5, 5, 5 },
                    Fill = null,
                    GeometrySize = 0,
                     Stroke = new SolidColorPaint
                    {
                        Color = (new SKColor(101, 97, 166)),
                        StrokeThickness = 2,

                        PathEffect = effect
                    },

                    LineSmoothness = 0
                },

           
            new LineSeries<double>
            {
                Name = "+2sd",
                Values = new double[] { 3, 3, 3, 3, 3, 3 },
                Fill = null,
                GeometrySize = 0,
                Stroke = new SolidColorPaint
                {
                    Color = (new SKColor(250, 220, 164)),
                    StrokeThickness = 2,

                    PathEffect = effect
                },

                LineSmoothness = 0
            },

          
        new LineSeries<double>
                {
                 Name="+1sd",
                    Values = new double[] { 1, 1, 1, 1, 1, 1 },
                    Fill = null,
                    GeometrySize = 0,
                     Stroke = new SolidColorPaint
                    {
                         Color = (new SKColor(194, 217, 193)),
                        StrokeThickness = 2,

                        PathEffect = effect
},

                    LineSmoothness = 0
                },

            };

      
    }

       public ISeries[] Series { get; set; }
    }

I want to know the LineSeries have a property like Echarts (a web charts tools) MarkLine .
Like this 

option = {

  xAxis: {
    data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
  },
  yAxis: {
    type: 'value',
    axisLabel: {
      formatter: '{value} °C'
    }
  },
  series: [
    {
      name: 'Highest',
      type: 'line',
      data: [10, 11, 13, 11, 12, 12, 9],
      markPoint: {
        data: [
          { type: 'max', name: 'Max' },
          { type: 'min', name: 'Min' }
        ]
      },
      markLine: {
        data: [ 
            
              {yAxis: 12}
            ]
      }
    }
  ]
};

![image](https://github.com/beto-rodriguez/LiveCharts2/assets/106213402/a40dff76-1974-4026-be2b-fb99fb0faef6)

just set a double value do not like this demo set a double array  
Thank you for your help

**Comment by xtz0602** [comment]
OK I try to use to  RectangularSection to draw "markline" .  it look so  nice .
But  I feel a BUG ...may be is my error 
This is my new code .
xalm:

<UserControl x:Class="iManager_wpf.View.Page.TestPage"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" 
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008" 
             xmlns:local="clr-namespace:iManager_wpf.View.Page" xmlns:materialDesign="http://materialdesigninxaml.net/winfx/xaml/themes"
             xmlns:lvc="clr-namespace:LiveChartsCore.SkiaSharpView.WPF;assembly=LiveChartsCore.SkiaSharpView.WPF"
                  xmlns:p="clr-namespace:iManager_wpf.View.Control"
              xmlns:prism="http://prismlibrary.com/"
             prism:ViewModelLocator.AutoWireViewModel="True"
             mc:Ignorable="d" 
             xmlns:testControls="clr-namespace:iManager_wpf.View.Control"
             d:DesignHeight="900" d:DesignWidth="1920">
    <Grid>
        <materialDesign:Card>
            <TabControl
    VerticalContentAlignment="Top"
    materialDesign:ColorZoneAssist.Mode="PrimaryMid"
    Style="{StaticResource MaterialDesignNavigationRailTabControl}">
                <TabItem>
                    <TabItem.Header>
                        <StackPanel
          Width="auto"
          Height="auto">
                            <materialDesign:PackIcon
            Width="24"
            Height="24"
            HorizontalAlignment="Center"
            Kind="ChartBoxOutline" />
                            <TextBlock
            HorizontalAlignment="Center"
            Text="BarChart" />
                        </StackPanel>
                    </TabItem.Header>
                    <Grid>
                        <Grid.ColumnDefinitions>
                            <ColumnDefinition Width="10*"></ColumnDefinition>
                            <ColumnDefinition></ColumnDefinition>
                        </Grid.ColumnDefinitions>

                        
                         <lvc:CartesianChart Margin="100" Series="{Binding Series}"  Sections="{Binding Sections}" YAxes="{Binding YAxes}"/>
                        <StackPanel Grid.Column="2">
                            <Button Margin="10" Content="ShowChart" Command="{Binding BtnCommand}" CommandParameter="show"/>
                            <Button Margin="10" Content="SavePic" Command="{Binding BtnCommand}" CommandParameter="save"/>
                        </StackPanel>


                    </Grid>
                </TabItem>
                <TabItem>
                    <TabItem.Header>
                        <StackPanel
          Width="auto"
          Height="auto">
                            <materialDesign:PackIcon
            Width="24"
            Height="24"
            HorizontalAlignment="Center"
            Kind="ChartBellCurve" />
                            <TextBlock
            HorizontalAlignment="Center"
            Text="LineChart" />
                        </StackPanel>
                    </TabItem.Header>
                    <Grid>

                        
                    </Grid>
                </TabItem>
                <TabItem>
                    <TabItem.Header>
                        <StackPanel
          Width="auto"
          Height="auto">
                            <materialDesign:PackIcon
            Width="24"
            Height="24"
            HorizontalAlignment="Center"
            Kind="Grid" />
                            <TextBlock
            HorizontalAlignment="Center"
            Text="DataGrid" />
                        </StackPanel>
                    </TabItem.Header>
                    <Grid>

                        
                    </Grid>
                </TabItem>
                <TabItem>
                    <TabItem.Header>
                        <StackPanel
          Width="auto"
          Height="auto">
                            <materialDesign:PackIcon
            Width="24"
            Height="24"
            HorizontalAlignment="Center"
            Kind="MusicBoxMultiple" />
                            <TextBlock
            HorizontalAlignment="Center"
            Text="Sounds" />
                        </StackPanel>
                    </TabItem.Header>
                    <Grid>
                        <testControls:TreeViewControl></testControls:TreeViewControl>
                    </Grid>
                </TabItem>
            </TabControl>
        </materialDesign:Card>
    </Grid>
</UserControl>

and my viewModel is 

using LiveChartsCore.Kernel.Sketches;
using LiveChartsCore.SkiaSharpView;
using LiveChartsCore.SkiaSharpView.Painting;
using LiveChartsCore.SkiaSharpView.SKCharts;
using Prism.Commands;
using Prism.Mvvm;
using SkiaSharp;
using System.Collections.Generic;
using System.Collections.ObjectModel;

namespace iManager_wpf.ViewModel.Page
{
    public class TestPageViewMode : BindableBase
    {
        public DelegateCommand<string> BtnCommand { get; set; }

        public ObservableCollection<LineSeries<double>> Series { get; set; }

        public ObservableCollection<RectangularSection> Sections { get; set; }
        public ObservableCollection<ICartesianAxis> YAxes { get; set; }
        public TestPageViewMode()
        {
            BtnCommand = new DelegateCommand<string>(Click);
            Sections = new ObservableCollection<RectangularSection>();
            YAxes = new ObservableCollection<ICartesianAxis>();
            Series = new ObservableCollection<LineSeries<double>>();
        }

        private void Click(string obj)
        {

            switch (obj)
            {
                case "show":
                    {
                        ShowCharts();
                        DrawMarkLine();
                        SetYAxis();
                    }
                    break;
                case "save":
                    {
                        Save();
                    }
                    break;
                default:
                    break;
            }
        }

        private void Save()
        {
            var pieChart = new SKCartesianChart
            {
                Width = 1000,
                Height = 400,
                Series = Series,
                Sections = Sections,
                YAxes = YAxes,
            };

            pieChart.SaveImage("export.png");
        }

        private void SetYAxis()
        {
            YAxes.Clear();
            Axis axis = new Axis()
            {
                MaxLimit = 85,
                MinLimit = 25,
            };
            YAxes.Add(axis);
        }

        private void DrawMarkLine()
        {
            var sections = new List<RectangularSection>();

            sections.Add(
                new RectangularSection
                {
                    Yi = 40,
                    Yj = 40,
                    Stroke = new SolidColorPaint
                    {
                        Color = new SKColor(39, 98, 42),
                        StrokeThickness = 1,
                    }
                });

            sections.Add(
                new RectangularSection
                {
                    Yi = 80,
                    Yj = 80,
                    Stroke = new SolidColorPaint
                    {
                        Color = new SKColor(145, 37, 34),
                        StrokeThickness = 1,
                    }
                });

            Sections.Clear();
            Sections.AddRange(sections);
        }

        private void ShowCharts()
        {
            Series.Clear();
            var tempSeriesList = new List<LineSeries<double>>();
            tempSeriesList.Add(new LineSeries<double>
            {
                Name = "value",
                Values = new double[10] { 5, 10, 22, 14, 62, 44, 11, 33, 78, 91 },
                LineSmoothness = 1,
                GeometrySize = 22,
                Stroke = new SolidColorPaint
                {
                    Color = SKColors.CornflowerBlue,
                    StrokeCap = SKStrokeCap.Round,
                    StrokeThickness = 1,

                },
                Fill = null
            });
            Series.AddRange(tempSeriesList);
        }

    }
}



first  I click ShowCharts button  the lineCharts is show.
![image](https://github.com/beto-rodriguez/LiveCharts2/assets/106213402/b60e35aa-e1b2-48d8-a504-1b74a966c080)

and then I click SavePic 。the picture is create good .
but when I save picture and move mouse on charts.the line charts will change.
![image](https://github.com/beto-rodriguez/LiveCharts2/assets/106213402/93ee3c45-847e-48f5-a8a5-b9d7b56906c4)

**Comment by beto-rodriguez** [comment]
Thanks for the report, I was able to get the error. It is strange, it seems that the section is updated when you create the image.

A workaround for now is to create a copy of the sections:

```c#
var pieChart = new SKCartesianChart
        {
            Width = 1000,
            Height = 400,
            Series = Series,
            Sections = Sections.Select(x => new RectangularSection
            {
                Xi = x.Xi,
                Xj = x.Xj,
                Yi = x.Yi,
                Yj = x.Yj,
                Fill = x.Fill?.CloneTask(),
                Stroke = x.Stroke?.CloneTask(),
            }).ToArray(),
            YAxes = YAxes,
        };

        pieChart.SaveImage("export.png");
```

**Comment by xtz0602** [comment]
maybe I Series use to  this 
public ObservableCollection<LineSeries<double>> Series { get; set; }
not sample use to 
public ISeries[] Series

**Comment by beto-rodriguez** [comment]
I think I will close this for now, the workaround seems a good alternative.... this might be fixed in a future release.

**Comment by xtz0602** [comment]
Yep that a good  function.and thank you for your help发自我的 iPhone在 2023年9月15日，11:45，Alberto Rodríguez ***@***.***> 写道：﻿
I think I will close this for now, the workaround seems a good alternative.... this might be fixed in a future release.
