### ISSUE TITLE
GeoMap

### ISSUE THREAD

**Issue by MoruaReyes** [beto-rodriguez/LiveCharts2#1062]
Estoy utilizando LiveCharts Version 1, Visual 2022, .Net Framework 4.7.2
Cuando abro el formulario que muestra el mapa, todos los demás formularios en mis aplicaciones comienzan a usar una fuente completamente diferente (y más pequeña).
Esto sucede cuando se ejecuta la linea
Dim geoMap As new  LiveCharts.WinForms.GeoMap

**Comment by MoruaReyes** [comment]
Codigo
Dim geoMap As new LiveCharts.WinForms.GeoMap
 geoMap.Source = Global.Presentacion.My.Resources.Resources.Mapa//Archivo Xml
 Dim values As Dictionary(Of String, Double) = New Dictionary(Of String, Double)
 geoMap.HeatMap = values

**Comment by beto-rodriguez** [comment]
Gracias port el reporte, es extraño el error, parece que la información que proporcionas no es suficiente para re-crear el problema desde mi lado, podrías por favor crear un proyecto pequeño en el cual se pueda ver el error?

Por ahora cerraré este issue, pero sientete libre de crear uno nuevo donde anexes un ejemplo, o bien más codigo que nos pueda ayudar a reproducir el error, también por respeto a la mayoría de usuarios te invito a que escribas en íngles (usa un traductor si se te complica) de esta manera tu reporte va a poder servir para futuros usuarios que enfrenten un problema similar, gracias por el reporte!
