### ISSUE TITLE
Migrating license from V0 to V2

### ISSUE THREAD

**Issue by ilmoris** [beto-rodriguez/LiveCharts2#1064]
i've been trying to reach the suppor team in order to be able to use my geared license (v0 livecharts) - but got no replies back. login via microsoft account on the https://v0.lvcharts.com/ site seems impossible now..
Can i migrate my license to V2? is there an option in V2 to actually be able to manage my team license? Right now i got the payed license but have no possibility to use it as I cannot assign individual users to that...

**Comment by beto-rodriguez** [comment]
I will close this for now since this was solved my mail.
