### ISSUE TITLE
Tooltipstext size not working in 800

### ISSUE THREAD

**Issue by rpascalegh** [beto-rodriguez/LiveCharts2#1066]
**Describe the bug**
Unable to change size of tool tip text.  In 710, worked. In 800 size doesnt change.

**Smartphone (please complete the following information):**
Testing on Andriod Galaxy S22

**Comment by beto-rodriguez** [comment]
Thanks for the report, this will be fixed in `beta.801`.

**Comment by rpascalegh** [comment]
Legend is still not working.  Its losing values again. 810 version
