### ISSUE TITLE
Line chart tool tips choping labels

### ISSUE THREAD

**Issue by rpascalegh** [beto-rodriguez/LiveCharts2#1074]
Tool tips line chart data display chop when changing value selected.
Version
801

**Describe the bug**
Line chart with multipule months of data chops off labels.
Have 12 months loaded with values in a line chart
See image.  First lable tool tip shows correct values of legend + values
When selecting second month, the value gets choped missing first two char of legend and value in tool tip.
When selctiong another it returns to correct values.

Image
![chop](https://github.com/beto-rodriguez/LiveCharts2/assets/14371980/1b5bf9ac-2571-4bb5-bc07-a88e4e85369e)

**Comment by beto-rodriguez** [comment]
Should be fixed in beta.803 thanks for the report.

**Comment by rpascalegh** [comment]
Ok.  Will test when released.
Thank you,
Richard

**Comment by beto-rodriguez** [comment]
it is now, sorry it was beta.802

**Comment by rpascalegh** [comment]
ok.   Look like all 3 issue are fixed
chopping was fixed
legend is not disappearing anymore
Tool tips size working.

I will run it for a few days to make sure.  Thanks
Richard
