### ISSUE TITLE
Legend Values are disapearing when values are updated Pie

### ISSUE THREAD

**Issue by rpascalegh** [beto-rodriguez/LiveCharts2#1075]
**Describe the bug**
Load A pie with values and legend values.

Update pie with new values and repost same legend names
Pie updates correctly with new values, but legend goes blank.

Code:
code that loads the legend names into series uses the "Name" properity of the pie.  This works intially. 
When the Name propery is updated (in the test, with same value is updated no change)  the value gets blanked out.

code worked fine in other versions.  Had issue in 700 and 800 where values would disapear.  There was a  fixed pushed out for  801 but there may be an issue as this code is unchanged and was working.

**Expected behavior**
Legend should stay the same and display text

**Screenshots**

![legend](https://github.com/beto-rodriguez/LiveCharts2/assets/14371980/301efb8b-2425-4da3-b084-35e27c61006f)

**Desktop (please complete the following information):**
IOS ipad and Andriod phone (maui)

**Comment by rpascalegh** [comment]
The values are also disappering when I come back and run the app, its not just when I update values.

**Comment by beto-rodriguez** [comment]
This should be fixed in the latest release, feel free to re-open if the issue persists.
