### ISSUE TITLE
ClickEvent for chart point

### ISSUE THREAD

**Issue by Developer-Alexander** [beto-rodriguez/LiveCharts2#1077]
**Describe the solution you'd like**
I don't know if there is already a solution for this that I am simply not aware of. However I would like to have a `OnClick` event for a chart data point. Alternatively it would be nice to have the possibility to add an `Action` (or `Func<ChartPoint>`) that gets executed when a chart point got clicked.

**Comment by beto-rodriguez** [comment]
Yes this is supported:

https://lvcharts.com/docs/Avalonia/2.0.0-beta.800/samples.events.cartesian
