### ISSUE TITLE
PieChart OnClick Index not working

### ISSUE THREAD

**Issue by Tremlton** [beto-rodriguez/LiveCharts2#1079]
**Describe the bug**
When I use the ChartPointPointerDown Event from the PieChart, then the ChartPoint's Index is always 0 no matter what section i click

**To Reproduce**
Just code a regular PieChart and implement the ChartPointPointerDown Event, the ChartPoint.Index is always 0.

**Screenshots**
![image](https://github.com/beto-rodriguez/LiveCharts2/assets/85153099/fa52c3a4-e9da-4c3c-88a1-cbd7ed158111)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version [2.0.0-beta.800]

**Comment by beto-rodriguez** [comment]
Becuase it is `0`, that is the correct output, you could instead ask for the index of the series in your series collection.
