### ISSUE TITLE
Individually colored data points

### ISSUE THREAD

**Issue by phanthanhdat077** [beto-rodriguez/LiveCharts2#1084]
How I can do it with Livechart 2? Any suggestions I tried searching but to no avail

![image](https://github.com/beto-rodriguez/LiveCharts2/assets/34691283/90beef0d-981e-47d7-86b0-7edb27fe5780)

**Comment by network-interface-controller** [comment]
@phanthanhdat077 Did you try to use ConditionalDraw (see https://github.com/beto-rodriguez/LiveCharts2/releases/tag/beta.500)? It allows to recolor data points based on their value.

**Comment by phanthanhdat077** [comment]
How I can set many colors by index with use ConditionalDraw

**Comment by beto-rodriguez** [comment]
This is now easy on the latest version:

https://livecharts.dev/docs/WPF/2.0.0-beta.950/samples.general.mapPoints

Feel free to reply or create a new issue if that is not enough!
