### ISSUE TITLE
CartesianChart DateTimePoint Labeler's value sometime is empty.

### ISSUE THREAD

**Issue by yuyihu** [beto-rodriguez/LiveCharts2#1086]
![image](https://github.com/beto-rodriguez/LiveCharts2/assets/64644171/7d777200-0188-4c93-96b1-2f4388e3f279)

**Comment by beto-rodriguez** [comment]
Thanks for the report, this is related to #1074 and will be fixed in the next release, we can track this issue at #1074.

Thanks again!
