### ISSUE TITLE
AutoUpdate of DateTimePoint Series through 'null' causes full series re-draw (Avalonia)

### ISSUE THREAD

**Issue by houstonhaynes** [beto-rodriguez/LiveCharts2#1087]
**Describe the bug**
When the line series `ObservableCollection<DateTimePoint>` updates with a 'null' value at the first position `RemoveAt(0)` the chart performs a full redraw of the series.

**To Reproduce**
1. Build/run my AvaloniaExample app https://github.com/houstonhaynes/Elmish.Avalonia/tree/main/src/Samples/AvaloniaExample
2. Click on AutoUpdate (null values are inserted 5% of the time)
3. Observe the "gap" reaching the left edge of the display area of the chart
4. Note that when the last value *before* the gap is removed that the full series re-draws in the chart

**Expected behavior**
The chart should continue to "slide left" smoothly without a full redraw of the series.
Along those lines, the series should visually "hold" the position for the null value so that "slide" increment remains a consistent cadence.

**Screenshots**
See attached video

https://github.com/beto-rodriguez/LiveCharts2/assets/8174976/05b068f0-573c-422b-857b-52b7b8fdb731

**Desktop (please complete the following information):**
 - OS: MacOS M1
 - Browser: N/A
 - Version 2.0.0-beta.801

**Additional context**
LiveCharts is AMAZING! 😺 👍

**Comment by beto-rodriguez** [comment]
Th recefenced commit fixes this issue, but the algorithm needs a review, this issue is still present when we insert a `null` instance. As a temporal solution this seems ok, but we can improve this.

**Comment by beto-rodriguez** [comment]
![v](https://github.com/beto-rodriguez/LiveCharts2/assets/10853349/46688139-4567-4ae2-a211-a291040ad9bf)

**Comment by houstonhaynes** [comment]
This is so great - everythig at this level feels like an interim step. 👍
