### ISSUE TITLE
ToolTip constant position.

### ISSUE THREAD

**Issue by nusuev** [beto-rodriguez/LiveCharts2#1091]
It would be nice to be able to customize the tooltip so that it is fixed in one position, and not following the cursor.

**Comment by beto-rodriguez** [comment]
This can be done, checkout the custom tooltip example:

https://lvcharts.com/docs/WPF/2.0.0-beta.800/samples.general.customTooltips

Specially at:

```
var location = foundPoints.GetTooltipLocation(size, chart);

_stackPanel.X = location.X;
_stackPanel.Y = location.Y;
```

That part sets the tooltip location, just set it where you need.
