### ISSUE TITLE
InnerRadius has no effect on the position of DataLabels

### ISSUE THREAD

**Issue by Belitharian** [beto-rodriguez/LiveCharts2#1096]
**Describe the bug**
The InnerRadius attribute no longer has any effect on the position of DataLabels when DataLabelsPosition is set.

**To Reproduce**
- Create a new WPF application ;
- Create a new ViewModel :
```cs
public class ViewModel
{
    public ISeries[] Series { get; set; }
        = new ISeries[]
        {
            new PieSeries<double>
            {
                Values = new double[] { 2 },
                Stroke = new SolidColorPaint(SKColors.White, 2),
                Fill = new SolidColorPaint(SKColors.Aqua),
                DataLabelsPaint = new SolidColorPaint(SKColors.Black),
                InnerRadius = 160,
                DataLabelsSize = 24,
                DataLabelsPosition = LiveChartsCore.Measure.PolarLabelsPosition.Middle,
            },
            new PieSeries<double>
            {
                Values = new double[] { 6 },
                Fill = new SolidColorPaint(SKColors.GreenYellow),
                Stroke = new SolidColorPaint(SKColors.White, 2),
                DataLabelsPaint = new SolidColorPaint(SKColors.Black),
                InnerRadius = 160,
                DataLabelsSize = 24,
                DataLabelsPosition = LiveChartsCore.Measure.PolarLabelsPosition.Middle,
            },
            new PieSeries<double>
            {
                Values = new double[] { 8 },
                Stroke = new SolidColorPaint(SKColors.White, 2),
                Fill = new SolidColorPaint(SKColors.Magenta),
                DataLabelsPaint = new SolidColorPaint(SKColors.Black),
                InnerRadius = 160,
                DataLabelsSize = 24,
                DataLabelsPosition = LiveChartsCore.Measure.PolarLabelsPosition.Middle,
            }
        };
}
```
- Create the UI :
```xaml
<Window
    x:Class="WpfApp1.MainWindow"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="clr-namespace:WpfApp1"
    xmlns:lvc="clr-namespace:LiveChartsCore.SkiaSharpView.WPF;assembly=LiveChartsCore.SkiaSharpView.WPF"
    Width="960"
    Height="540"
    Background="#FF0A0A10">

    <Window.DataContext>
        <local:ViewModel />
    </Window.DataContext>

    <Grid Margin="45">
        <lvc:PieChart x:Name="PieChart" Series="{Binding Series}" />
    </Grid>

</Window>
```
- Observe the DataLabels position.

**Expected behavior**
The DataLabels should be in the position : middle, start, outer, end ; according to what the developer decided.
Only the `Measure.PolarLabelsPosition.ChartCenter` position works.

**Screenshots**
_With InnerRadius set :_
![image](https://github.com/beto-rodriguez/LiveCharts2/assets/50078413/3aeedbfa-3a77-4738-a721-4c570e4783b9)

_Without InnerRadius set :_
![image](https://github.com/beto-rodriguez/LiveCharts2/assets/50078413/ab2a5c15-6f66-415c-bfee-de2eba5ec2df)

**Desktop (please complete the following information):**
 - OS:  ``Windows 10 Professionnel 20H2 - Build 19042.985 - Windows Feature Experience Pack 120.2212.2020.0`` 

**Additional context**
LiveChartsCore & LiveChartsCore.SkiaSharpView.WPF : ``v. 2.0.0-beta.802``

That's my first bug report, hope this helps! 👍

**Comment by network-interface-controller** [comment]
I'm not quite sure if I understand that issue correctly but in general I would not expect that the labels move automatically if I change the inner radius of a pie chart. The postions of DataLabels should be handled separately. However, this might be a side-effect of the fix for https://github.com/beto-rodriguez/LiveCharts2/issues/771.

**Comment by beto-rodriguez** [comment]
This is already fixed in `beta.900` thanks for the report.
