### ISSUE TITLE
Xamarin.Forms: Image from chart looks different

### ISSUE THREAD

**Issue by trdsolutions** [beto-rodriguez/LiveCharts2#1100]
**Describe the bug**
When saving a chart to an image, the image content looks different then the chart

**To Reproduce**

Create a content view add insert the following:

```
<StackLayout>
        <forms:CartesianChart
             x:Name="CartesianChart"
             Title="{Binding LineChartTitle}"
             HeightRequest="300"
             Background="White"
             Series="{Binding LineSeries}" />

        <Image x:Name="CartesianChartImage" HeightRequest="300" />
</StackLayout>
```

(I used the default title and series from the [example page](https://www.lvcharts.com/docs/Xamarin/2.0.0-beta.800/samples.lines.basic)

In the ContentViews code-behind add the following:

```
CartesianChart.SizeChanged += (o, e) =>
{
        //CartesianChartImage.Source = CartesianChart.ToImageSource();

        InMemorySkiaSharpChart inMemoryChart = new SKCartesianChart(CartesianChart);
	inMemoryChart.Width = (int)CartesianChart.Width;
	inMemoryChart.Height = (int)CartesianChart.Height;
			
	SKImage image = inMemoryChart.GetImage();
	SKData data = image.Encode(SKEncodedImageFormat.Png, 80);
			
	CartesianChartImage.Source = ImageSource.FromStream(() => data.AsStream());
};
```

**Expected behavior**
Chart and image should look the same, but as can be seen on the screenshot, they don't.

Am I doing something wrong?

**Screenshots**
![image](https://github.com/beto-rodriguez/LiveCharts2/assets/4069571/96f8fbbe-41fb-4eb8-84ec-f2618f56c9cd)

**Comment by trdsolutions** [comment]
After proceeding with more research I finally found the answer:

When applying `Width` and `Height`, the devices display density needs to be noted.
So instead of 

```
inMemoryChart.Width = (int)CartesianChart.Width;
inMemoryChart.Height = (int)CartesianChart.Height;
```

if must be 

```
double density = DeviceDisplay.MainDisplayInfo.Density;

inMemoryChart.Width = (int)(CartesianChart.Width * density);
inMemoryChart.Height = (int)(CartesianChart.Height * density);
```

I'm not quite sure, if this is just a workaround and may need some touches in the source code, so I keep the issue open for now, but feel free to close :-)

**Comment by beto-rodriguez** [comment]
This is the correct solution thanks for finding a solution.
