### ISSUE TITLE
There is no ChartEngine Registered

### ISSUE THREAD

**Issue by aspeculat0r** [beto-rodriguez/LiveCharts2#1101]
**Describe the bug**
I get the no ChartEngine registered exception event though I have the Config like:

            LiveCharts.Configure(
                config =>
                    config.HasMap<BaseDataSeries>(
                        (data, chartPoint) =>
                        {
                            chartPoint.PrimaryValue = data.X;
                            chartPoint.SecondaryValue = data.Y;
                        }
                    )
            );

I put this config in app.xaml.cs and also in the usercontrol but still. 
**To Reproduce**
It is a bigger app so not really sure 

**Expected behavior**

**Screenshots**
You can see in below image that setting have the mapper registered
![image](https://github.com/beto-rodriguez/LiveCharts2/assets/43305682/47723ede-4f4a-4c73-b94d-bac2dd118fa0)

But I still get the error:

![image](https://github.com/beto-rodriguez/LiveCharts2/assets/43305682/66eaeade-2840-4ff3-a55a-4c7cf7c3f8ec)
This is for WinUI Application

**Comment by beto-rodriguez** [comment]
Thanks for the report, the referenced commit should fix this, as an alternative you can also register SkiaSharp in that call:

```c#
LiveCharts.Configure(
            config =>
                config
                    .AddSkiaSharp()
                    .AddDefaultMappers()
                    .AddLightTheme()
                    .HasMap<BaseDataSeries>(
                        (data, chartPoint) =>
                        {
                            chartPoint.PrimaryValue = data.X;
                            chartPoint.SecondaryValue = data.Y;
                        }
                )
        );
```

**Comment by aspeculat0r** [comment]
Thank you Beto. Much Appreciated
