### ISSUE TITLE
Zooming on heatseries causes Data Labels to appear off the edge

### ISSUE THREAD

**Issue by joshbevans** [beto-rodriguez/LiveCharts2#1109]
When having a heat series with data labels, zooming in will cause the data labels to appear off the side of the graph, overlapping with the axis. The colour boxes disappear but the overlayed text does not.

Code im using to create the heat series:
HeatSeries.Add( new HeatSeries<WeightedPoint>
			{
				HeatMap = new[]
				{
					SKColors.Transparent.AsLvcColor(), // the first element is the "coldest
					SKColors.LightGreen.AsLvcColor(),
					new SKColor(245, 208, 98).AsLvcColor(),
					SKColors.LightCoral.AsLvcColor() // the last element is the "hottest"
				},
				Values = timeSheetData,
				DataLabelsFormatter = (point) => point.TertiaryValue.ToString().TrimStart('0'),
				DataLabelsPosition = LiveChartsCore.Measure.DataLabelsPosition.Middle,
				DataLabelsSize = 12,
				DataLabelsPaint = new SolidColorPaint(SKColors.Black),
				ColorStops = new[]
				{
					0,
					0.0000001,
					0.5,
					1
				}
			});

XAML:
<lvc:CartesianChart
            Grid.Row="1"
            Series="{Binding HeatSeries}"
            XAxes="{Binding HeatXAxis}"
            YAxes="{Binding HeatYAxis}"
            ZoomMode="Both" />

Screenshot of issue: https://imgur.com/a/SVqqPgY
As you can see the numbers appearing on the left side of the axis labels, happens on all axis regardless of position

Using LiveChartsCore.SkiaSharpView.WPF 2.0.0-beta.810

**Comment by beto-rodriguez** [comment]
Thanks for the report, the referenced commit fixes this and will be included in the next version of the library.
