### ISSUE TITLE
Last selected datapoiont does not lose focus when pointer leaves chart.

### ISSUE THREAD

**Issue by lukaszossowski** [beto-rodriguez/LiveCharts2#1112]
**Describe the bug**
After upgrading to beta 800 the new charts do not lose focus when pointer leaves, last data point that was hovered over remains in the "selected" state. 

**Expected behavior**
After pointer leaves chart all data points should be in their "idle" state.

**Screenshots**
![infocus](https://github.com/beto-rodriguez/LiveCharts2/assets/112421929/42c3fe13-0796-4aa8-89dc-15f802ff7611)
Jul data point is still selected.
![infocus2](https://github.com/beto-rodriguez/LiveCharts2/assets/112421929/d204be21-36be-4ce0-a4d8-90f86f1fc36e)
Middle bar is highlighted (barely visible due to used colours but you can see the chart lines behind it, unlike in left and right bars).

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
I am using Avalonia 11.0 (latest stable).

**Comment by beto-rodriguez** [comment]
Thanks for the report, the referenced commit fixes this and will be included in the next version of the library.
