### ISSUE TITLE
Can't override the tool tip background color in beta 800

### ISSUE THREAD

**Issue by misirlou-tg** [beto-rodriguez/LiveCharts2#1113]
**Describe the bug**
Can't override the tool tip background color in beta 800

**To Reproduce**
I am overriding the tool tip background color as explained in:
https://lvcharts.com/docs/WPF/2.0.0-beta.800/CartesianChart.Tooltips#view

I am binding to a property, the property is initialized to a constant color value. When running in the debugger no binding failures show up.

**Expected behavior**
The tool tip's background color should change

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows

**Comment by beto-rodriguez** [comment]
Thanks for the report, the referenced commit fixes this and will be included in the next version of the library.
