### ISSUE TITLE
[MAUI] Net7.0 target dispeared

### ISSUE THREAD

**Issue by Rodama-20** [beto-rodriguez/LiveCharts2#1120]
**Describe the bug**
until version 2.0.0-beta.810 the plugin has a target for net6.0 without plateforme but this disappear in beta 850

This target is necessary when testing a project with xUnit

**To Reproduce**
1. Go to NuGet package manager and try to update from beta 810 to 850
2. See error in the output console

**Expected behavior**
Working as before the update to net7 

**Additional context**
see https://github.com/beto-rodriguez/LiveCharts2/commit/2f4b2c73e4f7fd2ee3255b3ac15fb55d48c5f598 on line 4

**Comment by beto-rodriguez** [comment]
Forget about my old comment (deleted).

It is fixed with the referenced commit and will be included in the next version of the library.
