### ISSUE TITLE
Draw different sized line serie points?

### ISSUE THREAD

**Issue by Diogoaf420** [beto-rodriguez/LiveCharts2#1122]
I have a Cartesian chart where my X axis is time and my chart points are events that take different amounts of time. My need is to allow different geometry sizes depending on the point that is drawn. For instance, in one case my chart point would be from 12am to 12:30am and in other case a rectangle from 13pm to 13:15pm. However, since the GeometrySize of a lineSeries is fixed this is not possible.

The perfect solution would be a formatter like the ones that exist the data labels but for the geometry of the points.

A workaround I tried was to override the OnDraw() of a new TVisual, however, there is no access to the Chart Entity nor the ChartPoint that is being drawn at the moment. Maybe that would be something easier to do?

Thank you, and keep the good work :)

**Comment by beto-rodriguez** [comment]
Hi

This sounds like a custom type of series, there is the bubble plot, that uses a third coordinate to assign a "weight" to each point:

https://lvcharts.com/docs/Maui/2.0.0-beta.850/samples.scatter.bubbles

You need a mix of both series, the `LineSeries` and the `ScatterSeries`, for now this is not implemented but it sounds like and interesting feature.

> A workaround I tried was to override the OnDraw() of a new TVisual, however, there is no access to the Chart Entity nor the ChartPoint that is being drawn at the moment. Maybe that would be something easier to do?

The `OnDraw()` is called on every frame (60 frames per seconds by default in most of the supported platforms), that method should only do graphical things, maybe you can find a workaround to do it in that method, but if not efficient you will lose a lot of performance there.

**Comment by Diogoaf420** [comment]
Hello,

Is it then possible to access the Weight or any value regarding the graph point in the on draw method? Because I need to reflect the weight in the drawing point but only in the width and not in the height.  

Thank you!

**Comment by beto-rodriguez** [comment]
Now there is an example where the drawn geometry is mapped to the data:

https://github.com/beto-rodriguez/LiveCharts2/blob/dev/samples/ViewModelsSamples/Lines/CustomPoints/ViewModel.cs

This will be in the web site in the next release, this is a good base to build this kind of features.
