### ISSUE TITLE
UI Freezes if Min Step is 0

### ISSUE THREAD

**Issue by gktval** [beto-rodriguez/LiveCharts2#1124]
Very low priority bug, but if the YAxis has a MinStep of 0, the UI will freeze. 

I had a flat line graph where all the y values were constant. In some calculations, this produced a MinStep value of 0. Very easy workaround for me was to make the increase the MinStep just slightly. 

Not sure if you want to throw an error or just add a small value to MinStep if 0. Otherwise, you can close this issue.

**Comment by beto-rodriguez** [comment]
Hi and thanks for the report, to reproduce this issue it is also necessary to set the `ForceStepToMin` to `true`.

This will throw now in future versions and let know the developer about it, thanks for the report.
