### ISSUE TITLE
Conditional Paint buggy visual

### ISSUE THREAD

**Issue by Diogoaf420** [beto-rodriguez/LiveCharts2#1132]
**Describe the bug**
When using conditional Paint with a lineSeries the line is drawn over the point unlink happens with the points when not painted with the condition.

1. Create a line series with a condition paint
2. See line drawn over the chart point.

My line series:
           var createdSerie = new LineSeries<GraphStop, StopGeometry>
            {
                Name = serviceDescriber,
                Fill = null,
                LineSmoothness = 0,
                DataLabelsFormatter = (point) =>  point.Model.IsStartOfTrip() ? point.Model.Stop.TripDescriber : "",
                DataLabelsPosition = DataLabelsPosition.Top,
                DataLabelsPaint = new SolidColorPaint(paintingColor, 3),
                Stroke = new SolidColorPaint(paintingColor, 1),
                GeometryStroke = new SolidColorPaint(paintingColor, 1),
                GeometryFill = new SolidColorPaint(SKColors.Black),
                GeometrySize = 5,
                Values = newServiceStops,
                TooltipLabelFormatter = (chartPoint) => $"{"Service: " + serviceDescriber}" + Environment.NewLine +
                $"{"TDN: " + chartPoint.Model.Stop.TripDescriber}" +
                ConstructArrivalAndDepartureString(chartPoint.Model)
            }.WithConditionalPaint(new SolidColorPaint(SKColors.Red, 3)).When((point) => point.Model.PaintNoStabling());

**Expected behavior**
Normal draw of chart point in top of the line.

**Screenshots**
Check that when the conditional paint is drawn with red the line overlaps the chart point. What not happens with the others.
![image](https://github.com/beto-rodriguez/LiveCharts2/assets/134623223/5101c07d-e0ac-4c21-9a91-d52f9c47efa8)

Thank you!

**Comment by beto-rodriguez** [comment]
this is now fixed in the latest release, thanks for the report .
