### ISSUE TITLE
Assigning Axes to Chart Control adds multiple axes

### ISSUE THREAD

**Issue by zeusongit** [beto-rodriguez/LiveCharts2#1136]
**Describe the bug**
We are working on migrating from LC1 to LC2. In this specific example, we are creating a (Cartesian)BarChart by assigning it a series in the code-behind and then assigning the values to CartesianChart.XAxes and YAxes as well, but the chart is rendering multiple axes on top of each other.

![Screenshot 2023-07-25 at 4 14 25 PM](https://github.com/beto-rodriguez/LiveCharts2/assets/32665108/ee3afee5-8d24-495d-b1d2-6d54fca408e1)

**To Reproduce**

Create a graph like this on the xaml side:
```
<UserControl x:Class="CoreNodeModelsWpf.Charts.Controls.BarChartControl"
             xmlns:local="clr-namespace:CoreNodeModelsWpf.Charts.Controls"
             xmlns:lvc="clr-namespace:LiveChartsCore.SkiaSharpView.WPF;assembly=LiveChartsCore.SkiaSharpView.WPF"
             xmlns:p="clr-namespace:Dynamo.Wpf.Properties"
             mc:Ignorable="d" 
             d:DesignHeight="300" d:DesignWidth="500" 
             Height="300" Width="300"
             d:DataContext="{d:DesignInstance local:BarChartControl}">

    <Grid>
        <lvc:CartesianChart Grid.Row="1"
                            Name="BarChartNode"
                            LegendPosition="Bottom">
//Adding Binding for XAxes and YAxes here makes no difference
        </lvc:CartesianChart>
    </Grid>
</UserControl>
```

Code-Behind DataContext(BarChartControl.xaml.cs)
```
public Axis[] XAxes { get; set; } = new Axis[]
        {
            new Axis
            {
                Name = "Index",
                NamePaint = Utilities.Colors.AxisColor,
                LabelsPaint = Utilities.Colors.AxisColor,
                TextSize = axisFontSize,
                SeparatorsPaint = Utilities.Colors.AxisSeparatorColor,
                NameTextSize = axisFontSize,
                ShowSeparatorLines = false,
            }
        };

public Axis[] YAxes { get; set; } = new Axis[]
        {
                new Axis
                {
                    Name = "Values",
                    NamePaint = Utilities.Colors.AxisColor,
                    LabelsPaint = Utilities.Colors.AxisColor,
                    TextSize = axisFontSize,
                    SeparatorsPaint = Utilities.Colors.AxisSeparatorColor,
                    NameTextSize = axisFontSize,
                }
        };

//CTOR
BarChartNode.Series = DefaultSeries();  //returns IEnumerable<ISeries>
BarChart.XAxes = XAxes;
BarChart.YAxes = YAxes;
```

**Expected behavior**
Single Axes to be displayed

**Screenshots**
![Screenshot 2023-07-25 at 4 33 28 PM](https://github.com/beto-rodriguez/LiveCharts2/assets/32665108/91629308-151c-4cc5-9639-7f7c58c29426)

**Desktop (please complete the following information):**
 - OS: Win10

**Additional context**
Recreating the chart this way also adds on to the number of axes, so if I close and reopen the chart it displays an increasing number of axes.

The charts are used inside [Dynamo](https://github.com/DynamoDS/Dynamo) nodes

**Comment by zeusongit** [comment]
The problem can be reproduced by using static colors in Axes.
In the above example `Utilities.Colors.AxisColor` is a static field in a static class `Colors`.

**Comment by beto-rodriguez** [comment]
Hi

I this is expected, paint tasks (like `SolidColorPaint`) should be unique for a canvas.

Instead make the color static:

```c#
Utilities.Colors.AxisColor = SKColors.Red; // or new SkColor(r, g, b, a)

// then:

public Axis[] YAxes { get; set; } = new Axis[]
        {
                new Axis
                {
                    NamePaint = new  SolidColorPaint(Utilities.Colors.AxisColor),
                }
        };
```

**Comment by beto-rodriguez** [comment]
I will close this for now, please feel free to open a new issue or reply here if you face another issue.
