### ISSUE TITLE
Gouge builder label offset and animation

### ISSUE THREAD

**Issue by MariusMK1** [beto-rodriguez/LiveCharts2#1139]
**Describe the bug**
I'm using a Gouge builder and after updating to Avalonia UI 11.0.1 and to Live charts 2.0.0-beta.860 The chart label  That should be positioned at the start now is positioned with a offset. And also has an animation where the label also turns and I can't seem to disable that. 

**To Reproduce**
Steps to reproduce the behavior

**Expected behavior**
Should behave  like in this example: https://lvcharts.com/docs/Avalonia/2.0.0-beta.850/samples.pies.gauge5

**Screenshots**
![image](https://github.com/beto-rodriguez/LiveCharts2/assets/93864647/9a3a7f40-a051-47f9-8dd9-8259e9292b28)

**Desktop (please complete the following information):**
 -Windows 10

**Comment by beto-rodriguez** [comment]
This is already fixed in `beta.900` thanks for the report.
