### ISSUE TITLE
RowSeries will not show rightly if the value of MinLimit is greater than 0

### ISSUE THREAD

**Issue by yangmijun** [beto-rodriguez/LiveCharts2#1140]
WPF, .net 5.0 with version 2.0.0-beta.860.
One CartesianChart with one RowSeries with a few values ( between 80 ~120), the chart is OK if the value of MinLimit is auto or 0, but if I set it to 20, or 50 e.g., the RowSeries will become a single line.

![org](https://github.com/beto-rodriguez/LiveCharts2/assets/8545433/c10f1577-a0c4-47a4-bd11-58ddb724863e)

![image](https://github.com/beto-rodriguez/LiveCharts2/assets/8545433/d2be9ccf-7dbb-4937-8030-2a6524949923)

![image](https://github.com/beto-rodriguez/LiveCharts2/assets/8545433/52027976-af61-49af-8b38-00a1c1c89370)

**Comment by beto-rodriguez** [comment]
this time is kow fixed in the latest release, thanks for the report.

**Comment by yangmijun** [comment]
@beto-rodriguez Thank you very much. I just test the 2.0.0-beta.900,  but till got wrong result. 
![image](https://github.com/beto-rodriguez/LiveCharts2/assets/8545433/9a548298-7f39-4830-b4c1-21aa7d961d99)

Maybe I did somthing wrong in the code.
This is the whole "MainWindow.xaml.cs" file:

using LiveChartsCore.SkiaSharpView;
using LiveChartsCore.SkiaSharpView.Painting;
using System.Collections.Generic;
using System.ComponentModel;
using System.Runtime.CompilerServices;
using System.Windows;
using SkiaSharp;
using LiveChartsCore;
using LiveChartsCore.SkiaSharpView.VisualElements;
using LiveChartsCore.Measure;
using RowSeriesTest.Annotations;

namespace RowSeriesTest
{
    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window, INotifyPropertyChanged
    {
        private List<double> _seriesValues = new();

        public Axis[] YAxes { get; set; } =
        {
            new()
            {
                Labels = new[] { "Value1", "Value2", "Value3", "Value4", "Value5", "Value6", "Value7" },
                ForceStepToMin = true,
                MinStep = 1,
                LabelsPaint =
                    new SolidColorPaint
                    {
                        Color = SKColors.Black,
                    },
            }
        };

        public Axis[] XAxes { get; set; } =
        {
            new()
            {
                //MinLimit = 0,  
                MinLimit = 20,  //will got wrong result
                //MaxLimit = 130,
                LabelsPaint =
                    new SolidColorPaint
                    {
                        Color = SKColors.Black,
                    },
            },
        };

        private ISeries[] _rowSeries;

        public ISeries[] RowSeries
        {
            get => _rowSeries;
            set
            {
                _rowSeries = value;
                OnPropertyChanged();
            }
        }

        public LabelVisual ChartTitle { get; set; }
            = new()
            {
                Text = "Chart With RowSeries",
                TextSize = 20,
                Paint = new SolidColorPaint
                {
                    Color = SKColors.Black,
                },
            };


        public MainWindow()
        {
            InitializeComponent();
            DataContext = this;

            RowSeries = Create_RowSeries();

            _seriesValues.AddRange(new[]
            {
                119.5,
                97.2,
                94,
                99.5,
                108,
                117,
                106
            });
        }

        private ISeries[] Create_RowSeries()
        {
            var ser1 = new RowSeries<double>
            {
                Values = _seriesValues,
                Fill = new SolidColorPaint(new SKColor(227, 127, 121)),
                DataLabelsPaint = new SolidColorPaint(SKColors.White),
                DataLabelsSize = 14,
                DataLabelsPosition = DataLabelsPosition.Middle,
                DataLabelsFormatter = point => point.Coordinate.PrimaryValue.ToString("F2"),
            };

            return new ISeries[] { ser1 };
        }

        public event PropertyChangedEventHandler? PropertyChanged;

        [NotifyPropertyChangedInvocator]
        protected virtual void OnPropertyChanged([CallerMemberName] string? propertyName = null)
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
        }
    }
}

**Comment by beto-rodriguez** [comment]
Let me give this a second check, I'll re-open to check this out.
