### ISSUE TITLE
DataLabel do not display

### ISSUE THREAD

**Issue by lindadamama** [beto-rodriguez/LiveCharts2#1145]
**Describe the bug**
![123123](https://github.com/beto-rodriguez/LiveCharts2/assets/48863486/0f707c60-1d85-488a-9fd0-dbb28adece6f)

![123](https://github.com/beto-rodriguez/LiveCharts2/assets/48863486/920d9aee-c45b-4011-b8bd-3c4948639f1f)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by beto-rodriguez** [comment]
I think they are there, they are just outside of the bounds of the chart,  try to set the alignment to bottom, or use the [DataPadding](https://lvcharts.com/api/2.0.0-beta.900/LiveChartsCore.LineSeries-5#property-DataPadding) property in your series to set a greater "data padding"

**Comment by lindadamama** [comment]
I try to increase the size of Datapadding, but the effect is not obvious
![123123123](https://github.com/beto-rodriguez/LiveCharts2/assets/48863486/d530b812-d6e3-44dd-93b1-b7f04009518f)

**Comment by lindadamama** [comment]
Because that will lead to inconsistent display styles, and the top line is not always on top

**Comment by beto-rodriguez** [comment]
the chart also has the DrawMargin property, it allows you to set a margin to the area where aeries are drawn.

**Comment by beto-rodriguez** [comment]
https://lvcharts.com/docs/WPF/2.0.0-beta.900/CartesianChart.Cartesian%20chart%20control#drawmargin-property

**Comment by lindadamama** [comment]
![image](https://github.com/beto-rodriguez/LiveCharts2/assets/48863486/621f33a0-1f90-4980-a737-868768673d0f)
Setting the margin seems to have no effect.

**Comment by beto-rodriguez** [comment]
Thanks for the feedback, it seems that the labels paint set a Clip to the draw margin, we need a way to change that, that is currently not supported.

**Comment by beto-rodriguez** [comment]
In beta.920 we can now customize the labels clip rectangle; in your case you can try:

```c#
new LineSeries<double>
{
    Values = new double[] { 2, 1, 3, 5, 3, 4, 6 },
    Fill = null,
    ClippingMode = LiveChartsCore.Measure.ClipMode.X, // None would also work 
}
```
