### ISSUE TITLE
Bug: Axis Labels Overlapping when Multiple Cartesian Charts used in the same WPF Window

### ISSUE THREAD

**Issue by arefmourtada** [beto-rodriguez/LiveCharts2#1146]
**Describe the bug**
I am using a tab control in WPF and including two Cartesian Charts in two different tabs.

**To Reproduce**
Once the window loads and navigate to one of the tabs with charts, the chart will shows properly. Once I go to the other tab with the other chart, the labels on the axis from both charts show up on the screen. 
If you navigate back to the other chart, the same happens as both charts have been display on the screen.

Each chart has it own properties to bind to. The data is displayed properly in the both charts. Only the axis (both x & y) are having doable labels.
 
```xaml
<TabControl TabStripPlacement="Left" >
        <TabItem  Height="50" HorizontalAlignment="Left"  >
            <TabItem.Header>
                <TextBlock Text="Grade Distribution" FontSize="16"/>
            </TabItem.Header>

            <lvc:CartesianChart x:Name="gradeDistributionChart"
                                Series="{Binding GradeDistributionChartData.Series}"
                                XAxes="{Binding GradeDistributionChartData.XAxes}"
                                YAxes="{Binding GradeDistributionChartData.YAxes}" />

        </TabItem>

        <TabItem  Height="50" HorizontalAlignment="Left" >
            <TabItem.Header>
                <TextBlock Text=" Submission" FontSize="16"/>
            </TabItem.Header>

            <Grid Margin="10">
                <StackPanel Orientation="Horizontal" HorizontalAlignment="Center">
                    <Label Content="Assignement Due Date" FontWeight="Bold" FontSize="20"/>
                    <Label x:Name="lblDueDate" FontSize="20"/>
                </StackPanel>
                
                <lvc:CartesianChart x:Name="submissionDistributionChart"
                                Series="{Binding SubmissionDateChartData.Series}"
                                XAxes="{Binding SubmissionDateChartData.XAxes}"
                                YAxes="{Binding SubmissionDateChartData.YAxes}"/>
            </Grid>

        </TabItem>
```
First Tab clicked on
![image](https://github.com/beto-rodriguez/LiveCharts2/assets/34233984/d8a5a94f-d848-40dc-af67-9384a6ab2d36)

Second Tab clicked on: notice the labels at the axis
![image](https://github.com/beto-rodriguez/LiveCharts2/assets/34233984/2b44e265-e234-4d48-8c8e-c619a6a4f93a)

Going back to first tab
![image](https://github.com/beto-rodriguez/LiveCharts2/assets/34233984/3378eb00-8b59-46f1-8cbe-4492b607b8df)

**Expected behavior**
When moving from one tab to another, the labels should not mix.

**Note**
If I do not set both the axises (x & y) for one of the charts, the labels will appear properly and wont mix.

**Update**
I tried adding both charts in the same tab to load the both charts at the same time. The label mixing happens immediately. 
![image](https://github.com/beto-rodriguez/LiveCharts2/assets/34233984/c7be805a-aae3-4626-b372-2a162d6b2ef0)

**Comment by arefmourtada** [comment]
I found the bug. I am using a single variable for the color of the labels for x axis and y axis for both charts. When I used different variables, the labels would not overlap.

**Comment by beto-rodriguez** [comment]
Glad you found it, that is a limitation for now, paints should be unique per axis instance, and also per canvas (you can't share between charts), it is not super intuitive, I will add that to the docs, maybe in a future release we can manage that case.
