### ISSUE TITLE
[Ask] How to plot live data without memory leak ?

### ISSUE THREAD

**Issue by kshfire** [beto-rodriguez/LiveCharts2#1147]
I'm a newbie to this library. First of all, this plot library is awesome; very beautiful and cool. 
I would like to know how to draw a graph in real time without the memory leak problem.

@kshfire That is a knows issue in WPF, WPF bindings can cause memory leaks if INotifyPropertyChanged is not implemented in your view model, that is an issue of WPF, not LiveCharts.

=> I used observable collection. Are there any my mistakes in the attached code snippet ?
=> I did two simple tests for plotting live data, but I've encountered memory leaks. Since I don't know how to plot live data without the memory leak, I'm appreciated if anyone let me know how to do it.

Test conditions
  - .NetFramework 4.7.2

Test1 : Using Non-UI thread
 - Using [https://github.com/beto-rodriguez/LiveCharts2/blob/master/samples/ViewModelsSamples/General/MultiThreading2/ViewModel.cs](url)
    But, just one thread is used as below

            /*
            // create {readTasks} parallel tasks that will add a point every {_delay} milliseconds
            for (var i = 0; i < readTasks; i++) {
                ReadData();
            }
            */
            ReadData();

Result:  By Visual studio debugging tool:   Memory is increasing....  Why ?  I think there is no memory generation in the ReadData() method.
If  only  _values.Add(s_current) and  _values.RemoveAt(0)  codes are removed in the ReadData method,  there is no memory leak.  Curiously, total number of items in the graph is not changed (Add and RemoveAt), but the memory is increased...Hmmm.  I need an expert help. ^^

![image](https://github.com/beto-rodriguez/LiveCharts2/assets/17819458/90a4b1a0-d0df-405b-93ba-0c1382a647c6)

Test2 : Using UI thread (DispatcherTimer)
  - Total sample numbers: 100
  - Using DispatcherTimer, the graph is updated.

=>  Likewise, the memory continues to grow.

    public class MainWindowViewModel : INotifyPropertyChanged
    {
        // Graph
        public ObservableCollection<ISeries> Series { get; set; }
        private ObservableCollection<double> observableValuesUpdateRate;
        public Axis[] XAxes { get; set; }
        public Axis[] YAxes { get; set; }

        const int _plotDataTotal = 100;

        private readonly DispatcherTimer MonitorTimer;
        Stopwatch _sw = new Stopwatch();

        public event PropertyChangedEventHandler PropertyChanged;
        protected void OnPropertyChanged(string name)
        {
            PropertyChangedEventHandler handler = PropertyChanged;
            if (handler != null) {
                handler(this, new PropertyChangedEventArgs(name));
            }
        }

        public MainWindowViewModel()
        {
            observableValuesUpdateRate = new ObservableCollection<double>();
            for (int i = 0; i < _plotDataTotal; ++i) {
                observableValuesUpdateRate.Add(0.0);
            }
            Series = new ObservableCollection<ISeries> {
                new ScatterSeries<double> {
                    Name = "Period",
                    Fill = new SolidColorPaint(SKColors.Green),
                    GeometrySize = 4,  
                    Values = observableValuesUpdateRate,
                },
            };
            // X axis
            XAxes = new Axis[] {
                new Axis {
                    Name = "Sample",
                    NamePaint = new SolidColorPaint(SKColors.Black),
                    LabelsPaint = new SolidColorPaint(SKColors.Black)
                }
            };
            YAxes = new Axis[] {
                new Axis {
                    Name = "Time [ms]",
                    NamePaint = new SolidColorPaint(SKColors.Black),
                    //TextSize = 10,
                    LabelsPaint = new SolidColorPaint(SKColors.Black),

                    SeparatorsPaint = new SolidColorPaint(SKColors.LightSlateGray) {
                        PathEffect = new DashEffect(new float[] { 3, 3})
                    },
                }
            };
            _sw.Start();

            MonitorTimer = new DispatcherTimer();
            MonitorTimer.Tick += OnMonitoring;
            MonitorTimer.Interval = TimeSpan.FromMilliseconds(50); // 50 [ms] => 20 [Hz]

            MonitorTimer.Start();
        }

        private void OnMonitoring(object sender, EventArgs e)
        {
            var elaspedTime = _sw.ElapsedMilliseconds;
            _sw.Restart();

            if (observableValuesUpdateRate.Count < _plotDataTotal) {
                observableValuesUpdateRate.Add(elaspedTime);
            } else {
                observableValuesUpdateRate.Add(elaspedTime);
                observableValuesUpdateRate.RemoveAt(0);
            }
        }
    }

**Comment by beto-rodriguez** [comment]
Hello

In the example in your image, the memory seems stable at ~110MB, does the memory consumption increases over time? 

The yellow marks in your image, means that the GC ran, that is not the optimal and might be improved in future versions, but at this point there are workarounds for that, please see https://github.com/beto-rodriguez/LiveCharts2/issues/1083 for more info.

**Comment by kshfire** [comment]
Thanks for your reply.

Below is a result for about 13 hours. (Begin: about 50 MB memory,  723 MB after about 13 hours)
It seems that memory release is not going well somewhere in the logic. 
I want to plot live data for a long time, but I couldn't apply it due to this memory issue.
I wonder if anyone has been doing live plotting for a long time.  

![image](https://github.com/beto-rodriguez/LiveCharts2/assets/17819458/6d6857ab-0f07-44dd-afcd-8921021f8c14)


The yellow marks in your image, means that the GC ran, that is not the optimal and might be improved in future versions, but at this point there are workarounds for that, please see https://github.com/beto-rodriguez/LiveCharts2/issues/1083 for more info.

==>  I will check Case 2. (First, I need to study codes to understand what the difference is)

**Comment by beto-rodriguez** [comment]
Thanks, I was able to reproduce the issue, I will try to get this fixed in the next release.

**Comment by kshfire** [comment]
@beto-rodriguez Thank you!!!

Looking forward to the next release. ^^

**Comment by beto-rodriguez** [comment]
Just published beta.910, the issue should be fixed there, please let me know if it works for you.

**Comment by kshfire** [comment]
I applied v9.11 and monitored the Test2 (live plotting (total 100 samples) based on Dispatcher Timer) for about 40 minutes.

The memory issue for live plotting seems to be resolved.  Looks perfect and Thanks ^^.

![image](https://github.com/beto-rodriguez/LiveCharts2/assets/17819458/3f8ab8d2-2fc7-442e-a216-ea7fbe21795f)

**Comment by beto-rodriguez** [comment]
Nice to read that!!! thanks for testing this out!
