### ISSUE TITLE
Tooltip background size and layers are broken

### ISSUE THREAD

**Issue by kojima-imamura** [beto-rodriguez/LiveCharts2#1154]
Version in which the problem occurred
--> beta.911

If you use "tooltip", the display will collapse.
Occurs when the first data has many digits and the second and subsequent names are long.
Also, the protruding "tooltip" overlaps the "legend".

![image](https://github.com/beto-rodriguez/LiveCharts2/assets/118875864/d47a59d6-94ad-42ce-a7e6-dd6ea8ff3db0)
![image](https://github.com/beto-rodriguez/LiveCharts2/assets/118875864/addd1a17-678b-467d-8b33-ddd429a1f7a3)

.\LiveCharts2-master\samples\WPFSample\Test\ChangeSeriesInstance\View.xaml
Edit Code
```
        <lvc:CartesianChart
            Series="{Binding Series}"
            XAxes="{Binding XAxes}"
            YAxes="{Binding YAxes}">
        </lvc:CartesianChart>
```
->
```
        <lvc:CartesianChart
            Series="{Binding Series}"
            XAxes="{Binding XAxes}"
            YAxes="{Binding YAxes}"
            LegendPosition="Right">
        </lvc:CartesianChart>
```

.\LiveCharts2-master\samples\ViewModelsSamples\Test\ChangeSeriesInstance\ViewModel.cs
Edit Code

```
        new LineSeries<double>
        {
            Values = new ObservableCollection<double> { 200, 558, 458, 249, 457, 339, 587 },
        },
        new LineSeries<double>
        {
            Values = new ObservableCollection<double> { 210, 400, 300, 350, 219, 323, 618 },
        },
```
->
```
        new LineSeries<double>
        {  
            Values = new ObservableCollection<double> { 200, 558, 458, 249, 457, 339000, 150000 },
        },
        new LineSeries<double>
        {
            Name = "NameName",
            Values = new ObservableCollection<double> { 210, 400, 300, 350, 219, 323, 618 },
        },
```

**Comment by beto-rodriguez** [comment]
Fixed in beta.920, thanks for the report!
