### ISSUE TITLE
StackedAreaSeries displays 0 values incorrectly

### ISSUE THREAD

**Issue by pkamp** [beto-rodriguez/LiveCharts2#1162]
**Describe the bug**
When there are at least two StackedAreaSeries and a 0 value is given, the display of this series is irritating. It is interpolated between the last non 0 value and 0.

**Expected behavior**
It should interpolate between the last value and the next value of the previous Series.

**Screenshots**
![image](https://github.com/beto-rodriguez/LiveCharts2/assets/64216673/1191e582-320b-471d-bc95-91e3ab530f72)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 21H2

**Comment by beto-rodriguez** [comment]
Thanks for the report, this is related to #863 and will be fixed with that issue in a future release.

**Comment by beto-rodriguez** [comment]
Fixed with the referenced commit and will be included in the next version of the library, thanks for the report!
