### ISSUE TITLE
When using a PieChart with two series, in order to make a "progressbar" effect, the piechart bugs. 

### ISSUE THREAD

**Issue by Juansero29** [beto-rodriguez/LiveCharts2#1163]
**Describe the bug**
When using a PieChart with two series, in order to make a "progressbar" effect, the piechart bugs. When I try to make the "count" value equal to the "Total" value the colors are inversed. Example, I want to have a piechart with two series, one representing 100 which is the total of items available, and another representing 50 which is the total of items purchased. When 100 items have been purchased, then the piechart bugs and it would seem like 0 items have been purchased from the 100 availble. 

**To Reproduce**
Here's a small project that reproduces the problem: [PieChart100Problem-master.zip](https://github.com/beto-rodriguez/LiveCharts2/files/12303615/PieChart100Problem-master.zip) also available in a [repo here](https://github.com/Juansero29/PieChart100Problem)

**Expected behavior**
The colors shouldn't be switch, the series should stay in the color they're supposed to be.

**Screenshots**
Here's some gifs that clearly shows the problem.

![PieChart100Problem_71jppli1hj](https://github.com/beto-rodriguez/LiveCharts2/assets/19156405/e2992111-d912-4b22-84fa-70a1654af3e2)
![Controls Tests_uJmYvqcePZ](https://github.com/beto-rodriguez/LiveCharts2/assets/19156405/c20c8d7a-837b-4155-827d-8d8cbc781ec6)

**Desktop (please complete the following information):**
 - OS: Windows (WinUI3)
 - Browser [e.g. chrome, safari] : NA

**Smartphone (please complete the following information):**
 - Version 2.0.0-beta.900

**Additional context**
Not any more info to add.

**Comment by beto-rodriguez** [comment]
Hi, it is interesting your case!

Even there is maybe a bug (not sure yet), I think that the main issue is how you are trying to achieve it, instead of using the total property (which is designed to be used in gauges) better try to calculate the completed and remaining parts, for example in your code, remove from the XAML the `Total` binding, then your `RefreshPieSeries` method shhould look like this:

```c#
private void RefreshPieSeries()
{
    var completed = CountValue;
    var remaining = TotalValue - CountValue;

    var newTotal = new PieSeries<ObservableValue>
    {
        MaxRadialColumnWidth = 20,
        HoverPushout = 0.0,
        Values = new ObservableValue[] { new ObservableValue { Value = remaining } },
        Stroke = null,
        Fill = new SolidColorPaint() { Color = SKColors.LightGray },
        DataLabelsSize = 14,
        IsHoverable = false,
    };

    var newCount = new PieSeries<ObservableValue>
    {
        MaxRadialColumnWidth = 20,
        HoverPushout = 0.0,
        Values = new ObservableValue[] { new ObservableValue { Value = completed } },
        Fill = new SolidColorPaint() { Color = SKColors.Orange },
        DataLabelsSize = 14,
        IsHoverable = false
    };

    if (Series != null)
    {
        var pieChartSeries = Series as List<PieSeries<ObservableValue>>;
        (pieChartSeries[0].Values.ToList())[0].Value = remaining;
        (pieChartSeries[1].Values.ToList())[0].Value = completed;
    }
    else
    {
        Series = new List<PieSeries<ObservableValue>>()
        {
            newTotal,
            newCount
        };
    }
}
```

and now it works:

![v](https://github.com/beto-rodriguez/LiveCharts2/assets/10853349/d06796d0-738e-49f8-b5ef-34fd31ad3a55)

I will close this for now, since it seems that the issue in your implementation and not in the library, but feel free to re-open or reply if the issue persists.

**Comment by Juansero29** [comment]
Just saw this now and indeed your workaround fixes the issue. Thanks!
