### ISSUE TITLE
PieChart is not refreshed in Avalonia with CommunityToolKit

### ISSUE THREAD

**Issue by geelapidus** [beto-rodriguez/LiveCharts2#1167]
In Avalonia with CommunityToolkit MVVM PieChart/Gauge are not refreshed although get updates    from ViewModel. It worked well with ReactiveUI.  
 
1. Create MVVM Avalonia 11 preview 7 or later C# project.
2. Nuget install CommunityToolkit MVVM 8.2 and LiveChartsCore.SkiaSharpView.Avalonia 2.0.0-...
3. Use proovided source files of code attached below
4. Expected behavior : Gauge should be visually updated.
5. Current behavior : the gauge is frozen and refreshed only if mouse hovers. 
6.OS Windows 11.  
Code 

[LivechartsIssue.pdf](https://github.com/beto-rodriguez/LiveCharts2/files/12311579/LivechartsIssue.pdf)

**Comment by beto-rodriguez** [comment]
This issue seems strange, LiveCharts should redraw every time the Gauge changes, as a work around you can also try to call the `chart.Update()` method.

**Comment by beto-rodriguez** [comment]
I will close this for now because we have a workaround and the API changed on the latest version, the new API is more stable and is recommended to follow it.

Thanks for the report!
