### ISSUE TITLE
NullReferenceException in Axis.cs (LiveChartsCore) due to _animatableBounds being set to null

### ISSUE THREAD

**Issue by steffos** [beto-rodriguez/LiveCharts2#1168]
**Describe the bug**
On some occasions my Maui app crash with a `NullReferenceException` that is thrown from Axis.cs (LiveChartsCore) since `_animatableBounds` is null.

![bild](https://github.com/beto-rodriguez/LiveCharts2/assets/1426950/22e387fe-5eaa-44eb-9ebe-1e80782e6f50)

This seems strange since `_animatableBounds` has a default value of `AnimatableAxisBounds` type:
![bild](https://github.com/beto-rodriguez/LiveCharts2/assets/1426950/75b26567-f0c1-45ee-8a17-1df6941a4930)

but is later on set to null in `RemoveFromUI`
![bild](https://github.com/beto-rodriguez/LiveCharts2/assets/1426950/631cbfc3-283a-4ce9-adea-137cb5d01fae)

Shouldn't it be `_animatableBounds = new();` in `RemoveFromUI`as well? As far as I can see, that change should avoid the `NullReferenceException` regardless of its origin.

**Expected behavior**
_animatableBounds should never be able to cause a `NullReferenceException`.

Thanks for an awesome library :)

**Comment by beto-rodriguez** [comment]
Thanks for the report, fixed with the referenced commit.
