### ISSUE TITLE
Is there a way to guarantee that the MinLimit value appears in the auto generated axis points?

### ISSUE THREAD

**Issue by edgiardina** [beto-rodriguez/LiveCharts2#1171]
**Describe the bug**
I'm unsure why "1" does not appear at the bottom of my Y axis on the left side of my chart. This is in .NET MAUI 7.0.86 on a Pixel 5

**Expected behavior**
The first entry in the axis should be 1. Instead it looks like in my chart the first and last lines of the chart aren't drawn?

**Screenshots**
Here, I expect that 1 appears at the bottom of the chart
![image](https://github.com/beto-rodriguez/LiveCharts2/assets/3627193/fb2f6f97-97f1-4893-8cd5-3d3f3813af07)

Here is the Axis used
```
public Axis[] RatingAxis { get; set; } =
{
    new Axis
    {
        MinLimit = 1,
        MinStep = 1,
        ForceStepToMin = true
    }
};
```

Here is the only series for this chart
```
var playerRatingSeries = new LineSeries<RatingHistory>
{
    Values = playerHistoryData.RatingHistory,
    Fill = null,
    GeometryFill = null,
    GeometryStroke = null,
    Stroke = new SolidColorPaint(SKColor.Parse(resourceColor.ToHex())) { StrokeThickness = 2 },
    Mapping = (history, point) =>
    {
        point.Coordinate = new Coordinate(history.RatingDate.Ticks, history.Rating);
    }
};
PlayerRatingHistoryLineSeries.Add(playerRatingSeries);
```

Here is the XAML for rendering the chart
```
<lvc:CartesianChart HeightRequest="300"
    Series="{Binding PlayerRatingHistoryLineSeries}" XAxes="{Binding TimeAxis}" YAxes="{Binding RatingAxis}">            
</lvc:CartesianChart>
```

**Smartphone (please complete the following information):**
 - Device: Android Pixel 5

**Comment by beto-rodriguez** [comment]
Hi

> I'm unsure why "1" does not appear at the bottom of my Y axis.

Because the step of the axis is 500, that means that it will draw a label each 500 units, it would draw the `0, but since you forced the axis to start at 1 (with `MinLimit = 1`) then it is ignored.

In a custom case like this, you can also pass your own separators array: 

https://github.com/beto-rodriguez/LiveCharts2/blob/master/samples/ViewModelsSamples/Axes/CustomSeparatorsInterval/ViewModel.cs

**Comment by beto-rodriguez** [comment]
I will close this for now, please feel free to reply or open a new issue if the issue persists.
