### ISSUE TITLE
NuGet installation error  "LiveChartsCore.SkiaSharpView.WinUI beta,911"

### ISSUE THREAD

**Issue by PRRoss** [beto-rodriguez/LiveCharts2#1173]
**Describe the bug**

Can't install LiveChartsCore.SkiaSharpView.WinUI beta,911.  I get an error (see attached), that says It only installs on "net6.0 =-Windows10.0.19041.  I have a later version of Windows 10.  I tried on two computers, with Window 10-19045.  The error message implies that I have Windows 7 - "Package LiveChartsCore.SkiaSharpView.WinUI 2.0.0-beta.911 is not compatible with net6.0-windows7.0".  

I am using Visual Studio 2022. using .NET6.0 and WPF. When I try to install this package I get the error:  I spent hours to make sure I didn't make some silly mistake (still possible).

NU1202: Package LiveChartsCore.SkiaSharpView.WinUI 2.0.0-beta.911 is not compatible with net6.0-windows7.0 (.NETCoreApp,Version=v6.0). Package LiveChartsCore.SkiaSharpView.WinUI 2.0.0-beta.911 supports: net6.0-windows10.0.19041 (.NETCoreApp,Version=v6.0).

I don't have Window7. I have tried this on two different computers without success.

**To Reproduce**
1, Use Visual Studio 2022 {I updated to the latest version).  
2, Select: "Tools\NuGet Package Manager\Manage NuGet Packages for Solution".  
3. Select "Browse" tab
4. Search for "Live Charts 2".
5. Select "LiveChartsCore.SkiaShartView.WinUI".
6. Select project to install into.
7. Select Install, follow the prompts.
8. Note the error in the 'Output" window.

**Expected behavior**
Should install the package.

**Screenshots**

**Desktop (please complete the following information):**
 Window 10-19045.3324

**Additional context**
<img width="1346" alt="Output Window" src="https://github.com/beto-rodriguez/LiveCharts2/assets/101659152/4513fde0-6b79-4c09-a9ff-4ee25885af5e">

**Comment by beto-rodriguez** [comment]
Hello

This issue is caused because your target framework is `net6.0-windows7.0`, can you please change it to `net6.0-windows10.0.19041` and let me know if it works?

**Comment by PRRoss** [comment]
Hello Alberto,

It worked!  Thank you so much.  I was afraid that I had overlooked
something since no one else seemed to have a problem.  I did read about the
target OS, but somehow didn't understand it.

So I hate to bother you over something like this.  I don't like to ask for
help so I always struggle before asking for help.  And you answered within
an hour!

Thanks again!

*Philip Ross*

*Software Engineer*

*[image:
https://docs.google.com/a/thermalproductsolutions.com/uc?id=0B_EF9cCUPppkcGJnTGVhVWVDdHc&export=download]*

TPS, LLC  •  2821 Old Route 15  •  New Columbia, PA 17856 | USA
Direct: (570) 538-72 <%28570%29%20538-7282>00  •  Main: (570) 538-7200  •
Fax: (570) 538-7380  •   Email: ***@***.*** ***@***.***>

**Comment by PRRoss** [comment]
Hello Alberto,

I have been trying to understand what NuGet packages I need for a .NET6.0
WPF application with the beta.911.  Is it supported in beta-911?

Looking at the packages on NuGet the package that looks obvious is

* *LiveChartCore.SkiaSharpView.WPF.  But it does not support .NET6.0*

[image: image.png]


   - I thought this must be it, but although it supports .NET6.0, I found
   that it was not compatible with WPF.

[image: image.png]

   - *I am pretty sure I need LiveChartsCore*
   - *and LiveChartsCore.SkiaSharpView*

I am not sure what else I need.  Should I go to another beta version?

Thank you for your patience!


*Philip Ross**Software Engineer*

*[image:
https://docs.google.com/a/thermalproductsolutions.com/uc?id=0B_EF9cCUPppkcGJnTGVhVWVDdHc&export=download]*

TPS, LLC  •  2821 Old Route 15  •  New Columbia, PA 17856 | USA
Direct: (570) 538-72 <%28570%29%20538-7282>00  •  Main: (570) 538-7200  •
Fax: (570) 538-7380  •   Email: ***@***.*** ***@***.***>

**Comment by beto-rodriguez** [comment]
Hello, it is compatible with net 6, 7, 8 and also net framework 4.6.2 and above, what is the error message you are getting?

**Comment by PRRoss** [comment]
Hello Alberto,

Thank you for your reply.  I have gone over things once more.  First I will
show you the error messages, then I will go over the process I used to set
things up that lead to this error..

ERROR MESSAGES:
[image: image.png]

VERIFICATION PROCESS(In Visual Studio 2022):

   1. Create new WPF project - Test2:
   2. Set Target Framework = .NET6.0
   3. Set 'Target OS Version' = 10.0.19041.0
   4. Set 'Supported OS Version' =  10.0.19041.0

Compile = Success.

   1. Add reference to 'LiveChartsCore' = 2,0.0-beta.920
   2. Compile = success
   3. Add reference to 'LiveChartsCore.SkiaSharpView' = 2,0.0-beta.920
   4. Compile = success
   5. Add reference to 'LiveChartsCore.SkiaSharpView.WinUI' = 2,0.0-beta.920
   6. Compile = Fail.  See error messages.

Here is what my dependencies look like.

[image: image.png]

Thank you Alberto!

Best Regards,


*Philip Ross**Software Engineer*

*[image:
https://docs.google.com/a/thermalproductsolutions.com/uc?id=0B_EF9cCUPppkcGJnTGVhVWVDdHc&export=download]*

TPS, LLC  •  2821 Old Route 15  •  New Columbia, PA 17856 | USA
Direct: (570) 538-72 <%28570%29%20538-7282>00  •  Main: (570) 538-7200  •
Fax: (570) 538-7380  •   Email: ***@***.*** ***@***.***>
