### ISSUE TITLE
WPF touch device feature like scrollable charts

### ISSUE THREAD

**Issue by DorisSMD** [beto-rodriguez/LiveCharts2#1175]
Thanks for this amazing chart library, it is really useful! 
I'm using  version **2.0.0 beta.911** for WPF application with .net 6 in Windows 10.
Want to know do we have the features: 
1. Scrollable chart inside of a container( like scrollviewer), if the chart length is longer than container length, dont need to compress all content, but show scroll bar. Like this pic: 
![image](https://github.com/beto-rodriguez/LiveCharts2/assets/65791880/493c3332-9b48-4ad3-88e8-5d747e8fc23b)
2. Can we only use zoom mode in panning and scroll the chart using touch? Like the image above, use touch scroll instead of mouse to scroll.
In current feature seems touch scroll can work after using zoom feature in the chart.

**Comment by beto-rodriguez** [comment]
Hello

> 1. Scrollable chart inside of a container( like scrollviewer), if the chart length is longer than container length, dont need to compress all content, but show scroll bar. Like this pic:

Yes, the sample is not on the website (will be updated soon), but you can find it here:

https://github.com/beto-rodriguez/LiveCharts2/blob/master/samples/WPFSample/General/Scrollable/View.xaml
https://github.com/beto-rodriguez/LiveCharts2/blob/master/samples/ViewModelsSamples/General/Scrollable/ViewModel.cs

> Can we only use zoom mode in panning and scroll the chart using touch? Like the image above, use touch scroll instead of mouse to scroll.

In Xamarin, Maui, Uno we do zooming and panning using the touch screen, but on WPF it is harder to test, in theory it was implemented by @wenya90, but there is an issue open related: https://github.com/beto-rodriguez/LiveCharts2/issues/553
