### ISSUE TITLE
MAUI iOS charts prevent scrolling

### ISSUE THREAD

**Issue by edgiardina** [beto-rodriguez/LiveCharts2#1180]
**Describe the bug**
If you have your line based chart in a scrollview, it seems that trying to start a scroll from a chart won't allow you to scroll. My guess is the interception of touches on the chart means that a touch down event isn't monitored or passed through as a drag event if it originated from a chart. I can scroll a scrolview that has a chart but my first touch of the scroll action needs to be on a non chart object like a label.

This does not appear to be a problem with a pie chart BTW. It only seems to be a problem in my testing for a bar chart or line chart.

**To Reproduce**

**Expected behavior**
A scroll started from a chart should work 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 

**Smartphone (please complete the following information):**

**Additional context**

**Comment by beto-rodriguez** [comment]
I am not able to reproduce this issue on net 7, already tried on Android and iOS.

When the chart zoom is enabled, this should be the expected behaviour, do you have more information that helps me to reproduce the issue?

**Comment by edgiardina** [comment]
Ok, I think this is a misunderstanding on my part. I set ZoomMode to disabled and I can start a scroll up/down pan on a chart now. Sorry about this! I guess it makes sense that pie charts worked too, since pie charts can't be zoomed. Thanks for the info!
