### ISSUE TITLE
LiveCharts.Definitions.Points.IChartPointView.ValidArea.get 返回 null。

### ISSUE THREAD

**Issue by ym9288** [beto-rodriguez/LiveCharts2#1181]
**Describe the bug**
![image](https://github.com/beto-rodriguez/LiveCharts2/assets/33686173/738316b1-470b-44c6-a98e-654d00c741f3)
![image](https://github.com/beto-rodriguez/LiveCharts2/assets/33686173/597d2491-16a8-4b7d-ad2e-7166366c82dc)
![image](https://github.com/beto-rodriguez/LiveCharts2/assets/33686173/1fe057fd-8d33-4777-bf62-77cd358d1647)
![image](https://github.com/beto-rodriguez/LiveCharts2/assets/33686173/74778d3a-007a-4f51-a851-21bc99f2e118)
![image](https://github.com/beto-rodriguez/LiveCharts2/assets/33686173/5865d0df-7fd3-4f95-8fba-277de8b7e7b2)
Attention： The time point at which the exception above occurs is anytime.
![image](https://github.com/beto-rodriguez/LiveCharts2/assets/33686173/6dfff895-1ad2-4a95-9fad-029e5d8ef010)
Some times appear OutofRangeException , it can be caused by anytime too.

Version:
![image](https://github.com/beto-rodriguez/LiveCharts2/assets/33686173/be6c2187-dcdd-4af0-98d4-5c008c4a6a65)
runtime:net4.7.2

**Comment by beto-rodriguez** [comment]
Hello, have you tried to invoke the changed in the UI Thread? it seems like the issue is that.

**Comment by ym9288** [comment]
> 

![image](https://github.com/beto-rodriguez/LiveCharts2/assets/33686173/3ceab8bc-cbca-4ba6-9443-35012996b8ba)


> Hello, have you tried to invoke the changed in the UI Thread? it seems like the issue is that.

Still  throw  exception

**Comment by ym9288** [comment]
This is an absolute mistake that will occur
This is Xaml:
      <wpf:CartesianChart >
            <wpf:CartesianChart.Series>
                <wpf:ScatterSeries x:Name="chart"/>
            </wpf:CartesianChart.Series>
        </wpf:CartesianChart>
![image](https://github.com/beto-rodriguez/LiveCharts2/assets/33686173/5df9cc0a-4331-4a48-864f-0ca4f6dfe32a)

All codes  done.
