### ISSUE TITLE
Scrollable Line Graph With Live Charts 2

### ISSUE THREAD

**Issue by tugsadhk** [beto-rodriguez/LiveCharts2#119]
Hello, in the first version, there is a scrollable chart with the Geared version, but I want to make a scrollable line graph with .Net5. Does this feature exist, if not when will it be added? Thank you.

**Comment by kMOsmane** [comment]
Hello , I wanted to know if the scrollable chart is still not available in livechart 2, otherwise when will it be available ?
thank you.

**Comment by IM-001** [comment]
I was hoping to use this as well.  Thanks

**Comment by beto-rodriguez** [comment]
There is now an example in the repository, it should be uploaded to the web site soon, in the meanwhile you can see an example here:

https://github.com/beto-rodriguez/LiveCharts2/tree/master/samples/WPFSample/General/Scrollable
