### ISSUE TITLE
BuildSolidGauge does not exist on type GaugeGenerator

### ISSUE THREAD

**Issue by Schoof-T** [beto-rodriguez/LiveCharts2#1191]
**Describe the bug**
I was currently creating a gauge chart by using `GaugeBuilder`. With the latest update this has become Obsolete and tells me to switch to `GaugeGenerator.BuildSolidGauge`. However upon trying to use `GaugeGenerator.BuildSolidGauge` I get the error: `BuildSolidGauge does not exist on type GaugeGenerator`

**To Reproduce**
1. Add `GaugeGenerator.BuildSolidGauge` to any code file

**Expected behavior**
I expected to be able to use the new method

**Screenshots**
![image](https://github.com/beto-rodriguez/LiveCharts2/assets/2319986/fdeaa660-e5f9-40a7-bf23-80fe8d039bf8)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 2.0.0 beta 920
 
**Additional context**
![image](https://github.com/beto-rodriguez/LiveCharts2/assets/2319986/355a425e-36ae-41ff-b3b9-e6ddc65d4b1a)

**Comment by Schoof-T** [comment]
> Hi and thanks for the report, docs are now updated:
> 
> https://livecharts.dev/docs/Maui/2.0.0-beta.920/samples.pies.gauge2

Thank you! I'm still having the issue that the method 'BuildSolidGauge' can not be found though. Am I missing a nuget package or something? I just want to generate an Image.

**Comment by beto-rodriguez** [comment]
>  I just want to generate an Image.

You can use the old `GaugeBuilder`, it was just marked as obsolete, because the new approach (as shown in the docs) should scale better in most of the cases, just ignore that warning.

LiveCharts2 is in a beta stage, so things can change (sorry about that); If you want to migrate to the new way of creating a gauge, you can follow the docs again, please forget your old code and try to follow the new docs.

I will close this for now, but feel free to reply or let me know if you face a new issue.

**Comment by Schoof-T** [comment]
> > I just want to generate an Image.
> 
> You can use the old `GaugeBuilder`, it was just marked as obsolete, because the new approach (as shown in the docs) should scale better in most of the cases, just ignore that warning.
> 
> LiveCharts2 is in a beta stage, so things can change (sorry about that); If you want to migrate to the new way of creating a gauge, you can follow the docs again, please forget your old code and try to follow the new docs.
> 
> I will close this for now, but feel free to reply or let me know if you face a new issue.

I want to migrate to the new way, but I am getting a compile time error: `BuildSolidGauge does not exist on type GaugeGenerator`, I copy pasted the code from the docs to my solution and it does **not** work.

That's what I've been trying to say. 😅

**Comment by beto-rodriguez** [comment]
Strange, it works, ensure that you are using the correct namespaces/NuGet packages.

**Comment by Schoof-T** [comment]
Which nuggets do I need? I posted the ones I am using in my opening ticket. ---- On Sun, 27 Aug 2023 16:41:17 +0200  ***@***.***  wrote ----
Strange, it works, ensure that you are using the correct namespaces/NuGet packages.

**Comment by beto-rodriguez** [comment]
The package `LiveChartsCore.SkiaSharpView` contains that method, so it should be available for you, you must also use the following namespace as shown in the docs:

```
using LiveChartsCore.SkiaSharpView.Extensions;
```

**Comment by Schoof-T** [comment]
Yup, I am using those. I'm working in a class libraby and dotnet 6, if that makes a difference? ---- On Sun, 27 Aug 2023 18:39:49 +0200  ***@***.***  wrote ----
The package LiveChartsCore.SkiaSharpView contains that method, so it should be available for you, you must also use the following namespace as shown in the docs:
using LiveChartsCore.SkiaSharpView.Extensions;

**Comment by beto-rodriguez** [comment]
Notice that the syntax in your image is incorrect, it should not be `new GaugeGenerator`, only `GaugeGenerator.BuildSolidGauge`
