### ISSUE TITLE
Data decimation for static data sets

### ISSUE THREAD

**Issue by feanor12** [beto-rodriguez/LiveCharts2#1194]
Is data decimation already included? Like plotting min/max values in a time span instead of every data point. This would likely be most effective for static data sets.

I saw that there is talk about a high-performance version, which I expect to include something like this.

If there is no data decimation strategy yet, where would this be implemented in the code? From my first glimpse into the code, it might fit into the `DataFactory.Fetch` method. Would this be correct?

Alternatively, a new series type might work, which switches from line/scatter types to a binned data series. Is there anything planned in that direction?

**Comment by beto-rodriguez** [comment]
Hello and thanks for the report.

Error bars were introduced in the last release, it was missing 2 things that you mentioned: ScatterSeries and DateTime; The referenced implements both features, in the next version of the library we will be able to:

![result](https://github.com/beto-rodriguez/LiveCharts2/assets/10853349/add90f86-c8be-4407-95cb-e91b8c864e0b)

With this code:

https://github.com/beto-rodriguez/LiveCharts2/blob/dev/samples/ViewModelsSamples/Error/Basic/ViewModel.cs
