### ISSUE TITLE
An empty grid (10*10) is drawn when use MAUI NET 8.0 framework

### ISSUE THREAD

**Issue by DJVova** [beto-rodriguez/LiveCharts2#1197]
**Describe the bug**
I made simple column chart from your samples. It's work good when use MAUI NET 7.0 framework. But if i change target framework on 8.0 - An empty grid (10*10) is drawn instead of normal chart. Axes and Legends also dissapear. This behavior is the same when compiling for windows or android

**To Reproduce**
Change target framework from 7.0 to 8.0

**Desktop (please complete the following information):**
 - OS: Windows 10 64
 - Visual studio preview 17.8.0-pre1.0
 - MAUI 8.0.0-preview.7.8842

**Smartphone (please complete the following information):**
 - Redmi note 9 pro
 - OS: Android 31

**Comment by beto-rodriguez** [comment]
I will close this for now, because I really think that this issue is not in the library, but thanks for the report, I will keep an eye on Maui net 8 release and see if there is a braking change on November (official release date).
