### ISSUE TITLE
Angular Gauge Breaks With negative values

### ISSUE THREAD

**Issue by bsampica** [beto-rodriguez/LiveCharts2#1199]
**Describe the bug**
When creating the angular gauge as described here:
https://livecharts.dev/docs/Avalonia/2.0.0-beta.920/samples.pies.angularGauge

And providing it with a few negative values, like a MinValue of -20 and a value of -10, the needle can and will point to the wrong point on the chart.  Also the chart does not draw the background correctly into the negative values.

**To Reproduce**
1. Create Gauge According to this: https://livecharts.dev/docs/Avalonia/2.0.0-beta.920/samples.pies.angularGauge
2. Set Random Generator _random in the code to allow a value from -20 to 50
3. Set the MinValue=-20 and MaxValue=50 on the Chart in XAML
4. Run the project, and click the button to randomly generate the values, and watch the needle.

**Expected behavior**
When providing the chart with negative values, it should respond to the correct range, draw the correct visual, and point to the correct value.

**Additional context**

<img width="809" alt="Screenshot 2023-08-29 at 12 21 44 PM" src="https://github.com/beto-rodriguez/LiveCharts2/assets/16546166/b932feb2-165d-4dba-991c-ce66e924fb30">
<img width="811" alt="Screenshot 2023-08-29 at 12 21 55 PM" src="https://github.com/beto-rodriguez/LiveCharts2/assets/16546166/a739ff2e-8128-4b5a-baf5-9b6722d0d1e2">
<img width="806" alt="Screenshot 2023-08-29 at 12 22 02 PM" src="https://github.com/beto-rodriguez/LiveCharts2/assets/16546166/913d2eda-9f9f-4879-a59b-e5d1cfaa874f">
<img width="809" alt="Screenshot 2023-08-29 at 12 22 23 PM" src="https://github.com/beto-rodriguez/LiveCharts2/assets/16546166/8646babc-4d8d-4d85-b2ab-591cc1552593">

**Comment by beto-rodriguez** [comment]
Thanks for the report, this is now fixed in 2.0.0-beta.950.

**Comment by bsampica** [comment]
> Thanks for the report, this is now fixed in 2.0.0-beta.950.

Awesome, thank you for the quick response!
