### ISSUE TITLE
Installing LiveChart into a WinUI Uno Platform

### ISSUE THREAD

**Issue by tompinnacle** [beto-rodriguez/LiveCharts2#1203]
Windows
Visual Studio 2022
.Net 6 & 7
Latest version of Uno - installed yesterday
Most recent version of LiveChart (pre-release)
New clean Uno WinUI solution
- Net 6 or 7
- Material
- Frame navigation

When I add the LiveChart NuGet, either at the solution level or the project level after install I get the error

A referenced assembly was compiled using a newer version of Microsoft.Windows.SDK.NET.dll. Please update to a newer .NET SDK in order to reference this assembly.

Updating everything else that can be updated in the solution doesn't help

**Comment by beto-rodriguez** [comment]
I am not completely sure of the root of this issue, but I have also seen this on WinUI without uno.

I am sure that the Uno team is aware of this issue, and they included a note in their template to fix that, you find a solution here: https://github.com/beto-rodriguez/LiveCharts2/issues/1002

**Comment by beto-rodriguez** [comment]
I will close this for now, let me know if that did not help.
