### ISSUE TITLE
Setting fonts with the new SolidColorPaint statement results in high CPU usage on linux operating systems (even over 70%)

### ISSUE THREAD

**Issue by lshiren** [beto-rodriguez/LiveCharts2#1212]
**Describe the bug**
In linux, the CPU usage was high when I moved the mouse over the livechart2 control quickly, even over 70%. But under windows10, the CPU usage is normal，less than 5%。 If I don't move the mouse, the CPU usage is descreased to lower than 5%.  Note that the CPU is i7  with 16GB memory.
We found that if we set the font by new SolidColorPaint statement, the problem would happen. If we comment the statement, the CPU usage is normal, however the labels in axes will disappear in linux OS.

**To Reproduce**
1. Under linux, run the livechart2 with the avalonia 11 release version.
2. ZoomMode is set to X.
3. set font by   LabelsPaint = new SolidColorPaint
{
Color = SKColors.White,
FontFamily = "华文楷体",
SKFontStyle = new SKFontStyle(SKFontStyleWeight.ExtraBold, SKFontStyleWidth.Normal,
SKFontStyleSlant.Italic)
},
4.  Run top command in the console.
5. See error

**Expected behavior**
The cpu usage is normal，less than 5% under linux OS。

What can I do with this problem

**Comment by beto-rodriguez** [comment]
Thanks for the report, we maybe need to check this with the Avalonia team.
