### ISSUE TITLE
WPF: Placing of multi-line labels in pie- and doughnut charts in PolarLabelsPosition.Outer hard

### ISSUE THREAD

**Issue by network-interface-controller** [beto-rodriguez/LiveCharts2#1219]
**Describe the bug**
1. The line spacing for multi-line labels has increased in version 2.0.0-beta.950 compared to 2.0.0-beta.700. Consequently, the labels require more space.
2. The default distance between the chart and the labels has increased which makes the labels exceed the available plotting area. This can be corrected to a certain extend by means of DataLabelsPadding but the distances are not adapted similarly for all labels:
![grafik](https://github.com/beto-rodriguez/LiveCharts2/assets/118933349/0f977a5a-732b-4d89-8a95-a274084d73a4)

To Reproduce
--> Create pie- or doughnut chart with multi-line labels and place them outside the chart

Expected behavior
- Reduce line spacing in multi-line labels to make them smaller
- Implement padding more symmetrically for labels around pie- and doughnut charts

Screenshots
Compare same chart in version 2.0.0-beta.700:
![grafik](https://github.com/beto-rodriguez/LiveCharts2/assets/118933349/652f9dd9-c944-445f-9bf9-3c3b1111e84f)

Desktop (please complete the following information):

    OS: Windows 10, Version 22H2
    Browser --> Not applicable; WPF app
    Version: LiveChartsCore 2.0.0-beta.950, LiveChartsCore.SkiaSharpView.WPF 2.0.0-beta.950
    Framework: .NET 7.0

Smartphone (please complete the following information):
--> NA

Additional context
Described behavior did not occur with version 2.0.0-beta.700

**Comment by beto-rodriguez** [comment]
Thanks for the report! This should be already fixed in the latest version; I added an example to the repo https://github.com/beto-rodriguez/LiveCharts2/blob/master/samples/ViewModelsSamples/Pies/OutLabels/ViewModel.cs (will be on the web site).

Feel free to reply or create a new issue if that is not the expected behaviour.
