### ISSUE TITLE
Make MotionCanvas.DisableAnimations public

### ISSUE THREAD

**Issue by essenius** [beto-rodriguez/LiveCharts2#122]
**Is your feature request related to a problem? Please describe.**
I am trying to create a rendering of a chart to a base64 string. The SaveImage method in SKCartesianCharts does pretty much what I need, except for the last step. Instead of saving to file, I need to convert it to a Base64 string and return that,
However I cannot create such a function because it SaveImage accesses MotionCanvas.DisableAnimations which is internal, so I cannot access it in my function.

**Describe the solution you'd like**
I can see two options that would work. The simplest is to make MotionCanvas.DisableAnimations public.

**Describe alternatives you've considered**
Make a variant of the SaveImage function that returns the image byte array or a base64 encoding of it, or some other format that allows me to convert the response into a base64 representation of the rendered image.

The only workaround I could find right now is calling SaveImage with a dummy file (to get the DIsableAnimations switched on),  delete the file, and then run a function to save to a base64 string. But that's a bit of an inefficient workaround.

**Additional context**
None.

**Comment by beto-rodriguez** [comment]
Well I took a different approach.

I think it is better to expose the `SKImage`, this was we will be able to do more things.

I also updated the "chart to image samples"

Please take a look and let me know it this solution is not enough, this fill fill be included in the next version of the library (about to publish)

https://github.com/beto-rodriguez/LiveCharts2/blob/master/samples/AvaloniaSample/General/ChartToImage/View.axaml.cs#L39
