### ISSUE TITLE
About Defining X-axis Display Time

### ISSUE THREAD

**Issue by XzMitsui** [beto-rodriguez/LiveCharts2#1220]
In the wpf project, I wanted to display the query start and end times on the X-axis in two minute intervals and hour minute second formats, so I did the following processing in the code

·var time = (DateTime.Parse(endTime.Text) - DateTime.Parse(startTime.Text)).TotalSeconds;

                        List<string> timeIntervals = new List<string>();

                        // 循环添加每两秒的时间间隔到列表中  
                        for (int i = 0; i <= time; i += 2)
                        {
                            // 计算当前时间间隔的起始时间和结束时间  
                            DateTime startIntervalTime = DateTime.Parse(endTime.Text).AddSeconds(i);
                            DateTime endIntervalTime = DateTime.Parse(startTime.Text).AddSeconds(i + 2);

                            // 将时间间隔格式化为HH:mm:ss格式并添加到列表中  
                            timeIntervals.Add(startIntervalTime.ToString("HH:mm:ss"));
                        }

                        lvcchart.XAxes = new[]
                        {
                             new Axis
                             {
                                Labels = timeIntervals,
                                Labeler = value => value.ToString("HH:mm:ss"),
                                UnitWidth = TimeSpan.FromSeconds(5).Ticks,
                                MinStep = TimeSpan.FromMinutes(2).Ticks,
                             }
                        };

                        lvcchart.Series = new ISeries[]
                        {
                            new LineSeries<double>
                            {
                                Values = values,
                                Stroke = new SolidColorPaint(SKColors.Green) { StrokeThickness = 2 },
                                Fill = null,
                                GeometryFill = null,
                                GeometryStroke = null
                            },
                            //new ColumnSeries<DateTimePoint>
                            //{
                            //    Values = new List<DateTimePoint>
                            //    {
                            //       new DateTimePoint(new DateTime())
                            //    }
                            //}
                        };·

It works, like in the picture, but I think this may not be the best implementation? May I ask what is the best practice to achieve this effect? Thank you
![1693971817450](https://github.com/beto-rodriguez/LiveCharts2/assets/39321910/fa8f6182-94f9-4776-9f3a-ed8fa15010a2)
![1693971791701](https://github.com/beto-rodriguez/LiveCharts2/assets/39321910/ac072a67-1740-4f0e-bb68-04abe1cb54a8)

**Comment by beto-rodriguez** [comment]
Hello, I am sorry I am afraid that I don't understand the issue, what is the problem you are facing?

**Comment by XzMitsui** [comment]
@beto-rodriguez Hey，I tried using other code logic to define the x-axis as a time point, but after reviewing the documentation, I may not have found the API for LiveChart2 to achieve this effect, just like the annotated part of the code in the second image, which uses 
`new ColumnSeries<DateTimePoint>
 {
     Values = new List<DateTimePoint>
       {
         new DateTimePoint(new DateTime())
       }
}`
but I didn't succeed.Can you guide me on how to use APIs to define the x-axis as a timeline? Thanks a lot.

**Comment by beto-rodriguez** [comment]
I am sorry, I am afraid that I do not fully understand your request.

Could you please let me know what is the expected result and what is the result you are getting?

**Comment by beto-rodriguez** [comment]
I will close this for now, feel free to reply with more info or create a new issue.

**Comment by kiran-reddy1** [comment]
@XzMitsui Did you find the answer to your issue ? I find that date is converted to ticks causing the issue.
