### ISSUE TITLE
Incomplete display of Y-axis values

### ISSUE THREAD

**Issue by BigGodKiKi** [beto-rodriguez/LiveCharts2#1222]
**To Reproduce**
In the avalonia project，when the value increases from 0 to 99, the width of the maximum value on the Y-axis is too narrow, resulting in the inability to see the first digit of 100

![{6be31767-d2cd-4a43-a279-5b2d1cb6f5f2}](https://github.com/beto-rodriguez/LiveCharts2/assets/36023523/e71e1021-b272-49cc-a515-24aa425f1c45)

**Comment by beto-rodriguez** [comment]
Hello, I am afraid that I need more info to reproduce the issue, can you please provide some code or a small repo with the issue?

**Comment by BigGodKiKi** [comment]
However, I may have discovered how the problem was caused. If I deleted the modifications to the Y-axis Padding, this problem would not have occurred
![image](https://github.com/beto-rodriguez/LiveCharts2/assets/36023523/7068624e-515e-4f4a-a89f-2fb992abfed6)

**Comment by beto-rodriguez** [comment]
Glad to hear that it was caused by the padding, there are improvements in the labels and axis measurement, I will keep an eye and try with rc2 version.
