### ISSUE TITLE
Long Press event to get data point from chart

### ISSUE THREAD

**Issue by AkashSaxenaSaviantConsulting** [beto-rodriguez/LiveCharts2#1224]
I have a requirement where, upon touching a specific point on a chart by using the plotted data points, I need to change the data source corresponding to the touched area's data points. Additionally, I want to ensure that zooming and panning functionality continues to work seamlessly. I have attempted to implement this functionality, and I can successfully obtain the details of the touched point using the ChartPointPointerDown event. However, when I zoom the chart, it both zooms and changes the data points, which is not the desired behavior. I am looking for a solution that allows me to distinguish between the zooming/panning action and the touch event, so that both can work concurrently without any issues. Is there an event, such as a long-pressed event, that can help me achieve this separation of zooming/panning and touch events?

**Comment by beto-rodriguez** [comment]
This was just improved on the dev branch and will be included in the next version of the library, now zooming and panning works much better on touch screens, touch pads mouse (and magic mouse).

On the latest NuGet package, the [scrollable](https://livecharts.dev/docs/Maui/2.0.0-beta.950/samples.general.scrollable) example is not working working properly on IOS, Android and MacCatalyst, but now it works properly on the dev branch, to fix that I had to go to the native controls events and use the [UILongPressGestureRecognizere](https://github.com/beto-rodriguez/LiveCharts2/blob/dev/src/LiveChartsCore.Behaviours/ChartBehaviour.MacCatalyst.cs#L61C31-L61C31) on Mac Catalyst, and the [touch event](https://github.com/beto-rodriguez/LiveCharts2/blob/dev/src/LiveChartsCore.Behaviours/ChartBehaviour.Android.cs#L48) on Android.

In the next version of LiveCharts for MAUI, you will also have the `PressedCommad` and `ReleasedCommand` (sample [here](https://github.com/beto-rodriguez/LiveCharts2/blob/dev/samples/MauiSample/General/Scrollable/View.xaml)), that could be useful for you to detect a long press.

In case the new commands are not enough, you could build your own implementation, similar to what the library does here: https://github.com/beto-rodriguez/LiveCharts2/blob/dev/src/LiveChartsCore.Behaviours, I will consider an example based on this case for the site/repo.

**Comment by AkashSaxenaSaviantConsulting** [comment]
Hello,

Thank you for your response.

I would like to inquire about the availability of the LongPressedEvent in Xamarin.Forms. Could you please confirm if this event will be introduced in Xamarin.Forms, and if so, in which version we can expect it?

I have plans to migrate my app to .NET MAUI, but before doing so, I need to implement this feature in my Xamarin.Forms application. Your assistance in determining when this feature will be available in Xamarin.Forms would be greatly appreciated.

**Comment by beto-rodriguez** [comment]
Implementing this in Xamarin forms, this could be implemented but there is no date for it, the good news is that this will work in the next verions of MAUI and Uno.

**Comment by beto-rodriguez** [comment]
I have been trying to implement this feature without success, currently the library shares the same code for Uno and MAUI, that makes it easy to maintain, but on Xamarin I can't find a way to make it work, the idea is to get the Xamarin handlers and attach the events defined in https://github.com/beto-rodriguez/LiveCharts2/blob/dev/src/LiveChartsCore.Behaviours to the native controls, maybe I am missing something, so any help or a PR is appreciated, the only alternative I can see for now is to use a custom render, but that would be harder to maintain.

This will not be supported for now, but a PR is welcome.

**Comment by beto-rodriguez** [comment]
I will close this for now, sadly this seems hard to maintain, I cannot find an easy way to share the MAUI, Uno and Xamarin code, for now this will not be implemented in Xamarin, the good news is that this works perfectly fine on MAUI.
