### ISSUE TITLE
TappedCommand  is no longer working in beta 950

### ISSUE THREAD

**Issue by upswing1** [beto-rodriguez/LiveCharts2#1227]
**Describe the bug**
When clicking on a chart  TappedCommand="{Binding TappedCommand_Chart11}" is no longer bound in the view model. It used to work in the previous version..

**To Reproduce**
tap on  a chart  in my case click on wndows 11 app

**Expected behavior**
it should work as in the previous version
tappedCommand should trigger an action in the view model

 public Command TappedCommand_Chart11 { get; }

TappedCommand_Chart11 = new Command((parameters) =>
{ never gets there
 }

**Screenshots**
NA
**Desktop (please complete the following information):**
 - OS :windows 11 using .net Maui
 

**Smartphone (please complete the following information):**
 -NA

**Additional context**
It used to work in previous version

**Comment by beto-rodriguez** [comment]
This was replaced by the `PressedCommand` and `ReleasedCommand`, here is an example:   https://livecharts.dev/docs/Maui/2.0.0-rc1/samples.general.scrollable
