### ISSUE TITLE
WPF: Not working ZIndex with Stacked Step Area

### ISSUE THREAD

**Issue by lolaverde** [beto-rodriguez/LiveCharts2#1236]
I'm trying to place visual elements and sections on top of graphs. In the other types it works fine but when I use StackedStepAreaSeries it does not place any element type on top. When you modify the zindex values the graph is always on top. Here I give an example

<img width="109" alt="image" src="https://github.com/beto-rodriguez/LiveCharts2/assets/40018762/3f5e1465-30e4-492d-a594-18de959121e7">

**Comment by beto-rodriguez** [comment]
Hello, stacked area series have this limitation for now, please see https://github.com/beto-rodriguez/LiveCharts2/issues/862 for more info, feel free to reply if that does not work for you.
