### ISSUE TITLE
The type or namespace name 'Configure' does not exist in the namespace 'LiveCharts'

### ISSUE THREAD

**Issue by wangdaojun1985** [beto-rodriguez/LiveCharts2#1243]
Hi, in version 2.0.0-beta.950, this doesn't seem to work.
![123](https://github.com/beto-rodriguez/LiveCharts2/assets/87227314/cd41c912-6c45-426b-ad45-426a7001f051)

**Comment by beto-rodriguez** [comment]
It exits, it is strange, it seems that you are missing a NuGet package, or some conflict with your namespaces.

**Comment by wangdaojun1985** [comment]
Thanks, the problem is solved, it is wrong to install both the first and second versions of the NuGet package.
