### ISSUE TITLE
Custom labels live chart in WPF

### ISSUE THREAD

**Issue by phanthanhdat077** [beto-rodriguez/LiveCharts2#1249]
Help me with how I can custom labels like that. Any suggest? 
![image](https://github.com/beto-rodriguez/LiveCharts2/assets/34691283/92c54142-8671-493b-87ad-e244e894bd47)

**Comment by beto-rodriguez** [comment]
Hello.

Yes this can be done, but there are no docs about it, you need to dig into the source code.

1. Create your own label, you can take the [LabelGeometry  class](https://github.com/beto-rodriguez/LiveCharts2/blob/master/src/skiasharp/LiveChartsCore.SkiaSharp/Drawing/Geometries/LabelGeometry.cs) for reference, actually you could just inherit from it, and override the `OnDraw` method to create the background you need.
2. Implement your custom label in your series, for example, [this](https://github.com/beto-rodriguez/LiveCharts2/blob/master/src/skiasharp/LiveChartsCore.SkiaSharp/ColumnSeries.cs#L40) is the default implementation with the default geometries of the library.

I will close this for now, hopefully in a future will have better docs on this subject, but at this point feel free to reply if you need further assistance.

**Comment by phanthanhdat077** [comment]
Thank hope it will have a document about it
