### ISSUE TITLE
Chinese Series name display garbled code

### ISSUE THREAD

**Issue by 285984303** [beto-rodriguez/LiveCharts2#1252]
**Describe the bug**
Chinese Series name display garbled code

**Comment by beto-rodriguez** [comment]
Please refer to the docs, or search on the issues before open a new one.

https://livecharts.dev/docs/WPF/2.0.0-rc1/Overview.Installation

**Comment by 285984303** [comment]
> Please refer to the docs, or search on the issues before open a new one.
> 
> https://livecharts.dev/docs/WPF/2.0.0-rc1/Overview.Installation

![图片](https://github.com/beto-rodriguez/LiveCharts2/assets/3397070/e29d9002-283c-4276-86d2-5cb09825e925)
The type or namespace name 'Configure' does not exist in the namespace 'LiveCharts' (are you missing an assembly reference?)
