### ISSUE TITLE
How can LiveCharts clear drawn points?

### ISSUE THREAD

**Issue by 285984303** [beto-rodriguez/LiveCharts2#1253]
How can LiveCharts clear drawn points?

**Comment by beto-rodriguez** [comment]
https://livecharts.dev/docs/WPF/2.0.0-rc1/samples.lines.autoupdate

**Comment by 285984303** [comment]
> https://livecharts.dev/docs/WPF/2.0.0-rc1/samples.lines.autoupdate

Okay, thank you
