### ISSUE TITLE
Why is there only one normal display for mouse zoom?

### ISSUE THREAD

**Issue by 285984303** [beto-rodriguez/LiveCharts2#1257]
**Describe the bug**
Why is there only one normal display for mouse zoom?

![5F(6`{${Q)%% PNU4MIG`{W](https://github.com/beto-rodriguez/LiveCharts2/assets/3397070/499cc6ad-cc76-4e02-a212-8bbd6c5cf06f)

**Comment by beto-rodriguez** [comment]
I will close this for now, feel free to add more details or create a new issue with more info so we can reproduce and fix this.
