### ISSUE TITLE
How can I double-click a point to delete it?

### ISSUE THREAD

**Issue by 285984303** [beto-rodriguez/LiveCharts2#1258]
How can I double-click a point to delete it?

**Comment by beto-rodriguez** [comment]
https://livecharts.dev/docs/WPF/2.0.0-rc1/samples.events.cartesian

**Comment by 285984303** [comment]
> https://livecharts.dev/docs/WPF/2.0.0-rc1/samples.events.cartesian

Okay. Thank you.
