### ISSUE TITLE
How can livecharts add events to points?

### ISSUE THREAD

**Issue by 285984303** [beto-rodriguez/LiveCharts2#1260]
How can livecharts add events to points?

**Comment by beto-rodriguez** [comment]
yes, https://livecharts.dev/docs/WPF/2.0.0-rc1/samples.events.cartesian

**Comment by 285984303** [comment]
> yes, https://livecharts.dev/docs/WPF/2.0.0-rc1/samples.events.cartesian

Okay. Thank you.
