### ISSUE TITLE
Tooltip

### ISSUE THREAD

**Issue by caio27093** [beto-rodriguez/LiveCharts2#1262]
**Is your feature request related to a problem? Please describe.**

I am facing a problem with the tooltip display. When I use the emulator simulating mouse clicks it works and shows the tooltip but on a real device when I try to activate it with touch it doesn't work

Should it really be like this? Would there be any way around it? because I couldn't

**Comment by beto-rodriguez** [comment]
Hello, which version of LiveCharts are you using?

**Comment by ckmstydy** [comment]
Encountered the same problem.

**Comment by ckmstydy** [comment]
Encountered the same problem. Sometimes the tooltip works, sometimes it doesn't. Version of LiveCharts：2.00-rc1.2、2.00-bate950(I only tried these two versions)

**Comment by beto-rodriguez** [comment]
This had a huge improvement in version `rc1`, now we use the native events of each OS, for more info see:

https://github.com/beto-rodriguez/LiveCharts2/releases/tag/2.0.0-rc1
