### ISSUE TITLE
Charts will become misaligned and disordered when zoomed in and out with the mouse

### ISSUE THREAD

**Issue by 285984303** [beto-rodriguez/LiveCharts2#1267]
![图片](https://github.com/beto-rodriguez/LiveCharts2/assets/3397070/9ffcae90-340f-4542-ab3a-6cea86b76d3e)
Charts will become misaligned and disordered when zoomed in and out with the mouse

**Comment by 285984303** [comment]
![图片](https://github.com/beto-rodriguez/LiveCharts2/assets/3397070/aa73306f-a9b8-4987-bb80-7e66fb7d8612)
This is normal

**Comment by beto-rodriguez** [comment]
Hi and thanks for the report!

Can you provide some code please?

**Comment by beto-rodriguez** [comment]
I will close this for now, feel free to add more details or create a new issue with more info so we can reproduce and fix this.

**Comment by 285984303** [comment]
> Hi and thanks for the report!
> 
> Can you provide some code please?

 Series.Add(new ScatterSeries<ObservablePoint>
 {
     Name = "Pressure",
     Fill = new SolidColorPaint(SKColors.Blue),
     Stroke = null,
     GeometrySize = 3,
     IsHoverable = true,
     ScalesXAt = 2,
     ScalesYAt = 0,
     // = null,
     //DataPadding = new LvcPoint(2, 2),
     //TooltipLabelFormatter = (chartPoint) => $"{chartPoint.Context.Series.Name}: {chartPoint.SecondaryValue}, {chartPoint.PrimaryValue}",
     YToolTipLabelFormatter = (point) => $"{point.Coordinate.PrimaryValue}({point.Model.X})",
     Values = pointsC
 });

**Comment by 285984303** [comment]
> Hi and thanks for the report!
> 
> Can you provide some code please?

public static LiveChartsCore.SkiaSharpView.Axis[] XAxes { get; set; } =
{
    new Axis
    {
        //Name = "温度",
        //Labels = new string[] {"-70", "-60", "-50", "-40", "-30", "-20", "-10", "0", "10", "20", "30", "40", "50", "60", "70", "80", "90", "100" },
        //Labeler = val => val + "°",
        //LabelsRotation = 0,
        //UnitWidth = 0.01,
        //SeparatorsPaint = new SolidColorPaint(new SKColor(200, 200, 200)),
        //SeparatorsAtCenter = false,
        //TicksPaint = new SolidColorPaint(new SKColor(35, 35, 35)),
        //TicksAtCenter = true,
        //MinStep = 0.1,
        //ForceStepToMin = true,
        MinStep = 50,
        MinLimit = -90,
        MaxLimit = 110,
        LabelsPaint = new SolidColorPaint
        {
            Color = SKColors.Red,
            //SKTypeface = SKFontManager.Default.MatchCharacter('汉') // 汉语 
        },
        //NamePaint = new SolidColorPaint{
        //    SKTypeface = SKFontManager.Default.MatchCharacter('汉') // 汉语 
        //},
    },
    new Axis
    {
        //Name = "H/T",
        //Labels = new string[] {"-70", "-60", "-50", "-40", "-30", "-20", "-10", "0", "10", "20", "30", "40", "50", "60", "70", "80", "90", "100" },
        //Labeler = val => val + "°",
        //LabelsRotation = 0,
        //UnitWidth = 0.01,
        //SeparatorsPaint = new SolidColorPaint(new SKColor(200, 200, 200)),
        //SeparatorsAtCenter = false,
        //TicksPaint = new SolidColorPaint(new SKColor(35, 35, 35)),
        //TicksAtCenter = true,
        MinStep = 50,
        //ForceStepToMin = true,
        MinLimit = -90,
        MaxLimit = 110,
        IsVisible = false,
        Position = LiveChartsCore.Measure.AxisPosition.Start,
        LabelsPaint = new SolidColorPaint
        {
            Color = SKColors.Green,

            // you need to enable the Chinese characters for SkiaSharp
            // use the SKFontManager.Default.MatchCharacter() SkiaSharp function.

            //SKTypeface = SKFontManager.Default.MatchCharacter('汉') // 汉语 
            // SKTypeface = SKFontManager.Default.MatchCharacter('أ'), // Arab
            // SKTypeface = SKFontManager.Default.MatchCharacter('あ'), // Japanese
            // SKTypeface = SKFontManager.Default.MatchCharacter('Ж'), // Russian
        }
    },
    new Axis
    {
        //Name = "H/T",
        //Labels = new string[] {"-70", "-60", "-50", "-40", "-30", "-20", "-10", "0", "10", "20", "30", "40", "50", "60", "70", "80", "90", "100" },
        //Labeler = val => val + "°",
        //LabelsRotation = 0,
        //UnitWidth = 0.01,
        //SeparatorsPaint = new SolidColorPaint(new SKColor(200, 200, 200)),
        //SeparatorsAtCenter = false,
        //TicksPaint = new SolidColorPaint(new SKColor(35, 35, 35)),
        //TicksAtCenter = true,
        
        MinStep = 250,
        //ForceStepToMin = true,
        MinLimit = 0,
        MaxLimit = 1200,
        Position = LiveChartsCore.Measure.AxisPosition.End,
        LabelsPaint = new SolidColorPaint
        {
            Color = SKColors.Blue,

            // you need to enable the Chinese characters for SkiaSharp
            // use the SKFontManager.Default.MatchCharacter() SkiaSharp function.

            //SKTypeface = SKFontManager.Default.MatchCharacter('汉') // 汉语 
            // SKTypeface = SKFontManager.Default.MatchCharacter('أ'), // Arab
            // SKTypeface = SKFontManager.Default.MatchCharacter('あ'), // Japanese
            // SKTypeface = SKFontManager.Default.MatchCharacter('Ж'), // Russian
        }
    }
};

**Comment by 285984303** [comment]
> Hi and thanks for the report!
> 
> Can you provide some code please?

                                <ScrollViewer x:Name="scrollChat" Height="{Binding WinHeight.Value}" Grid.Row="1" CanContentScroll="False" PanningMode="None" HorizontalScrollBarVisibility="Disabled" VerticalScrollBarVisibility="Auto">
                                    <lvc2:CartesianChart Name="cartesianChart1" Series="{Binding Series}" ZoomMode="ZoomX" XAxes="{Binding XAxes}"
YAxes="{Binding YAxes}" Height="{Binding ChartHeight.Value}" DrawMargin="{Binding Margin}" ChartPointPointerDownCommand="{Binding DrillDownCommand}"  EasingFunction="{x:Null}">

                                        
                                         <lvc2:CartesianChart.CacheMode>
                                            <BitmapCache EnableClearType="False"  RenderAtScale="1"  SnapsToDevicePixels="False" />
                                        </lvc2:CartesianChart.CacheMode>
                                    </lvc2:CartesianChart>
