### ISSUE TITLE
overriding zoom and zoom out functionality on button click

### ISSUE THREAD

**Issue by VPatel28** [beto-rodriguez/LiveCharts2#1271]
**Is your feature request related to a problem? 
No

There are few points would be considering regarding the implementation. There are 3 different charts on single window, I want to keep x axis different for each chart but wants to keep and show single Y axis between 3 different charts.

Here each chart consists of multiple series. below are the few functionalities that can be done.

**Describe the solution you'd like**
1. Shared Y axis (show one Y and different X against each chart)
2. Custom zoom in and zoom out function - which can zoom all 3 charts same time with call on button click (with Reset to normal)

**Describe alternatives you've considered**
I am looking for overriding zoom and zoom out functionality.

**Additional context**

**Comment by beto-rodriguez** [comment]
Hello

I think there is no need to override the zoom method, zooming and panning is extremmely simple on LiveCharts, it is just controlled by the `Axis.MinLimit ` and `Axis.MaxLimit` properties:

https://livecharts.dev/docs/WPF/2.0.0-rc1/samples.axes.paging

To reset the zoom, all you need to do is set those properties to `null`.

https://livecharts.dev/docs/wpf/2.0.0-rc1/CartesianChart.Axes%20properties#maxlimit-and-minlimit-properties

I will close this for now but let me know if I missed something.
