### ISSUE TITLE
Deformation tween animation on linked data source changed

### ISSUE THREAD

**Issue by Flithor** [beto-rodriguez/LiveCharts2#1273]
![image](https://github.com/beto-rodriguez/LiveCharts2/assets/23412916/18d2dfa6-99ed-4534-b95e-b3c8b69b9daa)
Suppose this: I've display the count of data as bar chart. And I want to switch it to a line chart to show the trend of data.  
Currently can only remove existing bar charts and add new line chart data. During which there is only animation of the bar chart disappearing and the line chart drawing.  

If can directly transform from a bar chart to a line chart by a tween animation, it will have a very nice visual experience.

Just a idea. I think may hard to make it.

**Comment by beto-rodriguez** [comment]
It is a great idea, but it is really complex to do that, bar charts are just rounded rectangles, a line chart is cubic Bezier, do you have a clue on how to create a smooth transition between these shapes?

**Comment by beto-rodriguez** [comment]
This is an interesting feature but for now I will close this, but feel free to reply if you know a method, we can follow to generate this kind of transitions.

**Comment by Flithor** [comment]
@beto-rodriguez I've found this: https://github.com/eropple/UnglidePCL
I've not tried so not sure it work.

**Comment by Flithor** [comment]
The second: https://github.com/HandyOrg/HandyControl#geometryanimation
