### ISSUE TITLE
Is it possible to run on Blazor Server?

### ISSUE THREAD

**Issue by changingmission** [beto-rodriguez/LiveCharts2#1274]
I've used LiveCharts2 for one of my project & wasm app is running in AutoMode .net 8, its not working in first run when site connected as BlazorServer rendering.

**Comment by beto-rodriguez** [comment]
**Short answer**

Yes you can, generate the image then use an `<img />` tag to display the generated image on the server:

https://livecharts.dev/docs/WPF/2.0.0-rc1/samples.general.chartToImage#build-an-image-in-the-server-side-or-console-app

**More details**

The Blazor package provided on NuGet is for Blazor web assembly (or WASM), both technologies (Server and WASM) are extremely different.

On WASM, LiveCharts is running on the browser, thus we can get a nice FPS rate, and nice animations, but on Blazor server there is no practical way to run LiveCharts on the server and display it in the client (with animations and all the things of the library).

I will close this for now, but feel free to reply if you need further assistance.
