### ISSUE TITLE
How to bind IsVisible property to Source object

### ISSUE THREAD

**Issue by mpogra** [beto-rodriguez/LiveCharts2#1275]
Is there a way I can bind the `IsVisibile` property of LineSeries to my custom object observable property? I can have many line Graphs in a single CartesianChart (each can have at max 4 points) and the user has the ability to control which series he wants to see using the filter so I need to hide series dynamically.

Earlier with LiveChart1, I used `LineSeries.SetBinding` but I don't see any similar method with LiveChart2.x.

**Comment by beto-rodriguez** [comment]
You need to toggle the `Series.IsVisible` property.

In `v2` series do not inherit from `FrameworkElement`, this increases performance drastically, but removes the ability to creating Bindings, you can no longer use the `SetBinding` method on a series, but that does not mean that you cannot use bind the series visibility on Xaml, for example: https://livecharts.dev/docs/WPF/2.0.0-rc1/samples.general.visibility

I will close this for now, but feel free to reply or open a new issue if you are not able to find a solution for your case.

**Comment by mpogra** [comment]
Thanks for the details, I was able to achieve it in a different way.
