### ISSUE TITLE
Point getting clipped and tooltip overlapping over the series data point

### ISSUE THREAD

**Issue by DevHasher** [beto-rodriguez/LiveCharts2#128]
On plotting the line series, I m facing the following 2 issues:-

1.  Clipping issue
 if the values on series 1 are 0 and series 2 are 240+, the data points on the graph are getting clipped as highlighted in the below image
![image](https://user-images.githubusercontent.com/23658195/128041142-a7c8e32d-bf01-4298-a96b-2cfe3c727d95.png)
Expected behavior is that there should be some margin around the min max data points as below
![image](https://user-images.githubusercontent.com/23658195/128041355-4997944d-2264-4fd1-af80-845170ffbcd1.png)

2. The tooltip is coming on top of series ABCD, making it difficult to select or highlight the data point on that series, as highlighted in the image below
![image](https://user-images.githubusercontent.com/23658195/128047794-b8ec1619-2a60-4774-9e9c-1e0409b60d79.png)

**Comment by LabuzzMichal** [comment]
Please kindly use template when you report a bug.

**Comment by beto-rodriguez** [comment]
This fix will be included in the next version of the library, thanks for the report
