### ISSUE TITLE
Uno WASM (WinUI3): Tooltip and Crosshair are not shown.

### ISSUE THREAD

**Issue by SirArty** [beto-rodriguez/LiveCharts2#1281]
**Describe the bug**
Tooltip and Crosshair are not shown in Uno WASM (WinUI3).

**Expected behavior**
Crosshair and tooltips should appear on mouse hover.

**Desktop **
 - Browser [edge, chrome].
 

**Additional context**
Tested with both uno platform template and UnoPlatform Sample from LiveCharts2 repo.

**Comment by beto-rodriguez** [comment]
This is already fixed in rc2 version, thanks for the report!
