### ISSUE TITLE
[Question] How to show all labels on X-Axis when they are of type string

### ISSUE THREAD

**Issue by MANIKANTAABBURI** [beto-rodriguez/LiveCharts2#1284]
I am using column chart series in xamarin. My problem is not all the lables are visible even though labels are set to 90deg. I have to zoom, in order to see all the labels. 

There are no options to set them as visible.

![WhatsApp Image 2023-09-27 at 14 14 34](https://github.com/beto-rodriguez/LiveCharts2/assets/44364535/25c0a9fc-9aac-47bf-8903-ff21ae085b12)

Is there any setting I can look for or should I request for this as a feature.

**Comment by MANIKANTAABBURI** [comment]
`public ISeries[] Series { get; set; } =
  {
      
       new ColumnSeries<double>
          {
              Values = new double[] { 2, 1, 3, 5, 3, 4, 6,2, 1, 3 },
              Fill = new SolidColorPaint(SKColor.FromHsl(248, 85, 66)),
             Rx=50,
             Ry=50,
             MaxBarWidth=10,
             Padding = 0,
          }
  };

  public Axis[] XAxes { get; set; } =
  {
      new Axis
      {
          Name = "Resources",
          Labels = new String[]{"Manikanta Abburi", "Michel Johnson", "Virat Kohli", "Christiano Ronaldo", "J Oppenheimer", "Jos Buttler", "Lewis Hamilton", "Manikanta Abburi", "Michel Johnson"},
          LabelsRotation = 90,
          TextSize = 10,
          NameTextSize=12,
          MinStep=1,

      }
  };`

**Comment by MANIKANTAABBURI** [comment]
```
`public ISeries[] Series { get; set; } =
  {
      
       new ColumnSeries<double>
          {
              Values = new double[] { 2, 1, 3, 5, 3, 4, 6,2, 1, 3 },
              Fill = new SolidColorPaint(SKColor.FromHsl(248, 85, 66)),
             Rx=50,
             Ry=50,
             MaxBarWidth=10,
             Padding = 0,
          }
  };

  public Axis[] XAxes { get; set; } =
  {
      new Axis
      {
          Name = "Resources",
          Labels = new String[]{"Manikanta Abburi", "Michel Johnson", "Virat Kohli", "Christiano Ronaldo", "J Oppenheimer", "Jos Buttler", "Lewis Hamilton", "Manikanta Abburi", "Michel Johnson"},
          LabelsRotation = 90,
          TextSize = 10,
          NameTextSize=12,
          MinStep=1,

      }
  };
```

**Comment by beto-rodriguez** [comment]
At this point you have to force the labels (see the not note yellow):

https://livecharts.dev/docs/Xamarin/2.0.0-rc1/samples.bars.basic

But I agree, this should be improved in a future version.

**Comment by beto-rodriguez** [comment]
The referenced commit will improve this in future versions, for now please follow the suggestion above.

Thanks for the report, I will close this for now since the question seems to be answered.
