### ISSUE TITLE
PieChart Title not showing in MAUI

### ISSUE THREAD

**Issue by MarcosCostaDev** [beto-rodriguez/LiveCharts2#1285]
**Describe the bug**
Following the documentation

**To Reproduce**
following the documentation  https://livecharts.dev/docs/Maui/2.0.0-rc1/samples.pies.basic

**Expected behavior**
The title should show

**Screenshots**
![image](https://github.com/beto-rodriguez/LiveCharts2/assets/4077961/feb2296a-97ef-48cf-a1d1-ca8b55c9c4c1)

**Smartphone (please complete the following information):**
 - Device: Android Emulator Pixel 4 with Playstore

**Comment by ckmstydy** [comment]
I encountered the same problem when drawing a line chart, following the documentation https://livecharts.dev/docs/WPF/2.0.0-rc1/samples.lines.basic.
 Did you solve it?

**Comment by MarcosCostaDev** [comment]
Hi @ckmstydy, no I did not 😔. I am using another visual element for showing the title for now.
