### ISSUE TITLE
Custom tooltip for shared axis

### ISSUE THREAD

**Issue by DevHasher** [beto-rodriguez/LiveCharts2#129]
Is there a option to show the shared axis label on the tooltip in the current version, like the below image from old version
![image](https://user-images.githubusercontent.com/23658195/128049829-b7007567-4ab3-47cb-a9b9-3fe5a1c4457d.png)

In current version only the data point value is visible as shown below
![image](https://user-images.githubusercontent.com/23658195/128049960-ad11a675-0b86-4a8b-9a86-667150cbfb2f.png)

**Comment by LabuzzMichal** [comment]
You can create customized tooltip. There is already built in example: https://github.com/beto-rodriguez/LiveCharts2/blob/master/samples/WPFSample/General/TemplatedTooltips/View.xaml

Please take a look at this line:
`<TextBlock Text="{Binding Point.AsTooltipString}" Margin="0 0 8 0" Foreground="AntiqueWhite" />`
It is responsible for displaying point value. If you inspect ChartPoint class you will see it expose not only AsTooltipString property but also AsDataLabelString property, what is exactly what you are looking for.

**Comment by beto-rodriguez** [comment]
I am closing this issue for now, since custom tooltips are supported, take a look at @LabuzzMichal link.
