### ISSUE TITLE
MAUI CartesianChart does not update after leaving page and returning

### ISSUE THREAD

**Issue by christiaanderidder** [beto-rodriguez/LiveCharts2#1291]
**Describe the bug**
When using MAUI AppShell with a CartesianChart on one Page, navigating to another page and coming back, causes the chart to malfunction and not update any more.

**To Reproduce**
1. Check out https://github.com/christiaanderidder/livechartscore-not-updating
2. Open application
3. Click on refresh to load new random data into the chart and verify it redraws
4. Navigate to second tab 'Other'
5. Navigate back to tab 'Chart'
6. Click on refresh to load new random data into the chart and verify it does not redraw

**Expected behavior**
The chart should redraw after the view is loaded again

**Screenshots**
[https://gifyu.com/image/S6bCd](https://gifyu.com/image/S6bCd)

**Smartphone (please complete the following information):**
 - Device: Android Emulator
 - OS: API 34

**Additional context**
I have dug into the code and it seems to be caused by the following commit: https://github.com/beto-rodriguez/LiveCharts2/commit/3e678a48be12b7a86efe95e124d1dc39c6431b89 which stops the chart from updating after the view unloads. However, it does not activate the chart again after reloading.

The following change resolves the problem, but I am not familiar enough with the code to know whether this can cause other side-effects: #1292

**Comment by mgramley** [comment]
Is there any update on this? Looks like there is a PR out for the fix but it's not live yet? 

I'm having this problem as well, navigating away from the page with the chart seems to break the chart. I only see this on iOS though. 

This is a breaking bug for me, really kills my app to have my chart just stop working. Haven't found a work around yet.
