### ISSUE TITLE
[!important] DataLabel disappeared！

### ISSUE THREAD

**Issue by dazzlingjgy** [beto-rodriguez/LiveCharts2#1293]
I used the "CartesianChart" chart in the project, using the MVVM mode to bind the Series. Everything was displayed normally at first, but when I changed the IsVisible property of each item in the Series, such as hiding and then redisplaying it, The DataLabel will disappear. When scaling or moving the chart, the DataLabel will appear briefly and then disappear again. Why is this?

This is how I assign values to the Series：

Series = new ISeries[]
        {
            new LineSeries<ObservablePoint>
            { 
                Values = baiwei, 
                Fill = null, 
                LineSmoothness = 0,
                Name="H", 
                GeometrySize=20,
                GeometryFill=new SolidColorPaint(SKColors.Red),
                GeometryStroke=new SolidColorPaint(SKColors.Red),
                Stroke=new SolidColorPaint(SKColors.Red),
                DataLabelsSize=20,DataLabelsPaint=new SolidColorPaint(SKColors.White),
                DataLabelsPosition=LiveChartsCore.Measure.DataLabelsPosition.Middle,
                DataLabelsFormatter=(point)=>point.PrimaryValue.ToString()},
            new LineSeries<ObservablePoint>
            { 
                Values = shiwei, 
                Fill = null, 
                LineSmoothness = 0,
                Name="T", 
                GeometrySize=20,
                GeometryFill=new SolidColorPaint(SKColors.Orange),
                GeometryStroke=new SolidColorPaint(SKColors.Orange),
                Stroke=new SolidColorPaint(SKColors.Orange),
                DataLabelsSize=20,DataLabelsPaint=new SolidColorPaint(SKColors.White),
                DataLabelsPosition=LiveChartsCore.Measure.DataLabelsPosition.Middle,
                DataLabelsFormatter=(point)=>point.PrimaryValue.ToString()},
            new LineSeries<ObservablePoint>
            { 
                Values = gewei, 
                Fill = null, 
                LineSmoothness = 0, 
                Name="U",
                GeometrySize=20,
                GeometryFill=new SolidColorPaint(SKColors.Blue),
                GeometryStroke=new SolidColorPaint(SKColors.Blue),
                Stroke=new SolidColorPaint(SKColors.Blue),
                DataLabelsSize=20,
                DataLabelsPaint=new SolidColorPaint(SKColors.White),
                DataLabelsPosition=LiveChartsCore.Measure.DataLabelsPosition.Middle,
                DataLabelsFormatter=(point)=>point.PrimaryValue.ToString()}
        };

This is how I change the IsVisible property:
Series[0].IsVisible = IsVisibleBaiWei;
Series[1].IsVisible = IsVisibleShiWei;
Series[2].IsVisible = IsVisibleGeWei;

IsVisibleBaiWei，IsVisibleShiWei，IsVisibleGeWei binding via switch。

This is a recurrence of the problem：

https://github.com/beto-rodriguez/LiveCharts2/assets/51228048/be3d73c3-fd96-4d1c-a08a-ab92071a748e

**Comment by beto-rodriguez** [comment]
Hello and thanks for the report.

I am not able to reproduce this issue, could you provide a small zip/repo where I can see the issue?

My guess is that the issue you are facing could be caused by:

- a bug related to the easing function
- A wrong z-index in your paint

**Comment by dazzlingjgy** [comment]
已经收到您的来信，我会尽快回复。
