### ISSUE TITLE
X-Axis disappears and chart breaks when zooming out in empty area

### ISSUE THREAD

**Issue by jakobo06** [beto-rodriguez/LiveCharts2#1294]
**Describe the bug**
When selecting an area with no data points and zooming out, the x-axis occasionally disappears, causing the chart to break.

**To Reproduce**

1. Select an area with no charting elements (right-click and drag).
2. Zoom out.

**Expected behavior**
I expect the chart to behave the same way as when selecting an area with charting elements and zooming out.

**Screenshots**
I have attached a video of the chart breaking
https://github.com/beto-rodriguez/LiveCharts2/assets/19285957/71e3eebc-cbc2-477a-9a7a-7e47bacdb0d2

Desktop (please complete the following information):
OS: Windows 11 22000.2416
Browser: NA
Version: v2.0.0-rc1.2
.NET Version: net6.0-windows

**Comment by jakobo06** [comment]
I believe I have found a fix for this issue, although I'm not entirely certain if it is the correct approach or if there are other changes needed elsewhere in the code base. As far as I can tell, the problem is related to the limit calculation, where the minimum and maximum limit values are getting flipped.
The current code is as follows:

```c#
internal static void ValidateLimits(ref double min, ref double max)
{
    var isMax =
        min is double.MaxValue or double.MinValue ||
        max is double.MaxValue or double.MinValue;

    if (!isMax) return;

    min = 0;
    max = 10;
}
```
With my changes:

```c#
internal static void ValidateLimits(ref double min, ref double max)
{
    var isMax =
        min is double.MaxValue or double.MinValue ||
        max is double.MaxValue or double.MinValue;

    if (min > max)
    {
        double temp = max;
        max = min;
        min = temp;
    }

    if (!isMax) return;

    min = 0;
    max = 10;
}
```

These changes address the issue by swapping the `min` and `max` values if `min` is bigger than `max`.

**Comment by spewmaker** [comment]
I am facing a similar issue on my XAxis, I have my XAxis bound to a DateTimeAxis(similar to this https://livecharts.dev/docs/winforms/2.0.0-rc1/samples.axes.dateTimeScaled). 
I give the user option to toggle between series visibility on the Cartesian Chart, if there is no series visible on the chart and if the user zooms out. The time values on XAxis disappear and even when users toggle one of the series back on - to view on the graph, the XAxis (datetime values) do not appear causing all series to be plotted on the same point.

Currently, I am not setting MinLimit or MaxLimit on my XAxis, and I only have ZoomAndPanMode enabled for XAxis. 

Would greatly appreciate if you could help me debug through this you seem to have found a fix for your use case, let me know if you'd want me to share my cartesian chart setup. Thank you in advance.

**Comment by jakobo06** [comment]
Hi @spewmaker
My suggestion requires changes to the library itself (in the `AxisLimit.cs` file), so I do not think that you can handle the issue in your client code.

I was hoping that one of the maintainers of the project would come up with a better solution for this issue, as the problem is that the parameters `min` and `max` are flipped, which suggests that the actual issue lies somewhere else in the codebase.

This was just a suggestion for a Quick Fix.

**Comment by beto-rodriguez** [comment]
@jakobo06 that seems a valid workaround to prevent this kind of issues, it would also prevent wrong user input, thanks!
