### ISSUE TITLE
Answer Geared Package

### ISSUE THREAD

**Issue by mr-varyna** [beto-rodriguez/LiveCharts2#13]
I do not buy a Geared Package, because when many points on the poin Geometry plot are not visible, when you use scaling and the points become smaller, they appear, although there is no such in your standard plot. Please consider this possibility. Thanks!

**Comment by beto-rodriguez** [comment]
Would you like that the Geared package do not remove the Geometry points? I am sorry I am afraid I don't completely understand this request.

**Comment by mr-varyna** [comment]
If you build a graph with an interval of three years and 1000 poins. You won't see Point Geometry. But if you narrow the scaling down to 200 points and half a year, Poins Geometry will be displayed.

**Comment by danrayson** [comment]
> I do not buy a Geared Package, because when many points on the poin Geometry plot are not visible, when you use scaling and the points become smaller, they appear, although there is no such in your standard plot. Please consider this possibility. Thanks!

You do not make bug report by threatening the developer with no money.

I think what he's trying to say is;  There's a problem with the scaling of points on a chart, where a rounding issue occurs at small values which sometimes means the visual size of an element is 0.
