### ISSUE TITLE
LabelFormatter on LiveChartsCore.SkiaSharpView.Avalonia

### ISSUE THREAD

**Issue by henrrymoraes83** [beto-rodriguez/LiveCharts2#1302]
I'm trying to change decimal value from YAxes  Axis but I didn't find the parameter LabelFormatter.

The method below exists in the version of LiveCharts for WPF but does not exist in the Avalonia version:

```
Func<double, string> formatFunc = (x) => string.Format("{0:0.000}", x);

cartesianChart2.AxisY.Add(new Axis
{
    LabelFormatter = formatFunc,
});
```

Example:

![image](https://github.com/beto-rodriguez/LiveCharts2/assets/135464720/606c3f58-132c-4303-aa95-15bfc2c23086)

In the image above, I would like change the value with 2 decimal.

**Comment by beto-rodriguez** [comment]
Hello

You must use the `Axis.Labeler` property, see https://livecharts.dev/docs/Avalonia/2.0.0-rc1/samples.axes.crosshairs

Let me know if you need further assistance.
