### ISSUE TITLE
Error when touching the chart on android

### ISSUE THREAD

**Issue by inigofu** [beto-rodriguez/LiveCharts2#1303]
**Describe the bug**
When touching any chart on Android the apps crashes. It only happens when I am running on release mode.

**To Reproduce**
1. Open the app
2. Touch the chart
3. App closes

**Expected behavior**
I should not give an error

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: OnePlus 6
 - OS: Android 11

**Additional context**
This is the stack trace:

System.NotSupportedException: Cannot create instance of type 'LiveChartsCore.Behaviours.ChartBehaviour+CustomScaleListener': no Java peer type found.
  ?, in new JniInstanceMethods(Type)
  ?, in JniInstanceMethods JniInstanceMethods.GetConstructorsForType(Type)
  ?, in JniObjectReference JniInstanceMethods.StartCreateInstance(string, Type, JniArgumentValue*)
  ?, in new SimpleOnScaleGestureListener()
  File "ChartBehaviour.Android.cs", line 118, in new CustomScaleListener(Action<float> onSacaled)
  File "ChartBehaviour.Android.cs", line 59, in void ChartBehaviour.OnAndroidTouched(object sender, TouchEventArgs e)
  ?, in bool IOnTouchListenerImplementor.OnTouch(View, MotionEvent)
  ?, in bool IOnTouchListenerInvoker.n_OnTouch_Landroid_view_View_Landroid_view_MotionEvent_(IntPtr, IntPtr, IntPtr, IntPtr)
  ?, in bool JNINativeWrapper.Wrap_JniMarshal_PPLL_Z(_JniMarshal_PPLL_Z, IntPtr, IntPtr, IntPtr, IntPtr)

**Comment by beto-rodriguez** [comment]
Hi

I am not able to reproduce this issue. Please try the latest version and feel free to open a new issue if the issue persists.
