### ISSUE TITLE
Strange crosshair shows while swiping over Y-axis labels on Maui

### ISSUE THREAD

**Issue by steffos** [beto-rodriguez/LiveCharts2#1304]
**Describe the bug**
While swiping over the Y-axis labels, a crosshair with negative values is shown.

This in the latest LiveChartsCore.SkiaSharpView.Maui- 2.0.0-rc1.2.

**To Reproduce**
1. Download and run attached sample project
3. Swipe over the Y-axis
4. Crosshair is shown

**Expected behavior**
Nothing should happen while swiping over the Y-axis labels - no crosshair should be shown.

**Screenshots**
See attached gif.
![crosshai_yaxis](https://github.com/beto-rodriguez/LiveCharts2/assets/1426950/4511f6d8-1229-4255-991e-01f6c4ed4c61)

**Smartphone:**
This happens on both iOS and Android.

[ChartSwipe.zip](https://github.com/beto-rodriguez/LiveCharts2/files/12879840/ChartSwipe.zip)

**Comment by beto-rodriguez** [comment]
Thanks for the report and the sample.

This will not happen anymore since `rc2` because #1305 will be fixed there, now crosshairs are not invalidated when the pointer/finger is out of the "draw margin".

I will close this for now, but feel free to let me know if this is not working as expected in the next version of the library.

**Comment by xiaosa305** [comment]
> Thanks for the report and the sample.
> 
> This will not happen anymore since `rc2` because #1305 will be fixed there, now crosshairs are not invalidated when the pointer/finger is out of the "draw margin".
> 
> I will close this for now, but feel free to let me know if this is not working as expected in the next version of the library.

The problem has not been fixed in the LiveChartsCore.SkiaSharpView.WPF-2.0.0-rc2
