### ISSUE TITLE
Zooming while a heatmap refreshes causes labels to persist

### ISSUE THREAD

**Issue by joshbevans** [beto-rodriguez/LiveCharts2#1306]
While a heatmap redraws due to data change, if the user scrolls to zoom then it causes previous data labels to persist. Couldn't find a way to make them disappear again.

https://imgur.com/a/6GTWhLI
As you can see, there are floating data labels with no colours behind them that are from previous data and shouldn't still be there

 - OS: Windows 11
 - Version 2.0.0-rc1.2

**Comment by beto-rodriguez** [comment]
Hi and thanks for the report.

I am not able to reproduce this issue, it seems to work properly for me:

![heat](https://github.com/beto-rodriguez/LiveCharts2/assets/10853349/7ad2145b-4d3a-4a82-be34-017f3d491f01)

Could you please provide a minimal reproducible sample where I can see the issue?
