### ISSUE TITLE
How to always show all labels of Axis?  

### ISSUE THREAD

**Issue by luoqiang110** [beto-rodriguez/LiveCharts2#1308]
the same question with [https://github.com/beto-rodriguez/LiveCharts2/issues/90]

Is this problem solved now?
and my version is  2.0.0-rc1.2 
thanks ~

![image](https://github.com/beto-rodriguez/LiveCharts2/assets/22185857/f22ee28b-423a-421b-a186-c14a2550f90c)

![image](https://github.com/beto-rodriguez/LiveCharts2/assets/22185857/95fa9a15-ed05-4f59-b487-36f363922a40)

**Comment by beto-rodriguez** [comment]
Hi what is the issue you are facing, is there something wrong in your image?

**Comment by beto-rodriguez** [comment]
I will close this for now because there is not enough info, feel free to create a new issue or add more details here.
