### ISSUE TITLE
wpf  Chart plugins wrapped with StackPanel are not displayed

### ISSUE THREAD

**Issue by guaicaiboshi** [beto-rodriguez/LiveCharts2#1309]
**Describe the bug**
Chart plugins wrapped with StackPanel are not displayed

**To Reproduce**
1. update 'samples/WPFSample/Maps/World/View.xaml' 
`   <StackPanel>
       <lvc:GeoMap Series="{Binding Series}"
                   MapProjection="Mercator" />
   </StackPanel>`
3.  Run program
 

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS:win11 
   wpf
 - Version  LiveChartsCore.SkiaSharpView.WPF2.0.0-rc1.2
![image](https://github.com/beto-rodriguez/LiveCharts2/assets/2748771/b8d1c85a-b1e4-449a-adff-31c3f3c5b7f9)

**Comment by beto-rodriguez** [comment]
Hello and thanks for the report.

The controls in this library do not set the `MinWidth` or `MinHeight` properties, you can make this work on your side by setting the size of your charts, this way the stack panel can stack ti with the other child elements.
