### ISSUE TITLE
HowTo: Doughnut chart slice selection

### ISSUE THREAD

**Issue by danielnierlin** [beto-rodriguez/LiveCharts2#1311]
I was wondering if it's possible to select (pushout) a slice of the doughnut chart by mouse click/tap. I know it can be done programatically but can it be done by user interaction?

**Comment by beto-rodriguez** [comment]
You can use the pointer down event:

https://livecharts.dev/docs/Maui/2.0.0-rc1/samples.events.cartesian

this event will inject the `point` that was clicked, then use the `point.Visual` property to set the pushout of the slice.

I will close this for now, but feel free to reply if you need further assistance.
