### ISSUE TITLE
Scroll Wheel Breaking

### ISSUE THREAD

**Issue by mcash95** [beto-rodriguez/LiveCharts2#1313]
When using scroll wheel on a PieChart throws an Unable to cast error.

_Unable to cast object of type 'LiveChartsCore.PieChart`1[LiveChartsCore.SkiaSharpView.Drawing.SkiaSharpDrawingContext]' to type 'LiveChartsCore.CartesianChart`1[LiveChartsCore.SkiaSharpView.Drawing.SkiaSharpDrawingContext]'._

What is the scroll wheel attempting to accomplish?

Thank you in advance! Love the functionality you have provided

**Comment by beto-rodriguez** [comment]
Please update to rc1.2 the issue is gone there.

**Comment by beto-rodriguez** [comment]
duplicate of #1265
