### ISSUE TITLE
How to plot polygons and images?

### ISSUE THREAD

**Issue by HandsomeGoldenKnight** [beto-rodriguez/LiveCharts2#1314]
I try to plot polygons and images, but I can't find an example of that. May I ask if there is an implemented solution?

**Comment by beto-rodriguez** [comment]
Hello

LiveCharts uses SkiaSharp to render the charts in the UI, so anything that works on SkiaSharp should work here.

To access the SkiaSharp API you can follow the custom geometry sample:

https://livecharts.dev/docs/WPF/2.0.0-rc1/samples.lines.custom#mygeometry.cs

The `MyGeometry.OnDraw` method exposes the SkiaSharp API.

Let me know if you need further assistance.
