### ISSUE TITLE
Avalonia : Unable to find suitable setter or adder for property Values

### ISSUE THREAD

**Issue by mgth** [beto-rodriguez/LiveCharts2#1317]
**Describe the bug**
Produces AVLN:0004 
Unable to find suitable setter or adder for property Values of type LiveChartsCore:LiveChartsCore.Series`4 for argument Avalonia.Markup.Xaml:Avalonia.Markup.Xaml.MarkupExtensions.CompiledBindingExtension, available setter parameter lists are:
System.Collections.Generic.IEnumerable`1<System.Double>

**To Reproduce**
            <avalonia:CartesianChart.Series>
                <skiaSharpView:LineSeries
                    x:TypeArguments="sys:Double"
                    Values="{Binding MyObservableCollection}"/>
            </avalonia:CartesianChart.Series>

**Desktop (please complete the following information):**
 - OS: Windows
 - Avalonia UI 11.0.5

**Comment by beto-rodriguez** [comment]
Hello, its seems that your XAML has some errors, please take a look at the starting guide:

https://livecharts.dev/docs/Avalonia/2.0.0-rc1/Overview.Installation

I will close this for now, but feel free to reply if the issue persists.
