### ISSUE TITLE
[Uno.WinUI][WASM/Skia.GTK] Error when using Uno 5.x dev packages

### ISSUE THREAD

**Issue by kazo0** [beto-rodriguez/LiveCharts2#1318]
**Describe the bug**
An error occurs when trying to run the WASM and Skia.GTK heads of an Uno.WinUI app that is built with the latest Uno 5.x dev packages.

The upcoming Uno 5 includes breaking changes that seems to be affecting LiveCharts2

Works on Android/iOS

[TestLiveCharts3.zip](https://github.com/beto-rodriguez/LiveCharts2/files/13046009/TestLiveCharts3.zip)

**To Reproduce**
1. Launch sample app for WASM/Skia.GTK
4. See error:

> Exception thrown: 'System.InvalidOperationException' in TestLiveCharts3.dll
> An exception of type 'System.InvalidOperationException' occurred in TestLiveCharts3.dll but was not handled in user code
> Failed to load TestLiveCharts3.MainPage: System.MissingMethodException: Method not found: 'Void Microsoft.UI.Xaml.UIElement.set_Name(System.String)'.
>    at LiveChartsCore.SkiaSharpView.WinUI.CartesianChart.InitializeComponent_305BE924()
>    at LiveChartsCore.SkiaSharpView.WinUI.CartesianChart.InitializeComponent()
>    at LiveChartsCore.SkiaSharpView.WinUI.CartesianChart..ctor()
>    at TestLiveCharts3.MainPage.InitializeComponent() in X:\src\TestApps\TestLiveCharts3\TestLiveCharts3\Uno.UI.SourceGenerators\Uno.UI.SourceGenerators.XamlGenerator.XamlCodeGenerator\MainPage_4bfe64f3ba5c8da54b0a0cf0ba481633.cs:line 69
>    at TestLiveCharts3.MainPage..ctor() in X:\src\TestApps\TestLiveCharts3\TestLiveCharts3\MainPage.xaml.cs:line 10
>    at TestLiveCharts3.Skia.Gtk.MetadataBuilder_014.CreateInstance() in X:\src\TestApps\TestLiveCharts3\TestLiveCharts3.Skia.Gtk\Uno.UI.SourceGenerators\Uno.UI.SourceGenerators.BindableTypeProviders.BindableTypeProvidersSourceGenerator\BindableMetadata.g.cs:line 1014
>    at Microsoft.UI.Xaml.Controls.Frame.CreatePageInstance(Type sourcePageType) in /__w/1/s/src/Uno.UI/UI/Xaml/Controls/Frame/Frame.cs:line 463
>    at Microsoft.UI.Xaml.PagePool.DequeuePage(Type pageType) in /__w/1/s/src/Uno.UI/UI/Xaml/PagePool.cs:line 69
>    at Microsoft.UI.Xaml.Controls.Frame.CreatePageInstanceCached(Type sourcePageType) in /__w/1/s/src/Uno.UI/UI/Xaml/Controls/Frame/Frame.cs:line 453
>    at Microsoft.UI.Xaml.Controls.Frame.EnsurePageInitialized(PageStackEntry entry) in /__w/1/s/src/Uno.UI/UI/Xaml/Controls/Frame/Frame.cs:line 443
>    at Microsoft.UI.Xaml.Controls.Frame.InnerNavigate(PageStackEntry entry, NavigationMode mode) in /__w/1/s/src/Uno.UI/UI/Xaml/Controls/Frame/Frame.cs:line 291

**Expected behavior**

Expecting to see: 

![image](https://github.com/beto-rodriguez/LiveCharts2/assets/4793020/2fc3510d-affc-42f9-af88-3bd8ad8c8cba)

**Comment by beto-rodriguez** [comment]
Thanks for the update!

**Comment by beto-rodriguez** [comment]
The latest release (rc2) is now compatible with with Uno 5, thanks again for the report!
