### ISSUE TITLE
Finance Candlestick plots

### ISSUE THREAD

**Issue by MhAllan** [beto-rodriguez/LiveCharts2#1326]
* Rendering financial candlesticks/prices lines
* Red and Green candles
* Clickable and Selectable

**Comment by beto-rodriguez** [comment]
Hi

This is supported, please see:

https://livecharts.dev/docs/WPF/2.0.0-rc1/samples.financial.basicCandlesticks

About the click/select, you can follow this guide:

https://livecharts.dev/docs/WPF/2.0.0-rc1/samples.events.cartesian
