### ISSUE TITLE
All operations are not smooth enough, hope to focus on optimizing smoothness

### ISSUE THREAD

**Issue by 285984303** [beto-rodriguez/LiveCharts2#1328]
All operations are not smooth enough, hope to focus on optimizing smoothness

**Comment by beto-rodriguez** [comment]
Hello, can you please explain more, what are the operations that you consider that are not smooth enough?

**Comment by beto-rodriguez** [comment]
I will close this for now, feel free to add more details here or in a new issue.

**Comment by 285984303** [comment]
> Hello, can you please explain more, what are the operations that you consider that are not smooth enough?您好，能不能请您再解释一下，您认为哪些操作不够流畅？

When there are many data points, the mouse prompts
