### ISSUE TITLE
Cannot Get Uno.WinUI work on the Uno Platform -- Icon.png was not found

### ISSUE THREAD

**Issue by BigWarren** [beto-rodriguez/LiveCharts2#1329]
**Describe the bug**
Once install the Nuget package LiveChartsCore.SkiaSharpView.Uno.WinUI 2.0.0-rc1.2, the Uno Platform Project no longer build with following error

![image](https://github.com/beto-rodriguez/LiveCharts2/assets/10443953/81824ecc-8020-41a6-86b2-e77e59408543)

**To Reproduce**
Create Empty Uno Platform using .Net 7 template
Add the LiveChartsCore.SkiaSharpView.Uno.WinUI 2.0.0-rc1.2 packages from Nuget
Build the Solution --  Failed to Build

**Expected behavior**
Project Build without Error

**Desktop**
 - OS: Windows 10 19045.3393
- Uno Platform Version 4.10.26
- LiveChart Version 2.0.0-rc1.2

**Comment by beto-rodriguez** [comment]
fixed in [2.0.0-rc2](https://www.nuget.org/packages/LiveChartsCore/2.0.0-rc2), thanks for the report!
