### ISSUE TITLE
Request to Display Line Legend Instead of Circle When GeometryStroke and GeometryFill Are Null

### ISSUE THREAD

**Issue by ts-research7** [beto-rodriguez/LiveCharts2#1331]
Is your feature request related to a problem? Please describe.
When I create a LineSeries with GeometryStroke = null, GeometryFill = null, and Stroke = new SolidColorPaint(SKColors.Red), the legend of the series is displayed with a red circle followed by the legend name.

Describe the solution you'd like
Since GeometryStroke and GeometryFill are null, I want the legend to display as a red line followed by the legend name.

**Comment by beto-rodriguez** [comment]
Fixed with the referenced PR and will be included in the next version of the library.
