### ISSUE TITLE
WPF: Subsequent change of fill via OnPointMeasured() does not adapt icon color in tooltip

### ISSUE THREAD

**Issue by network-interface-controller** [beto-rodriguez/LiveCharts2#1335]
**Describe the bug**
A subsequent change of the Fill for single columns in a column series by means of OnPointMeasured() does not adapt the Fill of the icon in the associated tooltip.

**Code excerpt**
```
var series = new ColumnSeries<int>
{
    Values = input.Select(x => x.Rank),
    XToolTipLabelFormatter = (chartPoint) => $"TooltipText...",
    IsVisibleAtLegend = false
}.OnPointMeasured(point =>
{
    if (point.Coordinate.PrimaryValue == 1)
        point.Visual!.Fill = new SolidColorPaint(new SKColor(0, 128, 0));
    if (point.Coordinate.PrimaryValue == 2)
        point.Visual!.Fill = new SolidColorPaint(new SKColor(255, 255, 0));
    if (point.Coordinate.PrimaryValue == 3)
        point.Visual!.Fill = new SolidColorPaint(new SKColor(255, 128, 0));
    if (point.Coordinate.PrimaryValue == 4)
        point.Visual!.Fill = new SolidColorPaint(new SKColor(255, 0, 0));
});
```

**To Reproduce**
Create a column series and adapte the Fill of the columns based on their value => The Fill of the icon in the tooltip has a different color than the associated column

**Expected behavior**
An adaption of a columns Fill via OnPointMeasured() should also adapt the color of the associated tooltip icon, i.e. the color of the icon in the tooltip is defined per column and may differ within a series.

**Screenshots**
![grafik](https://github.com/beto-rodriguez/LiveCharts2/assets/118933349/5c1e4173-73d2-414e-96a5-ec8b6ad3d9b3)

**Desktop (please complete the following information):**
OS: Windows 10, Version 22H2
Browser --> Not applicable; WPF app
Version: LiveChartsCore 2.0.0-rc1.2, LiveChartsCore.SkiaSharpView.WPF 2.0.0-rc1.2
Framework: .NET 7.0

**Smartphone (please complete the following information):**
--> NA

**Additional context**

**Comment by beto-rodriguez** [comment]
Fixed with the referenced commit and will be included in the next version of the library, thanks for the report!
