### ISSUE TITLE
HeatSeries define max and min value for the Tertiary Value

### ISSUE THREAD

**Issue by WIPDarioDT** [beto-rodriguez/LiveCharts2#1337]
I am working with a HeatSeries and everything works perfectly but I miss one thing:
It is possible to define an absolute minimum and maximum for the tertiary values of my HeatSeries?

For example, I would like to define a minimum value of 0 and a maximum value of 100, to represent percentages in each box, and that the colour map together with the gradient stops that I have defined behave in relation to these limits.

Thanks in advance

**Comment by beto-rodriguez** [comment]
This feature will be included in the next version of the library.

Thanks for the report!
