### ISSUE TITLE
Performance issues with RC1 & RC1.2

### ISSUE THREAD

**Issue by En-JON-eer** [beto-rodriguez/LiveCharts2#1338]
Chart animation is wonky when using RC1.2

I have walked through my code but I see no difference in my approach to add new points to the plot(s).

**Screenshots**
![A1Q6UFXxmx](https://github.com/beto-rodriguez/LiveCharts2/assets/89985196/21acbcbf-665c-4ae9-81a0-219b8cc97db3)

**Desktop (please complete the following information):**
 - OS: Win10

**Additional context**
The issue doesn't present on my main form (see below). Only when I spawn a new form with the same chart data being injected..
![pux5XucjXD](https://github.com/beto-rodriguez/LiveCharts2/assets/89985196/995befe7-73d4-42d3-8b02-5ae4a9a91dbe)

**Comment by En-JON-eer** [comment]
Also,

I am still seeing issues with memory explosion when charting.

![4nFvHJy3TW](https://github.com/beto-rodriguez/LiveCharts2/assets/89985196/26fc0ada-27c1-4b8c-87b8-cbceb5edfad7)


This is how I set up my X axes:

private Axis GetTimeBasedXAxis(bool dataAvailable)
        {
            if (dataAvailable)
            {
                return new Axis
                {
                    Name = null,
                    Labeler = value => new DateTime((long)value).ToString("M/d/yyyy h:mm:ss.fff"),
                    LabelsRotation = 20,
                    LabelsAlignment = LiveChartsCore.Drawing.Align.Start,
                    TextSize = 15,
                    UnitWidth = TimeSpan.FromMilliseconds(1).Ticks,
                    LabelsPaint = new SolidColorPaint(SKColors.Green),
                    MinStep = TimeSpan.FromMilliseconds(1).Ticks,
                    CrosshairLabelsBackground = SKColors.Green.AsLvcColor(),
                    CrosshairLabelsPaint = new SolidColorPaint(SKColors.Black, 1),
                    CrosshairPaint = new SolidColorPaint(SKColors.Green, 2)
                };
            }
            else
            {
                return new Axis
                {
                    Name = "NO DATA LOADED",
                    LabelsRotation = 0
                };
            }
        }

**Comment by En-JON-eer** [comment]
![image](https://github.com/beto-rodriguez/LiveCharts2/assets/89985196/9cf59612-d50e-4406-9906-a138c66fad23)

**Comment by En-JON-eer** [comment]
This bug only occurs when AnimationSpeed > 0

**Comment by beto-rodriguez** [comment]
Hi and thanks for the report, this issue seems hard to reproduce, is it possible for you to provide a minimal zip/repo where I can see the issue? that would help a lot to get this fixed soon.
