### ISSUE TITLE
Custom Mapping Causes Chart Breakage on Zoom Out

### ISSUE THREAD

**Issue by jakobo06** [beto-rodriguez/LiveCharts2#1366]
**Describe the bug**
When multiple ISeries[] series share an Axis and the ISeries use custom mapping, zooming out can lead to unexpected behavior, causing the chart to break.

**To Reproduce**

ViewModel Code:

```c#
public partial class ViewModel : ObservableObject
{
    public ViewModel()
    {
        var data = new FinancialData[]
        {
            new(new DateTime(2021, 1, 1), 523, 500, 450, 400),
            new(new DateTime(2021, 1, 2), 500, 450, 425, 400),
            new(new DateTime(2021, 1, 3), 490, 425, 400, 380)
        };

        Series = new ISeries[]
        {
            new CandlesticksSeries<FinancialData>
            {
                Values = data.ToArray(),
                Mapping = (price, point) => new(price.Date.Ticks, price.High, price.Open, price.Close, price.Low),
            }
        };

        SecondarySeries = Array.Empty<ISeries>();

        XAxes = new[]
        {
            new Axis
            {
            }
        };
    }

    public Axis[] XAxes { get; set; }
    public ISeries[] Series { get; set; }
    public ISeries[] SecondarySeries { get; set; }

}

public class FinancialData
{
    public FinancialData(DateTime date, double high, double open, double close, double low)
    {
        Date = date;
        High = high;
        Open = open;
        Close = close;
        Low = low;
    }

    public DateTime Date { get; set; }
    public double High { get; set; }
    public double Open { get; set; }
    public double Close { get; set; }
    public double Low { get; set; }
}
```
View code

```C#
<Grid>
    <Grid.RowDefinitions>
        <RowDefinition Height="*"/>
        <RowDefinition Height="*"/>
    </Grid.RowDefinitions>

    <lvc:CartesianChart
        Grid.Row="0"
        Series="{Binding Series}"
        XAxes="{Binding XAxes}"
        ZoomMode="X"></lvc:CartesianChart>

    <lvc:CartesianChart
        Grid.Row="1"
        Series="{Binding SecondarySeries}"
        XAxes="{Binding XAxes}"
        ZoomMode="X"></lvc:CartesianChart>
</Grid>
```

1.  Run the application.
2. Zoom out on the chart.
3. Observe the unexpected behavior.

**Expected behavior**
I would expect the chart to behave consistently, even with custom mapping applied.

**Screenshots**
A video demonstrating the issue is available -  https://github.com/beto-rodriguez/LiveCharts2/assets/19285957/5e697834-30df-4dd7-b0fd-e9aaadd785b1

**Desktop (please complete the following information):**
OS: Windows 11 22000.2600
Browser: NA
Version: v2.0.0-rc2
.NET Version: net6.0-windows

**Comment by beto-rodriguez** [comment]
Hello and thanks for the report.

I see a couple of issues here:

1. This is not the way to share an axis between 2 charts, please follow the next article: https://livecharts.dev/docs/WPF/2.0.0-rc2/samples.axes.shared
2. You are also facing the issue described in #1456

I will close this for now because it seems that this is not an issue with the library, but feel free to reply or create a new issue if the error persists after applying the suggested changes.
