### ISSUE TITLE
Can you change the shortName of lands in "word-map-index.json" to CountryISOCode?

### ISSUE THREAD

**Issue by Ptkatz** [beto-rodriguez/LiveCharts2#1367]
Can you change the shortName of lands in "word-map-index.json" to CountryISOCode?

For example: China -> cn, Japan -> jp, United States -> us

**Comment by beto-rodriguez** [comment]
Hello

This is currently not supported, but yes there are plans to support custom maps, I will close this for now, we can track this feature at #1496 as both issues are related.
