### ISSUE TITLE
How to visualize a constant number of labels in XAxis? 

### ISSUE THREAD

**Issue by davideTES** [beto-rodriguez/LiveCharts2#1368]
This is my code:
``` c#
XAxes = new List<ICartesianAxis>
{
    new Axis
    {
        TextSize = 10,
        Labels = liveChartsTrendModel.XValues.Select(x => x.ToString("HH:mm:ss")).ToList(),
        Padding = new LiveChartsCore.Drawing.Padding(10),
        LabelsRotation = 45,
        SeparatorsPaint = new SolidColorPaint(SKColors.LightSlateGray)
        {
            StrokeThickness = 1,
            PathEffect = new DashEffect([3,3])
        },
        SeparatorsAtCenter = false,        
    }
},
```
where liveChartsTrendModel.XValues is of type ```IEnumerable<DateTime>``` with always 150 values.

I would like to visualize exactly 10 labels at every iteration, but sometimes they are 15:
<img width="404" alt="image" src="https://github.com/beto-rodriguez/LiveCharts2/assets/58504049/53ef340e-a68b-4d7a-bd2f-d9d638a32a21">
other times they are 8:
<img width="405" alt="image" src="https://github.com/beto-rodriguez/LiveCharts2/assets/58504049/9bf1bf97-77ce-478d-b4e7-8c78782b44af">

Thankyou

**Comment by beto-rodriguez** [comment]
Hello

The separators in the library are determined based on the chart size and labels size.

But you can also pass your own array of separators, here is a couple of examples:

- https://livecharts.dev/docs/WPF/2.0.0-rc2/samples.general.realTime
- https://livecharts.dev/docs/WPF/2.0.0-rc2/samples.axes.customSeparatorsInterval

I will close this for now, but feel free to reply if you require further assistance.
