### ISSUE TITLE
'Series<ObservableValue, RoundedRectangleGeometry, LabelGeometry, SkiaSharpDrawingContext>.OnPointMeasured(ChartPoint)' is inaccessible due to its protection level

### ISSUE THREAD

**Issue by LiamDHall** [beto-rodriguez/LiveCharts2#1369]
**Describe the bug**
'Series<ObservableValue, RoundedRectangleGeometry, LabelGeometry, SkiaSharpDrawingContext>.OnPointMeasured(ChartPoint)' is inaccessible due to its protection level

trying to get a conditional draw in terms of changing the colour of column when the value is over a certain value say 10 and have it drawn red. 

In the example it say to use the code below in the **To Reproduce** section which I have in the constructor of my public ViewModel but .OnPointMeasured is inaccessible due to its protection level.

**To Reproduce**

type the code

`var dangerPaint = new SolidColorPaint(SKColors.Red);

var _values = new ObservableCollection<ObservableValue>
{
	new(2), new(5), new(4), new(6), new(8), new(3), new(2), new(4), new(6)
};

ColumnSeries<ObservableValue> series = new ColumnSeries<ObservableValue>
{
	Name = "Mary",
	Values = _values
}
.OnPointMeasured(point =>
{
	if (point.Visual is null) return;

	var isDanger = point.Model?.Value > 5;

	point.Visual.Fill = isDanger
		? dangerPaint
		: null; // when null, the series fill is used 
});

ISeries[] Series = new ISeries[] { series };`

**Expected behavior**
 .OnPointMeasured to be accessible.

**Screenshots**
![image](https://github.com/beto-rodriguez/LiveCharts2/assets/63807594/b7dcc050-dc00-4141-b795-bd7b6a04888d)

**Desktop (please complete the following information):**
 -  Windows
 - WPF
 - 2.0.0-beta.701

**Additional context**

**Comment by jozeefkarajeh** [comment]
I am having the same issue. Have you been able to figure it out?

**Comment by nickcorlett** [comment]
If someone else runs into this I found that I needed to add a reference to LiveChartsCore.ConditionalDraw to reference the correct OnPointMeasured.

**Comment by beto-rodriguez** [comment]
@nickcorlett is correct, you must import the `LiveChartsCore.ConditionalDraw` namespace.

I will close this for now, but feel free to reply if you need further assistance.
