### ISSUE TITLE
WPF: Create/draw AngularTicksVisual raises IDE output log message with text '12'

### ISSUE THREAD

**Issue by N4gl3r** [beto-rodriguez/LiveCharts2#1370]
**Describe the bug**

I'm using the Angular Gauge with the Angular Ticks Visual and Needle. In case you use the Angular Ticks Visual it creates output messages with the text '12' in my IDE in Debug and also Release mode. This text output is created for every single AngularTicksVisual instance and due (re)draw (e.g. resize the view/window in which the Visual is placed).

**To Reproduce**

You can reproduce it using the example code on
https://livecharts.dev/docs/WPF/2.0.0-rc2/samples.pies.angularGauge.

**Expected behavior**

No output log message is expected.

**Screenshots**

![image](https://github.com/beto-rodriguez/LiveCharts2/assets/131244459/2099b2f7-bb93-4eed-9cf1-953e7bf4592a)

![image](https://github.com/beto-rodriguez/LiveCharts2/assets/131244459/0d5929db-26ac-43c0-8a82-a44cffa66893)

**Desktop**

 - OS: Win10 Enterprise, 21H2, German language
 - WPF
 - LiveCharts v2.0.0-rc1.2

**Comment by N4gl3r** [comment]
Same issue: https://github.com/beto-rodriguez/LiveCharts2/issues/1411

**Comment by beto-rodriguez** [comment]
Thanks for the report, this is fixed with the referenced commit and will be included in the next version of the library.
