### ISSUE TITLE
RadarChart 3 points

### ISSUE THREAD

**Issue by SmallFred** [beto-rodriguez/LiveCharts2#1382]
### Discussed in https://github.com/beto-rodriguez/LiveCharts2/discussions/1381

<div type='discussions-op-text'>

<sup>Originally posted by **SmallFred** November 28, 2023</sup>
I found an issue when we have only 3 points in a RADAR CHART. If we use IsClosed = true, the geometry is not closed. A line is missing beween the last point and the first point.</div>

**Comment by beto-rodriguez** [comment]
Fixes with the referenced commit, this fix will be included since the next version of the library, thanks for the report.
