### ISSUE TITLE
Logarithmic X Axis Sub Separator Spacing

### ISSUE THREAD

**Issue by skerr0** [beto-rodriguez/LiveCharts2#1387]
**Describe the bug**
Logarithmic X Axis SubSeparator Spacing appears to be backwards. The Y Axis spacing appears correct.

**To Reproduce**
Create a WPF project with a chart. Use a LogarithmicAxis for the x axis. 

**Screenshots**
<img width="575" alt="livecharts_log_bug" src="https://github.com/beto-rodriguez/LiveCharts2/assets/89878953/b8ac39d1-ed84-43c9-85fd-516e979eca53">

**Desktop (please complete the following information):**
Windows 10 - WPF .Net Framework 4.8

**Comment by ImpyKid** [comment]
Same problem here, but what i've figured out is that only the visual of the subseperators is incorrect. The values are correct.
![image](https://github.com/beto-rodriguez/LiveCharts2/assets/78656317/06d14164-4ac1-4eb6-8de4-0139efa5753b)

**Comment by beto-rodriguez** [comment]
Hi and thanks for the report.

This is fixed with the referenced commit and will be included in the next version of the library.
