### ISSUE TITLE
[Question] How to display name horizontally on the Y-axis？

### ISSUE THREAD

**Issue by wangdaojun1985** [beto-rodriguez/LiveCharts2#1388]
Hello, the Y-axis name is displayed vertically, and I want to change it horizontally. How can i do that?

![屏幕截图(17)](https://github.com/beto-rodriguez/LiveCharts2/assets/87227314/65585857-d4be-4c8c-82ef-9884a88835a6)

**Comment by beto-rodriguez** [comment]
Hi

Rotation on the Axis name is not supported :(

I will close this for now, since there are no plans to implement this in the short term.
