### ISSUE TITLE
Error regarding missing values in series

### ISSUE THREAD

**Issue by Albert634515** [beto-rodriguez/LiveCharts2#139]
I have created a test with 4 stackcolumn series with 2 different stack ids. I have not yet used value Nan or zero. Dates are all equal but the error regarding missing values in series still occurs. What is wrong with my setup?

This is related to issue #63 

`   public class ViewModel1
    {
        public IEnumerable<ISeries> Series { get; set; }

        public IEnumerable<IAxis> XAxes { get; set; }

        public ViewModel1()
        {
            var ob2list = new ObservableCollection<ISeries>();

            var cs = new StackedColumnSeries<DateTimePoint>
            {
                Name = "Test1",
                DataLabelsSize = 20,
                DataLabelsPaint = new SolidColorPaintTask(SKColors.Blue),
                DataLabelsPosition = LiveChartsCore.Measure.DataLabelsPosition.Top,
                Values = new ObservableCollection<DateTimePoint>
                    {
                        new DateTimePoint
                        {
                            DateTime = new DateTime(2006, 1, 1),
                            Value = 1
                        },

                        new DateTimePoint
                        {
                            DateTime = new DateTime(2006, 1, 2),
                            Value = 6
                        },
                         new DateTimePoint
                        {
                            DateTime = new DateTime(2006, 1, 3),
                            Value = 5
                        },
                          new DateTimePoint
                        {
                            DateTime = new DateTime(2006, 1, 4),
                            Value = 3
                        },
                           new DateTimePoint
                        {
                            DateTime = new DateTime(2006, 1, 5),
                            Value = 5
                        },
                        new DateTimePoint
                        {
                            DateTime = new DateTime(2006, 1, 6),
                            Value = 8
                        },
                        new DateTimePoint
                        {
                            DateTime = new DateTime(2006, 1, 7),
                            Value = 6
                        }
                    },
                StackGroup = 1
            };
            ob2list.Add(cs);

            cs = new StackedColumnSeries<DateTimePoint>
            {
                Name = "Test2",
                DataLabelsSize = 20,
                DataLabelsPaint = new SolidColorPaintTask(SKColors.Red),
                DataLabelsPosition = LiveChartsCore.Measure.DataLabelsPosition.Top,
                Values = new ObservableCollection<DateTimePoint>
                    {
                        new DateTimePoint
                        {
                            DateTime = new DateTime(2006, 1, 1),
                            Value = 3
                        },

                        new DateTimePoint
                        {
                            DateTime = new DateTime(2006, 1, 2),
                            Value = 7
                        },
                         new DateTimePoint
                        {
                            DateTime = new DateTime(2006, 1, 3),
                            Value = 2
                        },
                          new DateTimePoint
                        {
                            DateTime = new DateTime(2006, 1, 4),
                            Value = 8
                        },
                           new DateTimePoint
                        {
                            DateTime = new DateTime(2006, 1, 5),
                            Value = 9
                        },
                        new DateTimePoint
                        {
                            DateTime = new DateTime(2006, 1, 6),
                            Value = 2
                        },
                        new DateTimePoint
                        {
                            DateTime = new DateTime(2006, 1, 7),
                            Value =5
                        }
                    },
                StackGroup = 2
            };
            ob2list.Add(cs);

            cs = new StackedColumnSeries<DateTimePoint>
            {
                Name = "Test3",
                DataLabelsSize = 20,
                DataLabelsPaint = new SolidColorPaintTask(SKColors.Green),
                DataLabelsPosition = LiveChartsCore.Measure.DataLabelsPosition.Top,
                Values = new ObservableCollection<DateTimePoint>
                    {
                        new DateTimePoint
                        {
                            DateTime = new DateTime(2006, 1, 1),
                            Value = 3
                        },

                        new DateTimePoint
                        {
                            DateTime = new DateTime(2006, 1, 2),
                            Value = 2
                        },
                         new DateTimePoint
                        {
                            DateTime = new DateTime(2006, 1, 3),
                            Value = 8
                        },
                          new DateTimePoint
                        {
                            DateTime = new DateTime(2006, 1, 4),
                            Value = 1
                        },
                           new DateTimePoint
                        {
                            DateTime = new DateTime(2006, 1, 5),
                            Value = 3
                        },
                        new DateTimePoint
                        {
                            DateTime = new DateTime(2006, 1, 6),
                            Value = 7
                        },
                        new DateTimePoint
                        {
                            DateTime = new DateTime(2006, 1, 7),
                            Value = 7
                        }
                    },
                StackGroup = 1
            };
            ob2list.Add(cs);

            cs = new StackedColumnSeries<DateTimePoint>
            {
                Name = "Test4",
                DataLabelsSize = 20,
                DataLabelsPaint = new SolidColorPaintTask(SKColors.Orange),
                DataLabelsPosition = LiveChartsCore.Measure.DataLabelsPosition.Top,
                Values = new ObservableCollection<DateTimePoint>
                    {
                        new DateTimePoint
                        {
                            DateTime = new DateTime(2006, 1, 1),
                            Value = 8
                        },

                        new DateTimePoint
                        {
                            DateTime = new DateTime(2006, 1, 2),
                            Value = 1
                        },
                         new DateTimePoint
                        {
                            DateTime = new DateTime(2006, 1, 3),
                            Value = 7
                        },
                          new DateTimePoint
                        {
                            DateTime = new DateTime(2006, 1, 4),
                            Value = 9
                        },
                           new DateTimePoint
                        {
                            DateTime = new DateTime(2006, 1, 5),
                            Value = 1
                        },
                        new DateTimePoint
                        {
                            DateTime = new DateTime(2006, 1, 6),
                            Value = 5
                        },
                        new DateTimePoint
                        {
                            DateTime = new DateTime(2006, 1, 7),
                            Value = 8
                        }
                    },
                StackGroup = 2
            };
            ob2list.Add(cs);

            Series = new System.Collections.ObjectModel.ObservableCollection<ISeries>(ob2list);
            XAxes = new List<Axis>
            {
                new Axis
                {
                    Labeler = value => new DateTime((long) value).ToString("dd-MM-yyyy"),
                    //Labeler = value => new DateTime((long) value).ToString("yyyy"),
                    LabelsRotation = 15,
                    Position = AxisPosition.Start,
                    MinStep = 1,

                    // in this case we want our columns with a width of 1 day, we can get that number
                    // using the following syntax
                    UnitWidth = TimeSpan.FromDays(1).Ticks
                }
            };
        }
    }`

**Comment by beto-rodriguez** [comment]
Thanks for the report.

This is fixed and will be included in the next release.

Actually now using `0` or `double.NaN` is not required, the library should handle the missing points.
