### ISSUE TITLE
Memory Usage Anomaly in LiveCharts2 (2.0.0-rc2)

### ISSUE THREAD

**Issue by rmbadmin** [beto-rodriguez/LiveCharts2#1390]
Describe the bug
When using the lvc:CartesianChart control from LiveCharts2 in a project, there is an abnormal increase in memory usage. This issue is particularly noticeable when adjusting the window size or maximizing it. Even when the CartesianChart is not bound to any data and only displays an empty control, there is a significant spike in memory usage during window size adjustments or maximization. This behavior is consistent in both Avalonia and WPF projects and is more pronounced on displays with scaling enabled.

To Reproduce

Create a project with LiveCharts2 version 2.0.0-rc2.
Add a lvc:CartesianChart control to the page.
Do not bind any data to the CartesianChart (empty control).
Run the application.
Adjust the window size or maximize it.
Observe the increase in memory usage.
Expected behavior
I expected the CartesianChart control to maintain a reasonable and stable level of memory usage, even when adjusting the window size or maximizing it.

Screenshots
Include screenshots if applicable.

Desktop:

OS: Windows 11
Browser: N/A
Version: N/A
Additional context
This issue occurs in both Avalonia (version 11.0.5) and WPF projects. The problem is more severe on high-resolution displays with scaling enabled.

**Comment by beto-rodriguez** [comment]
Hello and thanks for the report.

What is the increase in memory you get?
