### ISSUE TITLE
IsVisible = false Axes will inevitably ThrowInfiniteSeparators()

### ISSUE THREAD

**Issue by BHandle** [beto-rodriguez/LiveCharts2#1391]
With the rc versions of the library, the new ThrowInfiniteSeparators is being thrown for even simple plots if axes are hidden.  This is because _stepCount is modified in Invalidate, but hidden axes never call that, despite having GetBounds called (and thus incrementing through each call to GetPossibleMaxLabelSize)

I have a setup (using WPF hosted WinForms due to https://github.com/beto-rodriguez/LiveCharts2/issues/1237) with a main chart that can zoom and an overview chart (can't zoom, hidden axes), fairly similar to your own example.

I downloaded the source and modified it to print out the current _stepCount at the start of each call that modifies it, and I get the following (stopped when it hit the 10000 and blew up):

GetPossibleMaxLabelSize - 9700
GetPossibleMaxLabelSize - 9970
GetPossibleMaxLabelSize - 9725
GetPossibleMaxLabelSize - 9996

If I make the overview axes visible, Invalidate is called, which clears the count.  I think this should be replicable by hiding the axes of any live data chart, but if you're having trouble I can try to replicate with one of the built-in samples.

**Comment by BHandle** [comment]
I temporarily fixed this by resetting the _stepCount in GetPossibleMaxLabelSize, which is obviously a no-go and defeats the whole point of the check.  However, I believe this is the first stack frame the code is entering the Axis class from the GetTick() that is being called.  I'm unsure what the correct fix is here, otherwise I would have just submitted a PR.

**Comment by kendragoni** [comment]
Any thing new on this? I am have the same issue.

**Comment by Diddlik** [comment]
> I'm currently working around it by building the library myself with the following change:
> 
> ![image](https://private-user-images.githubusercontent.com/3092680/298983334-7af526b1-5f6d-4dd2-8faa-f46f4ce75e4c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4NzgyMDksIm5iZiI6MTcxMDg3NzkwOSwicGF0aCI6Ii8zMDkyNjgwLzI5ODk4MzMzNC03YWY1MjZiMS01ZjZkLTRkZDItOGZhYS1mNDZmNGNlNzVlNGMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTlUMTk1MTQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTc0MmI2MzU4NWY4OGMyMGYxOWQ2YjM4ZGZkZGIyZmM4YTViNTQxMTEzNjU1YTc5MzBiMDVhMjk0MjA4Y2RiZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.LU9Ghi-_Xtxf2-W4XEXN3HD0DC7Kps7-HXMXn2tlGaY)
> 
> It isn't perfect and defeats the point of the check, but it allows me to proceed for now.

Do you have some solution? I think I have the same or similar problem too: https://github.com/beto-rodriguez/LiveCharts2/issues/1464

**Comment by Klinkas** [comment]
> > I'm currently working around it by building the library myself with the following change:
> > ![image](https://private-user-images.githubusercontent.com/3092680/298983334-7af526b1-5f6d-4dd2-8faa-f46f4ce75e4c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4NzgyMDksIm5iZiI6MTcxMDg3NzkwOSwicGF0aCI6Ii8zMDkyNjgwLzI5ODk4MzMzNC03YWY1MjZiMS01ZjZkLTRkZDItOGZhYS1mNDZmNGNlNzVlNGMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTlUMTk1MTQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTc0MmI2MzU4NWY4OGMyMGYxOWQ2YjM4ZGZkZGIyZmM4YTViNTQxMTEzNjU1YTc5MzBiMDVhMjk0MjA4Y2RiZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.LU9Ghi-_Xtxf2-W4XEXN3HD0DC7Kps7-HXMXn2tlGaY)
> > It isn't perfect and defeats the point of the check, but it allows me to proceed for now.
> 
> Do you have some solution? I think I have the same or similar problem too: #1464

Do you found solution?

**Comment by BHandle** [comment]
Only solution I have is the change described.  By injecting that line into CoreAxis.cs, the count is reset and it avoids the kill condition.  Not a perfect solution, but it works around the problem for now.

**Comment by Diddlik** [comment]
that means, I should compile the solution inside if projekt and do not use a package... Ok, hope it will be fixed in the release

**Comment by Klinkas** [comment]
I get this error when I try to do the following -> "Add a secondary axis, remove it and add it again"

**Comment by erdmenchen** [comment]
This fixed it for me:
https://github.com/beto-rodriguez/LiveCharts2/issues/1495#issuecomment-2088313998 

Hopefully there is soon a new release that ships a fix.

**Comment by kendragoni** [comment]
#1495 Also worked for me as well.

**Comment by beto-rodriguez** [comment]
This is fixed with #1514, sorry for the delay on releasing that patch, a new version with this fix will be released in a few days, thanks for the issue, I will close this for now, we can keep track of this issue at #1495
