### ISSUE TITLE
Why the Axis lables are not  located in the correct postion,how to solve it?

### ISSUE THREAD

**Issue by gujian2git** [beto-rodriguez/LiveCharts2#1393]
This is my code:
var rateSeries = new LineSeries<DateTimePoint>
            {
                LineSmoothness = 0,
                Values = new ObservableCollection<DateTimePoint>((from r in ListHoleRecords select new DateTimePoint(r.UpdateTime, r.CollapseRate)).ToArray()),
                Name = "xxxx"
            };
RateSeries = new ISeries[] { rateSeries };
RateXaxis = new[] { new DateTimeAxis(TimeSpan.FromDays(1), date => date.ToString("MM-dd")) };

![Snipaste_2023-12-08_08-47-52](https://github.com/beto-rodriguez/LiveCharts2/assets/27773539/3d6a20cb-ec1b-4c92-8d6a-ffda64b18897)

**Comment by beto-rodriguez** [comment]
Hello

does your DateTime object has hours? minutes?

Sadly, I was not able to reproduce this issue
