### ISSUE TITLE
CartesianChart XAxes.MinStep is not working when that are too many colume

### ISSUE THREAD

**Issue by vcloudtree** [beto-rodriguez/LiveCharts2#1399]
**Describe the bug**
I am using CartesianChart to display data that get from database. When my data records are small or equal than 10. Everything work perfect.
When data records more than 10. The XAxes miniStep will change automatically. Even if I set miniStep to 1.
It look like XAxes will auto change the miniStep when XAxes labels are to long.
Does it possible to force all of the XAxes labels show like LiveCharts1?

In WPF
```html
<lvc:CartesianChart Grid.Row="1" Series="{Binding Series2}" XAxes="{Binding Series2XAxes}" YAxes="{Binding Series2YAxes}" Margin="20,0,20,0">
``` 
In Code
```c#
            //SeriesData
            Series2.Add(new ColumnSeries<ObservableValue>
            {
                Values = Series2Values,
                DataLabelsSize = 8,
                DataLabelsPaint = new SolidColorPaint(SKColors.White),
                DataLabelsPosition = DataLabelsPosition.Top,
                DataPadding = new LvcPoint(0.5, 0.5),
                Stroke = new SolidColorPaint(SKColors.White),
            });

            List<string> labelData = new List<string>();
            for (int i = 1; i <= 31; i++)
            {
                labelData.Add("Day " + i.ToString());
            }

            //SeriesAxes
            Series2XAxes.Add(
                new Axis
                {
                    Labels = labelData,
                    LabelsPaint = new SolidColorPaint
                    {
                        Color = SKColors.White,
                    },
                    MinStep = 1,
                });
``` 

**Expected behavior**

**Screenshots**
Data small or equal than 10 records
![2](https://github.com/beto-rodriguez/LiveCharts2/assets/76141431/68428958-fa67-42db-92e5-14060c12f834)

Data big than 10 records
![3](https://github.com/beto-rodriguez/LiveCharts2/assets/76141431/83e273a0-65a6-411b-b79a-b6126607dc9d)

Data has 30 records
![1](https://github.com/beto-rodriguez/LiveCharts2/assets/76141431/f6f6e353-2273-4a33-b1c0-b3464f8ba22d)

LiveChart, It can display all label that I have set
![4](https://github.com/beto-rodriguez/LiveCharts2/assets/76141431/5ad87645-4d42-41d4-a5e9-a79d3d02614b)

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser: Chrome

**Additional context**

**Comment by KomodoCrypto** [comment]
I am facing the same issue that you describe also for Y Axis.

**Comment by vcloudtree** [comment]
Is there any solution for this problem?
Otherwise customizing axes will become very inconvenient. It cannot display all custom axis labels

**Comment by kojima-imamura** [comment]
Can I use the following options?
`ForceStepToMin = true`

**Comment by vcloudtree** [comment]
> Is it not possible with the following options?
> 
> `ForceStepToMin = true`

Yes, Thanks for @kojima-imamura, it work perfect!
