### ISSUE TITLE
Gradient/mask on chart

### ISSUE THREAD

**Issue by LabuzzMichal** [beto-rodriguez/LiveCharts2#14]
Hi,

I am currently using LiveCharts v0 but its missing possibility to add gradient/mask on chart serie. I would like to accomplish something like this:
![image](https://user-images.githubusercontent.com/17740334/112726272-cc0a1080-8f1c-11eb-8c5d-663b15911790.png)

I know I could accomplish it by dividing my bars into smaller pieces but I believe that adding mask/gradient is much better approach. Is it possible in v2? 

Best regards,
Michał

**Comment by beto-rodriguez** [comment]
Yes, there is no sample built yet, but yes you could.

Set the Stroke property of your series to a new [Solid Color Paint Task](https://github.com/beto-rodriguez/LiveCharts2/blob/master/src/skiasharp/LiveChartsCore.SkiaSharp/Painting/SolidColorPaintTask.cs) instance, then set the Shader property, Here are some samples about how shaders work:

https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/graphics/skiasharp/effects/shaders/

Feel free to create a pull request with the sample if you succeed.

**Comment by beto-rodriguez** [comment]
There is a sample already build with the `LinearGradientPaintTask` paint task @trympet added to the repo

https://github.com/beto-rodriguez/LiveCharts2/blob/master/samples/ViewModelsSamples/Design/LinearGradients/ViewModel.cs

![image](https://user-images.githubusercontent.com/10853349/116000797-462ec300-a5b7-11eb-9223-c16175fbab43.png)
