### ISSUE TITLE
When I want to set the x-axis name, the zh-CN content becomes a square

### ISSUE THREAD

**Issue by julingguyuan** [beto-rodriguez/LiveCharts2#140]
When I use WPF LiveCharts2, I create a line chart and set its x-axis. When I set the name of x-axis in zh-CN
, the box after garbled code is displayed in the interface
As shown in the figure below, the numbers on the y-axis or English will not be garbled, and the garbled squares will appear when Chinese characters are used on the x-axis
Thank you very much for your source code, but I still hope you can help me, thank you
![picture](https://user-images.githubusercontent.com/23516305/129052316-94a042f5-2c99-4dee-afb6-bc80b1874c36.png)

**Comment by aspion-ae** [comment]
The default SKTypeface does not seem to have characters for zh-CN. Insert the line `paint.Typeface = SKTypeface.FromFamilyName("Microsoft YaHei");` in `LabelGeometry.OnDraw(SkiaSharpDrawingContext context, SKPaint paint)`, Chinese characters are also displayed.
Suggestion: expose a property (FontFamilyName?) wherever a text is displayed, and use it if set.

**Comment by julingguyuan** [comment]
> The default SKTypeface does not seem to have characters for zh-CN. Insert the line `paint.Typeface = SKTypeface.FromFamilyName("Microsoft YaHei");` in `LabelGeometry.OnDraw(SkiaSharpDrawingContext context, SKPaint paint)`, Chinese characters are also displayed.
> Suggestion: expose a property (FontFamilyName?) wherever a text is displayed, and use it if set.

Thank you very much for your idea. I solved my problem by modifying the OnDraw event in Labelgeometry.cs in LiveChartsCore.SkiaSharpView, adding the setting of character font in the event, recompiling and generating dynamic library for replacement
![code](https://user-images.githubusercontent.com/23516305/129250623-d36a95dc-0412-49d6-b2ed-7ae6f15bf3d6.png)
![Window](https://user-images.githubusercontent.com/23516305/129250635-20d39827-ef13-4900-a9a7-805196039df6.png)

**Comment by beto-rodriguez** [comment]
Thanks for the report, in the next release, now we will be able to set the font family in any paint object/

see: https://github.com/beto-rodriguez/LiveCharts2/blob/master/samples/ViewModelsSamples/Axes/LabelsFormat/ViewModel.cs#L28
