### ISSUE TITLE
LiveChart2 is no more updated when switching tab in MAUI .NET8

### ISSUE THREAD

**Issue by CedreLo** [beto-rodriguez/LiveCharts2#1404]
LiveChart2 is no more updated when switching tab in MAUI .NET8 with Android and Windows

**Comment by CedreLo** [comment]
In fact it seems to be frozen, i can't even pan or zoom

**Comment by beto-rodriguez** [comment]
Hello, can you provide a repo/zip with the issue please?

it seems to work properly for me.

**Comment by beto-rodriguez** [comment]
Actually, I am trying with the source code in the dev branch, maybe you need to wait for the next release of the library, it will include the bits for net 8.

**Comment by CedreLo** [comment]
Hi
Thanks for your work.

I have reproduced the behavior in a sample application, maybe i do something wrong ?

[TestGraph.zip](https://github.com/beto-rodriguez/LiveCharts2/files/13701393/TestGraph.zip)

**Comment by CedreLo** [comment]
> Actually, I am trying with the source code in the dev branch, maybe you need to wait for the next release of the library, it will include the bits for net 8.

Thanks

Any release date ?

**Comment by CedreLo** [comment]
Hi,

I installed pre release version 2.0.0-rc2 and it works!!!

**Comment by beto-rodriguez** [comment]
I will close this since it seems that everything is working now, thanks for the report!
