### ISSUE TITLE
.NET Core 3.1 Server?

### ISSUE THREAD

**Issue by TRiBotWillB** [beto-rodriguez/LiveCharts2#141]
Would it be possible to run this library on a netcore3.1 web sever? I want to generate chart images on the backend

**Comment by beto-rodriguez** [comment]
It should be possible.

The package `LiveChartsCore.SkiaSharpView` can generate images using the `SKCartesianChart`, `SKPieChart` and `SKGeoMap` classes.

Install it from [NuGet](https://www.nuget.org/packages/LiveChartsCore.SkiaSharpView/2.0.0-beta.40)

Finally follow this sample:

https://github.com/beto-rodriguez/LiveCharts2/blob/master/samples/WPFSample/General/ChartToImage/View.xaml.cs#L47

**Comment by TRiBotWillB** [comment]
> It should be possible.
> 
> The package `LiveChartsCore.SkiaSharpView` can generate images using the `SKCartesianChart`, `SKPieChart` and `SKGeoMap` classes.
> 
> Install it from [NuGet](https://www.nuget.org/packages/LiveChartsCore.SkiaSharpView/2.0.0-beta.40)
> 
> Finally follow this sample:
> 
> https://github.com/beto-rodriguez/LiveCharts2/blob/master/samples/WPFSample/General/ChartToImage/View.xaml.cs#L28

Working perfectly, thank you!

**Comment by TRiBotWillB** [comment]
Is it also possible to show a legend using SKCartesianChart? I'm setting the LegendPosition but it's not visible in my image. I also notice it lacks the Font/Color options for the Legend that you get with the normal charts?

**Comment by beto-rodriguez** [comment]
Legends and tooltips are not supported by now in `ISkiaSharpCharts`, see #123 

What do you mean with SeriesColors?

**Comment by TRiBotWillB** [comment]
Is it possible to get the Canvas within my own IChartLegend? I can't see how I'm able to actually draw anything to the screen. Any pointers would be appreciated :)

**Comment by beto-rodriguez** [comment]
I am closing this issue for now, and moved the legend issue to #144.

To draw your own legend you must use the (SkiaShap API)[https://github.com/mono/SkiaSharp].

Feel free to submit a PR if you suceed.
