### ISSUE TITLE
Counter-clockwise Polar Chart Direction

### ISSUE THREAD

**Issue by seikosantana** [beto-rodriguez/LiveCharts2#1410]
**Is your feature request related to a problem? Please describe.**
There doesn't seem to be a way to specify polar chart to be counter-clockwise.

**Describe the solution you'd like**
A property in PolarChart or PolarAxis to make it counter clockwise.

**Describe alternatives you've considered**
Tried `IsInverted` in PolarAxis in AngleAxes collection but does not make any noticeable difference.

**Additional context**
Currently using Avalonia 11.0.2 and LiveChartsCore.SkiaSharpView.Avalonia Version=2.0.0-rc2

**Comment by beto-rodriguez** [comment]
This is fixed with the referenced commit and will be included in the next version of the library.

The sample in the web site will be also updated, but basically all we need to do is invert the axis:

```c#
public PolarAxis[] AngleAxes { get; set; } = [
    new PolarAxis
    {
        LabelsRotation = LiveCharts.TangentAngle,
        IsInverted = true // enables counter clockwise draw. // mark
    }
];
```
