### ISSUE TITLE
Critical Bug in WPF.

### ISSUE THREAD

**Issue by hukjin** [beto-rodriguez/LiveCharts2#1416]
=====================XAML====================

 <Border Grid.Column="0" Background="White" >
     <lvc:CartesianChart   ZoomMode="Y"  Name="ChartF" Series="{Binding SeriesF}" XAxes="{Binding XAxesF}" YAxes="{Binding YAxesF}" LegendPosition="Bottom"  Sections="{Binding SectionsF}"  DataPointerDown="ChartF_DataPointerDown"  />
 </Border>

=================ViewModel====================
  public ObservableCollection<ObservablePoint> ValuesAF = new ObservableCollection<ObservablePoint>();
  public ObservableCollection<ObservablePoint> ValuesBF = new ObservableCollection<ObservablePoint>();
  public ObservableCollection<ObservablePoint> ValuesCF = new ObservableCollection<ObservablePoint>();
  public ObservableCollection<ObservablePoint> ValuesDF = new ObservableCollection<ObservablePoint>();
  public ObservableCollection<ObservablePoint> ValuesEF = new ObservableCollection<ObservablePoint>();
    SeriesF = new ISeries[]
{
    // use the second type argument to specify the geometry to draw for every point
    // there are already many predefined geometries in the
    // LiveChartsCore.SkiaSharpView.Drawing.Geometries namespace
        new ScatterSeries<ObservablePoint, LiveChartsCore.SkiaSharpView.Drawing.Geometries.CircleGeometry>
        {
            Values = ValuesAF,
           Stroke = new SolidColorPaint(SKColors.Blue, 1),
           GeometrySize = 10,
            Name= "Hole(5mm)",
            YToolTipLabelFormatter=value=>$": {value.Coordinate.SecondaryValue} , {value.Coordinate.PrimaryValue*-1}",
         //   
            Fill=new SolidColorPaint(new SKColor(0, 0, 255)),

        },

     // Or Define your own SVG geometry   
          new ScatterSeries<ObservablePoint, SVGPathGeometry>
        {
            Values = ValuesBF,
            Stroke = null,
            GeometrySize = 10,
            Name="Dust(5mm)",
              Fill=new SolidColorPaint(new SKColor(146, 0, 128)),
              GeometrySvg=SVGPoints.Star,
               YToolTipLabelFormatter=value=>$": {value.Coordinate.SecondaryValue} , {value.Coordinate.PrimaryValue*-1}",
        },
           new ScatterSeries<ObservablePoint, SVGPathGeometry>
        {
            Values = ValuesCF,
            Stroke = null,
            Name="Dust(4mm)",
            GeometrySize = 10,
              Fill=new SolidColorPaint(new SKColor(255, 118, 120)),
               YToolTipLabelFormatter=value=>$": {value.Coordinate.SecondaryValue} , {value.Coordinate.PrimaryValue*-1}",
              GeometrySvg = SVGPoints.Gem,

        },
            new ScatterSeries<ObservablePoint, SVGPathGeometry>
        {
            Values = ValuesDF,
            Stroke = null,
            Name = "dust(1.5mm)",
           GeometrySize = 10,
             Fill=new SolidColorPaint(new SKColor(124, 252, 0)),
              YToolTipLabelFormatter=value=>$": {value.Coordinate.SecondaryValue} , {value.Coordinate.PrimaryValue*-1}",
             GeometrySvg = SVGPoints.Pin,
        },
             new ScatterSeries<ObservablePoint, SVGPathGeometry>
        {
            Values = ValuesEF,
            Stroke = null,
            Name= "noClass(0.5mm)",
            GeometrySize = 10,
              Fill=new SolidColorPaint(new SKColor(0, 0, 0)),
               YToolTipLabelFormatter=value=>$": {value.Coordinate.SecondaryValue} , {value.Coordinate.PrimaryValue*-1}",
                GeometrySvg=SVGPoints.Cross,
        },
};
=======================================================================================
1. Remain some point like a illusion

when i call in the Thread.

 private async void startingafter()
 {
     await Task.Delay(1500);
     ValuesAF.Clear();
     ValuesBF.Clear();
     ValuesCF.Clear();
     ValuesDF.Clear();
     ValuesEF.Clear();
 }

some point remain like a illusion please refer to attached video.

2. When i use by click event , if i call the the refreshlist function at below. sometime is not change the name in the UI.
  private async void refeshlist(string cls, string change, double ch)
  {
        await Task.Delay(200);
        if (cls.Equals("G1"))
            {
    
          SeriesF[0].Name = change;
    }
}

https://github.com/beto-rodriguez/LiveCharts2/assets/38930530/c1511d79-52e0-4207-b9d8-460260d0125e

**Comment by beto-rodriguez** [comment]
Hi and thanks for the report.

It is hard to understand where the issue exactly is, could you please provide a minimal reproducible sample where I can see this issue?

My first guess is that you are working on multiple threads, but you are not handling that, that is why you are getting random results, you can take a look at the next article:

https://livecharts.dev/docs/WPF/2.0.0-rc2/samples.general.multiThreading

**Comment by beto-rodriguez** [comment]
This is now fixed with the referenced PR.

It will be included in the next version of the library, thanks for the report!!
