### ISSUE TITLE
Bar chart spacing problem

### ISSUE THREAD

**Issue by SuperH-o** [beto-rodriguez/LiveCharts2#1418]
Padding = 0 is used when the X-axis coordinates are decimal and are displayed within 1; MaxBarWidth = double.PositiveInfinity; Causes the bar chart to overlap, and the column width is at least 1

Here is the code I used and a screenshot:

ColumnSeries<ObservablePoint> columnseries = new ColumnSeries<ObservablePoint>();
columnseries.Padding = 0;
columnseries.MaxBarWidth = double.PositiveInfinity;

![微信图片_20240108163650](https://github.com/beto-rodriguez/LiveCharts2/assets/75147860/e82a24d2-ee97-4df4-b0b4-28f52f933974)

How do you get him to show like this?
![微信图片_20240108164120](https://github.com/beto-rodriguez/LiveCharts2/assets/75147860/8eb1630d-1586-4021-9dba-a04afacf0f75)

**Comment by beto-rodriguez** [comment]
Hello

It seems that your issue is using `double.PositiveInfinity`, instead use `double.MaxValue`

Infinite is probably causing a math error when the bar width is measured.

**Comment by beto-rodriguez** [comment]
Just noticed the docs use `PositiveInfinity` also, that was updated with the referenced commit and will be included in the next release, sorry about that and thanks for the report!
