### ISSUE TITLE
[WPF] configure space between bars in ColumnSeries

### ISSUE THREAD

**Issue by LabuzzMichal** [beto-rodriguez/LiveCharts2#142]
**Is your feature request related to a problem? Please describe.**
Currently its not possible to change space size between bars in ColumnSeries. I have quite small chart with a lot of bars and the space between bars is larger than bar width 
![image](https://user-images.githubusercontent.com/17740334/129256341-8c3b5c5f-e3ee-4e3e-8384-df02c79d2674.png)

**Describe the solution you'd like**
I would like to have property allowing me to modify size of space between bars

**Comment by beto-rodriguez** [comment]
This was partially supported, but it was a buggy anyways, the referenced commit and the previous one fix this issue.

I also added a sample on how to customize the bars size, in your case it seems that setting `GroupPadding` to `0` is enough, but the `MaxBarWidth` property might also be useful.

https://github.com/beto-rodriguez/LiveCharts2/blob/master/samples/ViewModelsSamples/Bars/Spacing/ViewModel.cs

Thanks again for the report.
