### ISSUE TITLE
Just use `System.Text.Json` instead of swapping dependencies conditionally?

### ISSUE THREAD

**Issue by hawkerm** [beto-rodriguez/LiveCharts2#1420]
**Describe the bug**
While you don't need to include a reference to `System.Text.Json` on the newer .NET based targets, the package is still available and targets things like net framework and net standard on NuGet here: https://www.nuget.org/packages/System.Text.Json#supportedframeworks-body-tab

You can just remove your compilation conditional and update your msbuild conditional to include this package instead of including newtonsoft json at all.

**Expected behavior**
Same dependency chain regardless of target framework, latest json serialization from .NET itself, more consistency across platforms.

**Comment by beto-rodriguez** [comment]
Thanks for the tip! 

I have not noticed that it was compatible also with net462, the reference to Newtonsoft will disappear since the next version of the library.
