### ISSUE TITLE
[WinUI / Uno.WinUI] ArgumentNullException when DataContext is null

### ISSUE THREAD

**Issue by kazo0** [beto-rodriguez/LiveCharts2#1422]
**Describe the bug**
On a page with charts that are data-bound to the DataContext results in an `ArgumentNullException` when clearing the DataContext. 

Our navigation framework always clears the Page's DataContext when navigating back to a previous page. 

Sample app: [livecharts.zip](https://github.com/beto-rodriguez/LiveCharts2/files/13906184/livecharts.zip)

**To Reproduce**
1. Launch Sample App
2. Click on the Clear DataContext button
3. Crash

**Expected behavior**
No crash

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 
**Additional context**
Error log:

> Exception thrown: 'System.ArgumentNullException' in System.Linq.dll
> Exception thrown at 0x76579392 (KernelBase.dll) in livecharts.exe: WinRT originate error - 0x80004003 : 'Value cannot be null. (Parameter 'source')'.
> Unhandled exception at 0x757F2451 (combase.dll) in livecharts.exe: 0xC000027B: An application-internal exception has occurred (parameters: 0x149D7270, 0x00000001).

**Comment by beto-rodriguez** [comment]
Thanks for the report @kazo0 

This fix will be included in the next version of the library.
