### ISSUE TITLE
Polar chart with 3 values not closing the stroke

### ISSUE THREAD

**Issue by Bkara1981** [beto-rodriguez/LiveCharts2#1424]
**Describe the bug**
Polar chart with 3 values ends up as a two line instead of a triangle with 3 lines, does not close the stroke lines when stroke is used. But the area is closed as a triangle without any issues. 

**To Reproduce**
1.create a polar chart with 3 item in values of the series
2.define a series template using a stroke

**Expected behavior**
Stroke must be Closed just like the chart area

**Screenshots**
![image (1)](https://github.com/beto-rodriguez/LiveCharts2/assets/127882251/1b9f17f8-58e4-49cf-83f8-04972aa55c08)
![image](https://github.com/beto-rodriguez/LiveCharts2/assets/127882251/1acdde59-4561-413c-b18b-bfbe1b3c7056)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Platform: console application 
 - Version 2.0.0-rc2

**Comment by beto-rodriguez** [comment]
Hello and thanks for the issue, I will close this because it is already answered in #1542.

Hope ti helps!
