### ISSUE TITLE
BitmapVisual to support rendering of arbitrary bitmaps

### ISSUE THREAD

**Issue by fitdev** [beto-rodriguez/LiveCharts2#1429]
**Is your feature request related to a problem? Please describe.**
There was a need to put small bitmaps in relation to say the columns of the bar chart or pieces of a pie chart (for example these could be photos/avatars of people). However the closest thing to it was `SVGVisual` which, while good, is still ultimately only a vector-based graphic. There is definitely a need for bitmaps as well.

**Describe the solution you'd like**
Ideally a class like `SVGVisual`, but for bitmaps. Which can either accept an `SKBitmap` as a property or a parameter on the constructor. Also would be nice the ability to control disposal of such bitmaps with a setting - whether explicit by user, or automatic.

**Describe alternatives you've considered**
Tried too cook something up myself, but it did not work:

```cs

  public sealed class BitmapGeometry : RectangleGeometry/*, IDisposable*/ {

    public BitmapGeometry() { } //NOTE: Needed to satisfy generic constraints

    public BitmapGeometry(SKBitmap? bitmap) {
      _Bitmap = bitmap;
    }

    readonly SKBitmap? _Bitmap;


    public override void OnDraw(SkiaSharpDrawingContext context, SKPaint paint) {
      //Q: Why does this alternate between when Width == Height == 0 and _Bitmap not null, and the opposite (when Width == Height == ok, but _Bitmap is null)? => Maybe because these are different instances and one is instantiated properly through Paint, while the other is instantiated incorrectly by internal mechansims?
      if (_Bitmap is null) return;
      var c = context.Canvas;
      c.DrawBitmap(_Bitmap, SKRect.Create(X, Y, _Bitmap.Width, _Bitmap.Height), paint); //Q: Are coordinates correct, should we use rects?
    }

  }
  
  public sealed class BitmapPaint : SolidColorPaint {

    public BitmapPaint(IChartView<SkiaSharpDrawingContext> chart, SKBitmap? bitmap) {
      _g = new(bitmap);
      AddGeometryToPaintTask(chart.CoreCanvas, _g);
    }

    readonly BitmapGeometry _g;

    //Q: Maybe we can use this routine to draw? This way we do not need IChartView<SkiaSharpDrawingContext>?
    //public override void InitializeTask(SkiaSharpDrawingContext drawingContext) => base.InitializeTask(drawingContext);

  }
  
  public sealed class BitmapVisual : GeometryVisual<BitmapGeometry, LabelGeometry, SkiaSharpDrawingContext>, IDisposable {

    public BitmapVisual(IChartView<SkiaSharpDrawingContext> chart, SKBitmap? bitmap) {
      Fill = new BitmapPaint(chart, Bitmap = bitmap);
    }

    public SKBitmap? Bitmap { get; init; } //TODO: Update paint (Fill) on set!

    public void Dispose() => Bitmap?.Dispose();

  }

```

with the usage:

```cs

var skbmp = GetSKBitmap();
var vistest = new BitmapVisual(_Chart, skbmp) {
  SizeUnit = MeasureUnit.Pixels,
  Width = 48,
  Height = 48,
  LocationUnit = MeasureUnit.Pixels,
  X = 100,
  Y = 100,
};
_Chart.VisualElements = new[] {vistest};

```

**Comment by beto-rodriguez** [comment]
Hello

You can access the SkiaSharp layer, and draw anything there with the SkiaSharp API, I think this is probably the best alternative in your case, you can follow this thread where I explained more about it: https://github.com/beto-rodriguez/LiveCharts2/discussions/1586#discussioncomment-10608662

I will close this for now because there are no plans to include this in the short term of the library and there are options to build our own implementation (This feature will be implemented in the library, but not at this point)
