### ISSUE TITLE
[Uno.WinUI] SharedWith Can't align both

### ISSUE THREAD

**Issue by lld1995** [beto-rodriguez/LiveCharts2#1431]
I do like https://livecharts.dev/docs/UnoWinUi/2.0.0-rc2/samples.axes.shared
But it can't be align
![image](https://github.com/beto-rodriguez/LiveCharts2/assets/17978390/9cbd8454-4046-484c-a253-946662607120)

**Comment by lld1995** [comment]
If i set one xaxis IsVisible=false

**Comment by lld1995** [comment]
Or the axis has different text

**Comment by beto-rodriguez** [comment]
Hello, axes are aligned when setting the DrawMargin for both:

>  // Force the chart to use 70px margin on the left, this way we can align both charts Y axes. 
DrawMargin = new Margin(150, Margin.Auto, Margin.Auto, Margin.Auto);

There is also #1463 that explain more about this feature.

Hope it helps, let me know if there is something I can do to help.
