### ISSUE TITLE
ChartPointPointerHover Events are not raised when TooltipPosition is set to Hidden

### ISSUE THREAD

**Issue by fitdev** [beto-rodriguez/LiveCharts2#1437]
**Describe the bug**
`Series<,,,>.ChartPointPointerHover` and `Series<,,,>.ChartPointPointerHoverLost` Events are not raised when Chart's `TooltipPosition` is set to `Hidden`.

**Expected behavior**
Showing or hiding of tooltips should _not_ influence whether or not pointer-related events are raised.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Avalonia 11.0.7

**Comment by beto-rodriguez** [comment]
I will close this as duplicate of #1621, the good news is that this is already fixed and will be included in the next version of the library.
