### ISSUE TITLE
Zoom by section not drawing a section

### ISSUE THREAD

**Issue by guilhermeolisi** [beto-rodriguez/LiveCharts2#1438]
An user report in Discussions, Q&A Category, I open a issue report from this:

Tadza0641 reported on Dec 27, 2023:
When i do use zoom by section, it sometimes stops drawing a rectangle around the area that is supposed to be zoomed is not shown.

I have the same problem in my project. Initially the rectangle is shown normally, but when I pages and returning to the page containing the chart the rectangle no longer appears

**Expected behavior**
The section rectangle should always appear when zooming by section

**Screenshots**
Zoom by section working:
![Livecharts2 chart zoombysection working](https://github.com/beto-rodriguez/LiveCharts2/assets/25594740/fbcb43b8-b46d-4ea0-bc42-45daaa27e05a)

Zoom by section does not work after changing page and returning to page containing the chart:
![Livecharts2 chart zoombysection not working](https://github.com/beto-rodriguez/LiveCharts2/assets/25594740/4a36e94d-2ce4-4403-b226-3b93643fdf9b)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Avalonia 11.1.3
 - NET 8

**Livecharts version:** 2.0.0-rc2

_Originally posted by @Tadza0641 in https://github.com/beto-rodriguez/LiveCharts2/discussions/1414_

**Comment by beto-rodriguez** [comment]
Hi

I tried to reproduce without success, Which UI framework are you using? MAUI?

**Comment by valeneva** [comment]
Hi,

I'm struggling with the same problem. 

I have two TabItems which boths contain CartesianChart with almost same parameters.
When I set the zoom to "X", the rectangle in the chart (when zooming by section) only appears until I click to another TabItem and back. Then the rectangle stops appearing although zooming by section still works. 

WPF applications in .NET 8...

**Comment by guilhermeolisi** [comment]
Hi, I'm using Avalonia 11.1.3 and .NET 8.

> Hi
> 
> I tried to reproduce without success, Which UI framework are you using? MAUI?

**Comment by beto-rodriguez** [comment]
Fixed with the referenced commit and will be included in the next version of the library.
