### ISSUE TITLE
Support legends in memory charts

### ISSUE THREAD

**Issue by beto-rodriguez** [beto-rodriguez/LiveCharts2#144]
**Is your feature request related to a problem? Please describe.**
`ISkiaSharpChart` currently do not support legends, it is not possible to generate images that contain legends if there is no a UI framework (server or console apps).

**Describe the solution you'd like**
Define a default `IChartLegend<T>` that uses SkiaSharp to render the legend.

**Describe alternatives you've considered**
none.

**Additional context**
none.

**Comment by sigmarsson** [comment]
Is there an example I could follow to create my custom legend with  ```IChartLegend<TDrawingContext>``` ?

**Comment by beto-rodriguez** [comment]
Yes, [this](https://github.com/beto-rodriguez/LiveCharts2/blob/easier-drawables/src/skiasharp/LiveChartsCore.SkiaSharp/SKCharts/SKDefaultLegend.cs) is the legend I am building to close #144, notice it is not finished yet, but this seems almost complete.

**Comment by sigmarsson** [comment]
"this" is 404

**Comment by beto-rodriguez** [comment]
It was just merged to dev.

https://github.com/beto-rodriguez/LiveCharts2/blob/dev/src/skiasharp/LiveChartsCore.SkiaSharp/SKCharts/SKDefaultLegend.cs
