### ISSUE TITLE
IndexOutOfRangeException in ScaleDataToPixels/ScalePixelsToData when SKCartesianChart was created from ICartesianChartView<SkiaSharpDrawingContext>

### ISSUE THREAD

**Issue by fitdev** [beto-rodriguez/LiveCharts2#1440]
**Describe the bug**

Methods `LvcPointD ScaleDataToPixels(LvcPointD point, int xAxisIndex = 0, int yAxisIndex = 0)` and `LvcPointD ScalePixelsToData(LvcPointD point, int xAxisIndex = 0, int yAxisIndex = 0)` throw `IndexOutOfRangeException` because they are trying to access non-existing axes via `Core.XAxes` and `Core.YAxes`:

https://github.com/beto-rodriguez/LiveCharts2/blob/5836c7fe73fe49cead353c50691d3db735dff662/src/skiasharp/LiveChartsCore.SkiaSharp/SKCharts/SKCartesianChart.cs#L200

https://github.com/beto-rodriguez/LiveCharts2/blob/5836c7fe73fe49cead353c50691d3db735dff662/src/skiasharp/LiveChartsCore.SkiaSharp/SKCharts/SKCartesianChart.cs#L209

These axes are not apparently set on the Core when `new SKCartesianChart(ICartesianChartView<SkiaSharpDrawingContext> view)` is used as this constructor sets `XAxes = view.XAxes;` and `YAxes = view.YAxes;` but  not on the Core.

However using these axes manually as
```cs
  public static LvcPointD ScaleDataToPixelsFix(this SKCartesianChart chart, LvcPointD point) {
    var scaler = new Scaler(chart.Core.DrawMarginLocation, chart.Core.DrawMarginSize, chart.XAxes.First());
    var scaler2 = new Scaler(chart.Core.DrawMarginLocation, chart.Core.DrawMarginSize, chart.YAxes.First());
    return new(scaler.ToPixels(point.X), scaler2.ToPixels(point.Y));
  }
```
it produces incorrectly scaled `LvcPointD`s. So the fix for this issue should not only reference existing axes, but probably instantiate such axes first on the underlying `Core`.

**To Reproduce**
```cs
var chart = new SKCartesianChart(OriginalChart);
chart.ScaleDataToPixels(new LvcPointD(0d, 0d)); // <- IndexOutOfRangeException
```

**Expected behavior**
ScaleDataToPixels/ScalePixelsToData should also work.

**Desktop (please complete the following information):**
 - OS: Win 11, Avalonia

**Additional Context**
There is a need to construct a new `SKCartesianChart` from existing in order to be able to save it as a bitmap as described in one of your samples: https://livecharts.dev/docs/Avalonia/2.0.0-rc2/samples.general.chartToImage

The issue arises when the original chart also utilizes `CartesianChart.UpdateStarted` handler to perform additional drawing as described in your other sample: https://livecharts.dev/docs/Avalonia/2.0.0-rc2/samples.general.drawOnCanvas

So, in order to reproduce the original chart exactly (to save it as a bitmap), one also needs to reapply custom drawing, which does use APIs like ScaleDataToPixels/ScalePixelsToData. Hence the need to support these in `SKCartesianChart`.

**Comment by beto-rodriguez** [comment]
Hello and thanks for the report.

The problem you are facing is because the `SKChart` has not being measured yer, thus those axes are null.

Just measure the chart:

```c#
var chart = new SKCartesianChart(OriginalChart);

 // get an image from the "In-memory chart" to force the measure method.
var generatedImage = chart .GetImage();

 // now this works
chart.ScaleDataToPixels(new LvcPointD(0d, 0d)); 
```

I am not completely sure whether this is a bug, maybe we could throw with an exception that explains what is going on, for now I will close this issue, but I understand the confusion and will keep an eye on this, if others keep facing this issue, we will surely explicitly throw in this case with a message that explains the issue.
