### ISSUE TITLE
Window Forms (.NET Framework) issue

### ISSUE THREAD

**Issue by martamdf** [beto-rodriguez/LiveCharts2#146]
Hi, 
Sorry, I do not know if I am doing something wrong, but maybe there is a problem.

**Problem:**

I am trying to use the library in a Winform Application (.NET Framework). 
I installed the required NuGet packages, but when I try to instert a Cartesian Chart in the form[Design], the application throw an exception, and remove the Cartesian Chart from the Tools Panel. Then I try with the component GeoMap, and again, I have an error.

![errorCartesianChart](https://user-images.githubusercontent.com/73435257/129853246-71a61c31-c994-458b-8fa4-b08e9fc5d904.png)
![errorGeoMap](https://user-images.githubusercontent.com/73435257/129853427-47911812-3221-40ae-a53d-47d5bc090405.png)

Thank you in advance for your support!

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Visual Studio 2019

**Comment by beto-rodriguez** [comment]
Hi Marta, thanks for the report, can you please let me know you .Net Framework target version? the minim version to use v2 is `4.62`

**Comment by martamdf** [comment]
Hi Alberto!
I am using .NET Framework 4.7.2

![image](https://user-images.githubusercontent.com/73435257/129924316-0c6bc669-425b-4b6a-8120-41c9245c87c9.png)

**Comment by beto-rodriguez** [comment]
Fixed with 84378fc7a915564faead887211f2b217b177987d and 976ff1dc6e620f76d5a8815d1d2bc558ff6b64cf.

Since beta 60 version the packages should be designer-friendly/

Thanks for the report
