### ISSUE TITLE
Is this type of visualization possible?

### ISSUE THREAD

**Issue by johmarjac** [beto-rodriguez/LiveCharts2#1461]
In an CartesianChart I have an X-Axis and an Y-Axis.

The X-Axis shows a Date for each X-Point. Now I want to display two Stacked Columns for each single X-Point. And each column has its 3  stacked y-values.

Is that possible?

I mean it like this:
![image](https://github.com/beto-rodriguez/LiveCharts2/assets/30114127/9ec0a3cf-5ac0-44a6-ac75-1c798a81c1b5)

I found this here: 
![image](https://github.com/beto-rodriguez/LiveCharts2/assets/30114127/7bfccdb0-5501-4771-a4da-f34aba9462ec)
but I think its not exactly what I want as the categories are "just" axis labels in that example, correct?

Anyone an idea?

**Comment by Albert634515** [comment]
Shouldn't that just be two groups of stacked columns? 
Grouped on a date axis?

**Comment by johmarjac** [comment]
Yes meanwhile I got it working. Now I am wanting to put a text for each bar so I can tell the user which bar is for what. Is that possible?

**Comment by Albert634515** [comment]
Maybe you can try one of the following options:
https://docs.anychart.com/Common_Settings/Labels
https://docs.anychart.com/Axes_and_Grids/Text_Markers
