### ISSUE TITLE
If you set axis's property IsVisible=false and running a period of time, chart will popup exception.(The X axis has an excessive number of separators)

### ISSUE THREAD

**Issue by Overrainy** [beto-rodriguez/LiveCharts2#1462]
**Describe the bug**
When you set axis to hidden, then run a period of time, chart will throw exception.

**To Reproduce**
1. Set axis property: IsVisible = false.
2. Run a period of time. (LiveChartCore\CoreAxis\GetPossibleMaxLabelSize() => _stepCount  will keep increaseing until it exceeds the upper 10000.)
3. Chart will throw (The X/Y axis has an excessive number of separators) exception.

**Root Cause**
LiveChartCore\CoreAxis\GetPossibleMaxLabelSize() => _stepCount++; (Line:1050)
"_stepCount" will increases over time and can not be reset by method "Invalidate()".

**Desktop (please complete the following information):**
 - OS: Windows

**Additional context**
WPF
![image](https://github.com/beto-rodriguez/LiveCharts2/assets/35245893/4b42ebab-a015-47a5-a694-cc90f035be2f)

**Comment by weishour** [comment]
I am also facing the same problem here. Do you have a corresponding solution？

**Comment by Overrainy** [comment]
> I am also facing the same problem here. Do you have a corresponding solution？

Set Axis Property: IsVisible = true and Padding = new LiveChartsCore.Drawing.Padding(0) 
use property "Padding = new LiveChartsCore.Drawing.Padding(0) " to hide Axis

**Comment by BMaj7** [comment]
`Padding = new LiveChartsCore.Drawing.Padding(0)` does not work for me to hide labels
I use axis property **Labeler** as a workaround (CartesianChart with HeatSeries<WeightedPoint>)
`Labeler = value => ""`

**Comment by beto-rodriguez** [comment]
This is fixed with https://github.com/beto-rodriguez/LiveCharts2/pull/1514, sorry for the delay on releasing that patch, a new version with this fix will be released in a few days, thanks for the issue, I will close this for now, we can keep track of this issue at https://github.com/beto-rodriguez/LiveCharts2/issues/1495
