### ISSUE TITLE
When export svg, the background of part of legends is black

### ISSUE THREAD

**Issue by dumbnessrf** [beto-rodriguez/LiveCharts2#1470]
when i try to convert chart to svg file, i met some issues that my legends part become black, but it render well in the UI
![image](https://github.com/beto-rodriguez/LiveCharts2/assets/57406262/9c3923f1-326d-4e9f-801a-a9e27a95d4db)
in the ui
![image](https://github.com/beto-rodriguez/LiveCharts2/assets/57406262/789c2019-f58e-4a0e-8b4b-efd3717a29b5)

```csharp
public Axis[] XAxes { get; set; } = [new Axis() { 
    Name = "Minutes",
    MinLimit = 0-5, // forces the axis to start at -5
    MaxLimit = 60+5, // forces the axis to end at 65
    CustomSeparators = Enumerable.Range(0,61).Where(s=>s%5==0).Select(d=>Convert.ToDouble(d)).ToList()
}];
public Axis[] YAxes { get; set; } = [new Axis()
{ 
    Name= "Count" ,
    Labeler = (d) =>
    {
        return $"*{d:F0}";
    },
    MinLimit = 0,
    SubseparatorsPaint = new SolidColorPaint
    {
        Color = SKColors.Black.WithAlpha(50),
        StrokeThickness = 0.5f
    },
    SubseparatorsCount = 4
}];

var cartesianChart = new LiveChartsCore.SkiaSharpView.WPF.CartesianChart() { Width = 800, Height = 400};
cartesianChart.XAxes = XAxes;
cartesianChart.YAxes = YAxes;
cartesianChart.Series = Series;
cartesianChart.LegendPosition = LiveChartsCore.Measure.LegendPosition.Right;
```
thanks if any (๑￫ܫ￩)

**Comment by dumbnessrf** [comment]
i found reason in svg plain text, there is a tag `clipPath ` which defines svg rect size, and there is `id` key
```html
<clipPath id="cl_d">
	<rect width="800" height="400" />
</clipPath>
```
and there also have tag `g` with the same id `clip-path="url(#cl_d)"`, when i add `fill="none"`, the legend works fine!
```html
<g clip-path="url(#cl_d)" fill="none">
	<path d="M649.764 270.225L649.764 129.77 ....."
</g>
```
all you need is to find what `clipPath `'s id that define svg size, and find `<g clip-path="url(#your id)">`, add `fill="none"`
Actually, this is a bit troublesome. I don't know why it's like this. It doesn't happen when I export the PNG

**Comment by dumbnessrf** [comment]
here is my script for fix this bug, and it need thrid lib call `SVG`, you can download it from nuget
```csharp
var path = @"CartesianStraight.svg";
SvgDocument svgDocument = SvgDocument.Open(path);
var svgSizeElement = svgDocument.Children.First() as SvgRectangle;
var width = svgSizeElement.Width.Value;
var height = svgSizeElement.Height.Value;
var svgID = "";
foreach (var element in svgDocument.Children)
{
	if (element is SvgClipPath clip_path)
	{
		if (clip_path.Children.First() is SvgRectangle rect && svgID=="")
		{
			if (rect.Width.Value == width && rect.Height.Value == height)
			{
				svgID = clip_path.ID;
			}
		}
	}
	if (element is SvgGroup g)
	{
		var str = g.ClipPath.ToString();
		
		if (str.Contains(svgID))
		{
			g.Fill = new SvgColourServer(System.Drawing.Color.Transparent);
		}
	}
}
svgDocument.Write(@"1234Cartesian.svg");
```

**Comment by mimeie** [comment]
Hello @dumbnessrf 

could you provide what's behind `Series` in your code
`cartesianChart.Series = Series;`

it could help me with my issue: [https://github.com/beto-rodriguez/LiveCharts2/issues/1469](url)

Thanks
Michael

**Comment by dumbnessrf** [comment]
> Hello @dumbnessrf
> 
> could you provide what's behind `Series` in your code `cartesianChart.Series = Series;`
> 
> it could help me with my issue: [https://github.com/beto-rodriguez/LiveCharts2/issues/1469](url)
> 
> Thanks Michael

actually, it just some kind of plain data, the data type is `LineSeries`
```csharp
Series = new LineSeries<int>[] { };
var temp = new List<LineSeries<int>>();
foreach (var d in PeriodTrendParams)
{
    temp.Add(new LineSeries<int>
    {
        Values = new ObservableCollection<int>(d.PeriodParams.Select(d => d.LogsCount)),
        Fill = new SolidColorPaint(GetColorByLevel(d.Level)), // mark
        Name = d.Level.ToString(),
        Stroke = null,
        GeometryFill = null,
        GeometryStroke = null
    });
}
Series = temp.ToArray();

```

**Comment by dumbnessrf** [comment]
> Hi @dumbnessrf
> 
> thanks very much for your fast reply. So in this case what I don't get is what's exactly inside `Values`? It seems it is just an observable integer. so where is the Value for the x-axis in your data? somehow in your screenshot it starts at "40 minutes"
> 
> or do you just write zeros into the collection before 40minutes?

just write zeros into that collection
in my case, i made a logs viewer  in wpf, and the x-axis value just the minutes in an hour, y-axis value is the logs count in that period of minutes, and i use that to observe my logs trends

**Comment by beto-rodriguez** [comment]
Thanks for [your workaround](https://github.com/beto-rodriguez/LiveCharts2/issues/1470#issuecomment-2022119422) @dumbnessrf, I think this is the best alternative for now, SVG is parsed by SkiaSharp, there not much this library can do there, at the level of this library, your workaround is perfect, I am closing this because that seems a good alternative, If someone really needs the perfect SVG, then the issue should be raised to SkiaSharp.
