### ISSUE TITLE
WPF: Inverting axis does not work as expected

### ISSUE THREAD

**Issue by network-interface-controller** [beto-rodriguez/LiveCharts2#1473]
**Describe the bug**
I have a chart with a row series as illustrated below and want to change the direction of the x-axis (horizontal) to mirror it, i.e. the x-axis starts on the right at 0 and the rows are drawn to the left.
![grafik](https://github.com/beto-rodriguez/LiveCharts2/assets/118933349/fd815f29-03ee-466e-a0e8-c724a9cf4fc5)

However, if I set the x-axis to inverted (and remove the MinLimit of 0) a strange effect occurs and the bars behave totally unpredictable:
![grafik](https://github.com/beto-rodriguez/LiveCharts2/assets/118933349/bddd96bf-c26f-486c-a46c-5502c9e00e10)

```
public List<ISeries> Series
{
    get
    {
        ... [calculations]...

        List<ISeries> rowSeries =
        [
            new RowSeries<int>
            {
                Values = myValues,
                Fill = new SolidColorPaint(ChartColors.DodgerBlue),
                DataLabelsPaint = new SolidColorPaint { ... },
                DataLabelsSize = 20,
                DataLabelsPosition = DataLabelsPosition.End,
                DataLabelsFormatter = (chartPoint) => $"{chartPoint.Coordinate.PrimaryValue}",
                XToolTipLabelFormatter = (chartPoint) => $"..."
            }
        ];

        return rowSeries;
    }
}

public static Axis[] XAxesValues =>
[
    new Axis
    {
        MinLimit = 0,
        LabelsPaint = Configuration.StandardLabelsPaint
    }
];

public Axis[] YAxesValues =>
[
    new Axis
    {
        Labels = myLabels,
        LabelsPaint = Configuration.StandardLabelsPaint,
        ShowSeparatorLines = false,
        ForceStepToMin = true,
        Padding = new Padding(0, 0, 25, 0)
    }
];
```

**To Reproduce**
1. Create a row series as explained above
2. Set the x-axis to inverted
```
public static Axis[] XAxesValues =>
[
    new Axis
    {
        IsInverted = true,
        LabelsPaint = Configuration.StandardLabelsPaint
    }
];
```

**Expected behavior**
Something similar to this:
![grafik](https://github.com/beto-rodriguez/LiveCharts2/assets/118933349/f7eed4c6-38f4-4963-a66a-19f4a5907c97)

**Desktop (please complete the following information):**
OS: Windows 10, Version 22H2
Browser --> Not applicable; WPF app
Version: LiveChartsCore 2.0.0-rc2, LiveChartsCore.SkiaSharpView.WPF 2.0.0-rc2
Framework: .NET 8.0

**Comment by beto-rodriguez** [comment]
Fixed with the referenced PR and will be included in the next version of the library. Thanks for the report.
