### ISSUE TITLE
WPF: PieChart with AngularTicksVisual displays zero value as exponential value

### ISSUE THREAD

**Issue by N4gl3r** [beto-rodriguez/LiveCharts2#1482]
**Describe the bug**

I'm using the Pie Chart with Angular Ticks Visual and Needle. In some specific constellations of minimum and maximum values,  the zero value label is displayed as exponential value.

**To Reproduce**

![image](https://github.com/beto-rodriguez/LiveCharts2/assets/131244459/92667a89-2ca6-4537-8dd4-22a0146b3e4c)

![image](https://github.com/beto-rodriguez/LiveCharts2/assets/131244459/e9b2601c-4b0a-4c09-aaa9-c94851fc310f)

![image](https://github.com/beto-rodriguez/LiveCharts2/assets/131244459/ddecf582-92b6-437e-a1e1-4fa636cee99f)

![image](https://github.com/beto-rodriguez/LiveCharts2/assets/131244459/7ef2d939-3d90-41ad-94b0-409a6ed49c82)

**Expected behavior**

Zero value shall not be displayed as exponential value.

**Desktop**

OS: Win10 Enterprise, 21H2, German language
WPF
LiveCharts v2.0.0-rc1.2 and rc2.0

**Comment by beto-rodriguez** [comment]
Hi and thanks for the report, this was definitively missing, we need to have control over the format of the labels.

In the next version of the library (rc3) setting the `Labeler` property in the `AngularTicksVisual` will prevent this issue:

```c#
VisualElements = new VisualElement<SkiaSharpDrawingContext>[]
{
    new AngularTicksVisual
    {
        Labeler = value => value.ToString("N1"),
        ...
    },
    Needle
};
```

Thanks again!
