### ISSUE TITLE
PieChart doesn't show custom legend

### ISSUE THREAD

**Issue by kajsa-work** [beto-rodriguez/LiveCharts2#1489]
**Describe the bug**
Custom legend is not applied to PieChart.

**To Reproduce**
1. Create a custom legend using the guide: [Custom legends](https://livecharts.dev/docs/WPF/2.0.0-rc2/CartesianChart.Legends#customlegend.cs).

2. Add the legend to a cartesian chart as well as a pie chart:
```
<lvc:CartesianChart Series="{Binding Series}">
  <lvc:CartesianChart.Legend>
    <local:Legend/>
  </lvc:CartesianChart.Legend>
</lvc:CartesianChart>

<lvc:PieChart Series="{Binding Series2}">
  <lvc:PieChart.Legend>
    <local:Legend/>
  </lvc:PieChart.Legend>
</lvc:PieChart>
```
3. The Cartesian chart will have the custom legend, but the Pie chart will have the default one.

**Expected behavior**
PieChart should have the same legend style as the cartesian chart

**Screenshots**
![Skärmbild 2024-04-17 135339](https://github.com/beto-rodriguez/LiveCharts2/assets/123486025/4c768386-f083-41e3-8d29-b0e743ff3bac)

**Desktop (please complete the following information):**
WPF, version 2.0.0-rc2

**Comment by bsilvia** [comment]
This is related to #985 and was partially fixed with #859 for the `CartesianChart` control but not the `PieChart` or `PolarChart` controls.
