### ISSUE TITLE
Layout issues stacked columns

### ISSUE THREAD

**Issue by Albert634515** [beto-rodriguez/LiveCharts2#149]
Screen size windows 100%
- Labels on top of columns shows only one number:
 It does not make a difference if DataLabelsPosition = LiveChartsCore.Measure.DataLabelsPosition.Top, is used or not
![image](https://user-images.githubusercontent.com/85439711/130318139-e97615f0-1880-41bd-a5cf-f05aafa9fe6b.png)

Screen size windows 125%
- Labels overlap (when there is not enough space to place label in column)

![image](https://user-images.githubusercontent.com/85439711/130318281-003ca104-d124-4413-9014-6369f0b558f3.png)

**Comment by beto-rodriguez** [comment]
Labels on stacked bar series are now placed properly, thanks for the report.
