### ISSUE TITLE
toolbar

### ISSUE THREAD

**Issue by FreeVB** [beto-rodriguez/LiveCharts2#15]
It is recommended to add a toolbar in the new version, such as:

![LiveCharts](https://user-images.githubusercontent.com/30093956/112809972-2c2fbc80-90ad-11eb-9f27-cca2dadc1e11.png)

**Comment by beto-rodriguez** [comment]
This can be done out side the control, I do not see why it should be handled by the library.

**Comment by beto-rodriguez** [comment]
I am closing this now, since it seems out of of the scope of the library.
