### ISSUE TITLE
ScalesXAt, ScalesYAt should reference directly to XAxis,Yaxis instead of index

### ISSUE THREAD

**Issue by Daimonion1980** [beto-rodriguez/LiveCharts2#1504]
Hello
I'm using LiveCharts to display often two oder more data stream of consecutive values (from a serial interface). Every data stream has its own YAxis and the connection to the data stream is done vie the ScaleYAt Property. 
https://livecharts.dev/api/2.0.0-rc2/LiveChartsCore.SkiaSharpView.LineSeries-2#property-ScalesYAt

Adding a data stream:

```csharp
YAxis.Add(new Axis
{ 
   .. data from the Axis
});
ISeries elmnt = new LineSeries<DateTimePointScopeDatasetAdapter>
{
  ...other properties
  ScalesYAt = YAxis.Count() - 1
};
elmnt.SeriesId = generatedUniqueId;
PlotData.Add(elmnt);
```

When removing one data stream from the diagram (not the last) I also do remove the associated YAxis from the List. 

Removing a data stream:

```csharp
var existingPlot = PlotData.FirstOrDefault(i => i.SeriesId == parameter.Id);
if (existingPlot is not null)
{
    //Read index for the connected  YAxis
    int? yAxisPosition = (existingPlot as LineSeries<DateTimePointScopeDatasetAdapter>)!.ScalesYAt;
    if (yAxisPosition.HasValue)
    {
        YAxis.RemoveAt(yAxisPosition.Value);
    }
    PlotData.Remove(existingPlot);
}
```

But after doing this I have to reorder all the other ScalesYAt Values from the remaining data streams, because this property is an index to the list. 

**Describe the solution you'd like**
Is it possible to reference the Yaxis directly? e.g.
```csharp
  ScalesYAt = YAxis[index]
```

**Comment by beto-rodriguez** [comment]
Hello

Sadly no, axes are designed to work by index, sadly you would need to handle that manually :(

I will close this for now, but let me know if there is something I can do to help.

**Comment by Daimonion1980** [comment]
Hey, 

Is it possible to save this as a feature request?

From the perspective of 2.0.0, I can understand, that this will not be changed in this release.
