### ISSUE TITLE
Not Working with latest MAUI mobile app.

### ISSUE THREAD

**Issue by IsaacHatilima** [beto-rodriguez/LiveCharts2#1506]
**Describe the bug**
I installed the package as instructed using nuget cli, I have the latest version of a maui project.

**To Reproduce**
1. I coppy the code from the website and the ViewModel says **_The type or namespace name 'SeriesCollection' could not be found (are you missing a using directive or an assembly reference?)_**

What am I not doing right?

**Comment by dotMorten** [comment]
@IsaacHatilima are you missing a using directive? SeriesCollection works fine for me.

**Comment by beto-rodriguez** [comment]
Hi @IsaacHatilima I think that you are using the old library (v0, not available for MAUI), please ensure that you are using v2, you can find the docs here:

https://livecharts.dev/

I will close this for now, but let me know if there is something else I can do to help!
