### ISSUE TITLE
The legend does not reflect my Stroke color

### ISSUE THREAD

**Issue by Xixi0506** [beto-rodriguez/LiveCharts2#1507]
### Discussed in https://github.com/beto-rodriguez/LiveCharts2/discussions/1427

<div type='discussions-op-text'>

<sup>Originally posted by **Daimonion1980** January 19, 2024</sup>
Hello Community. 

Maybe someone can give me a hint, why my stroke color is not reflected in the legend.
Please take a look at the screenshot:

![image](https://github.com/beto-rodriguez/LiveCharts2/assets/12880413/54f4c868-04f7-4863-a2a4-d895c94c7293)

And here are the codesnippets, I use to display the series:

ViewModel:
```csharp
partial void OnInitialize()
{
    //temporäre initalisierung einer Achse, des Plots
    PlotData = new ObservableCollection<ISeries>
    {
        new LineSeries<ObservableValue>
        {
            Values = plotValue1,
            Fill = null,
            GeometrySize = 0,
            Stroke = new SolidColorPaint(SKColors.Red),
            LineSmoothness = 0.3,
            Name="Drehzahl rpm"
        }
    };
}
```

UserControl:
```xml
<Grid>
    <lvc:CartesianChart Grid.Row="0" Height="Auto" Series="{Binding PlotData}" 
                        ZoomMode="ZoomX" LegendPosition="Bottom" />
</Grid>
```

I found [issue 365](https://github.com/beto-rodriguez/LiveCharts2/issues/365) but this should already be fixed in 2.0.0-rc2 ?!

Does anybody see the problem?</div>

**Comment by beto-rodriguez** [comment]
Hello sorry about the confusion, what is shown in the legend is the geometry, not the line, setting the `GeometryStroke` will make the trick:

```c#
new LineSeries<double>
{
    Values = new double[] { 2, 1, 3, 5, 3, 4, 6 },
    Fill = null,
    GeometryStroke = new SolidColorPaint(SKColors.Red),
}
```

![image](https://github.com/user-attachments/assets/fadfd986-dac4-43ab-a4da-7613e56a13df)

In your case it is confusing because your geometry is null.
