### ISSUE TITLE
PIeChart Documentation Out of Date

### ISSUE THREAD

**Issue by MiaJohnson** [beto-rodriguez/LiveCharts2#1508]
.Net Maui, Pie Chart: Documentation shows using PrimaryValue, but PrimaryValue is Obsolete.

How do you set the DataLabel format?
https://livecharts.dev/docs/Maui/2.0.0-rc2/PieChart.Pie%20series#datalabels
DataLabelsSize = 22,
DataLabelsPosition = LiveChartsCore.Measure.PolarLabelsPosition.Middle,
DataLabelsFormatter = point => point.PrimaryValue.ToString("N2") + " elements"

**Comment by darrendowning16** [comment]
This is how I have my lineseries Y Axis set up. You should be able to use this example and apply it to your chart type

`YToolTipLabelFormatter = (chartPoint) => $"Flu: {chartPoint.Model?.Property1Name:N0} {Environment.NewLine}Wave: {chartPoint.Model?.Property2Name:N0}",`

**Comment by Darkproduct** [comment]
You can do it like this:
```c#
// …
new HeatSeries<WeightedPoint> {
  // …
  YToolTipLabelFormatter = (point) => $"{point.Model?.Weight}",
  // …
}
// …
```

Other options with the x and y values:
```c#
YToolTipLabelFormatter = (point) => $"Value: {point.Model?.Weight}\r\nX: {point.Model?.X}\r\nY: {point.Model?.Y}",
```

[Copied from my Answer on SO](https://stackoverflow.com/a/78472288/6411540)

**Comment by beto-rodriguez** [comment]
Thanks for the report 🚀 

this is now fixed int he lates version of the docs: https://livecharts.dev/docs/Maui/2.0.0-rc4/PieChart.Pie%20series#datalabels
