### ISSUE TITLE
3d hardware acceleration 

### ISSUE THREAD

**Issue by maxima120** [beto-rodriguez/LiveCharts2#1515]
I understand you are using SkiaSharp for hardware acceleration but I think it is 2d only. Am I correct? If yes - do you have any hardware acceleration for 3d charts? (besides the native wpf use of directx)?

**Comment by beto-rodriguez** [comment]
Hello, we completely rely on SkiaSharp and completely depend on the features provided there.

That's it, we are only a math library, we measure and place shapes in the UI, SkiaSharp handles all the details behind it, I wish I could assist you more, but that is all we do in this library :(

Let me know if I can assist you further.
