### ISSUE TITLE
FontFamily="{StaticResource myFont}" not work

### ISSUE THREAD

**Issue by mehdininja** [beto-rodriguez/LiveCharts2#1518]
Setting the font does not work in this way,
```
<Grid>
    <lvc:CartesianChart Series="{Binding Series}" XAxes="{Binding XAxes}" YAxes="{Binding YAxes}" VisualElements="{Binding VisualElements}" TooltipPosition="Hidden" FontFamily="{StaticResource myFont}" FontWeight="Bold" Typography.StylisticSet4="True"/>
</Grid>
```
also in the C# code FontFamily is **string** property. 
```
LabelsPaint = new SolidColorPaint(SKColors.Black) {FontFamily="", SKFontStyle = new SKFontStyle(SKFontStyleWeight.Bold, SKFontStyleWidth.Normal, SKFontStyleSlant.Upright)},
```

So how to apply FontFamily="{StaticResource myFont}" ?

**Comment by beto-rodriguez** [comment]
Hello

The `FontFamily` that you are binding there is not a properly of this library, it comes from the type of the control inherits from (`ContentView`) this property is defined by MAUI and I am not completely sure what is the usage of it in this context.

This library uses SkiaSharp to render things, so things inside a chart are not part of MAUI, fonts are set on Series or Axes, for example:

https://github.com/beto-rodriguez/LiveCharts2/blob/5836c7fe73fe49cead353c50691d3db735dff662/tests/LiveChartsCore.UnitTesting/SeriesTests/LineSeriesTest.cs#L245

This is the way fonts are defined in SkiaSharp, I know docs could be better here.

I hope this helps!
