### ISSUE TITLE
Building from CSV

### ISSUE THREAD

**Issue by Boobert21** [beto-rodriguez/LiveCharts2#1520]
Hello.

Sorry for posting this as a BugReport. I didn't find any mention in the documentation.

Is the library for WinForms able to build graphs from a CSV file? If yes, please send a link to the instructions

**Comment by beto-rodriguez** [comment]
Hi!

This article is the closes to that:

https://livecharts.dev/docs/Maui/2.0.0-rc2/Overview.Mappers

I hope it helps!
