### ISSUE TITLE
Custom Geometry binding to the point ,for  control the rotation of geometry

### ISSUE THREAD

**Issue by TianCaibailei** [beto-rodriguez/LiveCharts2#1527]
I’ve been experimenting with the example from [this link](https://github.com/beto-rodriguez/LiveCharts2), but I haven’t been able to achieve the functionality I want. Specifically, I’d like to customize the Geometry, and each Geometry’s rotation angle should be bound to the Y value of the data point. This way, when representing wind or flow direction curves, the custom Geometry can rotate along with the data to indicate the direction.
![企业微信截图_20240604084806](https://github.com/beto-rodriguez/LiveCharts2/assets/69564975/edf70504-7c61-409e-972b-9a3f17505e3d)

 Thank you for contributing such a beautiful tool, and I look forward to your response.”

**Comment by beto-rodriguez** [comment]
Hello and thanks for the issue.

This should be supported, and there should be at least a couple of ways to build this, there is a similar issue where I explain more about this:

https://github.com/beto-rodriguez/LiveCharts2/discussions/1586#discussioncomment-10608662

**Comment by beto-rodriguez** [comment]
There is now an example:

https://github.com/beto-rodriguez/LiveCharts2/blob/dev/samples/ViewModelsSamples/Lines/CustomPoints/ViewModel.cs

This will be in the web site in the next release, but this is already supported.
