### ISSUE TITLE
The update will not be displayed after 20 minutes

### ISSUE THREAD

**Issue by lizhuanshu** [beto-rodriguez/LiveCharts2#1537]
**Describe the bug**
Add a chart in a custom control, update once every three seconds, work very well, but after more than 20 minutes, the curve is no longer updated, the chart is not displayed after switching pages, Tooltip is working properly

**Screenshots**
![屏幕截图 2024-07-04 084408](https://github.com/beto-rodriguez/LiveCharts2/assets/35889803/b12d2e28-5f34-41df-b43c-6541c573c4da)
![屏幕截图 2024-07-04 084426](https://github.com/beto-rodriguez/LiveCharts2/assets/35889803/89a05c67-e6a7-41c8-a72f-0680eeb93d41)
![屏幕截图 2024-07-04 084603](https://github.com/beto-rodriguez/LiveCharts2/assets/35889803/8aeefca3-99ba-46a8-8356-1234bfd1946a)
![屏幕截图 2024-07-04 091011](https://github.com/beto-rodriguez/LiveCharts2/assets/35889803/c4fe0243-d84e-4bd6-abb5-b504423b2bab)
![屏幕截图 2024-07-04 091059](https://github.com/beto-rodriguez/LiveCharts2/assets/35889803/6ac0905e-081f-46f0-bea9-c0f5ff9043e6)

**Desktop (please complete the following information):**
 - OS: Win10
 - WPF
 - .net4.8

**Additional context**
I have a lot of Chart in my program

**Comment by lizhuanshu** [comment]
#1464 The same trouble

**Comment by erdmenchen** [comment]
This fixed it for me:
https://github.com/beto-rodriguez/LiveCharts2/issues/1495#issuecomment-2088313998 

Hopefully there is soon a new release that ships a fix.

**Comment by xiayaoxiang** [comment]
The same trouble

**Comment by beto-rodriguez** [comment]
This is fixed with #1514, sorry for the delay on releasing that patch, a new version with this fix will be released in a few days, thanks for the issue, I will close this for now, we can keep track of this issue at #1495
