### ISSUE TITLE
RTL Support

### ISSUE THREAD

**Issue by AbdullahUlber** [beto-rodriguez/LiveCharts2#154]
In the WPF version, setting the FlowDirection to RightToLeft mirrors the entire canvas, including all the labels.

FlowDirection = LeftToRight:
![image](https://user-images.githubusercontent.com/44041142/130325941-53c1523c-3c42-4776-81f9-c8be7c915dbe.png)

FlowDirection = RightToLeft:
![image](https://user-images.githubusercontent.com/44041142/130325267-1c0204fe-26fa-474e-98de-babe7fe2a0ec.png)

Instead, the labels should not be flipped and only their direction should change to right-to-left.

For example, the correct rendering of the above chart looks as follows:

FlowDirection = RightToLeft:
![image](https://user-images.githubusercontent.com/44041142/130325907-514ae3a2-7b04-4494-891b-0df5399875ca.png)

Proper RTL support in LiveCharts2 will be greatly appreciated.

**Comment by beto-rodriguez** [comment]
Have you tried the `IsInverted` property in the Axis class, setting this property to `true`, it will scale the axis in the opposite direction of the Cartesian coordinate system.

https://github.com/beto-rodriguez/LiveCharts2/blob/932ddd2c2254b09d9b4986ea8d7463f67e17b7bd/src/LiveChartsCore/Kernel/Sketches/IAxis.cs#L198

Is that enough in your case?

**Comment by AbdullahUlber** [comment]
I just tried out your suggestion. Setting `IsInverted` to `true` together with swapping the Y axes and changing the rotation of the x axis labels leads to the correct display. 

![image](https://user-images.githubusercontent.com/44041142/130331182-093f8231-1866-4cc0-a89c-9d8040b761e8.png)

Many thanks for the fast reply and the spot-on help. Greatly appreciated!
