### ISSUE TITLE
How to make DrawMarginFrame only show left and bottom borders？

### ISSUE THREAD

**Issue by ckmstydy** [beto-rodriguez/LiveCharts2#1549]
How to make DrawMarginFrame only show left and bottom borders？  Thanks~

**Comment by beto-rodriguez** [comment]
Hi

Currently the library does not directly support this feature, but you can build it, here is a related issue where you can find more info:

https://github.com/beto-rodriguez/LiveCharts2/discussions/1586

Let me know if there is something I can help with.
