### ISSUE TITLE
LiveChartsCore.SkiaSharpView.Uno.WinUI causes build issue in Uno 5.3.90

### ISSUE THREAD

**Issue by frogcrush** [beto-rodriguez/LiveCharts2#1552]
**Describe the bug**
Upgrading to Uno 5.3.90 with the LiveChartsCore.SkiaSharpView.Uno.WinUI package causes a build error for WinUI. 

**To Reproduce**
1. Create a new Uno WinUI project
2. Add a reference to LiveChartsCore.SkiaSharpView.Uno.WinUI 2.0.0-rc2
3. Build project for WinAppSDK

**Expected behavior**
Project should build successfully.

**Screenshots**
![image](https://github.com/user-attachments/assets/9745b19d-bd60-48a3-9579-c965db5b87b1)

**Desktop (please complete the following information):**
 - OS: Windows 11

**Additional context**
Worked fine with Uno 5.3.0-dev.1903

**Comment by ADD-David-Sancho** [comment]
The error is also reproduced upgrading to Uno 5.3.114, showing the same message with WinUI.
