### ISSUE TITLE
Scatter Series geometry size calculation - option to consider all series

### ISSUE THREAD

**Issue by DavidWiseman** [beto-rodriguez/LiveCharts2#1555]
**Is your feature request related to a problem? Please describe.**
I have multiple series in a scatter chart.  The size of the bubbles appears to be based on the weight within the series only.  My situation is that I want to compare SQL execution plans.  Each plan is a series with a different color.  I want to plot the durations on the Y axis and time on the X axis.  The weight of the bubble should be based on the count of executions.  At the moment one plan might have a max of 10 executions and the other 1000 - each currently producing the same size bubble.  The plan/series with a max of 10 should take into account that the max across all the series is 1000 and produce a smaller bubble.

**Describe the solution you'd like**
Ideally there would be an option to take into consideration the max/min value across all series.

**Describe alternatives you've considered**
I can add fake data points to each series with the min/max value across all series.  The X asis date time is set to DateTime.MinValue which is below the min limit for the chart.  These fake points don't get plotted but the values ensure that the weighting is consistent across the series.  
This workaround is good for me, but it would be nice to have a built in option.  If you decide not to implement the feature, the workaround above might help someone else.

Great work on this charting library. 🙏👍

**Comment by beto-rodriguez** [comment]
Hi and thanks for the report!

This makes sense! I'll schedule this for a future release!

**Comment by beto-rodriguez** [comment]
Fixed with the referenced commit, the sample in the website will be updated with this feature!

**Comment by DavidWiseman** [comment]
Nice - Having a StackGroup is a good fix for this issue.  Awesome work.  Thank you. ♥️
