### ISSUE TITLE
Classic Tooltips

### ISSUE THREAD

**Issue by brunossn** [beto-rodriguez/LiveCharts2#1558]
**Is your feature request related to a problem? Please describe.**
I understand the idea behind the new tooltips using Skia, but I ended up having to rely on an old version of LiveChart to support XAML tooltips. The old tooltips, although slower and more problematic, had several features, such as greater flexibility, the ability to use a reusable user control, and, in general, I had access to all the power of the .NET libraries.

Richer tooltips, like the one in the image below, become a huge challenge, almost impossible, with Skia.

![Captura de tela 2024-08-06 115118](https://github.com/user-attachments/assets/555c5acd-0d07-4ffb-b0ac-5b7349e042eb)

**Describe the solution you'd like**
I would like to have the possibility to include classic ToolTips, it could be a secondary option.

**Comment by beto-rodriguez** [comment]
You can use XAML tooltips, here is a comment I made about to achieve that:

https://github.com/beto-rodriguez/LiveCharts2/issues/912#issuecomment-1719959013

I will close this for now, but please let me know if you need further assistance.
