### ISSUE TITLE
Does not work 

### ISSUE THREAD

**Issue by Bodden007** [beto-rodriguez/LiveCharts2#1559]
The most stupid library. He doesn't see one or the other. All the examples are selected from the context and it is not clear how they are related to each other. It turned out to run only the very first example. It's a pity for the time spent

**Comment by beto-rodriguez** [comment]
Thanks!

Feel free to re-open an issue with context and a clear message on what you are trying to do.

**Comment by Bodden007** [comment]
I was trying to make this graph
https://livecharts.dev/docs/wpf/2.0.0-rc2/samples.lines.basic

I still couldn't figure out what to do with UserControl and why there is no Windows.XAML? There is no way to compare it in the examples. I'm new to XAML.
Why not complete examples?
I asked on two forums - no one knows.
