### ISSUE TITLE
in desk chinese characters work well,but in  browser (wasm) chinese become square

### ISSUE THREAD

**Issue by nollliu** [beto-rodriguez/LiveCharts2#1565]
I'm using livecharts2 in avalonia developping, the version is 2.0 RC2,it works well in desk ,just like this :
but,when I run in browser (wasm ) ,the chinese characters become square ,just like this :
I have already config ".HasGlobalSKTypeface(SKFontManager.Default.MatchCharacter('汉')); // <- Chinese ;",but it not work well in wasm,how can I fixed the issue? Can you give me some suggestion?
I'm sorry for my poor english,thank you very much!

**Comment by nollliu** [comment]
![ok](https://github.com/user-attachments/assets/ab827fcf-f1da-47c3-9fef-6c8deaef3357)
![fail](https://github.com/user-attachments/assets/3bbb4fb9-a97b-43e5-9215-a31544686b51)

**Comment by nollliu** [comment]
note: chinese characters , in wasm , avalonia control work well, but livecharts2  become square,just like this:
![show](https://github.com/user-attachments/assets/8fdc29f8-38db-4fec-9118-152a5176af0a)

**Comment by beto-rodriguez** [comment]
Hi!

You need to register the font manually for LiveCharts:

https://livecharts.dev/docs/Avalonia/2.0.0-rc2/Overview.Installation#configure-themes-fonts-or-mappers-optional

**Comment by nollliu** [comment]
That's great  to hear from you , I have already add the code: 
   LiveCharts.Configure(config =>
   {
       config.AddDarkTheme()
                .HasGlobalSKTypeface(SKFontManager.Default.MatchCharacter('汉')); // <- Chinese ;                       
   });
just like this:
![font-config](https://github.com/user-attachments/assets/24ac17d0-e8ce-4074-93a5-e20cdd42e436)
So,in the desk,chinese work well,but int the wasm  chinese become square,shall I need to do somthing extra?Can you give me some suggestion?  Thank you for your help !
