### ISSUE TITLE
Chart was unable to show up correctly while using WPF sample.

### ISSUE THREAD

**Issue by roface** [beto-rodriguez/LiveCharts2#1566]
**Describe the bug**
I followed the website and made a complete same WPF sample.
But somehow the chart didn't show up when I start the application.

**Code**
[ViewModel.cs]
```
using LiveChartsCore;
using LiveChartsCore.SkiaSharpView;

namespace WpfSample
{
    public class ViewModel
    {
        public ISeries[] Series { get; set; }
            = new ISeries[]
            {
                new LineSeries<double>
                {
                    Values = new double[] { 2, 1, 3, 5, 3, 4, 6},
                    Fill = null
                }
            };
    }
}
```

[MainWindow.xaml]
```
<Window x:Class="WpfSample.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:WpfSample"
        xmlns:lvc="clr-namespace:LiveChartsCore.SkiaSharpView.WPF;assembly=LiveChartsCore.SkiaSharpView.WPF"
        mc:Ignorable="d"
        Title="MainWindow" Height="450" Width="800">

    <Window.DataContext>
        <local:ViewModel />
    </Window.DataContext>

    <lvc:CartesianChart
        Series="{Binding Series}">
    </lvc:CartesianChart>
</Window>
```

**To Reproduce**
1. Start the application from Visual Studio 2022.
2. The chart didn't show up.

**Expected behavior**
A chart should be showed up correctly.

**Screenshots**
Started the application first, all is blank.
![lv1](https://github.com/user-attachments/assets/0d63c540-9083-4068-a472-1ca38ccea783)

When I click "maximize" button on window, the chart showed up.
![lv2](https://github.com/user-attachments/assets/f27608ee-8631-412c-aa8e-4c3018adce84)

Click "Restore" button on window, the window back to normal size and the chart left axis line only. 
![lv3](https://github.com/user-attachments/assets/0587eb81-5258-40fd-a8ec-2ac00f0049ee)

**Desktop (please complete the following information):**
 - OS: Windows 10 Professional  (Build 19045.4529)
 - Project with .NET 6.0

**Additional context**
A complete project files has been zip and uploaded to google drive.
https://drive.google.com/file/d/1KlJRkpG38tBk3S_pxETvnxcdO_9VrSoB/view?usp=sharing

**Comment by roface** [comment]
Does anyone help on this ?
Did the same code on all 3 PCs but still got the same result.

**Comment by kimseongmok** [comment]
I also experienced the same problem you experienced.

When I created and ran the sample project on another PC, I confirmed that it ran normally, and when I ran only the exe file on another person's PC, I confirmed that it ran normally.

The exact cause is unknown, but I think it may be caused by a conflict in the PC settings.

I am trying to run the project after initializing the PC.
[Uploading ChartTest.zip…]()

**Comment by kimseongmok** [comment]
> 저도 당신이 경험한 것과 똑같은 문제를 겪었습니다.
> 
> 다른 PC에서 샘플 프로젝트를 생성하여 실행해보니 정상적으로 실행되는 것을 확인하였고, 다른 사람의 PC에서 exe 파일만 실행해보니 정상적으로 실행되는 것을 확인하였습니다.
> 
> 정확한 원인은 알 수 없지만, PC 설정 충돌로 인해 발생하는 것이 아닐까 생각됩니다.
> 
> PC 초기화 후 프로젝트를 실행하려고 합니다. ChartTest.zip 업로드 중…

● Windows 10 Pro
● Microsoft Visual Studio Professional 2022 (64-bit) 
● .NET 8.0

**Comment by roface** [comment]
@kimseongmok 
Thanks for your reply. I am glad I am not the one who meets this issue.
I downgraded LiveCharts2 on Nuget for several versions but looks like it's an old problem.

@beto-rodriguez 
Is it possible to check WPF compatibiliy problem ?

**Comment by kvenkataraman** [comment]
Try explicitly adding the Height and Width properties in your XAML. This worked for the issue I was running into.

**Comment by roface** [comment]
@kvenkataraman 
Thanks for your recommendation.
However, same issue happens to me with dimension assignment.

**Comment by beto-rodriguez** [comment]
This issue is hard to reproduce from my side, I tried the sample you provided, and it work properly for me.

I have seen some WPF issues related with updating drivers: https://github.com/beto-rodriguez/LiveCharts2/issues/230

Sadly, that is all I know about this issue :(

**Comment by ukrock1990** [comment]
I have this problem too, with .net 6 and windows 11 23h2
I tested in some PC and see this problem in only 1 PC

**Comment by beto-rodriguez** [comment]
Can you try to update your drivers? I have seen a couple of reports fixed by this.

**Comment by roface** [comment]
@beto-rodriguez 
Thanks for the information, I will try the solution today and give feedback.

**Comment by roface** [comment]
After updating Intel graphic driver, the problem solved.
This is original driver version.
![originaldriver](https://github.com/user-attachments/assets/b9c36975-17be-405f-bcd9-fc600e8d6466)

This is the latest version.
![222](https://github.com/user-attachments/assets/7f874679-b615-40a3-93f8-2b93959844c1)

@beto-rodriguez 
Thanks again for mentioning it's about driver issue.

**Comment by beto-rodriguez** [comment]
Glad to help!
