### ISSUE TITLE
License Issue and Password Recovery Assistance Needed

### ISSUE THREAD

**Issue by songhwaPark** [beto-rodriguez/LiveCharts2#1568]
Hi
I purchased the Geared Live Chart for my work and have been using it well. However, I recently changed my work laptop and encountered a problem with the license. I tried to log in to your website to resolve this issue, but I couldn't log in because the password didn't match. I attempted to recover the password through your website, but I didn't receive the email. I must resolve this issue for my company work. I have no choice but to leave a message here. Please resolve this issue....

**Comment by beto-rodriguez** [comment]
Please mail me to rodriguezo.alberto@gmail.com, I can help you to activate your v0 license manually.
