### ISSUE TITLE
Axis ZeroPaint cannot be changed once set initially.

### ISSUE THREAD

**Issue by MajesticBevans** [beto-rodriguez/LiveCharts2#1578]
**Describe the bug**
ZeroPaint of Axis cannot be changed from one colour to another once the Axis has been constructed. It just disappears, as if it was set to null.

**To Reproduce**
Create a Cartesian plot and add an Axis reference, with ZeroPaint set to any colour. Then, set the ZeroPaint to a new colour. The separator at 0 will disappear.

**Expected behavior**
When the colour of ZeroPaint is set to a new value, the separator at 0 changes to newly set colour.

**Screenshots**

**Desktop**
 - OS: Windows 11
 - Avalonia, livecharts release 2.00-rc2

**Comment by beto-rodriguez** [comment]
Hi and thanks for the report!

The referenced commit fixes this issue and will be included in the next version of the library (rc3), thanks again!
