### ISSUE TITLE
LiveCharts 2 CartesianChart does not render when placed in an Avalonia UserControl

### ISSUE THREAD

**Issue by kvenkataraman** [beto-rodriguez/LiveCharts2#1581]
Bug (?):
Not entirely convinced this is a bug, but perhaps how the DataContext for the charts is being resolved. In any case ...

Embedded a CartesianChart in an AvaloniaUserControl (SubControlView/SubControlViewModel) and placed that on the MainView. The chart does not render when embedded in the control, but will render if placed directly on the MainView/MainViewModel.

**To Reproduce**
1. Create an Avalonia UserControl and associated ViewModel (e.g. SubControlView/SubControlViewModel).
2. Create an ISeries[] property with dummy data, and bind that to the control's CartesianChart.
3. Add SubControlView to the main view and run the app.
4. See that the chart does not render.
5. Remove control, and add an ISeries and CartesianChart directly to MainView/MainViewModel.
6. Observe that the chart renders.

**Expected behavior**
Expect charts to render whether from a control or main window.

**Desktop (please complete the following information):**
 - OS: Sonoma
 - Brave/Chrome and Desktop
 - Avalonia: 11.1.3
 - LiveCharts: 2.0.0-rc2

**Additional context**
Have tried ReflectionBinding, and setting RelativeSource but to no avail. Possibly related to this: https://github.com/beto-rodriguez/LiveCharts2/issues/1566

**Comment by kvenkataraman** [comment]
UPDATE:

Looks like you need to set the Height and Width properties in order for the chart to render if it's on a sub-control. Is this expected? The samples don't explicitly call out having to set those properties.

**Comment by beto-rodriguez** [comment]
Hello.

That depends on the layout the chart is placed on.

LiveCharts controls do not set an initial size, it is up to the developer to build that, maybe in a Future we will consider adding min height and width constraints to prevent this confusion.
