### ISSUE TITLE
Is it possible to display "month" on an axis

### ISSUE THREAD

**Issue by ClubberLangG** [beto-rodriguez/LiveCharts2#159]
Hi,

For now I have the X axis that display dates, but 

               new Axis
                {
                    Labeler = (value) => new DateTime((long) value).ToString("MMMM"),

                    MinLimit = minDate.Ticks,
                    MaxLimit = maxDate.Ticks,

                    Position = AxisPosition.Start,
                    //Padding = padding,
                    //ShowSeparatorLines = true,

                    LabelsRotation = 45,

                    // The MinStep property lets you define the minimum separation (in chart values scale)
                    // between every axis separator, in this case we don't want decimals,
                    // so lets force it to be greater or equals than 1
                    UnitWidth = TimeSpan.FromDays(30).Ticks
                }

What I wish is to align the month label, with the 15 of each month.
Is there a way to do this ?

Thx

**Comment by sigmarsson** [comment]
```
                Labeler = (value) =>
                {
                    var date = new DateTime((long) value);

                    return date.Day == 15 ? date.ToString("MMMM") : string.Empty;
                },
```

**Comment by beto-rodriguez** [comment]
Actually this is a good and valid solution for now @sigmarsson
