### ISSUE TITLE
Add Chart Title Property

### ISSUE THREAD

**Issue by MajesticBevans** [beto-rodriguez/LiveCharts2#1599]
I would like to be able to add a title to whole charts, rather than just individual axes,

**Describe the solution you'd like**
A 'Title' property (or perhaps ChartTitle) that shows a TextBlock above the chart, probably with a TitleFontSizeProperty. If the Title string is empty or white space, then the chart fills the space that the textblock would have taken up. This behaviour is similar to that of the Axis Name property.

**Describe alternatives you've considered**
I want this mainly for the purpose of exporting chart images, as I often have to stitch a separately made title image on top. It would be much more convenient and user friendly if titles could simply be added directly to the chart.

**Comment by beto-rodriguez** [comment]
Hello

The image in the article is not updated, but yes, Titles are supported:

https://livecharts.dev/docs/Maui/2.0.0-rc2/samples.lines.basic

Is that enough?

**Comment by MajesticBevans** [comment]
Ah I've never noticed that! Apologies

**Comment by MajesticBevans** [comment]
Ah I've never noticed that! Apologies
