### ISSUE TITLE
Increased UpdateFinished Event Frequency with Hidden Tooltip

### ISSUE THREAD

**Issue by ts-research7** [beto-rodriguez/LiveCharts2#1601]
Describe the bug
when setting the TooltipPosition to Hidden, the UpdateFinished event is triggered significantly more frequently compared to when the TooltipPosition is set to visible positions (e.g., Top). This behavior suggests that the chart control is updating more often than necessary when the tooltip is hidden, potentially leading to performance issues due to excessive rendering updates.

To Reproduce
1. Create a CartesianChart in a WPF application using LiveCharts2.
2. Bind the Series property to a view model providing data for a line series.
3. Set the TooltipPosition to Top and observe the frequency of UpdateFinished event triggers.
4. Change the TooltipPosition to Hidden.
5. Observe the frequency of UpdateFinished event triggers again and note the increase.

Code

```xml
<Window.DataContext>
    <local:ViewModel/>
</Window.DataContext>
<lvc:CartesianChart 
    Series="{Binding Series}" 
    TooltipPosition="Hidden"
    UpdateFinished="CartesianChart_UpdateFinished"/>
```

```c#
public partial class MainWindow : Window
{
    public MainWindow()
    {
        InitializeComponent();
    }

    private void CartesianChart_UpdateFinished(IChartView<SkiaSharpDrawingContext> chart)
    {
        Debug.WriteLine("Update finished");
    }
}

public partial class ViewModel : ObservableObject
{
    public ISeries[] Series { get; set; } =
    [
        new LineSeries<double>
        {
            Values = [2, 1, 3, 5, 3, 4, 6],
            Fill = null
        }
    ];
}
```

Expected behavior
The frequency of UpdateFinished event triggers should remain consistent regardless of whether the tooltip is visible or hidden, assuming no other variables affecting the update rate (like data changes or mouse interactions) are in play.

Actual Behavior
The UpdateFinished event is triggered far more frequently when TooltipPosition is set to Hidden. For instance, setting TooltipPosition to Top results in a normal trigger rate, but changing it to Hidden increases the trigger rate significantly under identical conditions.

Additional Information
LiveChartsCore.SkiaSharpView.WPF  Version: 2.0.0-rc2 
.NET Version: NET 8.0
Operating System: Windows 11 Pro
Visual Studio Version: Professional 2022

**Comment by beto-rodriguez** [comment]
Thanks for the report, the referenced commit will completely skip updates if tooltip is hidden.

This will be included in the next version of the library, thanks for the report!
