### ISSUE TITLE
Refactor access modifiers in base classes

### ISSUE THREAD

**Issue by jaybyrd42** [beto-rodriguez/LiveCharts2#1609]
Add possibility to override OnMouseDown, OnMouseUp and other related event handlers and reuse logic from those overriden methods in Classes derived from LiveChartsCore.Chart by changing InvokePointerDown, InvokePointerMove, InvokePointerUp, InvokePointerLeft... access modifiers to protected internal

**Comment by jaybyrd42** [comment]
Possibly refactor all internal modifers to protected internal.

Having internal access modifiers when using this library as Nuget package hinders modification

**Comment by beto-rodriguez** [comment]
I like this idea; I changed most of the internal methods to protected internal (at least the methods that make more sense).

This will be included in the next version, I hope this is enough, but let me know if something is not accessible enough.
