### ISSUE TITLE
Payment issues

### ISSUE THREAD

**Issue by hyungjun99** [beto-rodriguez/LiveCharts2#1610]
![image](https://github.com/user-attachments/assets/9ef8e98a-4cea-472e-bdbd-2459f6781ca6)

I'm contacting you because I'm having a problem with my payment site.

**Comment by beto-rodriguez** [comment]
Hello and sorry about the inconveniences, payments for v0 are disabled 😔

**Comment by hyungjun99** [comment]
> 안녕하세요, 불편을 끼쳐드려 죄송합니다. v0에 대한 결제가 비활성화되었습니다 😔

What if I want to use it commercially?

**Comment by beto-rodriguez** [comment]
You can do it, it is MIT licenced

**Comment by hyungjun99** [comment]
I want to use geared, should I still not pay?

**Comment by hyungjun99** [comment]
> You can do it, it is MIT licenced

I want to use geared, should I still not pay?
