### ISSUE TITLE
Auto resize based on section

### ISSUE THREAD

**Issue by shayolz** [beto-rodriguez/LiveCharts2#1611]
**Describe the bug**
I'm using last version of the package with WinForm. My graph plot real time data (Date + decimal) on a line graph. When i add a new section, outside the current series, i cannot see the section. For example, if a graph on Y got values from 1 to 10 and i plot a orizzontal section at 20, i cannot see the section.

**Expected behavior**
I would expect that adding a section outside the series, there was a resize of the graph to see also the section.

**Comment by beto-rodriguez** [comment]
Hello 

In my personal opinion, I think that the chart should only auto-scale to the data defined in the series, but I am open for discussion on this topic.

In your case, you can also manually set the axis range that you want to show to the user, using the max an min limits in the X or Y axes:

https://livecharts.dev/docs/wpf/2.0.0-rc2/CartesianChart.Axes%20properties#maxlimit-and-minlimit-properties

**Comment by shayolz** [comment]
Ok thanks, yea i was checking this section now. 

I was thinking to do this after i add the section dynamically.

`                    var minY = valuesToAdd.Min(x => x.Value);
                    var maxY = valuesToAdd.Max(x => x.Value);

                    var minSection = sections.Min(s => s.Yi);
                    var maxSection = sections.Max(s => s.Yj);

                    cartesianChart1.YAxes.First().MinLimit = (double)Math.Min(minY, (decimal)minSection);
                    cartesianChart1.YAxes.First().MaxLimit = (double)Math.Max(maxY, (decimal)maxSection);`

**Comment by beto-rodriguez** [comment]
That looks great, I will close this for now, but feel free to reply if need more help!
