### ISSUE TITLE
Check supported or Mapped Types

### ISSUE THREAD

**Issue by trashhacker** [beto-rodriguez/LiveCharts2#1628]
would be nice if i could check if a type is mapped or not 

LiveCharts.Supported(type type);
or 
LiveCharts.IsMapped(type type);

**Comment by beto-rodriguez** [comment]
Hi

This is not supported for now, why is this necessary? what is the issue you are facing that makes this necessary?

**Comment by beto-rodriguez** [comment]
I made public the mehotd to get the mappers, in the next version of the library you will be able to:

```c#
var map = LiveCharts.DefaultSettings.GetMap<ObservablePoint>();
var hasMap = map is not null;
```

This fixes your issue, but there are 2 ways to map an object to a chart:

https://livecharts.dev/docs/Maui/2.0.0-rc2/Overview.Mappers

The code here only detects mappers, not if the object implements `IChartEntity`.
