### ISSUE TITLE
Crash on series delete on a multiple Axis chart

### ISSUE THREAD

**Issue by nathangobinet** [beto-rodriguez/LiveCharts2#163]
**Describe the bug**
On a multiple Axis Chart, the function `CartesianSeries.SoftDelete()` causes a crash when the ContentPresenter in which the chart is placed change it content.
Looks like Axes are deleted before Series, so when Series are deleted, axes doesnt exist anymore.

**To Reproduce**
```cs

    class OutOfRangeChartVM
    {
        public List<ISeries> Series { get; set; }
        public List<Axis> YAxes { get; set; }

        public OutOfRangeChartVM()
        {
            YAxes = new List<Axis>
            {
                new Axis(), new Axis()
            };

            Series = new List<ISeries>()
            {
                new LineSeries<double>
                {
                    Values = new double[] { 0,1 , 2 ,4 ,5 ,1 ,0 ,4 ,0.4 ,3 ,2 ,1 ,1 ,3 ,2 ,1 ,2 ,1.2 ,1.21 ,1 },
                    ScalesYAt = 0,

                },
                new LineSeries<double>
                {
                    Values = new double[] { 2, 1, 0, 1, 2, 3, 1, 2, 5.4, 3.5, 0, 2, 0.1, -1, 2, 1,2, 2.2, 3.21, 0 },
                    ScalesYAt = 1,
                }
            };
        }
    }
```
See https://github.com/nathangobinet/LiveChart2-bugs/blob/master/LiveChart2Bugs/OutOfRangeChartVM.cs

**Screenshots**
![LiveChart2BugOutOfRange](https://user-images.githubusercontent.com/50440731/131110599-b6a901fd-54ba-48c1-952b-f38244532b39.gif)

**Desktop (please complete the following information):**
 - OS: WPF - Windows 10

**Comment by beto-rodriguez** [comment]
This is also fixed with fc05052cbbe6d466c3d63a9f4538c43133616f15, In general in that commit I reviewed how the library behaves when the library controls are attached/detached to the visual tree, it seems that IO also got this one.
