### ISSUE TITLE
Negative values in Stacked bar chart

### ISSUE THREAD

**Issue by korneliuscode** [beto-rodriguez/LiveCharts2#1639]
I use a stacked bar chart and some values are negative. In the tooltip, I show the share of the stacked value.
But for negative values it is zero.

`Func<ChartPoint, string> toolTipDataLabelFormatterPercentage = p => $"{p.PrimaryValue:N} ({p.StackedValue.Share:P})";
`

I think the values should either show negative percentages or even better (in my case) group positive values and negative values seperately.

I'm using the WPF version.

![image](https://github.com/user-attachments/assets/641e484e-9102-4143-a7c2-3bbd47c13fec)

**Comment by beto-rodriguez** [comment]
Fixed with the referenced commit and will be included in the next version of the library,

Thanks for the report!!
