### ISSUE TITLE
Use hardware-accelerated SKGLView

### ISSUE THREAD

**Issue by Kay-STL** [beto-rodriguez/LiveCharts2#1645]
**Is your feature request related to a problem? Please describe.**
In real-time charts that require high performance, using SKGLView rather than SKCanvasView results in much better frametimes. SKCanvasView is inherently software-rendered, whereas SKGLView is hardware-accelerated.

**Describe the solution you'd like**
Not 100% sure yet, mainly just want to ask a few questions first - namely, whether entirely switching to SKGLView would be feasible or not due to e.g. view incompatibility or other issues, or whether it'd be better to just document the option of using it with a ControlTemplate.

**Describe alternatives you've considered**
N/A

**Additional context**
I've tested switching to SKGLView in LiveChartsCore.SkiaSharpView.Maui on Android w/ SkiaSharp 3, and the frametime bump is pretty significant - a real-time chart that previously struggled to maintain 30fps is now much closer to 60fps.

**Comment by beto-rodriguez** [comment]
See https://github.com/beto-rodriguez/LiveCharts2/tree/hardware-accelerated

that branch works, but in my test, I get more frames on the SKCanvas than SKGLView, at least on windows, not completely sure why.

**Comment by Kay-STL** [comment]
> that branch works, but in my test, I get more frames on the SKCanvas than SKGLView, at least on windows, not completely sure why.

Huh, interesting - I've never had any issues with the Canvas view on Windows or iOS for what its worth, it's usually decently fast there, it's primarily Android where switching to the GL view makes a huge difference. I'm guessing the underlying `SKXamlCanvas` on Windows is probably fairly quick already.
