### ISSUE TITLE
Live Charts Activation

### ISSUE THREAD

**Issue by Alexandru-Taciuc** [beto-rodriguez/LiveCharts2#1646]
Hello,
I am contacting you regarding the **activation of Live Charts (1) Geared.**

As **no other means of communication worked** ([rodriguezo.alberto@gmail.com](mailto:rodriguezo.alberto@gmail.com), [Support@lvcharts.net](mailto:Support@lvcharts.net),  [support@lvcharts.net](mailto:support@lvcharts.net), Live-Charts repository archived) I found myself forced to open a ticket here.

I am part of a development team from Infineon Technologies to which you provided a **team license for Live Charts Geared** with the promise of **PRIVATE SUPPORT**.

My manager acquired development team licenses a while ago but is **no longer possible for him to share this licensees as your external account log in does NOT work anymore.**

**I require an offline activation for Live Charts geared.**

**Please provide any contact information (means of communication)** where I can provide you my Private Key together with all the necessary information required to validate the provided information (Manager name, team, department etc.)

**I would like to highlight the necessity of this, as we use Live Charts Geared in multiple projects!**

Thank you,
Alexandru

**Comment by beto-rodriguez** [comment]
Hello

Can you please mail me to [rodriguezo.alberto@gmail.com](mailto:rodriguezo.alberto@gmail.com), I can assist you there.

**Comment by Alexandru-Taciuc** [comment]
Hello,

Thank you for your fast response.
An email was sent to rodriguezo.alberto@gmail.com with additional information.
Subject - this issue - **Live Charts Activation #1646**.

Thank you,
Alexandru

> Hello
> 
> Can you please mail me to [rodriguezo.alberto@gmail.com](mailto:rodriguezo.alberto@gmail.com), I can assist you there.

**Comment by beto-rodriguez** [comment]
Email replied!
