### ISSUE TITLE
Disconnected Arabic letters in axis labels

### ISSUE THREAD

**Issue by AbdullahUlber** [beto-rodriguez/LiveCharts2#165]
OS: Windows 10
Version: WPF, preview 50

Arabic texts appear correctly in the legend and in tooltips, but axis labels are rendered in a disconnected way, with the letters wrongly ordered from left to right (or bottom to top because of the rotation).

![image](https://user-images.githubusercontent.com/44041142/131326397-2655d8f0-49e2-4172-99fc-87a69a827bec.png)

The axis labels should be rendered as in the legend and in the tooltips,

**Comment by beto-rodriguez** [comment]
On next version this will be supported.

See https://github.com/beto-rodriguez/LiveCharts2/blob/master/samples/ViewModelsSamples/Axes/LabelsFormat/ViewModel.cs#L22
