### ISSUE TITLE
Allow empty lists for AngleAxes Property

### ISSUE THREAD

**Issue by trashhacker** [beto-rodriguez/LiveCharts2#1683]
is it possible to allow empty collections for AngleAxis property. 

Im generating the live charts data on demand cant initiate it with values before user action...

**Comment by beto-rodriguez** [comment]
Why don't you you set an empty collection while the user set their axes?

**Comment by trashhacker** [comment]
i do it says => System.Exception: "AngleAxes and RadiusAxes must contain at least one element."

**Comment by beto-rodriguez** [comment]
It's not a workaround, it is required at least an axis for any chart to scale, the code is based on math, an axis is required to scale things.
