### ISSUE TITLE
Why removing .Net Framework support?

### ISSUE THREAD

**Issue by MartinLachm** [beto-rodriguez/LiveCharts2#1731]
Hello,

i have see, that you are removing the .Net Standard 2.0 support for LiveCharts 2.0 in your current "drawing"-Branch. Is that really necessary? Because with removing .Net Standard 2.0, you are removing also the support for .Net Framework 4.x.

Thank you

**Comment by beto-rodriguez** [comment]
I removed `netstandard2.0` but i kept the `net462` target, so net framework is still supported.

I just excited when removed the Xamarin project and also removed netstandard2.0 with it.

Thanks for the catch, there is actually no particular reason to remove this target, i reverted that commit with 17f74e50a755b8634eb9b29ca53c8eeec3834a5a.
