### ISSUE TITLE
MAUI code-behind don't display chart

### ISSUE THREAD

**Issue by evolcano** [beto-rodriguez/LiveCharts2#1736]
**Describe the bug**
MAUI code-behind don't display chart similar as #481 , without any error.

> internal class CodeBehindMainPage : ContentPage
    {
        public CodeBehindMainPage()
        {
            var chart = new CartesianChart();
            chart.Series = new ISeries[]
            {
                new LineSeries<double>
                {
                    Values = new double[] { 2, 1, 3, 5, 3, 4, 6 },
                    Fill = null
                }
            };
            var grid = new Grid();
            grid.Add(chart);
            Content = grid;
        }
    }

But when I drag the window to another display and resize the window , chart appears.

**To Reproduce**
1. run code in debug or release model, chart don't display
2. drag the window to another display, chart appears

**Expected behavior**
chart is visible .

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows 11
 - Visual studio :17.12.3
 - net : 9.0
 - LiveChartsCore.SkiaSharpView.Maui : 2.0.0-rc4.5

**Comment by evolcano** [comment]
LiveChartsCore.SkiaSharpView.Maui  Version 2.0.0-rc3  is OK.

So this maybe a  repetitive issue。

**Comment by evolcano** [comment]
No matter LiveChartsCore.SkiaSharpView.Maui : 2.0.0-rc4.5 or  2.0.0-rc3, when CartesianChart is hosted in a StackLayout using Code-Behind mode, CartesianChart will not visible, too.

**Comment by beto-rodriguez** [comment]
@evolcano 

>StackLayout using Code-Behind mode, CartesianChart will not visible, too.

Probably related to: https://github.com/beto-rodriguez/LiveCharts2/issues/1483

**Comment by evolcano** [comment]
@beto-rodriguez Yes, after I set size, CartesianChart appears in StackLayout. Thanks.

**Comment by beto-rodriguez** [comment]
Glad to read that! I will close this for now!
