### ISSUE TITLE
Control in tabControl don't refresh  value

### ISSUE THREAD

**Issue by atjbat** [beto-rodriguez/LiveCharts2#177]
Good night
I. m work with livecharts2 project inherit from wpfsample in section Lines Properties
I've put a control livecharts  in a usercontrol and then i've put it in other usercontrol into a tabItem of tab control ,

At the first when i start projet all is ok and i see the new value in grid every time then i click my random button , after i clich in other TabItem and return at the previous my graph never again refresh !!!
I think that the graph lost datacontext but it's very strange because i've put a textblock with same binding ant it's run after click whatever tabitem i click

**Comment by aspion-ae** [comment]
__WPF (beta 70)__ (related to #173 ?)
Similar issue here: two charts in two ```UserControls``` each of them in a ```TabItem```. After switching from one tab to another and back again, the diagram disappears as soon as the mouse is over the chart. This was working fine in the previous versions.
Workaround: Set the property ```IsVisible=true``` for all series in the chart in ```TabItem_IsVisibleChanged(object sender, DependencyPropertyChangedEventArgs eventArgs)``` if eventArgs.NewValue is true.
