### ISSUE TITLE
Xamarin.Mac interest?

### ISSUE THREAD

**Issue by trympet** [beto-rodriguez/LiveCharts2#18]
Hi, great work on v2! 

I am working on a Xamarin.Mac implementation. Is there any interest of bringing xamarin.mac controls or skiaview into the project? I already have a crude working implementation.

If so, it would require a separate build target and mac tooling if the API changes (i think). The best solution would probably be to have a `LiveCharts2.Mac` package.

**Comment by beto-rodriguez** [comment]
You are right.

The library could also have a view for Xamarin.Mac

**Comment by trympet** [comment]
Cool, I'll submit a PR soon.

**Comment by beto-rodriguez** [comment]
I will close this due Inactivity, let me know II should re-open or need any help in the process.
