### ISSUE TITLE
WPFSample Axes/DateTimeScaled rendering bug

### ISSUE THREAD

**Issue by jjbourne** [beto-rodriguez/LiveCharts2#182]
**Describe the bug**
The WPF Sample for Axes/DateTimeScaled does not correctly render the X axis when the window is maximized

**To Reproduce**
1) Build the repository tagged beta7.1 (commit hash: 67e703a98557290cf9582447207b495e77ac3b18)
2) Debug the WPFSample project
3) Select the Axes/DateTimeScaled view
4) Maximize the window (My screen resolution is 1920x1080, scaling @ 100%)

The X axis shows multiple entries for Jan 02 (and others) and the labels are misaligned with the bars

**Expected behavior**
Expecting a single entry for each day that is aligned with the corresponding data point

![image](https://user-images.githubusercontent.com/6306498/132359639-d999a821-0925-4fd8-9cff-3c43d9381a56.png)

**Comment by beto-rodriguez** [comment]
Thanks this was missing, the sample should now display properly with the referenced commit.
