### ISSUE TITLE
Calling IEnumerable<ISeries> outside VM with ObservablePoint not working

### ISSUE THREAD

**Issue by Senrir** [beto-rodriguez/LiveCharts2#185]
**Describe the bug**
As title states, following error is received.

A mapper for type LiveCharts.Defaults.ObservablePoint is not implemented yet, consider using LiveCharts.Configure() method to call HasMap() with the type you are trying to plot.

**To Reproduce**

``` c#
class ViewModel {

        private IEnumerable<ISeries> series;

          public IEnumerable<ISeries> Series
        {
            get
            {
                return series;
            }
            set
            {
                series = value;
                RaisePropertyChanged("Series");
            }
        }

        public ViewModel()
        {
            series = StaticClass.seriesFromAStaticClass;
        }
    }

public static StaticClass
{
public static IEnumerable<ISeries> seriesFromAStaticClass= new ObservableCollection<ISeries>
        {
            new LineSeries<ObservablePoint>
            {

                Values = new ObservableCollection<ObservablePoint>
                {
                    new ObservablePoint(2.2, 5.4),
                    new ObservablePoint(4.5, 2.5),
                    new ObservablePoint(4.2, 7.4),
                    
                }
            }
        };
}
```

**Expected behavior**
The code should work as having the series declared inside the VM.

This works with for example a lineseries consiting of doubles instead of observablePoints

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by athunot** [comment]
Had the same issue on my side and it was resolved by changing Default namespaces.
From "using LiveCharts.Defaults" to "using LiveChartsCore.Defaults" should solve it

**Comment by beto-rodriguez** [comment]
I will close this for now, feel free to reply/re-open if needed.
