### ISSUE TITLE
[Feature request] Zoom X/Y axis through code

### ISSUE THREAD

**Issue by WiproSarthak** [beto-rodriguez/LiveCharts2#19]
Will V2 have funtionality to zoom graph to some value when initialising?

**Comment by beto-rodriguez** [comment]
Yes it does, zooming and panning basically only moves the `Axis.MaxLimit` and `Axis.MinLimit` properties.

Similar to this sample in the previous version: 

https://lvcharts.net/App/examples/v1/Wpf/Data%20Pagination

**Comment by WiproSarthak** [comment]
So version 2 will have this funtionality too Great :)

**Comment by WiproSarthak** [comment]
After setting Axis.MaxLimit and Axis.MinLimit will it allow user to pan X asix to see other values ?

**Comment by beto-rodriguez** [comment]
Yes

When the user pans or zooms both properties will be calculated again
