### ISSUE TITLE
Hightlight selected points in CartesianChart

### ISSUE THREAD

**Issue by samirem** [beto-rodriguez/LiveCharts2#194]
Is it possible to highlight certain points in a cartesian chart, and display their value?

In LvCharts 1, I made some custom Visual Elements to solve this, see image below
![image](https://user-images.githubusercontent.com/20268636/133922692-a17d2375-d150-4da1-9ae8-e2d39551066b.png)

**Comment by beto-rodriguez** [comment]
This is now possible, now we also support visual elements.
