### ISSUE TITLE
Tag Property

### ISSUE THREAD

**Issue by ajayre** [beto-rodriguez/LiveCharts2#199]
It would be cool if the LineSeries class had a Tag object property:

`public object Tag {get; set; }`

because it would then allow developers to attach their own class instances to a series to store additional non-visual data about the series.

I know I can easily do this with a subclass of LineSeries but it would be nice if it was built in.

**Comment by LabuzzMichal** [comment]
I would suggest adding it as well to other chart elements like Axes and Sections

**Comment by sigmarsson** [comment]
When do you plan releasing this property ? Until then is there a workaround to tag series ?

**Comment by beto-rodriguez** [comment]
Fixed with the referenced commit and will be included in the next version of the library.
