### ISSUE TITLE
Is LiveCharts2 thread-safe?

### ISSUE THREAD

**Issue by trympet** [beto-rodriguez/LiveCharts2#20]
I have been playing around with lvcharts2 quite a bit now, and I love the new architecture and changes.

In my application, I am updating the ObservableCollection from a worker thread:
```csharp
int i = 0;
foreach (var item in points)
{
    ChartValues.Add(new ObservablePoint(i++, item.Value));
}
```

The most common error I see is related to collecting custom IEnumerables to arrays. Here is an example method (from `PathGeometry.cs`) which throws an out of bounds exception from the linq `ToArray(this IEnumerable obj)`:
```csharp
public override void Draw(SkiaSharpDrawingContext context)
{
    var toExecuteCommands = drawingCommands ?? (drawingCommands = commands.ToArray());
    ...
}
```

I tried fixing it with a simple lock, but it simply pushed the error to another enumeration somewhere else.

Is thread-safety within the scope of LiveCharts2, or are consumers expected to implement their own synchronization?

**Comment by beto-rodriguez** [comment]
It was just implemented, the library should be thread safe now, feel free to let me know your opinion if you think something can be better.

While the chart is measured, the chart is locked:

https://github.com/beto-rodriguez/LiveCharts2/blob/master/src/LiveChartsCore/CartesianChart.cs#L217

While we draw it, it is also locked:

https://github.com/beto-rodriguez/LiveCharts2/blob/master/src/LiveChartsCore/Drawing/MotionCanvas.cs#L53

There is no need for the user to implement their own thread safe collections.

**Comment by beto-rodriguez** [comment]
The lock should not have a performance impact one the high performance package is published
