### ISSUE TITLE
Xamarin Forms: Crash on disposing a multi-axes Cartesian Chart

### ISSUE THREAD

**Issue by XamMattia83** [beto-rodriguez/LiveCharts2#219]
The app crash when a multi-axes  (and multi-series) cartesian chart "live updated" is disposed (e.g.: the page is navigated out). I've catched a "**System.IndexOutOfRangeExeption**":

0xFFFFFFFFFFFFFFFF in System.Diagnostics.Debugger.Mono_UnhandledException_internal
0x1 in System.Diagnostics.Debugger.Mono_UnhandledException at /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/mcs/class/corlib/System.Diagnostics/Debugger.cs:125,4
0x20 in Android.Runtime.DynamicMethodNameCounter.27	
0x27 in LiveChartsCore.CartesianSeries<LiveChartsCore.Defaults.ObservablePoint,LiveChartsCore.Drawing.LineBezierVisualPoint<LiveChartsCore.SkiaSharpView.Drawing.SkiaSharpDrawingContext,LiveChartsCore.SkiaSharpView.Drawing.Geometries.CircleGeometry,LiveChartsCore.SkiaSharpView.Drawing.Geometries.Segments.CubicBezierSegment,SkiaSharp.SKPath>,LiveChartsCore.SkiaSharpView.Drawing.Geometries.LabelGeometry,LiveChartsCore.SkiaSharpView.Drawing.SkiaSharpDrawingContext>.SoftDeleteOrDispose	
 0x3 in LiveChartsCore.LineSeries<LiveChartsCore.Defaults.ObservablePoint,LiveChartsCore.SkiaSharpView.Drawing.Geometries.CircleGeometry,LiveChartsCore.SkiaSharpView.Drawing.Geometries.LabelGeometry,LiveChartsCore.SkiaSharpView.Drawing.SkiaSharpDrawingContext,LiveChartsCore.SkiaSharpView.Drawing.Geometries.PathGeometry,LiveChartsCore.SkiaSharpView.Drawing.Geometries.Segments.LineSegment,LiveChartsCore.SkiaSharpView.Drawing.Geometries.Segments.CubicBezierSegment,LiveChartsCore.SkiaSharpView.Drawing.Geometries.Segments.MoveToPathCommand,SkiaSharp.SKPath>.SoftDeleteOrDispose

 0x129F in LiveChartsCore.CartesianChart<LiveChartsCore.SkiaSharpView.Drawing.SkiaSharpDrawingContext>.Measure	
 0x1A in LiveChartsCore.Chart<LiveChartsCore.SkiaSharpView.Drawing.SkiaSharpDrawingContext>.<UpdateThrottlerUnlocked>b__139_1	

 0xE in Java.Lang.Thread.RunnableImplementor.Run at /Users/builder/azdo/_work/1/s/xamarin-android/src/Mono.Android/Java.Lang/Thread.cs:36,6	

 0x8 in Java.Lang.IRunnableInvoker.n_Run at /Users/builder/azdo/_work/1/s/xamarin-android/src/Mono.Android/obj/Release/monoandroid10/android-29/mcw/Java.Lang.IRunnable.cs:84,4

**To Reproduce**
 1: Make a cartesian chart with more than one y-axis and populate it with a couple of series. In my case the chart is live-updated 
     every 100ms;

2: Go to another page

**System**

Running in Android 11, using  **LiveCharts2 Beta.71**, Xamarin Forms 5.0.0.2083

**Comment by XamMattia83** [comment]
Hello! Do you have any update on this? Just to clarify, the issue is still here after Beta.80 release

Thanks in advance

**Comment by XamMattia83** [comment]
@beto-rodriguez  i Have some updates for you:

1. the problem persist event with "hardcoded" series values; 
2. There's a workaround to avoid App crashes : **clear series  and values before navigate away from page** . You could also leave the chart Series populated with **just one entry** to avoid the issue.

**Comment by beto-rodriguez** [comment]
Thanks for the research! I'll take a look

**Comment by beto-rodriguez** [comment]
I think I got it with the referenced commit, it should be fixed in the next release.

**Comment by XamMattia83** [comment]
> I think I got it with the referenced commit, it should be fixed in the next release.

Nice! i'll give you a feedback about it with next release ;) thanks again....your lib is great!

**Comment by XamMattia83** [comment]
with Beta .101 everything is OK...Thanks!
