### ISSUE TITLE
Labels on x-axis unclear with stack columns

### ISSUE THREAD

**Issue by Albert634515** [beto-rodriguez/LiveCharts2#221]
I have a set of stacked columns showing data per year.
I would like to have the stacked columns per year sit close together.
On the x-axis the year is shown for each stacked column, this should be only onces.
It is totally unclear to which year the columns belong.

![image](https://user-images.githubusercontent.com/85439711/135714060-b956ef58-ea9c-4835-8c90-55617eab7576.png)

Sample test code used:
`namespace WinFormsApp1.ViewModels
{
    public class ViewModelStackedColumnSeriesYear
    {
        public IEnumerable<ISeries> Series { get; set; }

        public IEnumerable<Axis> XAxes { get; set; }

        public ViewModelStackedColumnSeriesYear()
        {
            var ob2list = new ObservableCollection<ISeries>();

            var cs = new StackedColumnSeries<DateTimePoint>
            {
                Name = "Test1",
                DataLabelsSize = 20,
                DataLabelsPaint = new SolidColorPaint(SKColors.Black),
                GroupPadding = 100,
                Values = new ObservableCollection<DateTimePoint>
                    {
                        new DateTimePoint
                        {
                            DateTime = new DateTime(2018, 1, 1),
                            Value = 1
                        },

                        new DateTimePoint
                        {
                            DateTime = new DateTime(2019, 1, 1),
                            Value = 6
                        },
                         new DateTimePoint
                        {
                            DateTime = new DateTime(2020, 1, 1),
                            Value = 5
                        },
                          new DateTimePoint
                        {
                            DateTime = new DateTime(2021, 1, 1),
                            Value = 3
                        },
                           new DateTimePoint
                        {
                            DateTime = new DateTime(2022, 1, 1),
                            Value = 5
                        },
                        new DateTimePoint
                        {
                            DateTime = new DateTime(2023, 1, 1),
                            Value = 8
                        },
                        new DateTimePoint
                        {
                            DateTime = new DateTime(2024, 1, 1),
                            Value = 6
                        }
                    },
                StackGroup = 1
            };
            ob2list.Add(cs);

            cs = new StackedColumnSeries<DateTimePoint>
            {
                Name = "Test2",
                DataLabelsSize = 20,
                DataLabelsPaint = new SolidColorPaint(SKColors.Black),
                GroupPadding = 100,
                Values = new ObservableCollection<DateTimePoint>
                    {
                        new DateTimePoint
                        {
                            DateTime = new DateTime(2018, 1, 1),
                            Value = 3
                        },

                        new DateTimePoint
                        {
                            DateTime = new DateTime(2019, 1, 1),
                            Value = 7
                        },
                         new DateTimePoint
                        {
                            DateTime = new DateTime(2020, 1, 1),
                            Value = 2
                        },
                          new DateTimePoint
                        {
                            DateTime = new DateTime(2021, 1, 1),
                            Value = 8
                        },
                           new DateTimePoint
                        {
                            DateTime = new DateTime(2022, 1, 1),
                            Value = 9
                        },
                        new DateTimePoint
                        {
                            DateTime = new DateTime(2023, 1, 1),
                            Value = 2
                        },
                        new DateTimePoint
                        {
                            DateTime = new DateTime(2024, 1, 1),
                            Value =5
                        }
                    },
                StackGroup = 2
            };
            ob2list.Add(cs);

            cs = new StackedColumnSeries<DateTimePoint>
            {
                Name = "Test3",
                DataLabelsSize = 20,
                DataLabelsPaint = new SolidColorPaint(SKColors.Black),
                GroupPadding = 100,
                Values = new ObservableCollection<DateTimePoint>
                    {
                        new DateTimePoint
                        {
                            DateTime = new DateTime(2018, 1, 1),
                            Value = 3
                        },

                        new DateTimePoint
                        {
                            DateTime = new DateTime(2019, 1, 1),
                            Value = 2
                        },
                         new DateTimePoint
                        {
                            DateTime = new DateTime(2020, 1, 1),
                            Value = 8
                        },
                          new DateTimePoint
                        {
                            DateTime = new DateTime(2021, 1, 1),
                            Value = 1
                        },
                           new DateTimePoint
                        {
                            DateTime = new DateTime(2022, 1, 1),
                            Value = 3
                        },
                        new DateTimePoint
                        {
                            DateTime = new DateTime(2023, 1, 1),
                            Value = 7
                        },
                        new DateTimePoint
                        {
                            DateTime = new DateTime(2024, 1, 1),
                            Value = 7
                        }
                    },
                StackGroup = 1
            };
            ob2list.Add(cs);

            var padding = new LiveChartsCore.Drawing.Common.Padding
            {
                Left = 0,
                Right = 0,
                Top = 0,
                Bottom = 0
            };

            cs = new StackedColumnSeries<DateTimePoint>
            {
                Name = "Test4",
                DataLabelsSize = 20,
                DataLabelsPaint = new SolidColorPaint(SKColors.Black),
                
                GroupPadding = 100,
                Values = new ObservableCollection<DateTimePoint>
                    {
                        new DateTimePoint
                        {
                            DateTime = new DateTime(2018, 1, 1),
                            Value = 8
                        },

                        new DateTimePoint
                        {
                            DateTime = new DateTime(2019, 1, 1),
                            Value = 1
                        },
                         new DateTimePoint
                        {
                            DateTime = new DateTime(2020, 1, 1),
                            Value = 7
                        },
                          new DateTimePoint
                        {
                            DateTime = new DateTime(2021, 1, 1),
                            Value = 9
                        },
                           new DateTimePoint
                        {
                            DateTime = new DateTime(2022, 1, 1),
                            Value = 1
                        },
                        new DateTimePoint
                        {
                            DateTime = new DateTime(2023, 1, 1),
                            Value = 5
                        },
                        new DateTimePoint
                        {
                            DateTime = new DateTime(2024, 1, 1),
                            Value = 8
                        }
                    },
                StackGroup = 2
            };
            ob2list.Add(cs);

            Series = new System.Collections.ObjectModel.ObservableCollection<ISeries>(ob2list);
            XAxes = new List<Axis>
            {
                new Axis
                {
                    Labeler = value => new DateTime((long) value).ToString("yyyy"),
                    LabelsRotation = 15,
                    Position = AxisPosition.Start,
                    MinStep = 1,
                    Name = "Year",
                    UnitWidth = TimeSpan.FromDays(365.5).Ticks,
                }
            };
        }
    }
}
`

**Comment by beto-rodriguez** [comment]
This could be achieved by configuring the Axis.

Just set the unit width to 1 year and also the min step, it could also be useful to force the width to 1 year.

```c#
new Axis
{
    Labeler = value => new DateTime((long) value).ToString("yyyy"),
    LabelsRotation = 15,
    Position = AxisPosition.Start,
    //MinStep = 1, // instead force it to 1 year
    MinStep = TimeSpan.FromDays(365.5).Ticks,
    FDorceToMinStep = true, // this could be useful in some cases.
    Name = "Year",
    UnitWidth = TimeSpan.FromDays(365.5).Ticks,
}
```

**Comment by Albert634515** [comment]
Thanks that works. 
To get de columns right in the middle also the base date should be in the middle of the year.
So instead of using dates like DateTime = new DateTime(2019, 1, 1) it should be DateTime = new DateTime(2019, 6, 1), using June instead of January.
