### ISSUE TITLE
Getting "C# InvalidOperationException: Collection Was Modified" exception while updating chart at a high refresh rate.

### ISSUE THREAD

**Issue by kaara15** [beto-rodriguez/LiveCharts2#225]
The chart gets updated at a high refresh rate when the data is collected. It is kept at 100 Hz and the exception arises when the collection is modified and data is added to the chart. We tried BindingOperations.EnableCollectionSynchronization on all the collections involved as well. While updating the chart at 10 Hz, we get the exception occasionally.

Bind an ObservableCollection of Series to the chart and update it at an interval of 10ms 

 - OS: Windows 10, .Net5.0 
 - Version 2.0.0-beta.71

**Comment by LabuzzMichal** [comment]
Just try to Lock collection modifications
https://github.com/beto-rodriguez/LiveCharts2/blob/master/samples/ViewModelsSamples/General/MultiThreading/ViewModel.cs

**Comment by avsteele** [comment]
I set up a simple project showing this crash. 

https://github.com/avsteele/LiveCharts2_WPFcrash

It just generates a ransom stream of data and puts it in a cartesian chart.  On my machine it halts within ~10s if trying to add a point every ~10 ms.  Takes up to a few minutes to crash if you add points slower than ~0.10 s.

**Comment by beto-rodriguez** [comment]
thanks @avsteele I will take a look.

**Comment by sansamit** [comment]
Still not resolved? thank~

**Comment by beto-rodriguez** [comment]
@avsteele notice your example is not locking the collection as @LabuzzMichal  mentioned.

This is not an issue of the library as far as I can see but this deserves an article and further explanation.

When you add values from multiple threads, there is a chance that while the chart is measured you modified the data, thus you get this exception.

The library provides a way to sync your data changes with the UI plot.

When you are changing your data from multiple threads you must ensure that your code do not suffers from [Concurrency Hazards](https://docs.microsoft.com/en-us/archive/msdn-magazine/2008/october/concurrency-hazards-solving-problems-in-your-multithreaded-code).

1. Lock your collection when you add/remove/update/clear your data.

https://github.com/beto-rodriguez/LiveCharts2/blob/master/samples/ViewModelsSamples/General/MultiThreading/ViewModel.cs#L61

2. Let LiveCharts know your sync object, just bind it to the UI.

https://github.com/beto-rodriguez/LiveCharts2/blob/master/samples/WPFSample/General/MultiThreading/View.xaml#L14

There are things that can improve, but for the case of a data visualization library this probably is enough.

**Comment by avsteele** [comment]
Ah I see.  I didn't realize this was required. I verify that after adding the lock and the binding to the XAML I do not see this crash. Thanks!

**Comment by AndrasEros** [comment]
I ran into this issue while using windows forms. My solution is:
`cartesianChart1.Invoke((MethodInvoker)delegate
                        {
                            // Add datapoints here
                        });`
