### ISSUE TITLE
Scatter example doesn't work

### ISSUE THREAD

**Issue by iii2** [beto-rodriguez/LiveCharts2#23]
Hello,
wpf samples runs fine, but scatter points doesn't. (empty graph)

**Comment by iii2** [comment]
example - if I remove the Line series (with at least two points) the graph will be empty.
`Series = new ObservableCollection<ISeries>
                    {
                        new ScatterSeries<ObservablePoint>
                        {
                            Values = new ObservableCollection<ObservablePoint> 
                            {
                                new ObservablePoint(2.2, 5.4),
                                new ObservablePoint(4.5, 2.5),
                                new ObservablePoint(4.2, 7.4),
                                new ObservablePoint(6.4, 9.9),
                                new ObservablePoint(4.2, 9.2),
                                new ObservablePoint(5.8, 3.5),
                                new ObservablePoint(7.3, 5.8),
                                new ObservablePoint(8.9, 3.9),
                                new ObservablePoint(6.1, 4.6),
                                new ObservablePoint(9.4, 7.7),
                                new ObservablePoint(8.4, 8.5),
                                new ObservablePoint(3.6, 9.6),
                                new ObservablePoint(4.4, 6.3),
                                new ObservablePoint(5.8, 4.8),
                                new ObservablePoint(6.9, 3.4),
                                new ObservablePoint(7.6, 1.8),
                                new ObservablePoint(8.3, 8.3),
                                new ObservablePoint(9.9, 5.2),
                                new ObservablePoint(8.1, 4.7),
                                new ObservablePoint(7.4, 3.9),
                                new ObservablePoint(6.8, 2.3),
                                new ObservablePoint(5.3, 7.1),
                            }
                        },
                        new LineSeries<ObservablePoint>
                        {
                            Values = new ObservableCollection<ObservablePoint> 
                            {
                                new ObservablePoint(2.2, 5.4),
                                new ObservablePoint(6.4, 9.9),
                            }
                        },
                    };`

**Comment by beto-rodriguez** [comment]
It is fixed already in my local machine

will publish asap.

**Comment by beto-rodriguez** [comment]
Thanks for the report, I am closing this for now, try to clone again the library, it should be working now.
