### ISSUE TITLE
Incorrect display on windows 11 (WPF)

### ISSUE THREAD

**Issue by aleckmal90** [beto-rodriguez/LiveCharts2#230]
This bug is even in the examples, the graph is simply not displayed, I tested it in my software, the graph also disappeared from the UI

To reproduce this bug simply open the WPF sample

![изображение](https://user-images.githubusercontent.com/29405261/136448715-6a64dae4-9c07-48ad-b8dc-572aec4148f4.png)

OS: Windows 11
.NET Core 3.1, WPF

**Comment by beto-rodriguez** [comment]
This issue seems that is not from this library, I will close this for now, feel free to reply/re-open if you think this is related with this library.
