### ISSUE TITLE
[Feature Request] Nuget Package

### ISSUE THREAD

**Issue by CoelWu** [beto-rodriguez/LiveCharts2#24]
Hi, LiveCharts and LiveCharts2 are both very great projects. When will we have nuget package support for LiveCharts2? Thanks.

**Comment by beto-rodriguez** [comment]
Hi

Nuget packages will be published soon, maybe 15 days more, Im getting ready the last details (I hope)

**Comment by CoelWu** [comment]
I see. Thank you very much!

**Comment by RhomGit** [comment]
Heh, I came here just to ask this. Thanks @beto-rodriguez

**Comment by WiproSarthak** [comment]
You can list this amazing library here too : https://github.com/jsuarezruiz/awesome-xamarin-forms
So that it can reach to more xamarin developers

**Comment by beto-rodriguez** [comment]
@WiproSarthak thanks for the info.

 I will let the community know about it once the docs are ready and the nugget package is ready.

**Comment by beto-rodriguez** [comment]
Keep track of this at #35
