### ISSUE TITLE
The Chart is sticked to the x-axis and y-axis after zooming.

### ISSUE THREAD

**Issue by son11592** [beto-rodriguez/LiveCharts2#248]
**Describe the bug**
The Chart is sticked to the x-axis and y-axis after zooming.

**To Reproduce**
1. Build the project (attached in this issue)
2. See the padding on the left and right of the chart.
3. Starting zoom in
4. The zoom out
5. See error: **The xy-axis not padding to the left or right anymore.** 

**Expected behavior**
I expect that the chart must return to the state of the beginning after zoom in/out. Not sticked to the xy-axis like this.

**Screenshots**
https://user-images.githubusercontent.com/4739616/137665354-a5767279-7c79-4530-86a5-66496f0e925b.mp4

**Desktop (please complete the following information):**
 - OS: Windows 11 - 21H2
 - Browser: Chrome
 - Version 2.0.0-beta.71

**Additional context**
_Here is my testing source code_
[LiveChartsCore_Sample.zip](https://github.com/beto-rodriguez/LiveCharts2/files/7361648/LiveChartsCore_Sample.zip)

**Comment by beto-rodriguez** [comment]
Thanks for the report!.

This is already fixed with the latest version of the library.

![Animation2](https://user-images.githubusercontent.com/10853349/169584620-203aa655-4a30-4d3a-aa21-79ca3d15439f.gif)
