### ISSUE TITLE
Chart hanging

### ISSUE THREAD

**Issue by muchenz** [beto-rodriguez/LiveCharts2#25]
When data is like on picture. 

![ftt_chart_changing](https://user-images.githubusercontent.com/46926155/115292822-c3d97580-a156-11eb-8184-eb5807b6e741.jpg)

Scrolling cause hanging WPF application. Chart trying to zoom and then hang program.  Low value is  about 5.0*10^-8 like on  tip label. 

Edit1:

Seems in Axis.cs loops:

for (var i = start; i <= max; i += s)

and 

for (var i = start; i <= dataBounds.max; i += s)

cause hanging because variable 's' is in this case very, very small comparing to 'max'

Edit2:

I added before first for loop:
if (max / s > 1000) s = max / 1000;
and before second:
if (dataBounds.max / s > 1000) s = dataBounds.max / 1000;

It works (no hanging), but under high magnification Y axis labels disappear.

**Comment by beto-rodriguez** [comment]
Thanks for the report, this issue should be gone now.
