### ISSUE TITLE
WinForms: Names in legend (when its position is set to left or right) are partially masked and the name is not displayed fully.

### ISSUE THREAD

**Issue by AhmadKelany** [beto-rodriguez/LiveCharts2#254]
**Describe the bug**
Part of the series' name that appears in legend is masked 

**To Reproduce**
in winforms application
set Legend position to right or left
add series with names to the chart

**Expected behavior**
the series name should be displayed correctly

![image](https://user-images.githubusercontent.com/12924528/138290756-c862a439-3428-49bc-960c-d62c1a202a8a.png)

 - OS: windows 10 19043.1288

**Comment by beto-rodriguez** [comment]
This is probably a SkiaSharp bug.

**Comment by beto-rodriguez** [comment]
We are now using harfbuzz which should help in this scenarios, please let me know if the error persists.
