### ISSUE TITLE
Support: Y Scales margin/padding?

### ISSUE THREAD

**Issue by devwar87** [beto-rodriguez/LiveCharts2#255]
Hi, first of all thanks for the work you put into LiveCharts, its pretty awesome.

I been going through the winforms examples and have not been able to remove padding/margin on the YScales display, is there any way to achieve this? Seems to be taking too much space of the chart display rect.

![Padding](https://user-images.githubusercontent.com/72774832/138481109-60c89637-6f23-4c0d-bfc8-f8c31e48ea34.png)

Thanks.

**Comment by anversoft** [comment]
After hours of trying and trying again I found that the Axis class contains the Padding property, use that to take away the extra space while it gets fixed.

**Comment by anversoft** [comment]
Also, sets the DrawMargin property of the chart with a fixed margin, so it doesn't self-set with the axes.

**Comment by devwar87** [comment]
Hey @anversoft thanks for your answer, I already had the Axis Padding prop overrided to 1, by also modying DrawMargin this is all I achieved:

![PaddingIssue](https://user-images.githubusercontent.com/72774832/141163584-69b57a7a-bf5e-43ff-a8ac-d06499a5c556.PNG)

As you can see space between Y Axes scales remain the same.

**Comment by singhacadshravan** [comment]
This problem is pronounced when you have more than two multiple axis. Padding property doesn't work when set to 1. Here is the snapshot(see how gap between each axis keeps increasing as number of axis is increasing):

<img width="930" alt="MultipleAxis" src="https://user-images.githubusercontent.com/93949156/161673897-c053f662-7ec8-413d-9be3-2a554c8e9dae.png">

**Comment by beto-rodriguez** [comment]
This is already fixed in the latest version, I forgot to close this issue and reference it to the commit that fixed this, but I tried to reproduce this error without success.

I will close this for now, but feel free to open the issue again if it persists in the latest version of the library.
