### ISSUE TITLE
how to fill FinancialPoint

### ISSUE THREAD

**Issue by overstartup** [beto-rodriguez/LiveCharts2#258]
I need to fill the candlestick dynamics. It is a little complicated for me.
Could you please give me an easier way instead of this:
```
 public IEnumerable<ISeries> Series  { get; set; } = new ObservableCollection<ISeries>
        {
            new CandlesticksSeries<FinancialPoint>
            {
                Values = new ObservableCollection<FinancialPoint>
                {
                    //                                 date, high, open, close, low 
                    new FinancialPoint(new DateTime(2021, 1, 1), 523, 500, 450, 400),
                   
                }
            }
        };
```

i need to use loop to add points.

```
 private ObservableCollection<ISeries> series;
        public ObservableCollection<ISeries> Series
        {
            get { return series; }
            set
            {
                series = value;
                RaisePropertyChanged(() => Series);
            }
        }
```
my data are in this list:
`private ObservableCollection<CandleLine> level1Candles;`

```
 foreach (var item in level1Candles)
            {
// how i should do it here?
            }

```

**Comment by beto-rodriguez** [comment]
Thanks for the report @overstartup 

Is the alternative proposed by @aspion-ae  enough? if not please elaborate more and let us know how can we make the API easier, why is the API complicated? notice you can also implement your own types in your plot, the `FinancialPoint` is the 'ready-to-go' class that the library provides.

**Comment by beto-rodriguez** [comment]
I am closing this for now due inactivity, feel free to reply if you need more help.
