### ISSUE TITLE
How to replace skiasharp with gdi+ .

### ISSUE THREAD

**Issue by mt-yu** [beto-rodriguez/LiveCharts2#259]
As the end of 'readme.md' says, I can replace the drawing engine at will, what should I do, or refer to which example I can replace.

“
Then LiveCharts2 requires SkiaSharp?
Not necessarily, The SkiaAPI makes it much easier to take the library everywhere, but that does not means that LiveCharts2 requires it to work we could easily move to any other drawing engine.
”

So I don't have to quote skia's relevant dll? （I use winform to develop applications.）

**Comment by beto-rodriguez** [comment]
I will close this for now
