### ISSUE TITLE
Layout looks not good when chart show in a small area

### ISSUE THREAD

**Issue by cnszmike** [beto-rodriguez/LiveCharts2#267]
When I show the chart in a normal size, it is ok, like this:
![image](https://user-images.githubusercontent.com/51449050/139390056-09e75be5-1bc5-4b93-8c0c-129349dbf767.png)

But when I show it in a small area, layout looks not good:
![image](https://user-images.githubusercontent.com/51449050/139390172-1c9da29d-ccab-4a2e-b924-c59e762b7a46.png)

My test code:
[xaml]:
    <Grid>
        <StackPanel Margin="20">
            <StackPanel Orientation="Horizontal">
                <Button x:Name="expand" Content="expand" Click="expand_Click"
                        Margin="200 0 0 0" Width="100" Height="50"/>
                <Button x:Name="shrink" Content="shrink" Click="shrink_Click"
                        Margin="200 0 0 0" Width="100" Height="50"/>
            </StackPanel>
            <Grid Name="grid1" Margin="100">
                <Border x:Name="chartBorder" Width="200" Height="200" BorderBrush="red" BorderThickness="2">
                    <lvc:CartesianChart x:Name="chart1">
                    </lvc:CartesianChart>
                </Border>
            </Grid>
        </StackPanel>
    </Grid>

[cs]
       private void MainPage_Loaded(object sender, RoutedEventArgs e)
        {
            chart1.Series = new ObservableCollection<ISeries>
            {
                new LineSeries<double>
                {
                    Values = new ObservableCollection<double> { 2, 1, 3, 5, 3, 4, 6 },
                    LineSmoothness = 0,
                    Fill = null,
                    GeometryStroke = null,
                    GeometryFill = null,
                    GeometrySize = 0,
                    Stroke = new LiveChartsCore.SkiaSharpView.Painting.SolidColorPaint
                    {
                        Color = SkiaSharp.SKColors.CornflowerBlue,
                        StrokeThickness = 2,
                    }
                }
            };
        }

        private void expand_Click(object sender, RoutedEventArgs e)
        {
            chartBorder.Width = chartBorder.Width * 1.1;
            chartBorder.Height = chartBorder.Height * 1.1;
        }

        private void shrink_Click(object sender, RoutedEventArgs e)
        {
            chartBorder.Width = Math.Max(10, chartBorder.Width * 0.9);
            chartBorder.Height = Math.Max(10, chartBorder.Height * 0.9);
        }

**Comment by beto-rodriguez** [comment]
And why is that wrong?

**Comment by cnszmike** [comment]
because the empty area is too big, and the chart it self is too small:

![image](https://user-images.githubusercontent.com/51449050/139517311-df1a370c-2b29-4894-9db5-34f0e80015cc.png)

**Comment by beto-rodriguez** [comment]
You have a lot of options to fix that.

You can reduce the axes font size, you can also set the `Axis.IsVisible` property to false.

**Comment by cnszmike** [comment]
After set axis TextSize to 1 and IsVisible to false, it is still not good:
      
![image](https://user-images.githubusercontent.com/51449050/139633947-35419f8f-56fb-4dc4-bd02-b142d2fdddfd.png)


Below is the code:

  private void MainPage_Loaded(object sender, RoutedEventArgs e)
        {
            chart1.Series = new ObservableCollection<ISeries>
            {
                new LineSeries<double>
                {
                    Values = new ObservableCollection<double> { 2, 1, 3, 5, 3, 4, 6 },
                    LineSmoothness = 0,
                    Fill = null,
                    GeometryStroke = null,
                    GeometryFill = null,
                    GeometrySize = 0,
                    Stroke = new LiveChartsCore.SkiaSharpView.Painting.SolidColorPaint
                    {
                        Color = SkiaSharp.SKColors.CornflowerBlue,
                        StrokeThickness = 2,
                    }
                }
            };

            var axis = chart1.XAxes.First();
            axis.IsVisible = false;
            axis.TextSize = 1;

            axis = chart1.YAxes.First();
            axis.IsVisible = false;
            axis.TextSize = 1;

        }
