### ISSUE TITLE
Some Legend properties and Axis properties not working

### ISSUE THREAD

**Issue by cnszmike** [beto-rodriguez/LiveCharts2#268]
1. Legend problem: No matter what I set, below properties don't take effect:

chart1.LegendOrientation
chart1.LegendBackground
chart1.LegendTextBrush

2. Axis problem: 

It is not support unicode

When select any point in ColumnSeries, the AxisX point also been rendered and looks not good：

![image](https://user-images.githubusercontent.com/51449050/139424183-7bb6e89e-6ff6-497e-8aa3-7623946ea9a9.png)

**Comment by NPadrutt** [comment]
I have the same issue with the LegendTextBrush on UWP.

**Comment by beto-rodriguez** [comment]
This should be already fixed, let me know if the issue persists.
