### ISSUE TITLE
Visibility doesn't work properly

### ISSUE THREAD

**Issue by Possitron** [beto-rodriguez/LiveCharts2#270]
I have a problem with a Visibility of a CartesianChart control from the package "LiveChartsCore.SkiaSharpView.WPF 2.0.0-beta.80" on the Prism framework for .Net Core 3.1.

I have a property IsChartVisible on my bindable model (BindableBase from Prism), and the Visibility of the CartesianChart control is binded to it using a simple bool-to-visibility converter. If the property IsChartVisible is initialy false, the CartesianChart control is collapsed, but after changing the property to true, the chart stays collapsed.

I tried to put the chart in a border control, then bind the border visibility to the property IsChartVisible. When I change IsChartVisible to true, the border become visible, but the chart doesn't.

I tried also to debug, but everything is working properly, even the converter. It is triggered, and everytime it returns visibility correctly.

Note: if I remove the chart from the XAML in the runtime, and then put it back, its visibility starts working properly.

The property is:

```C#
private bool _isChartVisible;
public bool IsChartVisible
{
    get { return _isChartVisible; }
    set { SetProperty(ref _isChartVisible, value); }
}
```

The converter:
```C#
public object Convert(object value, Type targetType, object parameter, CultureInfo culture)
{
    try
    {
        var v = (bool)value;
        return v ? Visibility.Visible : Visibility.Collapsed;
    }
    catch (InvalidCastException)
    {
        return Visibility.Collapsed;
    }
}
```

XAML:
```C#
<Border Grid.Row="4" Grid.Column="0" Grid.ColumnSpan="3" Style="{StaticResource ChannelChartBorder}" Visibility="{Binding Model.IsChartVisible, Converter={StaticResource BoolToVisibilityConverter}}">
    <lvc:CartesianChart Series="{Binding Model.Series}" Style="{StaticResource ChannelCartesianChart}" />
</Border>
```

**Comment by Possitron** [comment]
The workaround is to use ```Visibility.Hidden``` instead of ```Visibility.Collapsed```.

**Comment by beto-rodriguez** [comment]
Thanks for the report!, this seems to be solved, I am closing this.
