### ISSUE TITLE
Assembly Signing

### ISSUE THREAD

**Issue by Foxlider** [beto-rodriguez/LiveCharts2#273]
**Is your feature request related to a problem? Please describe.**
LiveCharts2 cannot be used in a project using strong-name signing  :
` Could not load file or assembly 'LiveChartsCore' or one of its dependencies. A strongly-named assembly is required.` 
Using StrongNamer doesn't work for some of my projects and cause a lot of errors. 
LiveCharts 0.9 is signed though.

**Describe the solution you'd like**
Signing the assembly would allow strong-named projects to use LiveCharts2

**Describe alternatives you've considered**
Might keep using LiveCharts0.9 but I really prefer how LiveCharts2 works

**Additional context**
/

**Comment by beto-rodriguez** [comment]
Since beta 90, all the assemblies of this library have a strong name signature.
