### ISSUE TITLE
Stacked column not showing in legend

### ISSUE THREAD

**Issue by Albert634515** [beto-rodriguez/LiveCharts2#274]
I have stacked column series graph.
Some column series are only in the last column.
This is because I have graph per year, where for the last year some data is predicted data.
For the columns that are only in the last stack column don't showup in the legenda.

I have added a test view to reproduce this problem.
Test column 'Test 6' only has data for year 2024 and will not show up in legenda.
It does show up in the stack column

![image](https://user-images.githubusercontent.com/85439711/140607712-e9e21e1f-6a8d-47b2-8a1c-c3560ebaeef4.png)
[ViewModelStackedColumnSeriesYear.zip](https://github.com/beto-rodriguez/LiveCharts2/files/7490342/ViewModelStackedColumnSeriesYear.zip)

Using Windows 10
Beta 80
Visual studio 2022

**Comment by beto-rodriguez** [comment]
This should be fixed with the tooltips cleanup I made, the next release should fix this, I will test before closing this issue.

**Comment by Albert634515** [comment]
It is fixed thanks
