### ISSUE TITLE
Scatter Circle - Custom Size & Color per circle (in one serie)

### ISSUE THREAD

**Issue by ClubberLangG** [beto-rodriguez/LiveCharts2#275]
Hi,

I have a scatter graph and I try to change to have a custom color per scatter-circle, and custom size too.
For now, to achieve this, I have to create a serie per point :-(

I wish to have only one serie, but for now, I cannot find how?

Thanks

**Comment by beto-rodriguez** [comment]
I will close this for now, we can track this implementation at #229
