### ISSUE TITLE
Set chart size in blazor?

### ISSUE THREAD

**Issue by bonzaiferroni** [beto-rodriguez/LiveCharts2#278]
Is there a way to set chart size in blazor? I could not find it for the life of me. The canvas appears as 300 x 150.

**Comment by beto-rodriguez** [comment]
The size of the canvas is determined by the container.

The canvas takes the full space available.

https://github.com/beto-rodriguez/LiveCharts2/blob/master/src/skiasharp/LiveChartsCore.SkiaSharpView.Blazor/Chart.razor.css#L177

You should be able to force the chart size by forcing the size of the container:

``` html
<div style="width: 600px; height: 400px">
    <CartesianChart />
</div>
```

But that will disable the chart responsiveness.

**Comment by bonzaiferroni** [comment]
I tried that without any luck, here is what the generated html looks like:

![image](https://user-images.githubusercontent.com/10502552/141170560-1bcb271a-9192-41bb-8d6d-28e19db8de24.png)

**Comment by beto-rodriguez** [comment]
I just tested it in a new project and it seems to work properly.

I think that there might be a rule css rule in your project that interferes with the livecharts control canvas.

Ensure that your canvas is using the css rule defined in the LiveCharts bundle:

![image](https://user-images.githubusercontent.com/10853349/141174134-c8474cd5-6f52-4fb4-84ba-a71d2fc47bda.png)

This is how it looks for me:
![blazor](https://user-images.githubusercontent.com/10853349/141173570-4bd98fd1-cea2-4615-bd03-947a7d45f587.gif)

**Comment by bonzaiferroni** [comment]
That was my problem, thanks! I had changed the name of my project and hadn't fixed the link to my project stylesheet in index.html, so css isolation was broken.

**Comment by beto-rodriguez** [comment]
Glad to hear that!
