### ISSUE TITLE
Heatseries

### ISSUE THREAD

**Issue by cnycny** [beto-rodriguez/LiveCharts2#28]
Will there be a heatseries chart in livecharts 2, as in livecharts 1?

In livecharts 1 it was not possible to set the heatseries items fill with a custom mapper, only by gradient stop collection.
To handle this with a custom mapper would be a great feature!

**Comment by beto-rodriguez** [comment]
This is already supported and will be included since `2.0.0-beta.17`.

now custom mappers are supported:

https://github.com/beto-rodriguez/LiveCharts2/blob/master/docs/components/1.21.heatseries.md#plotting-custom-types
