### ISSUE TITLE
DataLabels visibility issues in RowSeries when zooming in

### ISSUE THREAD

**Issue by yiodal** [beto-rodriguez/LiveCharts2#282]
Hello!

I have a problem with the cartesian chart in WPF. 
I created a cartesian chart with one RowSeries and added zoom in both axes. 
The original chart is as seen below

![OriginalChart](https://user-images.githubusercontent.com/92317727/141456926-c48be9b0-8940-4088-9af9-1277d0962a7c.PNG)

Once I zoom in, some values of the series are no longer visible but their corresponding labels do not disappear. 

![ProblemInLabels](https://user-images.githubusercontent.com/92317727/141457374-f59dfdd0-6e8f-4f3d-bf5a-b9438d950e10.PNG)

ViewModel:

```
public List<ISeries> Series { get; set; } = new List<ISeries>
        {
            new RowSeries<int>
            {
                Values = new List<int> { 8, -3, 4, -3, 3, 4, -2, 5, 9, 11 },
                Stroke = null,
                DataLabelsPaint = new SolidColorPaint(new SKColor(45, 45, 45)),
                DataLabelsSize = 14,
                DataLabelsPosition = DataLabelsPosition.End
            }
        };
```

Xaml:

```
<UserControl x:Class="WPFSample.Bars.RowsWithLabels.View"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml" 
             xmlns:lvc="clr-namespace:LiveChartsCore.SkiaSharpView.WPF;assembly=LiveChartsCore.SkiaSharpView.WPF"
             xmlns:vms="clr-namespace:ViewModelsSamples.Bars.RowsWithLabels;assembly=ViewModelsSamples">
    <UserControl.DataContext>
        <vms:ViewModel/>
    </UserControl.DataContext>
    <Grid>
        <Grid.RowDefinitions>
            <RowDefinition Height="*"/>
        </Grid.RowDefinitions>
        <lvc:CartesianChart Series="{Binding Series}" ZoomMode="Both"></lvc:CartesianChart>
    </Grid>
</UserControl>
```

Please note that I previously used version beta.33 and this issues didn't happen. 
Can you please advice how I could resolve this?

**Comment by Yiotopia** [comment]
I have tested the problem with version beta.71 as well and it didn't occur. It seems that it only happens in beta.80

**Comment by langejay** [comment]
More images for something that is probably the same issue.  I hope this helps and is not a separate bug. :-)

![ZoomIssue_original](https://user-images.githubusercontent.com/29132935/153524901-ceafe91c-9519-4e6c-b23a-4193aaff87f6.png)
![ZoomIssue](https://user-images.githubusercontent.com/29132935/153524904-a96f1b00-2f1e-4088-a395-8cd997c27723.png)

**Comment by beto-rodriguez** [comment]
I forgot to close this, but this should be fixed with the latest version of the library, let me know if the issue persists!
