### ISSUE TITLE
Highlighted hover status does not work when chart becomes visible again

### ISSUE THREAD

**Issue by aspion-ae** [beto-rodriguez/LiveCharts2#286]
**Describe the bug**
Highlighted hover status does not work when chart becomes visible again

**To Reproduce**
1. Run WPFSample application
2. Go to 'VisualTest/Tabs', hover will highlight the bars:
![grafik](https://user-images.githubusercontent.com/87190751/141782021-48e6b181-cf6c-4722-928c-9108595e7429.png)
3. Click on 'tab 2' and then on 'tab 1' again 
4. See error: hover will no longer highlight the bars:
![grafik](https://user-images.githubusercontent.com/87190751/141782151-6f85fbae-1ac5-419d-ac55-861159377b9e.png)

**Expected behavior**
Hover will highlight the bars after switching the tabs.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: WPF beta.80

**Comment by beto-rodriguez** [comment]
This is finally fixed with the refenced commit and will be included in the next version of the library, thanks for the report!
