### ISSUE TITLE
How do I set the color of a particular column of the bar diagram so THAT I can highlight the color of a particular column  

### ISSUE THREAD

**Issue by YC946586** [beto-rodriguez/LiveCharts2#288]
How do I set the color of a particular column of the bar diagram so THAT I can highlight the color of a particular column  Help!!!!!!!!

**Comment by preintel** [comment]
Need to be more specific on your question. Do you have a number of columns displayed and want to highlight a specific column based on user action dynamically or just highlight a color out of the column series for display purposes only?

LiveCharts version 1 had a mapper (which lets you modify colors of specific point/columns in a series), I believe this feature was requested for Livecharts2 and are awaiting to have it implemented, see here:
https://github.com/beto-rodriguez/LiveCharts2/issues/229

**Comment by YC946586** [comment]
RowSeries How do I set up Mappers ,Do I already know how to set ColumnSeries   . The ColumnSeries code looks like this and I posted it to see if anyone needs it   
     var BlueSeries = new ColumnSeries()
                    {
                        Values = cityGroup,
                        MaxColumnWidth = 32,
                        Title = "建筑企业数量",
                        DataLabels = true,
                        LabelPoint = point => point.Y + "",
                    };
                    OperationSeries = new SeriesCollection() { BlueSeries };
                    if (curCoty!=null)
                    {
                        int indexOf = header.IndexOf(curCoty);
                        CartesianMapper<double> mapper = Mappers.Xy<double>()
                             .X((value, index) => index)
                             .Y(value => value)
                             .Fill((value, index) => index == indexOf ? 
                             new SolidColorBrush((Color)ColorConverter.ConvertFromString("#4280FB")) :
                             new SolidColorBrush((Color)ColorConverter.ConvertFromString("#B1CBFF")));
                        OperationSeries.Configuration = mapper;
                    }


The ColumnSeries code looks like this and I posted it to see if anyone needs it  
But I don't know how to do RowSeries. I hope I can get your guidance

**Comment by beto-rodriguez** [comment]
I am closing this since it seems related to #229, we can track the implementation of this feature there.
