### ISSUE TITLE
What is a proper way to determine a 'selected'/'clicked' point in a series?

### ISSUE THREAD

**Issue by xiaomi7732** [beto-rodriguez/LiveCharts2#295]
In WPF, I am looking for a way to let the user click a point and allows editing the point in somewhere else or delete the target point.

So, I wish the series to expose an SelectedModel property to be bound to for the model the user clicked on, or allows a delegate to handle point clicking.

For example:
![image](https://user-images.githubusercontent.com/3674549/142737050-ad0c019b-c4b9-4bfd-9d5c-08a9383872fd.png)

The closest thing that I found is `PointHovered`:

```csharp
series.PointHovered += SeriesPointHover;
private void SeriesPointHover(TypedChartPoint<DataPoint, LineBezierVisualPoint<SkiaSharpDrawingContext, CircleGeometry, CubicBezierSegment, SKPath>, LabelGeometry, SkiaSharpDrawingContext> point)
{
    _logger.LogDebug("Hover point: {point}", point.Model);
    if (point.Model is null)
    {
        return;
    }
    SelectedDataPoint.SetModel(point.Model);
}
```
That is not ideal because it is easy for it to hover over multiple points when they are close to each other.

It would be great if this could be done:

```csharp
LineSeries<DataPoint> series = new LineSeries<DataPoint>()
{
    Name = SelectedCategory.Id,
    TooltipLabelFormatter = FormatToolTip,
    Values = dataPoints,
    Mapping = SeriesMapping,
    ValueSelectedHandler = HandleSelectedDataPoint,    // Add a delegate to process selected point
};
```

Otherwise, if there's only 1 selected item, maybe make it a property to be bound on the chart?

Or maybe other ways to reach the goal?

Please help. Thanks!

**Comment by beto-rodriguez** [comment]
Yup, this was missing, I saw your issue and some other in discussions, I created a sample to handle the chart point click event:

Follows MVVM:
https://github.com/beto-rodriguez/LiveCharts2/blob/master/samples/ViewModelsSamples/Events/Cartesian/ViewModel.cs

Classic event:
https://github.com/beto-rodriguez/LiveCharts2/blob/master/samples/WPFSample/Events/Cartesian/View.xaml.cs#L20
https://github.com/beto-rodriguez/LiveCharts2/blob/master/samples/WPFSample/Events/Cartesian/View.xaml#L17

Thanks for the report! let me know if there is something wrong or something that can be improved in my example.

**Comment by xiaomi7732** [comment]
@beto-rodriguez Thanks for the example. I noticed the new event in the latest release. I am wondering, why is it a [group of points](https://github.com/beto-rodriguez/LiveCharts2/blob/343996fb90aaf8b7310b9bdafae3db830896609f/samples/ViewModelsSamples/Events/Cartesian/ViewModel.cs#L48) the click leads to? I could have a guess, but I am willing to hear from you directly. And then, is it possible to find out which one is the closest one to the mouse cursor upon clicking? Thanks.

**Comment by beto-rodriguez** [comment]
This need more documentation, I will keep an eye on this.

It is a group because there is always a change that 2 or more points overlap in the plot, this was you could decide what to do with all the points that were clicked. also the event is fired according to the `CartesianShart.TooltipfindingStategy` property, this means that any point that is shown in the tooltip will be passed in this group to the event when the user clicks on the chart.

But I think you are right there is something missing, most of the times we only need the closes point, so I added a new event, the `ChartPointPointerDown` will be called only with the closest point to the click.

https://github.com/beto-rodriguez/LiveCharts2/blob/master/samples/ViewModelsSamples/Events/Cartesian/ViewModel.cs#L51

it is available since `beta-101` version.

**Comment by langejay** [comment]
Tried using this:
`    <lvc:CartesianChart x:Name="myChart" Background="{Binding Background}" Series="{Binding Series}" DataPointerDown="PointClicked" Grid.Row="1"></lvc:CartesianChart>`

with this:

`    private void PointClicked(IChartView chart, IEnumerable<ChartPoint> points)
    {
      if (points.Count() > 0)
      {
        Console.WriteLine(points);
      }

      foreach (var point in points)
      {
        Console.WriteLine(points);
      }
    }`

I never get any points returned in the list.  I have three series and have clicked as  precisely a possible on a few points in each series, never get a point.

Any ideas?
![Untitled](https://user-images.githubusercontent.com/29132935/152096206-cc2b2165-c6b0-426f-853d-753b514ea068.png)

**Comment by langejay** [comment]
`
private void PointClicked(IChartView chart, IEnumerable<ChartPoint> points)
`

**Comment by beto-rodriguez** [comment]
@langejay can you provide a repo with the issue please?

**Comment by langejay** [comment]
Hi @beto-rodriguez, thanks for responding :-).  We are developing a dll to allow us to use live charts (1 and now 2) within our win32 based app.
As a result, I would need to send you a small executable within the repo that will be loaded (VS project) automatically.
Would this be ok with you?
You would simply need to start the repo in VS and it will load the exe and have a Live Chart displayed.
Click on the point in the chart and I will breakpoint in the DLL code where I expect to have the point returned.
Doing it this way would, selfishly, allow me to highlight some other issues I have experienced in other comments.

If this is NOT acceptable, it will take me some time to develop a UI for the developed DLL.
