### ISSUE TITLE
XAML parsing exception

### ISSUE THREAD

**Issue by alex4998** [beto-rodriguez/LiveCharts2#296]
Using LiveChartsCore.SkiaSharpView.WinUI 2.0.0-beta80. As soon as I add CartesianChart to XAML I start getting an exception -Microsoft.UI.Xaml.Markup.XamlParseException: 'XAML parsing failed.' No stack trace to a managed code line. CandleChartViewModel is the same ViewModel as in the WinUI example.

>
    <StackPanel Orientation="Vertical" HorizontalAlignment="Stretch" VerticalAlignment="Stretch">
      <StackPanel.DataContext>
         <viewModels:CandleChartViewModel />
      </StackPanel.DataContext>
      
      <winUi:CartesianChart XAxes="{Binding XAxes}" Series="{Binding Series}"></winUi:CartesianChart>
   </StackPanel>

   I wonder if there is a quick workaround? I assume the library was tested for WinUI. Is there something I might try to do differently to make it work?

   UPDATE: I cloned LiveChart2 repository and run WinUI sample. It worked just fine. The big difference that I see is that the sample is built against WinUI prerelease and it is 2 projects project (actual and packaging). In my case I created a single project WinUI and I referenced latest release Microsoft.WinodwsAppSDK v1.0.0.

   UPDATE: It turned out that the problem was with the new project type where WinUI and its packaging are part of the same single project. I separated my projects into two as you have it in the sample and it started working. Just in case I updated references in LiveCharts2 for WinUI. Here is a PR - https://github.com/beto-rodriguez/LiveCharts2/pull/299.

**Comment by beto-rodriguez** [comment]
beta 90 now has a dependency on Microsoft.WinodwsAppSDK v1.0.0, I am closing this for now.
