### ISSUE TITLE
Scales start from -0

### ISSUE THREAD

**Issue by alex4998** [beto-rodriguez/LiveCharts2#300]
At least when using the ColumnSeries scales X and Y start from -0 which looks weird. When the chart is rather stretched out scale X can start from -0.5 but it is always a -number.

![Screenshot 2021-11-22 233004](https://user-images.githubusercontent.com/15015347/142975873-6bed8670-737c-4798-b8bc-17470a6e7ac0.png)

**Comment by beto-rodriguez** [comment]
It is fixed with the referenced commit, thanks!
