### ISSUE TITLE
LiveCharts2 breaks .net native build

### ISSUE THREAD

**Issue by NPadrutt** [beto-rodriguez/LiveCharts2#304]
**Describe the bug**
There seems to be an issue with LiveCharts when the application was built with .net native. In my application it crashes with this exception on startup:

```
Exception thrown: 'System.Reflection.MissingMetadataException' in System.Private.Interop.dll
Windows.Foundation.IReference`1<Double>
```

In a newly created uwp app with .net native this is the error:

`Activation of the Windows Store app '878dd842-ce3f-4283-806b-b792f7346efb_agvz9rmh6sqym!App' failed with error 'Operation not supported. Unknown error: 0x80040905'.
`

**To Reproduce**
1. Create new universal windows app
2. Add LiveChartsCore.SkiaSharpView.UWP version 2.0.0-beta.80
3. Activate .net native
4. Add following to mainpage:
`<uwp:CartesianChart LegendPosition="Right" />`
5. Hit F5 to start compile and start application
6. See app crash

**Expected behavior**
App starts in .net native / release as does it in debug / without .net native.

**Desktop (please complete the following information):**

**Additional context**

**Comment by AliShahesmaeili** [comment]
@NPadrutt I have this issue in UWP
ANY UPDATE?

**Comment by NPadrutt** [comment]
@AliShahesmaeili I moved to WinUI with my application in the meanwhile.
Maybe @beto-rodriguez has an update to this.

**Comment by rossirpaulo** [comment]
no updates, then....

**Comment by beto-rodriguez** [comment]
This won't be implemented, but there are plans to enable AOT for modern platforms.

I will close this for now :(
