### ISSUE TITLE
Line Not Appearing on Line Chart

### ISSUE THREAD

**Issue by jamsoft** [beto-rodriguez/LiveCharts2#31]
**Describe the bug**

I have added a CartesianChart to an Avalonia view and wired it up to a LineSeries with a collection of ObservableValues set. This is all working great. However, there is no line being rendered. Just points.

The samples don't seem to be doing anything in particular with styles or themes and the themes doc is empty at the moment. I've tried looking for likely properties or setting on the LineSeries but nothing seems to suggest anyhting related to a line other than LineSmoothness.

I've tried setting Fill but it didn't seem to effect anything in the render.

**To Reproduce**

1. start a new avalonia app
2. Add a chat and line series
3. debug
4. No line is rendered, only geometry points.

**Expected behavior**
I would expect a Line series to default to rendering a line.

**Screenshots**

<img width="393" alt="missingline" src="https://user-images.githubusercontent.com/2502211/116907687-cf8a6900-ac39-11eb-8dd9-3c2fa7068f86.PNG">

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] n/a

**Comment by beto-rodriguez** [comment]
Is it showing when you run the Avalonia samples project?

**Comment by jamsoft** [comment]
All of the sameples seem to render without issue. So odd. I've been pouring over the samples and cannot see anything I'm missing style wise.

**Comment by beto-rodriguez** [comment]
The only thing I think could be messing is the configuration try using this skeleton to configure LiveCharts when your application starts:

``` c#
LiveCharts.Configure(settings =>
                settings.
                    AddDefaultMappers()
                    .AddSkiaSharp()
                    .AddLightTheme()

                    // .., your custom settings here
                    // .HasMap<Foo>( ... )

                    );
```

**Comment by jamsoft** [comment]
Also, if I set the legends, They push the actual chart out of the available viewbox rather than shrink the chart. Or is that expected behaviour?

**Comment by beto-rodriguez** [comment]
About the legend it should be a bug

**Comment by jamsoft** [comment]
Unfortunately, adding the config code didn't change any behaviour, still no line being rendered.

**Comment by beto-rodriguez** [comment]
I need more info to replicate the issue, I am building 2 different applications using Avalonia and both are working on my side.

**Comment by jamsoft** [comment]
OK, I'll try to replicate in an app and get that over to you. It's odd as I'm using a largely vanilla Avalonia app built from a template.

**Comment by beto-rodriguez** [comment]
I am closing this issue as there is not enough information to replicate the issue.
