### ISSUE TITLE
Legends Push Charts Out Of Visible Area

### ISSUE THREAD

**Issue by jamsoft** [beto-rodriguez/LiveCharts2#32]
**Describe the bug**
Legends push charts out of control visible areas.

**To Reproduce**
1. add `LegendPosition="Top"` to a chart.

**Expected behavior**
Chart should shrink in the view port.

**Screenshots**

<img width="400" alt="legendsbug" src="https://user-images.githubusercontent.com/2502211/116910865-22feb600-ac3e-11eb-85fb-93a767e3f1d8.PNG">

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10 Pro

**Comment by beto-rodriguez** [comment]
This was an Avalonia specific issue and the fix is included since v`beta.14`

**Comment by Senrir** [comment]
Still happening - beta.71
