### ISSUE TITLE
The legend is sometimes displayed outside the application

### ISSUE THREAD

**Issue by Albert634515** [beto-rodriguez/LiveCharts2#323]
The legend is sometimes displayed (partly) outside the application.
If this is the case, the first lines of the legend are then not readable.
This is the case when there are lots of items in the legend, or when there is simple not a lot of space above the graph to display the legend. The legend is currently always display on top of the graph instead of the place where there is the most/enough space to display it.

Possible solutions:
- Detect where there is space to display the legend
- Add a scroll to the legend when there is not enough space to display it

**Comment by Albert634515** [comment]
Also when the legend is outside the area of the charts, it regurly does not go away anymore. The only way to to get rid of the legend is to kill the app

**Comment by beto-rodriguez** [comment]
The rendering cycle of the library has a lot of improvements, this issue should not happen in the latest version of the library, I will close this for now, if the issue persists, please let me know and I'll dig into it.
