### ISSUE TITLE
Hand cursor on MouseOver

### ISSUE THREAD

**Issue by brunossn** [beto-rodriguez/LiveCharts2#326]
**Is your feature request related to a problem? Please describe.**
It's a new feature

**Describe the solution you'd like**
The graphics already give me the option to click on a datapointer series to get some action. However, I would like to indicate to the user that the series is clickable, with a hand cursor on mouse over

**Comment by Rainmaker52** [comment]
You can set the "Cursor" property for the inherited FrameworkElement. It would change the cursor above the entire chart (not just the clickable portion), but maybe it would suit your need.

`this.detailChart.Cursor = Cursors.Hand;`

**Comment by beto-rodriguez** [comment]
Closing this for now since this seems solved.
