### ISSUE TITLE
Tooltip always on top, don't disappear on mouse out

### ISSUE THREAD

**Issue by cheilmann** [beto-rodriguez/LiveCharts2#33]
**Describe the bug**
If you hover over a chart the tooltip will shine through to every application. The tooltip will not disappear on mouse out.

**To Reproduce**
1. Start the WPFSample
2. Pies/Basic
3. Hover over a section of the chart until the tooltip appears
4. Tap out and move another window above the chart
5. See the tooltip shine through the window

**Expected behavior**
The tooltip doesn't appear on other application windows. The tooltip disappears when I leave the chart area.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/50573990/116949615-13ee2700-ac83-11eb-86c5-882ce288bfc9.png)

**Desktop (please complete the following information):**
 - OS: Win 10 Pro

**Comment by beto-rodriguez** [comment]
It should be fixed with the previous commit

**Comment by cheilmann** [comment]
That's amazing, looking forward to it.  Great project.
