### ISSUE TITLE
YAxis collapse when set "Minlimit"

### ISSUE THREAD

**Issue by wenya90** [beto-rodriguez/LiveCharts2#332]
<img width="742" alt="屏幕截图 2021-12-10 084715" src="https://user-images.githubusercontent.com/23717278/145498397-3fa89f87-6cd0-4c31-a020-9f860b5063e1.png">

YAxis collapse when set "Minlimit"

**Comment by YegorStepanov** [comment]
duplicate #330

**Comment by beto-rodriguez** [comment]
Thanks for the snippet, this only happened in the Y axis, I was not able to find until you pointer your example @YegorStepanov.

This is fixed and will be included in the next release.
