### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by Inkathu** [beto-rodriguez/LiveCharts2#341]
Hi, 
I've tried to use v2 charts and found this behaviour:
When I use custom control with chart and use this control in items list I see that memory leak very fast.
I realize that recreating items in list is not a goo solution, but I've not expected this fast leakeage.

Here I've tried to reproduce the problem: https://github.com/Inkathu/LiveCharts2MemoryLeak

@beto-rodriguez  Do you have any suggestion how to avoid this behaviour? Is there a right approach to dispose the chartcontrol for this kind of usage?
Thanks.

**Comment by beto-rodriguez** [comment]
Thanks for the repo, I am investigating this issue.

**Comment by beto-rodriguez** [comment]
This is fixed and will be included in the next release, thanks for the report.

**Comment by Inkathu** [comment]
You are welcome! 
Thanks for fix!
