### ISSUE TITLE
There are any way to display Chinese in axis?

### ISSUE THREAD

**Issue by Luoyingliang** [beto-rodriguez/LiveCharts2#347]
**Describe the bug**
I wanna display Chinese labels use AngelAxis but there cannot fallback true fontfamily in act

**Comment by beto-rodriguez** [comment]
Yes, take look at the following sample  https://github.com/beto-rodriguez/LiveCharts2/blob/master/samples/ViewModelsSamples/Axes/LabelsFormat2/ViewModel.cs
