### ISSUE TITLE
What time will v2 released on nuget?

### ISSUE THREAD

**Issue by xufangda** [beto-rodriguez/LiveCharts2#35]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by beto-rodriguez** [comment]
You can now install an early version:

Avalonia:
`Install-Package LiveChartsCore.SkiaSharpView.Avalonia -Version 2.0.0-beta.3`

Winforms
`Install-Package LiveChartsCore.SkiaSharpView.WinForms -Version 2.0.0-beta.3`

WPF
`Install-Package LiveChartsCore.SkiaSharpView.WPF -Version 2.0.0-beta.3``

Xamarin
`Install-Package LiveChartsCore.SkiaSharpView.XamarinForms -Version 2.0.0-beta.3`

Docs should be ready soon, for now you can try to browse the [samples folder in this repo](https://github.com/beto-rodriguez/LiveCharts2/tree/master/samples)

**Comment by ClubberLangG** [comment]
Can you split the nuget and have a "Core" nuget, by example in your samples you have the "ViewModelSamples". It should be independent of WPF or WinForms etc...

Thanks

**Comment by beto-rodriguez** [comment]
there are core packages

https://www.nuget.org/packages/LiveChartsCore.SkiaSharpView/

https://www.nuget.org/packages/LiveChartsCore/

then any platform require these 2 packages.

**Comment by jasonpp** [comment]
> You can now install an early version from Nuget:
> 
> Avalonia: https://www.nuget.org/packages/LiveChartsCore.SkiaSharpView.Avalonia
> 
> Winforms https://www.nuget.org/packages/LiveChartsCore.SkiaSharpView.WinForms
> 
> WPF https://www.nuget.org/packages/LiveChartsCore.SkiaSharpView.WPF
> 
> Xamarin https://www.nuget.org/packages/LiveChartsCore.SkiaSharpView.XamarinForms
> 
> Docs should be ready soon, for now you can try to browse the [samples folder in this repo](https://github.com/beto-rodriguez/LiveCharts2/tree/master/samples).

Nice bro.

**Comment by langejay** [comment]
Are there any pages or documents floating around that help developers (C#/WPF) update from LC0 to LC2?  I notice objects like ScatterPoint and SeriesCollection need replacing/changing.  Would be nice if there was a cheat sheet for some of these changes.

TIA

**Comment by CasperH2O** [comment]
> Are there any pages or documents floating around that help developers (C#/WPF) update from LC0 to LC2? I notice objects like ScatterPoint and SeriesCollection need replacing/changing. Would be nice if there was a cheat sheet for some of these changes.
> 
> TIA
> 
> (I am a Geared, paid user)

Hey @langejay did you find anything related to this? We are also looking into migrating from v0 to v2 but when replacing the packages we had about 300+ errors to fix.
