### ISSUE TITLE
BarChart legend at bottom does not display Series color "Icon"

### ISSUE THREAD

**Issue by MichelZ** [beto-rodriguez/LiveCharts2#350]
**Version** 
2.0.0-beta.90

**Describe the bug**
BarChart legend at bottom does not display Series color

**Expected behavior**
Series color displayed in legend

**Screenshots**
![image](https://user-images.githubusercontent.com/1040252/147642362-4d7ff6c1-b9d5-46f6-8922-a0e6bdcb01b7.png)

**Desktop (please complete the following information):**
 - OS: Windows 10, Winforms

**Reproduction**
- Change the Winforms Sample  Bars/Basic/View.cs to LegendPosition = LegendPosition.Bottom and view the Bars/Basic sample

**Comment by beto-rodriguez** [comment]
Thanks, it is fixed with the referenced commit and will be included in the next release.
