### ISSUE TITLE
Bar chart not correctly displayed above x-axis period

### ISSUE THREAD

**Issue by Albert634515** [beto-rodriguez/LiveCharts2#361]
Bug description:
I have a chart per year. If the chart values only consist of year they are displayed wrong on the x-axis.
In the sample I have two colums, both in the year 2006.
As you can see in the screenshot, one is displayed as being in year 2005.

Grap created in Winforms (C#)
Using beta 90
Os: Windows 10

![image](https://user-images.githubusercontent.com/85439711/148677311-0d76f680-eb41-46ce-85f8-3eb4ae749fa1.png)

**To Reproduce**
I have added the data/view used to reproduce this behaviour:

`    public class ViewModelStackedColumnSeries1Year
    {
        public IEnumerable<ISeries> Series { get; set; }

        public IEnumerable<Axis> XAxes { get; set; }

        public ViewModelStackedColumnSeries1Year()
        {
            var ob2list = new ObservableCollection<ISeries>();

            var cs = new StackedColumnSeries<DateTimePoint>
            {
                Name = "Test1",
                DataLabelsSize = 20,
                DataLabelsPaint = new SolidColorPaint(SKColors.Black),
                Values = new ObservableCollection<DateTimePoint>
                    {
                        new DateTimePoint
                        {
                            DateTime = new DateTime(2006, 1, 1),
                            Value = 1
                        }
                    },
                StackGroup = 1
            };
            ob2list.Add(cs);

            cs = new StackedColumnSeries<DateTimePoint>
            {
                Name = "Test2",
                DataLabelsSize = 20,
                DataLabelsPaint = new SolidColorPaint(SKColors.Black),
                Values = new ObservableCollection<DateTimePoint>
                    {
                        new DateTimePoint
                        {
                            DateTime = new DateTime(2006, 1, 1),
                            Value = 5
                        }
                    },
                StackGroup = 1
            };
            ob2list.Add(cs);

            cs = new StackedColumnSeries<DateTimePoint>
            {
                Name = "Test3",
                DataLabelsSize = 20,
                DataLabelsPaint = new SolidColorPaint(SKColors.Black),
                DataLabelsPosition = LiveChartsCore.Measure.DataLabelsPosition.Top,
                Values = new ObservableCollection<DateTimePoint>
                    {
                        new DateTimePoint
                        {
                            DateTime = new DateTime(2006, 1, 1),
                            Value = 3
                        }
                    },
                StackGroup = 2
            };
            ob2list.Add(cs);

            // Add Year axis
            Series = new System.Collections.ObjectModel.ObservableCollection<ISeries>(ob2list);
            XAxes = new List<Axis>
            {
                new Axis
                {
                    Labeler = value => new DateTime((long) value).ToString("yyyy"),
                    //Labeler = value => new DateTime((long) value).ToString("yyyy"),
                    LabelsRotation = 15,
                    Position = AxisPosition.Start,
                    MinStep = 1,
                    Name = "Year",
                    UnitWidth = TimeSpan.FromDays(365.25).Ticks
                }
            };
        }
    }`

**Comment by Albert634515** [comment]
I think what is happening here is that the distance for the x-axis is calculated by checking the distance between columns instead of the columns group

**Comment by beto-rodriguez** [comment]
Thanks for the report, this issue seems related to #221, the solution I mentioned there should also improve this case. Yes, this need better docs, I have that on mind and will make things clear there.
