### ISSUE TITLE
Avalonia Charts not visible when using Measure/Arrange/Render

### ISSUE THREAD

**Issue by 8** [beto-rodriguez/LiveCharts2#364]
Hi,

thank you for your work on this library, it looks really cool!

I am using the Avalonia Chart Controls from `LiveChartsCore.SkiaSharpView.Avalonia` in Version `2.0.0-beta.90` and I am unable to render the controls - they are always empty and show no data.

I've tried both the `PieChart` and the `PolarChart` without success.

I am drawing them as any other Avalonia control by first calling `control.Measure(size)` followed by `control.Arrange(rect)` and then rendering them to a `RenderTargetBitmap` which is then saved to a filestream as a png.

As a first test, I set `BorderThickness` and a `BorderBrush` of the Chart controls, which works fine and is rendered correctly, so it seems that the control itself is drawn, only the Chart part it's always missing.

As a second test I also included them in an actual GUI application and when run, they show up fine. I noticed some movement on startup which got me thinking that maybe an animation is to blame. 
This lead me to the Issue: "Disable Animation" (https://github.com/beto-rodriguez/LiveCharts2/issues/45) and https://github.com/beto-rodriguez/LiveCharts2/blob/master/docs/overview/1.9.animations.md.

As instructed, I set `EasingFunction` to null but that didn't help. For good measure, I've also tried setting `AnimationSpeed` and `UpdaterThrottler` to `TimeSpan.Zero`, but the rendered control ist still empty.

Is there some additional step I overlooked to disable animations or maybe it's someting else entirely that I've missed? Any pointers are appreciated!

Thank you!

Take care,
Martin

**Comment by beto-rodriguez** [comment]
Hi Martin

I am really not sure about this one, any help with Avalonia is appreciated, in the case of Avalonia the library uses a custom draw operation:

https://github.com/beto-rodriguez/LiveCharts2/blob/master/src/skiasharp/LiveChartsCore.SkiaSharp.Avalonia/MotionCanvas.axaml.cs#L139

Could this be an Avalonia issue?

**Comment by beto-rodriguez** [comment]
Closing this due inactivity, feel free to reply if need help.
