### ISSUE TITLE
Series color change not reflected in legend

### ISSUE THREAD

**Issue by RealityStop** [beto-rodriguez/LiveCharts2#365]
**Describe the bug**
I'm using a Cartesian Chart with numerous series that support user customization of color through outside controls.  When I change the color of a LineSeries's Stroke, the chart updates the line color, but not the "preview" ball in the legend.

**To Reproduce**
1. Create a Cartesian Chart with a legend and a LineSeries.
2. Change the Stroke color of the series at some time after the things have initialized and drawn.
3. Observe that the legend still shows the old color in the preview ball.

**Expected behavior**
Either the legend should automatically update when a Stroke color is changed, or a call could be made to manually synchronize.

**Screenshots**
Note the line has updated to be cyan, but the legend still has the red preview.
![image](https://user-images.githubusercontent.com/33366270/149407648-b97a2b7a-b14a-4c85-88c7-8bd7d1a90314.png)

Windows 10
WPF (Skia)

**Comment by beto-rodriguez** [comment]
Thanks for the report, now the library is able to detect when a paint changed with the referenced commit and will be included in the next release of the library.
