### ISSUE TITLE
wpf i cant set PieSeries color 

### ISSUE THREAD

**Issue by T-MES** [beto-rodriguez/LiveCharts2#366]
gauge.AddValue
                       (
                           new ObservableValue(item.Count()),
                           item.Key.ToString(),
                           CellStatusColor[item.Key],
                           CellStatusColor[item.Key]
                       );

  { WarhouseModel.CellStatus.Empty, SKColors.LightGreen } ,
                { WarhouseModel.CellStatus.Available,  SKColors.LightBlue } ,
                { WarhouseModel.CellStatus.Lock,  SKColors.DarkRed } ,
                { WarhouseModel.CellStatus.ShipmentLock, SKColors.IndianRed} ,
                { WarhouseModel.CellStatus.CheckingLock,  SKColors.MediumVioletRed  },
                { WarhouseModel.CellStatus.Stockpiling,  SKColors.LightGreen },

label color is normal

**Comment by T-MES** [comment]
i want set series but series outside have default color

**Comment by beto-rodriguez** [comment]
So you want a custom color for a gauge?

**Comment by beto-rodriguez** [comment]
Closing due Inactivity.
