### ISSUE TITLE
Winform cartesianChart line bug

### ISSUE THREAD

**Issue by LaoGouXiaShan** [beto-rodriguez/LiveCharts2#372]
cartesianChart3.Series = new ISeries[]
            {
                new LineSeries<double>
                {
                    Values = new double[] {3, 1, 5, 3, 7, 2, 9, 6, 5, 9}
                },
                new LineSeries<double>
                {
                    Values = new double[] {8, 4, 9, 1, 5, 7, 2, 4, 9, 3}
                },
            };

When i put my mouse point above  one of the point some distance, the tag "serise * *" will blink.

**Comment by beto-rodriguez** [comment]
Thanks for the report! 

Fixed with the referenced commit, and this fix will be included in the next release.
