### ISSUE TITLE
PieChart disappearing when only one PieSeries contains data.

### ISSUE THREAD

**Issue by Daantje007** [beto-rodriguez/LiveCharts2#375]
**Describe the bug**
PieChart disappears when only one of three PieSeries has data bigger then 0. It appears only if two of three PieSeries has data bigger then 0. This happens in the livecharts2 version of UWP.

**To Reproduce**
1. Create LivePieChart.
2. Supply with two PieSeries with value 0 and one with a value bigger then 0.
3. Run the program. The animation starts and then the pie chart disappears.

**XAML code**
`<lvc:PieChart x:Name="LivePieChart3" LegendPosition="Right" Series="{Binding OnLoaded}" InitialRotation="-90"></lvc:PieChart>`

**Code behind (C#) code**

```
private async void OnLoaded()
        {
                IEnumerable<double> a = new List<double> { 1 };
                IEnumerable<double> b = new List<double> { 0 };
                IEnumerable<double> c = new List<double> { 0 };

                IEnumerable<ISeries> Series = new List<ISeries>
                {
                    new PieSeries<double> { Values = a, Name = "a" },
                    new PieSeries<double> { Values = b, Name = "b" },
                    new PieSeries<double> { Values = c, Name = "c"  }
                };
                LivePieChart3.Series = Series;
            }
        }
```

**Expected behavior**
That the pie chart does not disappear in the above given case.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Version [LiveChart2] UWP 2.0.0-beta.80

**Comment by beto-rodriguez** [comment]
Thanks for the report, this is already fixed, I tested and the chart is visible for me, I do not where I fixed this, probably at e307c959aa797c3914eda4f5bf132136caa0fc9e

This fix will be included in the next release of the library, feel free to reply or create a new issue if it persists.
