### ISSUE TITLE
WPF CartesianChart freezes when zooming in for DateTimePoints / ObservablePoints

### ISSUE THREAD

**Issue by MaxEtMoritz** [beto-rodriguez/LiveCharts2#376]
**Describe the bug**
When zooming in very closely in a CartesianChart with a series of DateTimePoints or ObservablePoints, the whole application gets stuck.
It is the same behavior as in #54, but i did not investigate if it's the same loop that's causing the freeze.

**To Reproduce**
1. Create a sample similar to the Lines/Zoom sample, but using ObservablePoint or DateTimePoint instead of int.
2. Run the sample and zoom in as close as possible.
3. try zooming out or moving the application's window, basically try to do anything.
4. See the app not reacting.

**Expected behavior**
The Chart should not freeze the whole application.

**Desktop:**
 - OS: Windows 10.0.19042
 - WPF
 - LiveCharts Version 2.0.0-beta.90

**Additional context**

**Comment by langejay** [comment]
I wonder if this is related to an issue(s) that I am experiencing?  The XFormatter doesnt seem to 'play nice' when using DateTimePoints.

Would be interested in knowing if you changed your points to Observable Points if you get the same issue.

I value returned for the formatter is a double and the DateTimePoint is a long, I wonder if this has something to do with it.  I know you convert value to a long before processing the formatter but my returned value doesn't appear to match the value in the DateTimePoint (ticks)

**Comment by beto-rodriguez** [comment]
Hi @MaxEtMoritz! and thanks for the report.

That issue is fixed in the current version of the library.

@langejay I do not think it is related, I will close this for now, we could move your case to a new issue.
