### ISSUE TITLE
Cartesian chart zooming loses scale if zoomed in too much

### ISSUE THREAD

**Issue by bbmmcodegirl** [beto-rodriguez/LiveCharts2#38]
In the Cartesian chart, when zooming in too much, the curve disappears, and zooming out does not bring it back.

**To Reproduce**
1. Run the WPFSample (I have not tried with any others).
2. Click on the Lines/Zoom example.
3. With Ctrl-Mousewheel, zoom in until only 1 or no data point is still in the visible window.
   The curve disappears.
4. Now with Ctrl-Mousewheel, zoom out again, try to get the curve back.
  The chart stays blank.

**Expected behavior**
The curve should not completely disappear. But if it does, at least it should reappear when zooming out.

**Screen capture**
https://user-images.githubusercontent.com/6622880/117813854-ef0f3a80-b2a6-11eb-8772-03c4b4423aa7.mp4

**Desktop:**
 - OS: Windows 10
 - Desktop application, WPFSample
 - Version : https://github.com/beto-rodriguez/LiveCharts2/commit/70ff67e092991083e82f373fe840d3b4a9d186d9

**Comment by beto-rodriguez** [comment]
It will be published soon, thanks.

I don't know what went wrong, I see your fork was just created but your PR is missing many commits:

Your Scaler.cs changes file
https://github.com/beto-rodriguez/LiveCharts2/commits/37c7b7ac52ae8b3aa343f6b6048d9ae90f393a7b/src/LiveChartsCore/Measure/Scaler.cs

Master branch Scaler.cs changes:
https://github.com/beto-rodriguez/LiveCharts2/commits/master/src/LiveChartsCore/Measure/Scaler.cs
