### ISSUE TITLE
EnableNullSplitting only works with 1 null value

### ISSUE THREAD

**Issue by Skuriles** [beto-rodriguez/LiveCharts2#382]
Hello all,

I just made a small example, to test if this functionallity it working with this version (as it is not available in Livecharts1)
The goal ist to set manually min/max values from a input form and show the graph restricted to these values.
As the min/max can be set freely, the chance is really high that there is no Y value according to this point.

So we want a graph which is restricted to the Min/max value. For that we add dummy "null" values in each series and set "EnableNullSplitting" to true.

Maybe I'm doing something wrong, but the result is strange as soon as you have more than one null value in the series.
But when you add a second "null" value the graph is broken.

Any ideas why this could be?

mainView is simple Grid here and we use WPF Version
thanks in advance

![image](https://user-images.githubusercontent.com/7985622/151804446-05483768-73b0-40c2-bec1-5cf4cb5d8c0d.png)

```
private void InitGraph()
        {
            MyChart = new CartesianChart();
            var xAxis = new Axis()
            {
                Labels = new List<string>() { "1", "2", "3", "5", "8", "12", "15", "23", "27" }
            };

            xAxis.MinLimit = 2;
            xAxis.MaxLimit = 6;

            var serie = new LineSeries<int?>()
            {
                Values = new List<int?>() { 1, 5, null , 7, 2 , 5 ,null, 8, 4 },
            };
            MyChart.Series = new List<ISeries>() {serie};

            var yAxis = new Axis();
            
            serie.EnableNullSplitting = false;
            MyChart.XAxes = new List<Axis>() {xAxis};
            MyChart.YAxes = new List<Axis>() {yAxis};
            this.mainView.Children.Add(MyChart);
        }
```

**Comment by beto-rodriguez** [comment]
Thanks for the report! this was already fixed in a previous release, I will close this for now, feel free to reply here or in a new issue if it persists.
