### ISSUE TITLE
Pie Chart Formatter Return Chart Point Tertiary Value percentage

### ISSUE THREAD

**Issue by langejay** [beto-rodriguez/LiveCharts2#390]
In line with some of the capability in LC1, it would be nice if the proportion as a PERCENTAGE (0-1 or 0-100) is returned in the tertiary value position when a ChartPoint object is returned for the data formatter (etc).

**Comment by beto-rodriguez** [comment]
Thanks, this was missing, and it should be fixed with the referenced commit.

In the next version of the library a chart point contains the info it used to build the stack.

```
var percentage = chartPoint.PrimaryValue / chartPoint.StackedValue.Total;
// chartPoint.StackedValue has more info there, the start value, the end...
```
