### ISSUE TITLE
Data Tooltip Position when Legend Position is Left

### ISSUE THREAD

**Issue by langejay** [beto-rodriguez/LiveCharts2#391]
**Describe the bug**
The positioning of the DataToolTip seemed to be a little off. It appears as though this is related to the positioning (no offset applied) when a legend is shown.

**To Reproduce**
Use your repo and set the legend to left for the the General/Legends

**Expected behavior**
should be centred a little more to the right (to account for the legend I suspect)

**Screenshots**
![DTT_Position_Left_Legend](https://user-images.githubusercontent.com/29132935/153538818-3faf651b-d842-4a36-af95-edc6e577c8f7.png)
![DTT_Position_Top_Legend](https://user-images.githubusercontent.com/29132935/153538825-ff5148f8-2de0-4f05-acfc-714452e402cf.png)

**Desktop (please complete the following information):**
Windows (11) WPF

**Smartphone (please complete the following information):**
NA

**Additional context**

**Comment by beto-rodriguez** [comment]
Thanks! I have seen inconsistencies in the way tooltips are shown. Now you found the reason!

**Comment by beto-rodriguez** [comment]
Thanks for the report, this is already fixed with the referenced PR and will be included in the next release of the library.
