### ISSUE TITLE
DataLabelToolTip - Large numbers in X Axis doesn't work (well)

### ISSUE THREAD

**Issue by langejay** [beto-rodriguez/LiveCharts2#393]
**Describe the bug**
When there are large numbers in the X axis (and possibly the y axis) hovering the mouse over a point doesn't trigger the datatooltip for the point.

**To Reproduce**
Replace the Series definition in the ViewModelSamples.Lines.Straight viewmodel to the following:

```
 public List<ISeries> Series { get; set; } = new List<ISeries>
      {
          new LineSeries<ObservablePoint>
          {
              // Values = new List<double> { -2, -1, 3, 5, 3, 4, 6 },
              Values = new List<ObservablePoint>{
                  new ObservablePoint{ X = 100000, Y = 3.4},
                  new ObservablePoint{ X = 110000, Y = 2.2},
                  new ObservablePoint{ X = 120000, Y = 3.9},
                  new ObservablePoint{ X = 130000, Y = 4.1},
                  new ObservablePoint{ X = 150000, Y = 3.4},
              },
              Fill = null,
              // use the line smoothness property to control the curve
              // it goes from 0 to 1
              // where 0 is a straight line and 1 the most curved
              LineSmoothness = 0
          }
      };
```

**Expected behavior**
Datatooltip should be displayed with consistency no matter the general size (scale) of the x/y axis values

**Screenshots**

**Desktop (please complete the following information):**
W 11 WPF

**Smartphone (please complete the following information):**
NA

**Additional context**
I suspect the detection for a mouse over is based on absolute numbers (delta distance) from a point and doesnt consider the scales of the values being displayed.  Perhaps some code changes to consider pixels rather than relative (delta) from point would work?

This may also be the reason for the a point click not being detected when clicking on a chart and expecting a list or the closest point when none are returned if you have some kind of proximity threshold based on values and not proximity based on pixels.

All assumptions of course :-)

**Comment by beto-rodriguez** [comment]
Thanks for the report! 

The referenced commits fix this issue, it will be included in the next release of the library.
