### ISSUE TITLE
Font Weight Setting for Axis (and other areas probably)

### ISSUE THREAD

**Issue by langejay** [beto-rodriguez/LiveCharts2#399]
**Is your feature request related to a problem? Please describe.**
I would like to be able to set Font Weights.

**Describe the solution you'd like**
Your example Axes.LabelFormat (WPF) shows how you can set the FontFamily and Color of the Axis name.  Using this example, I realised you can also set the Formatter (of the axis) font using the property LabelsPaint on an axis. (XAxes.first().LabelsPaint)

There doesn't appear to be a way of setting the WEIGHT of the font.  Our data comes in a the common numerical format in the 100-900 series). I can/have built a translator for the FontWeight Class from .net, just don't know how to apply it into the axis

This is possiblyan issue in other areas of the chart display such as Datatooltip and DataLabels but have not checked that part thoroughly.

**Describe alternatives you've considered**
I tried using StrokeThickness doesn't appear work (which makes sense but I tried).

**Comment by beto-rodriguez** [comment]
Thanks for the report, this is already supported and will be included in the next version of the library.

Fixed with: 64d6e814b1d318b444932282a563b7c52e7c0b01 and 64d6e814b1d318b444932282a563b7c52e7c0b01.
