### ISSUE TITLE
Adding new chart types hierarchical, tree , org, matrix  layouts

### ISSUE THREAD

**Issue by weedkiller** [beto-rodriguez/LiveCharts2#4]
Hello, can you add new hierarchical layouts as well in the chart types such as [here](https://echarts.apache.org/examples/en/index.html)

We can make these view components and included in Nugets directly in projects and dashboard/widgets

**Comment by beto-rodriguez** [comment]
For sure this version will support more charts, in this version it is much easier to create charts.

**Comment by pilipinoy** [comment]
In v0, there were some samples on making an OHLC chart. How do we go about doing so in v2? Any timeline of adding candlestick charts, as this is the most popular chart for financial trading?

**Comment by beto-rodriguez** [comment]
@pilipinoy The idea is that v2 will have more features than v0, v2 will support (not sure when) all the features v0 did, while v2 is ready you can use v0

**Comment by weedkiller** [comment]
Hey Beto, will this work in ASP MVC Core

**Comment by beto-rodriguez** [comment]
@weedkiller  do you mean in the client side (the browser)? 

I am not sure if ASP NET will support WASM.

There could be a couple of options, using UNO platform and maybe (in a future) Blazor

**Comment by weedkiller** [comment]
hi @beto-rodriguez  yes front wend web in the browser

**Comment by beto-rodriguez** [comment]
@weedkiller WASM is a game changer, it will allow us to do it, I love JS frameworks such as Angular, but I can not deny that I prefer C# over JS or even TS.

I have been playing with Uno platform, it looks promising but for the case of this library seems that the performance will not be enough, but they keep improving things. https://github.com/unoplatform/uno

Also the Avalonia team is (or will) working to take Avalonia to WASM.  https://github.com/AvaloniaUI/Avalonia/issues/2239

There is also Blazor https://dotnet.microsoft.com/apps/aspnet/web-apps/blazor.

I will try to create a web site hosting the samples project compiled in WASM, but I am afraid I won't get a nice performance, but I am sure performance will keep improving with the time.
