### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by rusoaica** [beto-rodriguez/LiveCharts2#405]
Hello! 

Possible reference to #341 
I am using live charts v2 (2.0.0-beta.101) in combination with Autofac and the composition root pattern. As explained [here](https://autofac.readthedocs.io/en/latest/advanced/owned-instances.html#owned-of-t), Autofac's `Owned<T>` should dispose the dependency on request. In my case, I have a WPF project with two windows, `Startup` and `MainWindow`. `Startup` only contains a button that opens `MainWindow` when pressed, using an abstract view factory:

```
IMainWindowView? view = viewFactory.CreateView<IMainWindowView>();
view.ShowDialog();
```

where CreateView resolves to a `Owned<T>` view:

```
public TResult CreateView<TResult>() where TResult : IView
{
    Owned<TResult>? view = scope.Resolve<Owned<TResult>>();
    view.Value.Closing += (s, e) => { view.Dispose(); };
    return view.Value;
}
```

With the constraint of `TResult` being only classes that implement `IView` (windows), I am subscribing to their `Closing` event, so that I can call `Dispose()` on their `Owned<T>` parent, effectively disposing it and its resources.

In the constructor of `MainWindow` I am populating a list with a huge number of dummy objects, just to cause a significant memory increase. When `MainWindow` is closed and a garbage collection is forced, in Release mode, the memory consumption decreases to normal levels, indicating the fact that the window and its resources was disposed. This is also verified by logging some text in the window finalizer (destructor). 

However, when adding a `CartesianChart` to `MainWindow`, even after unsubscribing to its events, setting its series, axis and itself to null, the window is not disposed and the memory maintains the high usage. Memory profiler confirms the list of dummy objects is still in memory.

I've created a repository to illustrate the problem, [here](https://github.com/rusoaica/LiveChartMemoryLeak). To reproduce, set configuration to Release mode, run the project, click on the button, wait for the second window to load, then close it and wait for the GC to collect. The memory will remain at high levels. Then, comment out any reference to the `CartesianChart` in both the XAML and code behind of `MainWindow`, repeat the testing steps, the memory will return to normal usage, finalizer will be hit.

Is there any particular way of disposing a chart? 

Thanks!

**Comment by beto-rodriguez** [comment]
Hi @rusoaica 

Thanks for the repo, I will take a look and let you know the results!

**Comment by beto-rodriguez** [comment]
So... In your example you do:

```
// simulate huge memory consumption, to illustrate memory not being collected when the window is closed
for (int i = 0; i < 8000000; i++)
{
    hugeList.Add(new TestsClass() { Name = new string(Enumerable.Repeat(chars, 30).Select(s => s[random.Next(s.Length)]).ToArray()) });
}
```

Then I close the window, I see the are a lot of things alive in memory, but I do not see how that is related with LiveCharts, your plot is too small, you have many things in memory, not only LiveCharts, I am afraid that this issue is not related witht he ibrary, it is realated on how you create/dispose/manage your views,something is stuck in memory and the garbage collector is not able to clean it.

I tried to identify where the issue is, but there is a lot of code there, could you please provide a minimal reproducible example that illustrates that the issue come from LiveCharts so I can reproduce and fix?

At this point I do not really think this is an issue with the library.
