### ISSUE TITLE
[WinForms] tooltips are terribly blinking

### ISSUE THREAD

**Issue by kirsan31** [beto-rodriguez/LiveCharts2#41]
**Describe the bug**
Tooltips are terribly blinking in WinForms demo app. In WPF all are ok.

**To Reproduce**
Run WinFormsSample, use any chart.

**Expected behavior**
No blinking on tooltip in WinForms.

**Screenshots**

https://user-images.githubusercontent.com/17767561/118527914-6bdc6180-b74a-11eb-8bbd-42dda15f6b1e.mp4

**Desktop (please complete the following information):**
 - OS: Win 10 20H2

**Comment by beto-rodriguez** [comment]
The referenced commit fixes this issue, it is not the ideal solution, there are some things to improve in tooltips and legends
