### ISSUE TITLE
Chart not updating when changing Axis value ShowSeparatorLines 

### ISSUE THREAD

**Issue by rteuteu55** [beto-rodriguez/LiveCharts2#413]
**Describe the bug**
When changing the ShowSeparatorLines value of an Axis, the chart is not update automatically. I'm using  live charts v2 (2.0.0-beta.101 also tested with 2.0.0-beta.60) and I have the following Nugets added to the test project: **liveChartsCore** &  **liveChartsCore.SkiaSharpView.WinForms**.

**To Reproduce**
1. create a chart with some values and an axis
2. try to toggle the "ShowSeparatorLines" of this Axis. Nothing will update.
- chartTest.XAxes.First().ShowSeparatorLines = !chartTest.XAxes.First().ShowSeparatorLines;
**Note**: If I toggle the Axis IsVisible value twice (through a button) the axis will display the Separator Lines correctly 

**Expected behavior**
My understanding is that all the values from an Axis trigger change Notification. Some values do impact the Axis instantly (like changing the SeparatorsPaint value, the label rotation, the visibility).

**Screenshots**
See attached Gif
![Demo-livecharts-v2-separatorLines](https://user-images.githubusercontent.com/1083543/156610118-caaaa3c7-90a4-4eb8-81e6-17c11a42c36b.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by langejay** [comment]
This might help?

https://github.com/beto-rodriguez/LiveCharts2/discussions/407

**Comment by beto-rodriguez** [comment]
strange 🤔 I will investigate this.

**Comment by rteuteu55** [comment]
> This might help?
> 
> #407
> 
> In my code I use:
> 
> `View.Chart.CoreChart.Update(new ChartUpdateParams { });`

Thank you for this link. I do not hold a reference to the Chart in the ViewModel normally so this might be an issue, but still worth investigating!

**Comment by beto-rodriguez** [comment]
Fixed with the referenced commit and will be included in the next version of the library.

**Comment by rteuteu55** [comment]
Hi @beto-rodriguez the changes you made have improved the situation, but it seems the issue partially remain still:
- Changing ShowSeparatorLines works when an axis is first made visible with ShowSeparatorLines  as true.
- Changing ShowSeparatorLines doesn't work when an axis is made visible with ShowSeparatorLines  as false.

See following gif:
![separatorLineIssue](https://user-images.githubusercontent.com/1083543/191768346-2cb752e4-c8ec-4feb-a5a5-e4af2a0b3dfa.gif)
