### ISSUE TITLE
Grouped Bar Chart

### ISSUE THREAD

**Issue by vinicius121** [beto-rodriguez/LiveCharts2#42]
Hi,

I'm trying to use the grouped column chart. But it doesn't show on the interface after I click a button to display the chart.
Here is the code behind:

```
public ObservableCollection<ISeries> SeriesCollectionBar { get; set; }

SeriesCollectionBar = new System.Collections.ObjectModel.ObservableCollection<ISeries>();

foreach (DataColumn column in performanceTable.Columns)
{
    SeriesCollectionBar.Add(new ColumnSeries<double>
    {           
        Name = column.ColumnName,
        Values = new ObservableCollection<double> { 2, 4, 6, 1, 7, -2 }
    });
}
```

I also want to append a new value so I'm doing the following:
`
SeriesCollectionBar[column.Ordinal].Values.Append(3);
`
To append, I've declared an extension method as follows:

```
public static IEnumerable Append(this IEnumerable first, params object[] second)
{
    return first.OfType<object>().Concat(second);
}

```
The xaml code:
`<lvc:CartesianChart Series="{Binding SeriesCollectionBar}"></lvc:CartesianChart>`

Any help?

Thanks

**Comment by beto-rodriguez** [comment]
Hi

Where are you initializing the `SeriesCollectionBar` property?

``` c#
// this should be called in the constructor of your VM, other wise you must implement INotifyPropertyChanged
SeriesCollectionBar = new System.Collections.ObjectModel.ObservableCollection<ISeries>();
```

**Comment by vinicius121** [comment]
Hi,

I'm not using MVVM. So, I initialize inside the button event. And I have also declared the INotifyPropertyChanged, as below:
```
private ObservableCollection<ISeries> seriesCollectionBar;
public ObservableCollection<ISeries> SeriesCollectionBar
{
    get { return seriesCollectionBar; }
    set { seriesCollectionBar = value; OnPropertyChanged("SeriesCollectionBar"); }
}
```

```
private void OnPropertyChanged(string propertyName)
{
    PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
}
```
I don't know what I'm missing...
Any other suggestions?
Thanks

**Comment by beto-rodriguez** [comment]
I am closing this issue for now, please feel free to create a new issue if the error persist, please try to include a small repository or the steps to recreate the issue.
