### ISSUE TITLE
Cartesian Chart Access to DISPLAYED X and Y min and max values.

### ISSUE THREAD

**Issue by langejay** [beto-rodriguez/LiveCharts2#420]
**Is your feature request related to a problem? Please describe.**
We currently have access to the MinLimit and MaxLimit values however we do not have access to the MinDisplayValue and MaxDisplayValue when the Min and Max Limits are set to NULL.

**Describe the solution you'd like**
A property for each Axis that contains the DisplayMin and DisplayMax values (which will match the limits when they are imposed)

**Describe alternatives you've considered**
Have a function that determines the Min and Max values for every enabled series but this requires a fair bit of management and overhead when anything changes (zooming, data changes, series enabled/disabled etc etc).

**Additional context**
The reason for the request is so that I can calculate the UnitWidth and applythe appropriate formatting in my axis, generally for the xAxis when it uses DateTime.

PLEASE LET ME KNOW IF YOU ARE LOOKING TO PROVIDE THIS. :-)

Then I can consider my development path, and not work on alternative solutions if this will be provided.

MANY thanks.

PS we bought a LC1 license.

**Comment by beto-rodriguez** [comment]
Hi @langejay 

Firs of all thank you so much for supporting the library with your purchase and opening this issue.

I Just exposed the internal property that has this information, it is documented now, you can find more info at:

https://github.com/beto-rodriguez/LiveCharts2/commit/12b7e80cb44d0b20c97eccaf7ff1f5f6bd710ed1#diff-fd4524d9d504aef174a6ea900c401271db42e38e90c8b07eb6b70f37a79c6e3cR149

This will be included in the next version of the library.

I will close this for now, feel free to reply if this is not enough or you think it could be better.

Thanks again 🚀
