### ISSUE TITLE
[Feature Request] Multi-line labels

### ISSUE THREAD

**Issue by rteuteu55** [beto-rodriguez/LiveCharts2#424]
#### How to reproduce?

1. Create a chart with a XAxis and a serie with some DateTime values.
2. Add a custom Labeler with a line break
2a. Example: 
` Labeler = value => new DateTime((long)value).ToString("dd.MM.yyyy ") + Environment.NewLine + new DateTime((long)value).ToString("HH:mm:ss"),`
3. run your test to see that the line break is replaced by a square character

#### Extra notes

I would expect the Labeler to allow for line break. See below how the labels get displayed:
![image](https://user-images.githubusercontent.com/1083543/158859692-18901daa-7502-4819-aec2-d6019a7839b6.png)

#### I am using

<table>
<tr>
    <td>Live-Charts version</td>
    <td>2.0.0-beta.101</td>
</tr>
<tr>
    <td>.Net Version</td>
    <td>5.0.301</td>
</tr>
<tr>
    <td>Windows</td>
    <td>Windows 10</td>
</tr>
</table>

**Comment by beto-rodriguez** [comment]
Hi @rteuteu55  and thanks for the issue!

The library draws the chart using SkiaSharp, and this feature is not supported by them, I really do not think SkiaSharp will ever support this, so this means that if we require multiline labels we should implement that.

I will keep this issue open as a reminder to implement this feature.

**Comment by rteuteu55** [comment]
Thank you for checking that.
I would love to have a go at trying to help but would have no clue where to start. Any suggestion would be welcome!

**Comment by beto-rodriguez** [comment]
[Here](https://github.com/beto-rodriguez/LiveCharts2/blob/master/src/skiasharp/LiveChartsCore.SkiaSharp/Drawing/Geometries/LabelGeometry.cs#L77)

You could split the text by each new line, then draw/measure the result.

A PR is welcome!

**Comment by beto-rodriguez** [comment]
Fixed with the referenced commit and will be included in the next version of the library,

Thanks for the report!
