### ISSUE TITLE
differrent color for each point

### ISSUE THREAD

**Issue by imtect** [beto-rodriguez/LiveCharts2#425]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by beto-rodriguez** [comment]
Hi @imtect

Thanks for the issue, you can find help at this discussion https://github.com/beto-rodriguez/LiveCharts2/discussions/134.

The library will have a better solution for this scenario in a future release.

I will close this issue for now, please reply in the linked discussion if you need assistance on this.
