### ISSUE TITLE
Support for UWP?

### ISSUE THREAD

**Issue by davisjohnsonaspect** [beto-rodriguez/LiveCharts2#43]
When do you anticipate UWP support becoming available?

**Comment by beto-rodriguez** [comment]
Should not take too long, maybe around one month.

Now I am focused on the docs, web site and themes., after that the missing platforms will  be added, should take 2 or 3 days to add a new platforms.

**Comment by johngagefaulkner** [comment]
> Should not take too long, maybe around one month.
> 
> 
> 
> Now I am focused on the docs, web site and themes., after that the missing platforms will  be added, should take 2 or 3 days to add a new platform.

I noticed you released around 20 hours ago. Does that version contain initial support for UWP? I only need bar graphs and pie charts.

**Comment by beto-rodriguez** [comment]
@johngagefaulkner No not for now i will try to include it in the next days

**Comment by beto-rodriguez** [comment]
Sadly I am not able to find the [skia sharp view for UWP](https://www.nuget.org/packages?q=SkiaSharp.Views.UWP).

This version will be suspended by now, the good news is that there is now a skia sharp view for WinUI

**Comment by johngagefaulkner** [comment]
> Sadly I am not able to find the [skia sharp view for UWP](https://www.nuget.org/packages?q=SkiaSharp.Views.UWP).
> 
> This version will be suspended by now, the good news is that there is now a skia sharp view for WinUI

Is this what you're talking about? https://github.com/mono/SkiaSharp/pull/1696
If so, how do I access that new build of WinUI that includes SkiaSharp? I apologize for my ignorance in advance!

**Comment by beto-rodriguez** [comment]
@johngagefaulkner Here you can know more about WinUI3, I think it will be the replacement from UWP, but not only that it is a whole new thing.

**Comment by beto-rodriguez** [comment]
It is now supported in the #118 branch, there are a couple of current issues, I will clean this PR and then publish.
