### ISSUE TITLE
X/Y axis in scatter plot does not account for delta 0 in values

### ISSUE THREAD

**Issue by alessiosacco** [beto-rodriguez/LiveCharts2#435]
**Describe the bug**
When using a ScatterSeries with a data series that contains only points that have a single value in one of the two axes, the corresponding axis is not shown correctly

**To Reproduce**
Build and run the attached example WPF application

**Expected behavior**
The axes should be shown and the values should be centered in the chart view.

**Screenshots**
![LiveChartsBugReport](https://user-images.githubusercontent.com/11064281/161969393-4ea4c598-c80a-4a13-8a12-7c1b17b83085.png)

**Desktop:**
 - OS: Windows 10
 - WPF

**Additional context**
[ScatterZeroAxis.zip](https://github.com/beto-rodriguez/LiveCharts2/files/8426611/ScatterZeroAxis.zip)

**Comment by beto-rodriguez** [comment]
Thanks for the report!

This issue is fixed with the referenced commit, the fix will be included with the next release of the library!
