### ISSUE TITLE
Setting LegendBackground color in XAML has no effect Xamarin.Forms

### ISSUE THREAD

**Issue by vadimffe** [beto-rodriguez/LiveCharts2#439]
**Describe the bug**
While setting LegendBackground="Transparent" or any other color, no effect has taken place.

**To Reproduce**
Setting following parameters in XAML:

```
    <lvc:CartesianChart Series="{Binding CartesianSeries}" Grid.Row="2" Grid.Column="1"
                        LegendBackground="Transparent" LegendTextBrush="Black"
                        LegendPosition="Right" Margin="5,5,5,5"/>
```

Same for other charts, for example:

```
    <lvc:PieChart Series="{Binding MyChartSeries}" Grid.Row="2" Grid.Column="0" 
                  AnimationsSpeed="0" BackgroundColor="Transparent" 
                  LegendBackground="Black" LegendTextBrush="Black"
                  TooltipBackground="Transparent" 
                  LegendPosition="Right" Margin="5,5,5,5"/>
```

**Expected behavior**
Expecting to see change of LegendBackground by setting it from XAML. Currently Legend background is always white.

**Smartphone (please complete the following information):**
 - OS: Android 12

**Comment by beto-rodriguez** [comment]
Fixed with #440
