### ISSUE TITLE
No colored HeatMap with LabelFormatter on both X and Y axes

### ISSUE THREAD

**Issue by NejibChennoufi** [beto-rodriguez/LiveCharts2#444]
**Describe the bug**
Once I use label formatter for both x and y axes to bind double values, the heat map doesn't get colored. In fact, when I look carefully, I see just small segments of colors but no heat map as one may expect.

**To Reproduce**
Use label formatter for both x and y axes to bind double values (say pressure versus depth).

**Expected behavior**
Colored HeatMap with hopefully the option of diffused/interpolated color scheme (not boxed in rectangles).

**Screenshots**
![image](https://user-images.githubusercontent.com/34676894/165047306-8a6972fd-cd5d-4f9e-8e77-f3324529cae4.png)

![image](https://user-images.githubusercontent.com/34676894/165046890-5f112fe9-261f-489f-9803-073390e8b7e6.png)

**Desktop (please complete the following information):**
 - Windows 10
 - WPF, .Net Version 4.7.2
 - Live-Charts Geared Version 1 (licensed)

**Additional context**
I have posted my request https://github.com/Live-Charts/Live-Charts/issues but got no answers which was frustrating especially for paid license. Now, I understand I wasn't targeting the correct forum.
Your help is highly appreciated.

**Comment by NejibChennoufi** [comment]
Dear @beto-rodriguez : Any help on the subject please?
I see that you tagged it as livecharts0.x.
Do you think the matter is solved in the newer version?
Can I transfer my license to livechart2 and how please?

**Comment by beto-rodriguez** [comment]
In v0, the heat map works only using integer positions, I mean it is indexed, one point per unit. 

Now in v2 we use the "Unit width" to solve this issue. This will work much better and will be more intuitive in v2.

Sorry about the inconvenient, and yes, the license of v0 will be also valid at v2. 

Thanks for your support and sorry about the inconvenient.
