### ISSUE TITLE
[Feature Request] Piecharts LabelPosition OutsideSlice

### ISSUE THREAD

**Issue by NeoKabamaru** [beto-rodriguez/LiveCharts2#450]
Trying to migrate livechart charts to livechart2, I discovered (if I'm not mistaken) that there is no possibility to use in PieSeries the old attribute: `LabelPosition = PieLabelPosition.OutsideSlice`  

I guess the "new" way to migrate it would be `DataLabelsPosition = PolarLabelsPosition.OutsideSlice`, but there is no such possibility.

#### Expected result (LiveCharts version with `LabelPosition = PieLabelPosition.OutsideSlice`):

![livecharts1](https://user-images.githubusercontent.com/7078923/165913720-69b188a8-e903-449d-8ca9-a982c631a017.png)

#### Current Result: (with `DataLabelsPosition = PolarLabelsPosition.Middle`)

![livecharts2](https://user-images.githubusercontent.com/7078923/165913727-9dbfdec5-86b2-4ed9-89ea-554a06221162.png)

#### I am using
Live-Charts version	2.0.0-beta.101
.Net Version 6
Windows 10

**Comment by beto-rodriguez** [comment]
This is now supported an will be included in the next version of the library. Thanks for the report!
