### ISSUE TITLE
All WPF sample chars not update unless I resize the window (Build from the latest source code of master branch)

### ISSUE THREAD

**Issue by kenizhou** [beto-rodriguez/LiveCharts2#453]
**Describe the bug**
All WPF sample chars not update unless I resize the window. but it can works on another computer
![image](https://user-images.githubusercontent.com/614477/166092687-310e5e72-fb3b-495c-a3f9-7bcfb1c74652.png)

Example:
For the processing chart, the numbers are showing as normal, but Chart disappear. The chart will appear when I resize the window, but it still not update afterwards.

![image](https://user-images.githubusercontent.com/614477/166092747-65b86cf9-0f30-445c-8b8d-224e14fea32f.png)

**Desktop (please complete the following information):**
![image](https://user-images.githubusercontent.com/614477/166092719-df1c0e67-13fc-4964-87db-14fe2d202e99.png)

**Comment by kenizhou** [comment]
Tried previous version, it has the same issue.

**Comment by kenizhou** [comment]
[WPF - cannot redraw page on Intel 11th Core Iris Xe Integration graphic card](https://github.com/dotnet/wpf/issues/3817#)
#3817

**Comment by beto-rodriguez** [comment]
Glad you found the solution
