### ISSUE TITLE
Null Reference Exception

### ISSUE THREAD

**Issue by alexachso** [beto-rodriguez/LiveCharts2#457]
**Describe the bug**
I had an application that was working correctly with version beta.100. I just updated to beta.200 and now systematically I obtain this exception. 

Am I missing something? I did not change anything in my code. Only updated the library.

**To Reproduce**
1. Create a WPF application.
2. In the grid, declare a TabControl and add to this TabControl two tab items in which you must declare a chart.
3. Run the app and try to change the tab to display the second chart.

**Screenshots**
![image](https://user-images.githubusercontent.com/12586000/166254602-ff9c6732-d374-4dce-8d76-58ba5f46002f.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 21H2

I have attached a very very simple project which demonstrates this bug. It is a simple WPF app with a TabControl and 2 charts.
In order to pop the bug just run the app and try to switch the tab.
[SimpleChartProject.zip](https://github.com/beto-rodriguez/LiveCharts2/files/8604026/SimpleChartProject.zip)

**Comment by beto-rodriguez** [comment]
Thanks for the report, this is a bug, I am working on this, should be fixed soon.

It seems that when the chart is unloaded it disposes multiple resources but then when the chart is loaded again something is missing.

**Comment by XamMattia83** [comment]
Hello! Just for a feedback, i have the same issue on Xamarin Forms Android / iOS with the library updated to to beta.200
Thanks for your attention

**Comment by sekulicb** [comment]
Hi. When using same workflow in Avalonia version (LiveChartsCore.SkiaSharpView.Avalonia), when you switch between tabs, you don't get exception, but for example PieChart that I'm using, then just disappear from the UI.

**Comment by beto-rodriguez** [comment]
Fixed since v 2.0.0-beta-230
