### ISSUE TITLE
Problem with install package

### ISSUE THREAD

**Issue by Nefarem** [beto-rodriguez/LiveCharts2#460]
**Describe the bug**
I downloaded packages: [LiveChartsCore.SkiaSharpView.WPF](https://github.com/beto-rodriguez/LiveCharts2/packages/896935) and [LiveChartsCore](https://github.com/beto-rodriguez/LiveCharts2/packages/896931) from https://github.com/beto-rodriguez?tab=packages&repo_name=LiveCharts2. 
In package manager I added path to folder with this packages, in NuGet manager I see this packages to install but when I click, get error in console.
Screen:
[https://imgur.com/a/cQOXTJQ](url)

**To Reproduce**
1. Download packages from description.
2. Create folder in any place and put them this packages.
3. In visual studio click Tools -> Options -> NuGet package Manager -> Package sources and add them path to created folder and update button.
4. Tools -> NuGet package manager select added package sources, enable `include prerelease`, you see this 2 packages to install, select one and try install.
5. Get error from screen

**Screenshots**
[https://imgur.com/a/cQOXTJQ](url)

**Desktop:**
 - OS: Windows 10 21H2
 -  Visual Studio: 2022 Community
 - Visual Studio version: 17.1.1

**Additional info:**
- Packages version: 2.0.0-beta.100 prerelease

**Comment by beto-rodriguez** [comment]
Packages are updated on GitHub now to beta-220 

Thanks for the report!
