### ISSUE TITLE
"SaveImage" action often saves image failed and results in memory increase 

### ISSUE THREAD

**Issue by WeiqingChen** [beto-rodriguez/LiveCharts2#462]
**Describe the bug**
The function **SaveImage** often save failed image with no picture infomation, espically in Framework4.8. And the same time, the memory will increase more after every SaveImage action. version="2.0.0-beta.220" 
![image](https://user-images.githubusercontent.com/23234734/167279141-445c876a-8be5-475a-b91e-294c411654c1.png)
![Capture](https://user-images.githubusercontent.com/23234734/167279146-b05fd465-81ed-472c-910f-d344f5f3c8b4.JPG)

**To Reproduce**
1. Run the attached solution code(VS2022).
2. Run General/ChartToImage action to creat image.

**Expected behavior**
Saves the right image and the memory is not increasing after saving image action.

**Screenshots**
![image](https://user-images.githubusercontent.com/23234734/167245502-5e68ce69-f4ba-4ba8-9511-424deb37cc5d.png)

**Desktop (please complete the following information):**
 - OS: Win10

**Smartphone (please complete the following information):**

**Additional context**
[LiveChart2WPFSample.zip](https://github.com/beto-rodriguez/LiveCharts2/files/8644736/LiveChart2WPFSample.zip)

**Comment by WeiqingChen** [comment]
![image](https://user-images.githubusercontent.com/23234734/167279120-b33222d7-da80-47a1-8baa-cc9c30f928bd.png)
![Capture](https://user-images.githubusercontent.com/23234734/167279126-26d0743f-5c62-4f0a-ac50-1d08af09256e.JPG)

**Comment by EricEzaM** [comment]
I am having a similar issue regarding images saving as all white/blank, although I do not get it in a new test project based on the introductory documentation.

**Comment by beto-rodriguez** [comment]
Thanks for the report, I was able to reproduce both, the memory leak an the blank image, both are fixed now with the refenced commit and it will be include in the next version of the library.

**Comment by WeiqingChen** [comment]
I have updated the version to 2.0.0-beta.240, now it can save image successfully. But it also has the memory issue.
