### ISSUE TITLE
[WPF] Clearing underlying series collection breaks chart 

### ISSUE THREAD

**Issue by LabuzzMichal** [beto-rodriguez/LiveCharts2#47]
**Describe the bug**
Calling "Clear" method on ObservableCollection bound to Series Values breaks chart funcationalities

**To Reproduce**
1. Add LineSeries and Y axis to the chart

```
            Values = new ObservableCollection<double> { 5, 6, 7, 8, 5, 6, 7, 8 };
            Series = new ObservableCollection<ISeries>
            {
                new LineSeries<double>
                {
                    Values = Values,
                }
            };
            YAxes = new List<Axis>
            {
                new Axis
                {
                    IsVisible = true,
                    MaxLimit = 20,
                    MinLimit = 0,
                    ShowSeparatorLines = false,

                }
            };
```
2. Add function allowing you to modify Values

```
        public void ClearValues()
        {
            Values.Clear();
        }
```

3. Line serie should be visible

![image](https://user-images.githubusercontent.com/17740334/119880188-47436f00-bf2c-11eb-9511-0b9d365df2cf.png)

4. Call Clear method. Whole application hangs and nothing could be clicked

![image](https://user-images.githubusercontent.com/17740334/119880328-6cd07880-bf2c-11eb-9bfb-91cb8250faaa.png)

5. Repeat steps above WITHOUT binding YXaxes in chart. Chart is partially clreared but line still stays on chart

![image](https://user-images.githubusercontent.com/17740334/119880695-cb95f200-bf2c-11eb-963c-4bba49959ef0.png)

**Expected behavior**
Clearing underyling collection shouldn't hang whole application

**Desktop (please complete the following information):**
 - Windows 10 PRO
 - Beta 10 WPF

**Additional context**
There seems to be a lot of different problems somehow connected to MinLimit and MaxLimit as well. For example if you dont specify MinLimit in example above you will not see Line Serie

**Comment by beto-rodriguez** [comment]
Nice report, thanks, I was able to reproduce and fix, it is fixed with the mentioned commit above and will be included in  version beta 11
