### ISSUE TITLE
[WebAssembly] Odd texts above chart

### ISSUE THREAD

**Issue by Conparator** [beto-rodriguez/LiveCharts2#473]
**Describe the bug**
Not sure whether it's a bug or a feature. In Blazor WebAssembly, 2 h1-elemts are placed right above the chart (tested with the financial candlestick-chart), with the text "legend class => start row-fx" ("star row-fx" is visible from the moment the animation of the chart starts) and below this text, in the other h1, "container class => column" is written.
I attach a screenshot of it.
I didn't find an option yet to disable these texts. Could somebody give me advice, please? 
I'm using Livecharts v2.0.0-beta.220. 

**Screenshots**
![Capture](https://user-images.githubusercontent.com/81414220/168421357-24fea576-51b8-4a04-8d7a-82784d1eb02d.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Vivaldi

**Comment by beto-rodriguez** [comment]
Hi

You are running the Uno sample right?

I keep working to improve Uno, the problem there is that we need to fire tooltips with a different logic, when we are on mobile we need to show the tooltip `on tap` but on desktop (including wasm) it needs to be fired when the pointer is above the point, this should be fixed in a future release of the library.

**Comment by Asyvix** [comment]
@beto-rodriguez 
remove
```

<h1>legend class => @LegendClass</h1>
<h1>container class => @ContainerClass</h1>
```

in Chart.razor

**Comment by Conparator** [comment]
> Hi
> 
> You are running the Uno sample right?
> 
> I keep working to improve Uno, the problem there is that we need to fire tooltips with a different logic, when we are on mobile we need to show the tooltip `on tap` but on desktop (including wasm) it needs to be fired when the pointer is above the point, this should be fixed in a future release of the library.

Hi there, sorry that I respond late. I lost "track" on this issue. I'm using the Blazor-exmaple:
https://github.com/beto-rodriguez/LiveCharts2/tree/master/samples/BlazorSample

**Comment by beto-rodriguez** [comment]
mmm I missed that so bad, thanks for the report, it is fixed with the referenced commit and it will be included in the next version of the library.
