### ISSUE TITLE
Blazor Wasm runs out of memory trying to resize HTML canvas

### ISSUE THREAD

**Issue by sajadkardel** [beto-rodriguez/LiveCharts2#475]
As I understand it,
SkiaSharp sets the screen size for the width of the charts. The problem occurs when we want to place the chart in a container more minor than the device screen. 
In this case, the size of the chart width enters the loop and will cause an out-of-memory exception.
You can see this issue in SkiaSharp [https://github.com/mono/SkiaSharp/issues/1838](https://github.com/mono/SkiaSharp/issues/1838)
You will definitely find more details in it because this is a closed issue :)

**Comment by beto-rodriguez** [comment]
It seems that this was a SkiaSharp issue, and it should be fixed both SkiaSharp and LiveCharts because the latest version of the library references a version of SkiaSharp without issues.
