### ISSUE TITLE
.WithLabelFormatter not invoked with zero value

### ISSUE THREAD

**Issue by diegobarile** [beto-rodriguez/LiveCharts2#477]
**Describe the bug**
If I bind a PieChart to one serie to achieve one Gauge only when I set the serie value to 0 (zero) the .WithLabelFormatter is not invoked.

**To Reproduce**

1. Define members like these:
```
public ObservableValue MotorCurrent { get; set; }

public IEnumerable<ISeries> MotorCurrentSeries { get; set; }

MotorCurrent = new ObservableValue (0);
MotorCurrentSeries = new GaugeBuilder ()
  .WithInnerRadius ( 65 )
  .WithBackgroundInnerRadius ( 65 )
  .WithLabelFormatter(cp =>
  {
      return cp.PrimaryValue > 0 ? string.Format(CultureInfo.CurrentCulture, "{0:0.0} A", cp.PrimaryValue) : "Off";  
     // "Off" is never formatted.
  })
  .WithLabelsPosition ( PolarLabelsPosition.ChartCenter )
  .AddValue ( MotorCurrent )
  .BuildSeries ();
```
2. Bind the Pie:

```
<lvc:PieChart
  Width="200"
  Height="200"
  InitialRotation="-225"
  MaxAngle="270"
  Series="{Binding MotorCurrentSeries}"
  Total="1000" />
```
3. Run and set the value as follow:
```
MotorCurrent.Value = 0;
```

**Expected behavior**
When value is not zero the formatter is called properly. Otherwise not.

**Desktop:**
 - OS: Edition	Windows 10 Pro
  Version	21H2
  OS build	19044.1706
  Experience	Windows Feature Experience Pack 120.2212.4170.0

Thanks in advance.

**Comment by diegobarile** [comment]
One possible workaround is to set double.Epsilon instead zero (when possible) and then:

```
.WithLabelFormatter ( cp =>
{
    return cp.PrimaryValue > double.Epsilon ? string.Format ( CultureInfo.CurrentCulture, "{0:0.0} A", cp.PrimaryValue ) : "Off"; 
} )
```
Not exciting but it works.

Diego.

**Comment by beto-rodriguez** [comment]
Thanks for the report, this was definitely wrong.

The referenced commit fixed this, and it will be included in the next version of the library.
