### ISSUE TITLE
Zooming automatically after Axis MaxLimit reached

### ISSUE THREAD

**Issue by fvelasquez-scantech** [beto-rodriguez/LiveCharts2#479]
Hello to the community, i would like to go straight forward with my issue.

This is my ViewModel
```
    Public Property Series As IEnumerable(Of ISeries)
    Public Property Frame As DrawMarginFrame
    Public Property XAxes As IEnumerable(Of Axis) = New Axis() {New Axis With {
        .MinLimit = 0,
        .MaxLimit = 10,
        .ForceStepToMin = False,
        .MinStep = 1
    }}
    Public Property YAxes As IEnumerable(Of ICartesianAxis)
```

The Xaml
```
<lvc:CartesianChart
    x:Name="ChartMetrology"
    Grid.Row="1"
    Series="{Binding Series}"
    XAxes="{Binding XAxes}"
    ZoomMode="X"
    YAxes="{Binding YAxes}"             
    Height="450" 
    Width="670">
</lvc:CartesianChart>
```

and code behind:

```
Private series As IEnumerable(Of ISeries) 
Private valuesCollection = New ObservableCollection(Of ObservableValue)() 

Sub New()
 series = New ISeries() {New LineSeries(Of ObservableValue) With {
            .Values = valuesCollection,
            .Fill = Nothing,
            .GeometrySize = 0
        }}

    ChartMetrology.Series = series
End Sub

 Dim i As New Random
Private Sub Agregar10(sender As Object, e As RoutedEventArgs) 'This is a button click that plots a value

    valuesCollection.Add(New ObservableValue With {
        .Value = i.Next(0, 10)
    })
End Sub
```

Graph result:

![image](https://user-images.githubusercontent.com/61747153/168903115-5a662195-87cc-4db7-a57b-fc259ee0076f.png)

I can't find out how to move X axis when i a add a new value, like this [gif](https://raw.githubusercontent.com/beto-rodriguez/LiveCharts2/master/docs/_assets/zoom-x.gif) taken of [this example](https://lvcharts.com/docs/wpf/2.0.0-beta.220/CartesianChart.Cartesian%20chart%20control#zooming-and-panning) but automatically. I was also trying with [this example](https://lvcharts.com/docs/WPF/2.0.0-beta.220/samples.axes.paging) but same results. What i'm missing here?, i thought that specifying MinLimit and MaxLimit was enough but with this values set the graph stays static with only the first 10 values (like the graph result attached)

Thank you for you reading

**Comment by EricEzaM** [comment]
To automatically move the X axis bounds when new data is added, simply `MinLimit` and `MaxLimit` of the X Axis to `null` (this is the default). 

Remove these lines from your view model:
```cs
.MinLimit = 0,
.MaxLimit = 10,
```

**Comment by fvelasquez-scantech** [comment]
Thank you for your answer @EricEzaM, sadly i've already tried that with no success. This is the graph result:

![image](https://user-images.githubusercontent.com/61747153/169052656-54cc8149-b848-4e9b-832c-c45f1e73faf8.png)

As you can see, it doesn't show only the last 10 values in the X axis. You can imagine it like a zooming in only the last 10 values of X axis.

If you see [this GIF image](https://raw.githubusercontent.com/beto-rodriguez/LiveCharts2/master/docs/samples/axes/paging/result.gif) there are a lot of values in the X that you can inspect. In that GIF image example when you press "Page 3" it goes to the last values. I need to do that but automatically when i insert a new value, for this issue my MinLimit was 0 and my MaxLimit was 10, so in the 11 value it should show only last 1 to 11 values.

Thank you for your reading!

**Comment by EricEzaM** [comment]
Ah, I understand what you want now. Try adding the below. I have written it in c# since I am unfamiliar with the VB sytax.

```cs
// your existing code in 'Agregar10'
valuesCollection.Add(New ObservableValue With {
    .Value = i.Next(0, 10)

// new code (in c#)
XAxes[0].MaxLimit = valuesCollection.Count - 1;
XAxes[0].MinLimit = valuesCollection.Count - 10;

// You may also wish to surround with Math.Max so that the range does not go into negatives.
XAxes[0].MaxLimit = Math.Max(0, valuesCollection.Count - 1);
XAxes[0].MinLimit = Math.Max(0, valuesCollection.Count - 10);
```

If you data is not just ObservableValue, but instead ObservablePoint for example, you may need determine the bounds based on the X value of the points, rather than just the collection size. Meaning, get the `X` value of the last point, and this is your `MaxLimit`. Get the `X` value of the 10th last point (or the Nth last point if N < 10) and the `MinLimit` will be that value.

**Comment by beto-rodriguez** [comment]
Thanks for the report, and thanks @EricEzaM for the answer!

Did you find an answer @fvelasquez-scantech ?

**Comment by fvelasquez-scantech** [comment]
Hello, it worked charmly, thank you so much. Now i have to plot real data, let's see how it's going!

Thank you again !!!
