### ISSUE TITLE
candlesticks/high performant line plot

### ISSUE THREAD

**Issue by pavlexander** [beto-rodriguez/LiveCharts2#48]
**Is your feature request related to a problem? Please describe.**
I would like to render million of candlesticks (financial data). Currently it's not possible.

**Describe the solution you'd like**
 Would be nice having this plot type built-in and optimized for high data record count..

**Describe alternatives you've considered**
In a meanwhile I tried rendering 10k of close price records, but the library is not performing well. Lot's of series are shown. If we were to increase the size to 500k records, this would surely crash my pc..

![image](https://user-images.githubusercontent.com/20644772/120116563-60992500-c191-11eb-97e2-c32cb6b9e748.png)

![image](https://user-images.githubusercontent.com/20644772/120116371-85d96380-c190-11eb-84c8-b5b163d15276.png)

**Additional context**
I am really just looking into high-performant code that would allow to render lots of financial data. Candles and close prices are the basics. Here is the test code I am using:

            int totalPoints = 10_000;
            var sth = DataGen.RandomStockPrices(null, totalPoints);
            var sth2 = sth.Select(s => s.Close).ToList();
            var Series = new ObservableCollection<ISeries>
            {
                new LineSeries<double>
                {
                    //Values = new ObservableCollection<double> { 200, 558, 458, 249, 457, 339, 587 },
                    Values = sth2,
                    Stroke = null,
                    GeometrySize = 0,
                    GeometryFill = null,
                    GeometryStroke = null,
                    // Fill = null,
                    LineSmoothness = 0,
                },
            };

            var cartesianChart = new CartesianChart
            {
                Series = Series,
                ZoomMode = LiveChartsCore.Measure.ZoomAndPanMode.X,
                Location = new System.Drawing.Point(0, 0),
                Size = new System.Drawing.Size(50, 50),
                Anchor = AnchorStyles.Left | AnchorStyles.Right | AnchorStyles.Top | AnchorStyles.Bottom,
                AnimationsSpeed = TimeSpan.Zero,
            };

Animation, line smoothing are disabled. Zooming-in enabled.. but it's nearly impossible to use the plot.

**Comment by beto-rodriguez** [comment]
The high performance package is not published yet, in my tests in can plots millions in 50ms, but it is not the final result.

**Comment by pavlexander** [comment]
@beto-rodriguez I see... Would you mind if I asked 3 follow-up questions?
1. Do you have any plans on releasing candlestick data series? (in regards to my original question)
2. High performance package release date? :)
3. Is it possible to disable the point tooltips? (like you see in the picture above). I went through all the OxyPlot examples, but couldn't find a single plot where tooltip wouldn't be shown on mouse hover.. So I couldn't disable the tooltips completely.

**Comment by beto-rodriguez** [comment]
@pavlexander yes it is possible to disable tooltips, but take a look again at them, I improved a lot of things on them, they should now behave better.

Also here are some docs (it will be easier to read when the new site is published):

https://github.com/beto-rodriguez/LiveCharts2/blob/master/docs/1.overview/1.10.tooltips.md

For questions 1 and 2 I would say 1 month maybe
