### ISSUE TITLE
Geo map exception

### ISSUE THREAD

**Issue by joootdooot** [beto-rodriguez/LiveCharts2#480]
**Describe the bug**
Exception file not found using geo map on .NET 4.8 and LiveCharts.WinForms

**To Reproduce**
Drag the winforms geo map from toolbox to form

**Expected behavior**
No exception

**Screenshots**
![Screenshot 2022-05-18 181450](https://user-images.githubusercontent.com/20543556/169016212-4c4bfdfd-331f-43ca-a8b2-ba06782a9974.png)

**Desktop (please complete the following information):**
 - OS: Win 11

**Additional context**

**Comment by beto-rodriguez** [comment]
Hi

From the error message I see you are using LiveCharts 0.x, can you update to 2.0 and try again?

**Comment by joootdooot** [comment]
![Screenshot 2022-05-21 203617](https://user-images.githubusercontent.com/20543556/169651759-0812106d-685f-4fe8-ad5d-ce67391a2038.png)
I don't see a 2.0, is this a bug with nuget?

**Comment by joootdooot** [comment]
Oh it's under prerelease, seems to work now. Thanks!

**Comment by beto-rodriguez** [comment]
Glad to read that!
