### ISSUE TITLE
MAUI basic sample only display when navigated using Shell for both Android and iOS. Normal navigation does not render

### ISSUE THREAD

**Issue by hbraasch** [beto-rodriguez/LiveCharts2#481]
**Describe the bug**
Initially:
MAUI basic sample crashes for both Android and iOS with[LiveChartsCore.SkiaSharpView.Maui.MotionCanvas is incompatible].
Sample app is a simple CartesianChart based on MAUI install example
Finally: Realized it has to do with [Shell] or normal navigation (see later discussion).

**To Reproduce**
1. Go to github repository for sample project: https://github.com/hbraasch/LiveChartsMauiSample.git
2. Clone project and run for both Android and iOS
3. Observe exception

**Expected behavior**
Line chart should display

**Screenshots**
![image](https://user-images.githubusercontent.com/7484186/169195876-33019a15-f573-4ca5-89c1-4f1e9ce638cb.png)

**Smartphone (please complete the following information):**
 - Device: Latest emulators for IOS and Android
- MAUI RC3

**Comment by hbraasch** [comment]
Yes, its in there. Unfortunately.
Must be a different problem. Have found a lot of regression problems with MAUI RC. Could be the issue resolves itself 😊
Regards.

**Comment by hbraasch** [comment]
Hi

My sincere apologies! I forgot to add [.UseSkiaSharp(true)] in the repro project. It now works with the chart defined in XAML.

However (as it started for me), I prefer defining my GUIs using code-behind, and the code I created to embed a graph does not render.
Here is the code example, it is also in the updated repro on Github
```
internal class CodeBehindMainPage : ContentPage
    {
        public CodeBehindMainPage()
        {
            var chart = new CartesianChart();
            chart.Series = new ISeries[]
            {
                new LineSeries<double>
                {
                    Values = new double[] { 2, 1, 3, 5, 3, 4, 6 },
                    Fill = null
                }
            };
            var grid = new Grid();
            grid.Add(chart);
            Content = grid;
        }
    }
```
Any idea what I'm doing wrong?

Thanks and regards

**Comment by beto-rodriguez** [comment]
> I forgot to add [.UseSkiaSharp(true)]

Glad to hear that, so the control is working!

I think that you second question is not related with the library, try to add another control first, like a button or something from MAUI, then see if it renders, if it does but the chart does not then the issue is from this library.

**Comment by hbraasch** [comment]
I've now noticed that if I navigate to the code-behind page using [Shell], it renders.
But if I navigate to it using my regular approach (which works if I replace the graph with a label), it renders fine.
Regular approach:
```
MainPage = new NavigationPage(new CodeBehindMainPage());
```

Any ideas maybe?

**Comment by beto-rodriguez** [comment]
Not completely sure.

Been honest, I think that that kind of issues have a low chance to be an issue in this library, it could be an issue with SkiaSharp or MAUI.

but feel free to re-open this issue if you think that this issue is related with this library.

**Comment by hbraasch** [comment]
Thanks for looking at this.
I'll generate a repro project and raise it as a issue under MAUI and see how they react.
Regards

**Comment by hbraasch** [comment]
Issue raised at MAUI: https://github.com/dotnet/maui/issues/7350

**Comment by hbraasch** [comment]
I've now discovered the chart does not display while running under the debugger. If running outside the debugger, all works fine.

Any possibility there is a [if (Debugger.IsAttached)... somewhere inside your code?

**Comment by beto-rodriguez** [comment]
Thanks for the Research, it seems that the error is here in LiveCharts, I tested your repo and added a view containing a `SKCanvasView` (from skia sharp) and it works 🤔

**Comment by hbraasch** [comment]
Hope you find it. Its a great library!

**Comment by beto-rodriguez** [comment]
This seems a Maui issue, I added information to the issue you opened in Maui, lets wait for them to fix that, if they do not, then we could build a workaround.

**Comment by hbraasch** [comment]
Great, Thanks

**Comment by beto-rodriguez** [comment]
Since beta.860 we removed the support for the XAML preview in MAUI, so this should be already working. Thanks for the report.
