### ISSUE TITLE
GC Collector working like a threadmill

### ISSUE THREAD

**Issue by forReason** [beto-rodriguez/LiveCharts2#489]
I have a chart with ~100 points per second.
the GC is running constantly:
![image](https://user-images.githubusercontent.com/12736950/170027335-0d89ceeb-cb57-48ae-bf0d-d4fa5d08e1ba.png)

This is my Code to update Data:
```C#
// amount of datapoints to keep in chart per series 
// (200 points / 25points per second = 8 seconds)
static int dataLength = 200;
// 4 series in total
private static List<ObservableCollection<ObservableValue>> seriesDataPoints 
    = new List<ObservableCollection<ObservableValue>>();
private static List<string> seriesNames = new List<string>();
// variable in attempt to reduce GC pressure
private static ObservableValue ReUseShell = null;
// add new datapoint (and remove old datapoint if series > dataLength )
public static void AddDataPoint(double point, string seriesName)
{
    // search for the correct series
    int seriesIndex = -1;
    for (int i = 0; i < seriesNames.Count; i++)
    {
        if (seriesNames[i] == seriesName)
        {
            seriesIndex = i;
            break;
        }
    }
    // series was not found, create new serries
    if (seriesIndex == -1)
    {
        seriesIndex = CreateNewSeries(seriesName);
    }
    // check if we have a reusable datapoint (in order to reduce gc)
    if (ReUseShell != null)
    {
        ReUseShell.Value = point;
        seriesDataPoints[seriesIndex].Add(ReUseShell);
        ReUseShell = null;
    }
    else
    { // we dont have a empty data point (series < datalengt / ~initialisation)
        seriesDataPoints[seriesIndex].Add(new(point));
    }
    // remove oldest datapoint and reuse it for the next data fill
    if (seriesDataPoints[seriesIndex].Count > dataLength)
    {
        ReUseShell = seriesDataPoints[seriesIndex][0];
        seriesDataPoints[seriesIndex].RemoveAt(0);
    }
}
```
is there an issue with my code, an issue with LiveCharts or is that just expected behavior?

**Comment by forReason** [comment]
hmm visually no, but as this is a financial application, I'm not terribly happy about the garbage collector to run constantly.
I notice the GC turns off when I uncomment the very line that calls the add datapoint function from above:
`AddDataPoint(point, "btc-usdt_ask")`

Could the gc reside in ObservableCollection?

I guess what Ill do for now is to implement a checkbox to enable/disable charting..

**Comment by Kevin-Seiden** [comment]
@forReason Is there a specific reason you have everything marked static?  Avoid using mutable (non-constant) static fields unless you have a very good reason and really know what you're doing.  I'm not 100% sure but I suspect this may be the issue as the GC behaves differently when static fields are involved.

Bonus tip: For performance, you might consider using a Dictionary<string, ObservableCollection<ObservableValue>> rather than two lists so that you can look them up by name instead of looping to find the indices.  If you don't have many series, it probably won't affect much but it's a good practice regardless.

**Comment by beto-rodriguez** [comment]
I will close this for now since there is no evidence that this is an issue relate with the library, feel free to reply or reopen the issue if you find something we can work on!
