### ISSUE TITLE
Could it possible to add Crosshair feature to chart?

### ISSUE THREAD

**Issue by AndrewKhloptsau** [beto-rodriguez/LiveCharts2#490]
Hello everyone!  Could it possible to add crosshair feature to chart? It's very useful thing with custom axes.
![image](https://user-images.githubusercontent.com/86781681/170200065-d379722b-2232-44c1-9078-14042c72dfe3.png)
More information https://js.devexpress.com/Documentation/ApiReference/UI_Components/dxChart/Configuration/crosshair/

**Comment by beto-rodriguez** [comment]
Hi an thanks for the issue!

This is a great feature that is missing currently in the library, I will keep this issue open to track this implementation.

**Comment by beto-rodriguez** [comment]
This is going to be included in the next version of the library.

Sample here:
https://github.com/beto-rodriguez/LiveCharts2/blob/dev/samples/ViewModelsSamples/Axes/Style/ViewModel.cs

![micael](https://user-images.githubusercontent.com/10853349/193343823-a1b09ad1-d741-4582-9210-ddfa35fd6101.gif)
