### ISSUE TITLE
Drag up and down a point on the chart 

### ISSUE THREAD

**Issue by ricbrue** [beto-rodriguez/LiveCharts2#491]
Hi, I would like to know if there is any possibility to drag a certain point (up/down).

I am developing using the MAUI framwork.

Is a feature like this available? Thank you.

**Comment by beto-rodriguez** [comment]
Hi!

Yes this should be possible, have your tried the add on click sample?

I think that you should be able to build that base on the 'Events/AddPointOnClick' sample:

https://github.com/beto-rodriguez/LiveCharts2/tree/master/samples/MauiSample/Events/AddPointOnClick
https://github.com/beto-rodriguez/LiveCharts2/tree/master/samples/ViewModelsSamples/Events/AddPointOnClick

**Comment by beto-rodriguez** [comment]
Closing this issue due inactivity, feel free to re-open reply if required.
