### ISSUE TITLE
Uno Platform WinUI3 (.NET 6)

### ISSUE THREAD

**Issue by tsorger1403** [beto-rodriguez/LiveCharts2#492]
I created a project using the [Uno Platform Blank Application for WinAppSDK - WinUI 3 (.NET 6 - Preview) template](https://platform.uno/docs/articles/get-started-dotnet-new.html?tabs=windows#uno-platform-blank-application-for-winappsdk---winui-3-net-6---preview). When adding LiveCharts as described in [this article](https://platform.uno/blog/livecharts-announces-support-for-uno-platform/), I get the follwing error:
`The type 'SuspendingEventArgs' exists in both 'Microsoft.Windows.SDK.NET, Version=10.0.22000.24, Culture=neutral, PublicKeyToken=31bf3856ad364e35' and 'Uno, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null'`

**Comment by beto-rodriguez** [comment]
Yes,  WinUI3 is not working yet for LiveCharts, the library needs https://github.com/mono/SkiaSharp/issues/1787 for that, the PR linked to that issue is active and it seems that should be ready soon.

**Comment by francoistanguay** [comment]
FYI, Skia/WinUI is now supported and people are interested here: https://github.com/unoplatform/uno/discussions/9193

**Comment by sasakrsmanovic** [comment]
@beto-rodriguez  Please let us know if we need to adjust anything at our LiveCharts announcement blog post - someone asked here https://github.com/unoplatform/uno/discussions/9193

**Comment by beto-rodriguez** [comment]
Thanks @francoistanguay and @sasakrsmanovic  for the update, I will work on that soon.
