### ISSUE TITLE
Could not load file or assembly

### ISSUE THREAD

**Issue by KingIthra** [beto-rodriguez/LiveCharts2#493]
![image](https://user-images.githubusercontent.com/50165893/170363683-0a9a178d-7d4e-44f1-be11-5ed320d492a7.png)

<UserControl x:Class="Optimum.Views.ManagerView"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" xmlns:lvc="clr-namespace:LiveChartsCore.SkiaSharpView.WPF;assembly=LiveChartsCore.SkiaSharpView.WPF"
             xmlns:viewmodels="clr-namespace:Optimum.ViewModels" d:DataContext="{d:DesignInstance Type=viewmodels:ManagerViewModel}"
             mc:Ignorable="d"
             d:DesignHeight="450" d:DesignWidth="800">
    
    <Grid>
        <Grid.RowDefinitions>
            <RowDefinition Height="*"/>
        </Grid.RowDefinitions>
        
        <lvc:CartesianChart Series="{Binding Series}" XAxes="{Binding XAxes}"></lvc:CartesianChart>
    </Grid>
</UserControl>

that is my code. However I am getting this error : could not load file or assembly

I am using .net 6 and WPF , the code behind seems to be okay. I installed live charts 2 using only this command in the package manager console : Install-Package LiveChartsCore.SkiaSharpView.WPF -Version 2.0.0-beta.240, i don't know if there is anything else i should do. Thank you in advance.

**Comment by beto-rodriguez** [comment]
Hi and thanks for the report!

Does your code compile? can you please try to compile the code and ignore the warning?

**Comment by KingIthra** [comment]
Hi, well i'm very sorry. There was a conflict with the old lvcharts, so it worked perfectly after I removed it's references which i was not aware of at the time. thanks for the response. Highly appreciated

**Comment by beto-rodriguez** [comment]
what do you mean with hard? please let me know the error message

**Comment by KingIthra** [comment]
Task task = new Task(new Action(() =>
            {
                ObservableCollection<FinancialPoint> values = new ObservableCollection<FinancialPoint>();

                foreach (CandlestickModel candle in candlestickList)
                {
                    FinancialPoint financialPoint = new FinancialPoint(candle.OpenTime, (double)candle.High, (double)candle.Open, (double)candle.Close, (double)candle.Low);
                    values.Add(financialPoint);

                }
                // This one is working fine
                Series = new ISeries[]
                {
                    new LineSeries<double>
                    {
                        Values = (IEnumerable<double>)values
                    }
                }


                    ;
            }));

            task.Start();

there is no error message, it just does't do anything

**Comment by KingIthra** [comment]
![image](https://user-images.githubusercontent.com/50165893/170380816-7e8045d5-9e7c-4ea1-a797-a21f9d32d44c.png)
this function is called when there is new data from the server, but the UI doesn't change at all

**Comment by KingIthra** [comment]
![image](https://user-images.githubusercontent.com/50165893/170380901-116cf3c0-fd46-4972-ae15-6d1bac64a441.png)
I even tried to do this

**Comment by KingIthra** [comment]
private void UpdateAllOnClick(object sender, RoutedEventArgs e)
        {
            var r = new Random();
 
            foreach (var point in SeriesCollection[0].Values.Cast<OhlcPoint>())
            {
                point.Open = r.Next((int) point.Low, (int) point.High);
                point.Close = r.Next((int) point.Low, (int) point.High);
            }
        }

this is an example from the first version of Live charts. now how do I do this with live charts2?

**Comment by KingIthra** [comment]
How do I update the chart with new data?

**Comment by beto-rodriguez** [comment]
Please avoid spamming a message every minute, you can find help on the automatic updates sample:

https://lvcharts.com/docs/WPF/2.0.0-beta.240/samples.lines.autoupdate

I will close this issue from now since this is not an issue with the library.
