### ISSUE TITLE
With a Dark Theme the gauge label color is not toggled accordingly.

### ISSUE THREAD

**Issue by diegobarile** [beto-rodriguez/LiveCharts2#497]
**Describe the bug**
If I apply a dark theme to one CartesianChart all axis labels changes colors correctly.
But if I apply the same theme to one PieChart/Gauge the inner value remains too dark while the dark theme is active.

**Screenshots**
![LightTheme](https://user-images.githubusercontent.com/21259529/170506833-2c10a1cb-a763-48d4-bff7-c55ac9d63863.jpg)

**Yellow arrows indicates the wrong label color.**
![DarkTheme](https://user-images.githubusercontent.com/21259529/170506841-cd85013f-05a1-40a0-8f9b-d68ce372d304.jpg)

**To Reproduce**
Setup environment:
```
BaseTheme baseTheme = CoreWindowsDictionaryClass.Instance.GetTheme ().GetBaseTheme ();

LiveCharts.Configure ( config =>
{
    config
        // registers SkiaSharp as the library backend
        // REQUIRED unless you build your own
        .AddSkiaSharp ()

        // adds the default supported types
        // OPTIONAL but highly recommend
        .AddDefaultMappers ();

    if ( baseTheme == BaseTheme.Dark )
        config.AddDarkTheme ();
    else
        config.AddLightTheme ();
} );
```

Build gauge serie:

```
public IEnumerable<ISeries> CurrentValue { get; set; }

...

CurrentValue = new GaugeBuilder ()
                .WithInnerRadius ( 60 )
                .WithBackgroundInnerRadius ( 60 )
                .WithLabelFormatter ( cp =>
                {
                    return string.Format ( CultureInfo.CurrentCulture, "{0:0.0}", cp.PrimaryValue );
                } )
                .WithLabelsPosition ( PolarLabelsPosition.ChartCenter )
                .AddValue ( _observableValue )
                .BuildSeries ();
```

**Note: currently the theme is managed by the Material Design XAML toolkit: http://materialdesigninxaml.net/**
https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/wiki/Advanced-Theming#changing-the-theme
Something like:

```
using MaterialDesignColors;
using MaterialDesignThemes.Wpf;
...
var paletteHelper = new PaletteHelper();
//Retrieve the app's existing theme
ITheme theme = paletteHelper.GetTheme();

//Change the base theme to Dark
theme.SetBaseTheme(Theme.Dark);
//or theme.SetBaseTheme(Theme.Light);
```

**Expected behavior**
The Gauge value color must switch to bright with the dark theme.

**Desktop (please complete the following information):**
PC Core i7.
OS: Edition Windows 10 Pro, Version 21H2
OS build 19044.1706
Experience Windows Feature Experience Pack 120.2212.4170.0

**Comment by beto-rodriguez** [comment]
Thanks for the report!

It is fixed with the referenced commit an will be included in the next release of the library.
