### ISSUE TITLE
Geared Package

### ISSUE THREAD

**Issue by BananaFritters** [beto-rodriguez/LiveCharts2#5]
Will there be a Geared Package or similiar performance approach for LiveCharts2?

**Comment by beto-rodriguez** [comment]
Yes, and if you own v0 geared package you have a free upgrade to the v2 WPF high performance package.

**Comment by STichelaar** [comment]
Will the livechart site ever be functional? 

Right now there is now way for a paying customer to access the site login or even worse add licenses to my developers!!

**Comment by beto-rodriguez** [comment]
@STichelaar the team license has an issue righr now, but I am helping wny one one who mails to supoort@lvcharts.net with thre process, feel free to mail to support if you or your customers require assistance.

And yes the site is beeing updated also

**Comment by LabuzzMichal** [comment]
@beto-rodriguez  Does buying geared package v1 right now also legalise me for free upgrade to v2 :) ?

**Comment by beto-rodriguez** [comment]
Yes the update will be free

**Comment by danrayson** [comment]
Can we close the "issues" that have been answered/resolved?  It looks bad :P
