### ISSUE TITLE
Lazy load data on chart scroll

### ISSUE THREAD

**Issue by dmfdv** [beto-rodriguez/LiveCharts2#50]
Is there are a possibility to "lazy load" data on bar/column chart scroll? If no, it would be very nice to have for big amount of positions to be visualized or some instruction how this can be done. 

Sorry if this is already implemented. You can then remove this question/feature request. 

Here is an example (not really a lazy loading, just to show an idea):

![9161EF38-AB3C-4206-BA1A-F8B618F23D5F](https://user-images.githubusercontent.com/84660220/120358794-92d09100-c30f-11eb-95ef-db3181329b32.GIF)

**Comment by beto-rodriguez** [comment]
Hi

Is this enough?

https://github.com/beto-rodriguez/LiveCharts2/blob/master/docs/1.overview/1.7.axes.md#maxlimit-and-minlimit-properties

You can play with `MaxLimit` and `MinLimit` to achieve that

**Comment by beto-rodriguez** [comment]
I am closing this issue for now, feel free to open new one.
