### ISSUE TITLE
Blazor Sample Require wasm-tools, after installing it, it cannot build

### ISSUE THREAD

**Issue by JawadJaber** [beto-rodriguez/LiveCharts2#500]
**Describe the bug**
I cloned the repo, and tried to run BlazorSample. Visual Studio displayed this message

To build this project, the following workloads must be installed: wasm-tools
To install these workloads, run the following command: dotnet workload restore

Similarly, I added LiveChartsCore.SkiaSharpView.Blazor nuget to another project and same message is displayed.

I have installed the webassembly work load already, and
I tried also to run 'dotnet workload restore' and it failed.

Would you recommend a suitable solution?

**Comment by Asyvix** [comment]
install WebAssemblyBuildTools in VisualStudioInstaller

**Comment by JawadJaber** [comment]
I have installed WebAssemblyBuildTools in VisualStudioInstaller and did not succeed by only installing it
I have found and resolved the issue, after you install the WebAssemblyBuildTools, you have to run this command 
`dotnet workload install wasm-tools`
and follow the necessary steps as per the following doc
[https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-workload-install](url)
