### ISSUE TITLE
Chart breaks with consecutive null values

### ISSUE THREAD

**Issue by finict** [beto-rodriguez/LiveCharts2#502]
**Describe the bug**
Chart breaks with consecutive null values

**To Reproduce**
Assign consecutive null values to values
```cs
public ISeries[] Series { get; set; } = new ISeries[]
        {
            new LineSeries<double?>
            {
                Name = "1(works)",
                Values = new List<double?> { 2, -4, 4, 5, 3, 4, 6, 2, 6, 4 },
                Fill = null,
                GeometrySize = 1,
                LineSmoothness = 0
            },
            new LineSeries<double?>
            {
                Name = "2(works)",
                Values = new List<double?> { 1, -5, null, 4, 2, 3, 5, 1, 5, 3 },
                Fill = null,
                GeometrySize = 1,
                LineSmoothness = 0
            },
            new LineSeries<double?>
            {
                Name = "3(broken)",
                Values = new List<double?> { 0, -6, 2, 3, 1, null, null, 0, 4, 2 },
                Fill = null,
                GeometrySize = 1,
                LineSmoothness = 0
            },
            new LineSeries<double?>
            {
                Name = "4(works)",
                Values = new List<double?> { -1, -7, null, 2, null, 1, null, -1, 3, 1 },
                Fill = null,
                GeometrySize = 1,
                LineSmoothness = 0
            }
        };
```

**Expected behavior**
Draw by skipping all null values
![bug](https://user-images.githubusercontent.com/16084632/171065916-930be379-6469-462e-9350-b4f592b87b46.png)

**Screenshots**
![bug](https://user-images.githubusercontent.com/16084632/171065687-c9d54fbf-7210-4078-9f1a-0c3fe35e3671.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 19044.1706
 - Browser Not relevant
 - Version 2.0.0-beta.240 from nuget LiveChartsCore.SkiaSharpView.WPF

**Additional context**
The reference does not mention consecutive null values
https://lvcharts.com/docs/WPF/2.0.0-beta.240/samples.general.nullPoints

**Comment by beto-rodriguez** [comment]
Nice catch! notice that what caused this issue is when the first element of a "segment" is null, if you only place a null instance at the first position then it will also fail, but when you place 3 null together it works.  

This is now fixed with the referenced commit and will be included in the next release of the library, thanks for the report!
