### ISSUE TITLE
Chart doesn't appear

### ISSUE THREAD

**Issue by Coolava** [beto-rodriguez/LiveCharts2#509]
**Describe the bug**
I tried [installation-and-first-chart](https://lvcharts.com/docs/WPF/2.0.0-beta.240/Overview.Installation#installation-and-first-chart)
I can build example code.
But I can't see any chart, just display empty white space.
When i hover mouse on example app, series value is appear.
![image](https://user-images.githubusercontent.com/45839935/171784557-78b82be1-1d58-48ad-872e-f0e2486cda51.png)

And resizing window, x/y axis also appear
![image](https://user-images.githubusercontent.com/45839935/171784708-a5ed15b8-9c7b-44f6-9bf3-7e47246c1a30.png)

**To Reproduce**
1. Build & run Application
2. resize window

**Desktop (please complete the following information):**
 - OS: Windows 10 21H2
 - Visual studio 2022 
 - .NET 6.0 
 - WPF

Source Code
[Git repo](https://github.com/Coolava/LiveChart2Example.git)

**Comment by beto-rodriguez** [comment]
Strange, it works for me when I run your repo.

**Comment by Coolava** [comment]
I found solution. 
I'm working on laptop. There is 2 graphic card. 
Internal : Intel Xe Graphics
External : Nvidia MX450

Default is using internal graphic card.
In Nvidia Control Center, it was set to Auto by default. (Maybe using Internal)
I changed 'High performance NVIDIA processor'

And Problem solved.

**Comment by sertitto** [comment]
Hello,
I'm facing the same issue on my laptop, but my laptop has only the integrated GPU Intel Iris XE

**Comment by Sarex69** [comment]
Same problem.
The application works perfectly on different desktops,
but on one in particular it has the same problem.
Just resize the window with the mouse and the axes and series appear.
Also doesn't work Zoom X which works fine on other desktops. 
Legend and Tooltip always appear correctly.
The computer is new:
Windows 10 PRO
21H2 Build 19044
I5-11400 CPU
Integrated UHD730 GPU

**Comment by mmab123** [comment]
Hi,

I'm facing the same problem. Series doesn't appear until I resize the app. 

I am using prism with its content region manager (and navigation) and the chart is inside an usercontrol that is inside a region.

I have an integrated Intel UHD Graphics and also a Nvidia RTX 2060 but even forcing to use the last, the issue persists.

**Comment by sertitto** [comment]
Hi, I'm also using Prism in my application...but the same application that runs on another PC (with an older gpu) displays correctly the chart...so I would exclude Prism from the possible causes of the issue

**Comment by beto-rodriguez** [comment]
I will close this for now since this issue seems that is not related with the library, I will keep an eye on this.

**Comment by sigmarsson** [comment]
@mmab123 , have you solved this ? your stack is akin to my application. For navigation , do you utilize ```Frame``` ? 
@beto-rodriguez  , [I am not sure. in my ```Frame``` navigating to a ```Page```](https://github.com/microsoft/microsoft-ui-xaml/discussions/7414) , every control is displayed but the chart. Perhaps it isn't the chart but a lib the chart depends on.

**Comment by beto-rodriguez** [comment]
I will take a look to your project @sigmarsson , thanks for the `.zip`, not sure if it is related with this issue.

**Comment by mmab123** [comment]
I forgot to answer to muy post! I am so sorry.
 My problem was that the chart was inside a container, in fact they were 2, a grid and a border.  Removing the border and placing the chart directly in the grid solved the issue.
