### ISSUE TITLE
Error adding chart to winform:

### ISSUE THREAD

**Issue by Albert634515** [beto-rodriguez/LiveCharts2#51]
I created a new Winforms project with .net 5

Added nuget package LiveChartsCore.SkiaSharpView.WinForms, version 2.0.0-beta.14
When trying to add a cartesian chart from the toolbox I get the errror:
Microsoft.DotNet.DesignTools.Client.DesignToolsServerException: Constructor on type 'LiveChartsCore.KiaSharpView.Winforms.CartesianChart' not found.

Adding a default legend or motion canvas is possible.
Adding a pie chart gives the same error.

This is in the designer of VS2019

![image](https://user-images.githubusercontent.com/85439711/120923081-e0148000-c6cc-11eb-8c0d-422e8bbfca69.png)

**Comment by beto-rodriguez** [comment]
This should be fixed now with https://github.com/beto-rodriguez/LiveCharts2/commit/fe61cfaeb77f1bb7234a2b2e3f5151dc2327dba8

**Comment by Albert634515** [comment]
Yes, thank you it now works
