### ISSUE TITLE
The axis autoscale is broken when a null point exist

### ISSUE THREAD

**Issue by zylalx1** [beto-rodriguez/LiveCharts2#515]
**Describe the bug**
Seems like the last null point fix in the beta.300 is not perfect. A hidden (0,0) point will still be included in the series when a null point exist, and that caused the autoscale on both X and Y axes working incorrectly. 

**To Reproduce**
ISeries[] chartSeries = new ISeries[]
{
new LineSeries<ObservablePoint>
{
Name = "The original series",
Values = new ObservablePoint[]
{
new ObservablePoint { X = 2, Y = 5 },
new ObservablePoint { X = 3, Y = 3 },
new ObservablePoint { X = 5, Y = 7 },
new ObservablePoint { X = 6, Y = 4 },
new ObservablePoint { X = 8, Y = 6 },
},
Fill = null
}

**Expected behavior**
The 3rd column in the screenshot. 

**Screenshots**
![bug](https://user-images.githubusercontent.com/17636174/172216690-3419cd41-3687-404b-8f5f-f5d2747f6916.png)

**Comment by beto-rodriguez** [comment]
Thanks for the detailed report, this is already fixed with the referenced commit and will be included in the next version of the library.
