### ISSUE TITLE
With animations enabled scatter chart crashes when resizing while adding a lot of points WPF

### ISSUE THREAD

**Issue by nadim-241** [beto-rodriguez/LiveCharts2#517]
**Describe the bug**
When you are adding points to a cartesian scatter series, and resize the chart a lot, the chart will crash with an InvalidOperationException if the number of displayed points exceeds around 2-300.

**To Reproduce**
ON WPF:
Create a Scatter Series and add ObservablePoints to the ObservableCollection of its values, once around 300 points are added, rezise the window as fast as possible.

**Expected behavior**
The application will crash with the following Exception thrown:

`System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at LiveChartsCore.Kernel.Providers.DataFactory`2.Fetch(ISeries`1 series, IChart chart)+MoveNext()
   at LiveChartsCore.ScatterSeries`4.Measure(Chart`1 chart)
   at LiveChartsCore.CartesianChart`1.Measure()
   at `LiveChartsCore.Chart`1.<UpdateThrottlerUnlocked>b__144_1()`

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 2.0.0-beta.300

**Additional context**
A temporary fix I have discovered is to set the AnimationSpeed of the chart to 0 in XAML, and as of yet this bug is yet to occur.
UPDATE: All this does is cause it to crash later around 350 points. If i do not resize the window I can reach thousands of points with no issues.

I imagine it is some issue with collection synchronization when points are being added from a thread?

**Comment by beto-rodriguez** [comment]
Hi an thanks for the report!

How are you adding the point? this seems a threading related issue.

**Comment by beto-rodriguez** [comment]
Maybe I misunderstood the issue, are you adding a point and at the same time you are resizing the window? or you are just resizing the window?

**Comment by nadim-241** [comment]
My model subscribes to an event which is raised in a thread elsewhere. The eventargs contain a List of pairs of int values, and I create an observable point from one of these pairs and pass it to a method called AddPoint() in my viewmodel, this adds the point to the ObservableCollection which the ScatterSeries uses for its values.

**Comment by nadim-241** [comment]
The data is being added while the window is being resized.

**Comment by nadim-241** [comment]
On reading again, I think I have discovered it's a mistake on my part, I did not realise that version 2 had a SyncContext for the chart, currently seeing if this makes any difference.

**Comment by beto-rodriguez** [comment]
Nice then this is a threading issue, glad you find it, for future readers you can find a solution for this problem [here](https://github.com/beto-rodriguez/LiveCharts2/issues/225#issuecomment-1012488255).

Note:
I wanted to point the article about it in the web site but it is not uploaded yet, I noted that an will upload it in the next review to the site.

**Comment by nadim-241** [comment]
Thanks! Glad it was a simple fix on my part.
