### ISSUE TITLE
X axis labels in tooltips

### ISSUE THREAD

**Issue by korneliuscode** [beto-rodriguez/LiveCharts2#519]
V1 had the X axis label in the tooltip as headline by default. V2 does not show that, so that the user always has to recheck the hovered X position.

It would be great to bring this back (optionally). I was not even able to add this by creating a custom template :(

**Comment by rteuteu55** [comment]
@korneliuscode I think you are looking for the "TooltipLabelFormatter" to add for each of your Series

```
new ColumnSeries<DateTimePoint>
{
TooltipLabelFormatter = (chartPoint) =>
$"{new DateTime((long) chartPoint.SecondaryValue):MMMM dd}: {chartPoint.PrimaryValue}",
```

From [https://github.com/beto-rodriguez/LiveCharts2/blob/88679eb0794d79f01f04f2308add3e2253e65167/samples/ViewModelsSamples/Axes/DateTimeScaled/ViewModel.cs](url)

**Comment by korneliuscode** [comment]
Thanks @rteuteu55, but not quite what I'm looking for. 
I use a ColumnSeries<decimal> and use "Labels" on the XAxis. Also there might be several Series for the same Label, so it would be great to have one unified headline above the tooltip like in the old version.
Here an image how it looked:
<img width="308" alt="image" src="https://github.com/beto-rodriguez/LiveCharts2/assets/7031553/31cb12de-07f5-4210-8409-f9f5de40f57e">
