### ISSUE TITLE
[WPF] Calling Clear method on underlying empty Series Values change axes limits

### ISSUE THREAD

**Issue by LabuzzMichal** [beto-rodriguez/LiveCharts2#52]
**Describe the bug**
Calling Clear method on empty ObservableCollection bounded to Values property change axes limits

**To Reproduce**

1. Define CartesianChart in xaml
`        
<lvc:CartesianChart ZoomMode="None"  XAxes="{Binding XAxes}" YAxes="{Binding YAxes}" Series="{Binding Series}"  />
`
2. Define Series, YAxes and XAxes
```

            Values = new ObservableCollection<double> { 5, 6, 7, 8, 5, 6, 7, 8 };
            Series = new ObservableCollection<ISeries>
            {
                new ColumnSeries<double>
                {

                    Values = Values,
                }
            };
            YAxes = new List<Axis>
            {
                new Axis
                {
                    IsVisible = true,
                    MaxLimit = 20,
                    MinLimit = 0,
                    ShowSeparatorLines = false,

                }
            };

            XAxes  = new List<Axis>
            {
                new Axis
                {
                    IsVisible = true,
                    MaxLimit = 10,
                    ShowSeparatorLines = false,
                }
            };
```

3. Define method allowing you to clear series underlying collection

```
        public void ClearValues()
        {
            Values.Clear();
        }
```

4. Run application. Column series with defined values should be visible
![image](https://user-images.githubusercontent.com/17740334/120989263-a2246400-c77f-11eb-8cea-7e645ec4e916.png)

5. Call ClearValues method several times. With every next Clear the axis change limits even though no data is available

![image](https://user-images.githubusercontent.com/17740334/120989531-f0396780-c77f-11eb-935d-1c1ee2ef755a.png)

**Expected behavior**
Axis limits shouldn't change if collection didnt change

**Desktop (please complete the following information):**
 - OS: Windows 10PRO
 - Version: Beta14 WPF

**Comment by beto-rodriguez** [comment]
The referenced commit fixes this, it should also help to get a better behavior for #46, now series are smarter to report its bounds when they do not change or they have an invalid state.

This fix will be included since `v2.0.0-beta.17`
