### ISSUE TITLE
CartesianChart DateTimePoint drawn bug with 1 LineSeries has 1 value

### ISSUE THREAD

**Issue by philn0401** [beto-rodriguez/LiveCharts2#522]
**Describe the bug**
When adding 2 LineSeries<DateTimePoint> to a CartesianChart with 1 LineSeries only has 1 value, the chart is displayed incorrectly

**To Reproduce**
Use below code in ViewModel:
```
        public ISeries[] Series { get; set; }
            = new ISeries[]
            {
            new LineSeries<DateTimePoint>
            {
                Values = new DateTimePoint[] { new DateTimePoint(DateTime.ParseExact("2022-06-11 01:00:00", "yyyy-MM-dd HH:mm:ss", null), 10)}
            },
            new LineSeries<DateTimePoint>
            {
                Values = new DateTimePoint[] { new DateTimePoint(DateTime.ParseExact("2022-06-11 00:00:00", "yyyy-MM-dd HH:mm:ss", null), 5),  
                              new DateTimePoint(DateTime.ParseExact("2022-06-11 02:00:00", "yyyy-MM-dd HH:mm:ss", null), 15)}
            }

            };
```

**Expected behavior**
The chart should be drawn correctly

**Screenshots**
![Screenshot 2022-06-12 105526](https://user-images.githubusercontent.com/106651917/173209819-2592ba57-4e84-4b69-af9c-bacc76491bde.png)

**Desktop (please complete the following information):**
 - OS: Windows 10/11

**Comment by beto-rodriguez** [comment]
Hi and thanks for the report!

What is the X axis showing? is it not showing?

**Comment by philn0401** [comment]
Hi @beto-rodriguez 

X-Axis is showing. 
![Screenshot 2022-06-12 105526](https://user-images.githubusercontent.com/106651917/173210585-6f8812cf-60e0-4e29-9f4a-2d34c99b9406.png)

**Comment by beto-rodriguez** [comment]
Could you please try to format the axis and set the unit with?

https://lvcharts.com/docs/WPF/2.0.0-beta.240/samples.axes.dateTimeScaled

I just noticed that this article is not listed on the latest docs

**Comment by philn0401** [comment]
@beto-rodriguez:
The x-axis value is wrong
ViewModel:
```
    public class ViewModel
    {
        public ISeries[] Series { get; set; } = new ISeries[]
        {
            new LineSeries<DateTimePoint>
            {
                Values = new DateTimePoint[] { new DateTimePoint(DateTime.ParseExact("2022-06-11 01:00:00", "yyyy-MM-dd HH:mm:ss", null), 10)}
            },
            new LineSeries<DateTimePoint>
            {
                Values = new DateTimePoint[] { new DateTimePoint(DateTime.ParseExact("2022-06-11 00:00:00", "yyyy-MM-dd HH:mm:ss", null), 5),
                                                                   new DateTimePoint(DateTime.ParseExact("2022-06-11 02:00:00", "yyyy-MM-dd HH:mm:ss", null), 15)}
            }
        };

        public Axis[] XAxes { get; set; } =
        {
            new Axis
            {
                Labeler = value => new DateTime((long) value).ToString("yyyy-MM-dd HH:mm"),
                LabelsRotation = 15,
                UnitWidth = TimeSpan.FromHours(1).Ticks,
                MinStep = TimeSpan.FromHours(1).Ticks
            }
        };
    }
```
Chart:
![123](https://user-images.githubusercontent.com/106651917/173211018-65c57290-542b-4724-8560-48bdec97b7f8.png)

However, if I add 1 datapoint to the first LineSeries:
ViewModel:
```
    public class ViewModel
    {
        public ISeries[] Series { get; set; } = new ISeries[]
        {
            new LineSeries<DateTimePoint>
            {
                Values = new DateTimePoint[] { new DateTimePoint(DateTime.ParseExact("2022-06-11 01:00:00", "yyyy-MM-dd HH:mm:ss", null), 10),
                                                                   new DateTimePoint(DateTime.ParseExact("2022-06-11 03:00:00", "yyyy-MM-dd HH:mm:ss", null), 20)}
            },
            new LineSeries<DateTimePoint>
            {
                Values = new DateTimePoint[] { new DateTimePoint(DateTime.ParseExact("2022-06-11 00:00:00", "yyyy-MM-dd HH:mm:ss", null), 5),
                                                                   new DateTimePoint(DateTime.ParseExact("2022-06-11 02:00:00", "yyyy-MM-dd HH:mm:ss", null), 15)}
            }
        };

        public Axis[] XAxes { get; set; } =
        {
            new Axis
            {
                Labeler = value => new DateTime((long) value).ToString("yyyy-MM-dd HH:mm"),
                LabelsRotation = 15,
                UnitWidth = TimeSpan.FromHours(1).Ticks,
                MinStep = TimeSpan.FromHours(1).Ticks
            }
        };
    }
```

The chart is drawn correctly 
![456](https://user-images.githubusercontent.com/106651917/173211048-6b251285-16bf-4430-a469-57c6c3ff6632.png)

**Comment by beto-rodriguez** [comment]
Thanks for the update, I will check this up.

**Comment by beto-rodriguez** [comment]
Thanks for the report, this is already fixed with the referenced commit and will be included in the next version of the library.

**Comment by TravyDale** [comment]
I am seeing the same x-axis labels on version 2.0.0-beta.701 when using DateTimePoints with TimeSpan.FromHours(1) for my UnitWidth & MinStep. Has this fix been deployed out in updates since last year? 

All of my DataTimePoint time values are at an exact hour (no minutes/seconds at all). I am seeing my labels show very weird times. They actually match up very close to what his are on his error image. I expected them to just show 

![image](https://user-images.githubusercontent.com/5438512/234705234-0cfba650-0aad-4ec9-8dd4-6f5d5fc8e2c0.png)
