### ISSUE TITLE
Animation Bug on PieChart, when InnerRadius is set

### ISSUE THREAD

**Issue by Dennis-Scheurer** [beto-rodriguez/LiveCharts2#525]
**Describe the bug**
When hovering over a PieSeries the animation makes it looking weird.

**To Reproduce**
1. Create a PieChart
2. Set InnerRadius Value to 50
3. Hover over PieSeries

**Expected behavior**
Clean Animation

**Screenshots**
Normal:
![image](https://user-images.githubusercontent.com/87133882/173531364-01da3e46-d428-4ff8-88b4-3c304692fb3b.png)

When hovering over
<img width="220" alt="image" src="https://user-images.githubusercontent.com/87133882/173531251-9354c27b-cef7-4044-8b64-06497fae6e08.png">

**Comment by SCLD-JMcCoard** [comment]
Confirmed, I have to use "Hidden" to disable it for now. Would like to see this fixed.
![image](https://user-images.githubusercontent.com/70153610/183462730-bf2ab359-c270-46ae-a8b7-200464f9993b.png)

**Comment by beto-rodriguez** [comment]
Thanks for the report!

This should be already fixed with the referenced commit and it will be included since the next version of the library.
