### ISSUE TITLE
Performance in Maui Android

### ISSUE THREAD

**Issue by pijnappel** [beto-rodriguez/LiveCharts2#527]
I am trying to display a chart in my Maui Android App. 
It contains a pretty simple LineSeries with 8000 points. It takes about half height, full width of the screen.
I want to navigate in the chart unsing panning and zooming gestures.

After Updating the ViewModel the rendering takes about 4 seconds. 
Panning and zooming is unusable. Any visible change to the chart happens seconds after.

Are there any recommendation to improve the performance? Thankful for every hint.

**Comment by beto-rodriguez** [comment]
Hi and thanks for the issue.

The library will provide a high performance package, but it is not ready now.

I will close this for now, you can find more information about it at #486
