### ISSUE TITLE
New setting : DisplayLegend in series

### ISSUE THREAD

**Issue by JeanPhilippeLux** [beto-rodriguez/LiveCharts2#529]
Hi,

firt of all, thank you for your works. I just wondering if you can add a settings in series, like "DisplayLegend", to set a boolean on each serie to say if legend has to be displayed on the chart for this serie.

On some charts, I have 3 series but I need to display the legend for only 2 of the 3.

Thank you.

**Comment by beto-rodriguez** [comment]
Interesting, this will be added definitively.

Thanks for the report!

**Comment by beto-rodriguez** [comment]
This will now be supported with the next release of the library, thanks again for the report.

`series.IsVisibleAtLegend = false;`

**Comment by JeanPhilippeLux** [comment]
Thank you very much :).
