### ISSUE TITLE
blazor wasm can‘t publish

### ISSUE THREAD

**Issue by WhyILoveSpringRoll** [beto-rodriguez/LiveCharts2#531]
![微信截图_20220619150700](https://user-images.githubusercontent.com/14737143/174469896-5ce82fa0-0bb0-4841-a9dd-8382c34ccbb6.png)

**Comment by WhyILoveSpringRoll** [comment]
only  2.0.0-beta.80 version can publish succees

**Comment by WhyILoveSpringRoll** [comment]
i know how to resolve it.
you need install all this package.

1.LiveChartsCore.SkiaSharpView
2.LiveChartsCore.SkiaSharpView.Blazor
3.Microsoft.AspNetCore.Components.Web
4.SkiaSharp.Views.Blazor

then u can publish successfully

**Comment by beto-rodriguez** [comment]
Thanks for the report, I will close this for now since it has a workaround and it seems that this issue does not belong to this library, probably a VS or NuGet issue.
