### ISSUE TITLE
legend class =>，container class =>，Show abnormal

### ISSUE THREAD

**Issue by WhyILoveSpringRoll** [beto-rodriguez/LiveCharts2#535]
![微信截图_20220621155925](https://user-images.githubusercontent.com/14737143/174747705-fa5702fa-a652-4f0c-b8d2-ab55c439a109.png)

**Comment by WhyILoveSpringRoll** [comment]
blazor wasm

**Comment by WhyILoveSpringRoll** [comment]
blazor wasm

**Comment by WhyILoveSpringRoll** [comment]
version beta300

**Comment by beto-rodriguez** [comment]
mmm I missed that so bad, thanks for the report, it is fixed with the referenced commit and it will be included in the next version of the library.

**Comment by WhyILoveSpringRoll** [comment]
thanks so much
