### ISSUE TITLE
Save chart as image using .net core

### ISSUE THREAD

**Issue by andapex-mavel** [beto-rodriguez/LiveCharts2#537]
I need to generate chart image on server side. Framework: .NET Core 5.0. I expected that chart will be drawn with legend and data labels. Image contains only chart (without legend and data labels).

1. Go to VS
2. Create Asp .Net core web app and add LiveChartCore and LiveChartCore.SkiaSharpView
3. Use code below:     

```
        public string GetPieChartImagePath(string folderPath)
        {
            var data = new Dictionary<string, int> { { "one", 1 }, { "two", 2 } };
            var fileName = $"{Guid.NewGuid()}.png";
            var filePath = Path.Combine(folderPath, fileName);

            var chart = new SKPieChart
            {
                Width = 1200,
                Height = 600,
                LegendPosition = LegendPosition.Right,
                LegendOrientation = LegendOrientation.Vertical,
                
                Series = data .Select(
                    _ => new PieSeries<int> { Name = _.Key, Values = new[] { _.Value }, DataLabelsPosition = PolarLabelsPosition.Middle }),
            };
            chart.SaveImage(filePath);
            return filePath;
        }
```

**Expected behavior**
Chart will be drawn with legend

**Screenshots**
![29b51362-26f7-40a4-b499-87bc5c0b92fc](https://user-images.githubusercontent.com/107987376/174977713-e2c3a074-2376-4279-a521-215047755eee.png)

**Comment by beto-rodriguez** [comment]
Hi and thanks for the report.

For now legends are drawn using platform specific code, I will close this issue for now, you can find more information about it at #144.
