### ISSUE TITLE
PolarChart/PolarAxis can't set a Max Value 

### ISSUE THREAD

**Issue by kikipoulet** [beto-rodriguez/LiveCharts2#540]
**Describe the bug**

I can't find a way to set a Max Value in the PolarChart/PolarAxis.

**Expected behavior**
To set a max value of 100 to visualize percentage even if all the values are below. 
I wantto put a Max Value of 100, so if all the value oin the polarchart are 50 then the area would take 50% of the polarchart

**Comment by beto-rodriguez** [comment]
Hi and thanks for the report.

You need to set the `MaxLimit` property:

```c#
public PolarAxis[] RadialAxes { get; set; } =
    {
        new PolarAxis
        {
            LabelsAngle = -60,
            MaxLimit = 30 // null to let the chart autoscale (defualt is null) // mark
        }
    };```

This sample was missing and it will be included in the next same of the docs.
