### ISSUE TITLE
CandlesticksSeries Chart - eliminate missing points from chart

### ISSUE THREAD

**Issue by lullo73** [beto-rodriguez/LiveCharts2#544]
Is there a way to add an attribute to eliminate from chart missing points value?
If in the graph I have 01-Jan val1, 03-Jan val2, 04-Jan val3, is it possible to eliminate from the chart the 02-Jan hole and so on?
I mean just showing available value points

**Comment by lullo73** [comment]
![GapGrafico](https://user-images.githubusercontent.com/39082989/177823216-f49cc930-b2ac-469a-9d93-82251bdcac1d.JPG)

**Comment by beto-rodriguez** [comment]
The problem is that there is some math involved in that, how do we we scale an axis without those holes?

I think that the best in your case is to use a custom point, where the x axis uses the position of the element in the data collection instead of the date time value.

**Comment by lullo73** [comment]
That could be perfect, but I need to see the date labels instead of points 1, 2, 3,.......

**Comment by beto-rodriguez** [comment]
For that you can use a custom set of labels https://lvcharts.com/docs/WPF/2.0.0-beta.300/samples.axes.labelsFormat.

**Comment by lullo73** [comment]
Another problem I have is: in the way you suggest I cannot use candlestick. Is it right?

**Comment by beto-rodriguez** [comment]
Yeah it is not supported by default, I think I will add an article about that in the docs.

But this is the idea:

``` c#
public partial class ViewModel
{
    public ISeries[] Series { get; set; } =
    {
        new CandlesticksSeries<CustomFinancialPoint>
        {
            Values = new CustomFinancialPoint[]
            {
                new() { O = 10, H = 12, L = 8, C = 11  },
                new() { O = 11, H = 13, L = 9, C = 12  },
                new() { O = 12, H = 14, L = 10, C = 13  },
            },
            Mapping = (customPoint, chartPoint) =>
            {
                chartPoint.PrimaryValue = customPoint.H;
                chartPoint.SecondaryValue = chartPoint.Context.Index; // <-- this should make the trick
                chartPoint.TertiaryValue = customPoint.O;
                chartPoint.QuaternaryValue = customPoint.C;
                chartPoint.QuinaryValue = customPoint.L;
            }
        }
    };

    public Axis[] X { get; } =
    {
        new Axis
        {
            Labels = new [] { "day 1", "day 2", "day 3" }
        }
    };
}

public class CustomFinancialPoint
{
    public int O { get; set; }
    public int H { get; set; }
    public int L { get; set; }
    public int C { get; set; }
}
```

**Comment by lullo73** [comment]
![Prova Grafico](https://user-images.githubusercontent.com/39082989/178787824-884896bc-c7fc-4a75-9903-75bf69eaf7c2.JPG)

**Comment by lullo73** [comment]
Now it looks like it works :)
