### ISSUE TITLE
Is there a way to force the max and min range, like it use to be in LiveCharts?

### ISSUE THREAD

**Issue by azhali** [beto-rodriguez/LiveCharts2#55]
Hi, 
I have been using LiveCharts and trying to move to v2. 
One problem I have is, I have a RowSeries chart with multiple series. I need to set Max and Min Range on it so that when values change and chart is updated, it doesn't adjusts the X or Y Axis, I want it to stay static just the bars to animate and redraw based on the new values. Values can range from -10 to 10 and I don't want to see decimal points.
Anyway that is possible?

regards
azhar

**Comment by beto-rodriguez** [comment]
Hi, yes it is possible:

https://github.com/beto-rodriguez/LiveCharts2/blob/master/docs/1.overview/1.7.axes.md#maxlimit-and-minlimit-properties

**Comment by azhali** [comment]
thanks. thats solved the issue.
