### ISSUE TITLE
Buy a Lvchart Licence not possible

### ISSUE THREAD

**Issue by jhamecher** [beto-rodriguez/LiveCharts2#551]
I try since some weeks to buy a licence.

**To Reproduce**
1. Go to https://lvcharts.com/invoice/shop
2. Click on LiveCharts Premium +ADD
3. Scroll down to "Licence Agreement" - Check Checkbox 
4. Click on "ACEPT AND CONTINUE"
5. Click on "ACEPT AND CONTINUE TO PAYMENT"
6. On the "Please select a payment method." - click on "Debit or Credit Card"
7. See error:

Something strage happened 😕

There was an error calling the PayPal API, the payment was not processed, this is an error from our side, sorry 😞.

Please try again, if the error persists feel free to contact [support@lvcharts.net](mailto:support@lvchart.net?subject=Help!).

**Expected behavior**
I should be able to pay on PayPal.

**Screenshots**
![lvchart_payment_error](https://user-images.githubusercontent.com/4974366/178755163-a0ce35df-1584-4d49-8fbd-d900ef79da8c.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox or Chrome
 - Version: up to date versions

**Comment by beto-rodriguez** [comment]
Thanks for your interest.

V2 is not on sell at this point, actually that link is not public 😄, I really appreciate your interest but this is not on sale at this point.

**Comment by beto-rodriguez** [comment]
I will close this for now, thanks for the issue and the interest I hope soon we can provide extra services for the library.

**Comment by jhamecher** [comment]
Hello Alberto, thank you for the answer. I have send you an eMail with a list of things we need and and offer. Please check if you have received the mail. Thank you!

**Comment by beto-rodriguez** [comment]
I answered your email.
