### ISSUE TITLE
[Blazor WASM] Canvas/`Cartesian Chart is ignoring height of parent container.

### ISSUE THREAD

**Issue by Carmondai** [beto-rodriguez/LiveCharts2#552]
As the title states, in Blazor when defining a height it is ignored and instead calculated at about half of the width.
Definition in the Razor Component:
`<div style="width: 100%;height: 900px">
        <CartesianChart Series="series" XAxes="xAxes"/>
    </div>`
The Page is looking like this:
![Site](https://user-images.githubusercontent.com/6135310/178997144-33aefb33-3c3c-450f-b013-b8d9bcd429d6.PNG)
If you need more info don't hesitate to message me.

**Comment by beto-rodriguez** [comment]
Hi and thanks for the issue.

I think this is related to the <h1> tag I forgot to delete in a previous release:

![image](https://user-images.githubusercontent.com/10853349/179239672-9638e6d2-7435-4a07-9933-c89423264def.png)

Probably this will be gone in the next release since that tag is removed already.

**Comment by Carmondai** [comment]
Tested it with Beta 330 nand observed the same issue as seen in the attached screenshot.
![Chart](https://user-images.githubusercontent.com/6135310/179465995-706b8604-236a-4190-9b9e-71285c6f0f5f.PNG)

**Comment by Carmondai** [comment]
@beto-rodriguez Any update?

**Comment by bbo76** [comment]
I have the same problem in v350, it doesn't take the parent dimension

**Comment by beto-rodriguez** [comment]
Sorry about the late response, this should be fixed now with the referenced commit and will be included in the next version of the library.
