### ISSUE TITLE
Can't execute WASM mode in Uno Platform.

### ISSUE THREAD

**Issue by wuweisin** [beto-rodriguez/LiveCharts2#554]
In Uno Platform with WASM mode，
use this package: LiveChartsCore.SkiaSharpView.Uno.WinUI 2.0.0-beta.330

it will show this error: System.Exception: Failed to generate AOT layout (More details are available in diagnostics mode or using the MSBuild /bl switch)
![wasm_error](https://user-images.githubusercontent.com/45276164/179454397-d37b5cd2-945f-4902-8a15-e6c5edc7d7b4.png)

My visual studio version is : Microsoft Visual Studio Professional 2022 Preview 17.3.0 Preview 3.0 
Uno template version is : 4.4.13.8

Thank for your help!

**Comment by beto-rodriguez** [comment]
I am not able to reproduce this issue.

The sample in this repo uses Uno.WinUI 4.5, can you upgrade to this version and verify if the issue is gone?

**Comment by wuweisin** [comment]
Dear @beto-rodriguez :

After uses Uno.WinUI 4.5, the erros is the same...

My installed pakage is shown in the image, could you show your package configuration?
![螢幕擷取畫面 2022-07-28 125736](https://user-images.githubusercontent.com/45276164/181424110-8a7eea65-4549-4a50-ab47-0790eec033c1.png)

Thanks a lot!

**Comment by wuweisin** [comment]
Dear @beto-rodriguez :
I found the problem is due to I can't GIT clone the https://github.com/emscripten-core/emsdk/ ,

After solve the GIT connection problem, the WASM mode is running sucessful!

Thank for your help!
