### ISSUE TITLE
MAUI: Unable to view chart

### ISSUE THREAD

**Issue by sattasundar** [beto-rodriguez/LiveCharts2#559]
I have added prerelease version of LiveChartsCore.SkiaSharpView.Maui nuget into Maui project. But while running on android emulator, i am unable to see chart control. It's not throwing any error as well.

Here,  I am attaching the solution file.
[MauiCharts.zip](https://github.com/beto-rodriguez/LiveCharts2/files/9173502/MauiCharts.zip)

![Screenshot_1658570104](https://user-images.githubusercontent.com/62828724/180600360-ca5f7dc1-9fde-4f25-89de-3b8551f72d08.png)

**Comment by sattasundar** [comment]
Sorry!, It's fixed. There was a minor issue happened from my side.
Thanks :)

**Comment by tongvietdung** [comment]
@sattasundar Hi, what was your issue and how did you fix it? I have the same problem.

**Comment by Gloryorb1** [comment]
@sattasundar hello I would also like to know what the issue was  and how did you fix it as I have a similar problem but cant determine if its the same or not so I'm just trying different solutions.
Even though this is an old post any direction of how you found the solution would be nice
