### ISSUE TITLE
DataLabels do not get updated/removed

### ISSUE THREAD

**Issue by cheilmann** [beto-rodriguez/LiveCharts2#56]
**Describe the bug**
When displaying datalabels and the series changes, the old datalabels won't disappear.

**To Reproduce**
1. Go to ViewModelsSamples.Pies.AutoUpdate.ViewModel class
2. Replaces series definition in constructor with 
Series = new ObservableCollection<ISeries>
            {
                new PieSeries<ObservableValue> { Values = new[] { new ObservableValue(2) }, DataLabelsPosition = LiveChartsCore.Measure.PolarLabelsPosition.Start , DataLabelsPaint = new SolidColorPaintTask(new SKColor(45, 45, 45)), },
                new PieSeries<ObservableValue> { Values = new[] { new ObservableValue(5) }, DataLabelsPosition = LiveChartsCore.Measure.PolarLabelsPosition.Start , DataLabelsPaint = new SolidColorPaintTask(new SKColor(45, 45, 45)), },
                new PieSeries<ObservableValue> { Values = new[] { new ObservableValue(3) }, DataLabelsPosition = LiveChartsCore.Measure.PolarLabelsPosition.Start , DataLabelsPaint = new SolidColorPaintTask(new SKColor(45, 45, 45)), },
                new PieSeries<ObservableValue> { Values = new[] { new ObservableValue(7) }, DataLabelsPosition = LiveChartsCore.Measure.PolarLabelsPosition.Start , DataLabelsPaint = new SolidColorPaintTask(new SKColor(45, 45, 45)), },
                new PieSeries<ObservableValue> { Values = new[] { new ObservableValue(4) }, DataLabelsPosition = LiveChartsCore.Measure.PolarLabelsPosition.Start , DataLabelsPaint = new SolidColorPaintTask(new SKColor(45, 45, 45)), },
                new PieSeries<ObservableValue> { Values = new[] { new ObservableValue(3) }, DataLabelsPosition = LiveChartsCore.Measure.PolarLabelsPosition.Start , DataLabelsPaint = new SolidColorPaintTask(new SKColor(45, 45, 45)), }
            };
3. Go to method AddSeries and replace Series.Add(...) with
Series.Add(
                new PieSeries<ObservableValue> { Values = new[] { new ObservableValue(random.Next(1, 10)) }, DataLabelsPosition = LiveChartsCore.Measure.PolarLabelsPosition.Start, DataLabelsPaint = new SolidColorPaintTask(new SKColor(45, 45, 45)), });
4. Run the WPF sample app -> Pies / AutoUpdate
5. Click on "Constant changes"

**Expected behavior**
The datalabels for the series added / changed should adjust to current value, position, disappear, etc.

**Screenshots**
Start
![grafik](https://user-images.githubusercontent.com/50573990/121518239-8a9fe200-c9f0-11eb-9da4-46e4a1c4b6e7.png)

After "constant changes"
![grafik](https://user-images.githubusercontent.com/50573990/121518319-a4412980-c9f0-11eb-9772-f5d853b75c65.png)

**Desktop (please complete the following information):**
 - OS: Win 10 Pro

**Additional context**
This is also true for bar series.

**Comment by azhali** [comment]
Hi, 

I am having the same issue as described above. Any chance this can be fixed?

**Comment by beto-rodriguez** [comment]
Fixed with the referenced commit this issue was present in all the series, should be gone now.

The fix is included since `2.0.0-beta.17`
