### ISSUE TITLE
CartesianChart axis fails to update after form was hidden

### ISSUE THREAD

**Issue by Fiahblade** [beto-rodriguez/LiveCharts2#562]
**Describe the bug**
CartesianChart fails to update properly after its form is displayed from a hidden state.

**To Reproduce**
I've created a demo application that showcases this behaviour: [CartesianChartScale.zip](https://github.com/beto-rodriguez/LiveCharts2/files/9197463/CartesianChartScale.zip)

1. Launch app
2. Change form size (everything works as expected)
3. Hide it to tray by clicking the button
4. Click on the green tray icon to restore form
5. Change form size (scaling fails)

**Screenshots**
Working:
![works](https://user-images.githubusercontent.com/2144509/181224115-124ce833-a4ae-4ac4-8987-7b115b346249.gif)

Broken:
![broken](https://user-images.githubusercontent.com/2144509/181224153-0346b702-5b3b-408b-8775-c4efb1169a1c.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10 21H2
 - LiveChartsCore.SkiaSharpView.WinForms 2.0.0-beta.330

**Additional context**
Other chart types weren't tested and might be affected too.
Winforms .NET 6

Thanks for maintaining LiveCharts, I'm happy to further help resolve this issue.

**Comment by Fiahblade** [comment]
After disabling the animations:
`cartesianChart1.EasingFunction = null;`

It might be hard to spot in the gif but it seems like the animation is making it worse, masquerading the real problem.
![better](https://user-images.githubusercontent.com/2144509/181355705-53ea0664-6b95-458b-bd77-3750dfef2d1e.gif)

**Comment by ajayre** [comment]
It seems the easing function also causes the x-axis and y-axis values to randomly disappear and they won't come back unless the application is restarted. This is when "scrolling" data by removing the oldest data point and adding the newest.

**Comment by beto-rodriguez** [comment]
Sorry about the late response, and thanks for the report and the sample.

This should be fixed with the referenced commit and will be included in the next version of the library.

@ajayre I think I also fixed that issue #556  and #555.

Please feel free to re-open this issue or reply to let me know if the issue persists, I will close this for now.
