### ISSUE TITLE
Incorrect namespaces for Uno WinUI packages

### ISSUE THREAD

**Issue by nickrandolph** [beto-rodriguez/LiveCharts2#568]
**Describe the bug**
The namespace for controls within the Uno-WinUI specific packages includes both Uno and WinUI. These should be dropped to make controls more discoverable and allow for consistent documentation

**To Reproduce**
1. Create new Uno application based on the [dotnet new 'unoapp' template](https://www.nuget.org/packages/Uno.ProjectTemplates.Dotnet) - this creates a Uno app that uses WinUI and targets net6
2. Add package references to https://www.nuget.org/packages/LiveChartsCore.SkiaSharpView.Uno.WinUI
3. Attempt to add a control by first adding xml namespace eg LiveChartsCore.SkiaSharpView. This namespace isn't discoverable since actual namespace required is LiveChartsCore.SkiaSharpView.Uno.WinUI

**Expected behavior**
It would be good for the xml namespace to be just "LiveCharts", rather than having to specify SkiaSharpView, Uno and WinUI

**Screenshots**
![image](https://user-images.githubusercontent.com/1614057/182005683-1102ad71-036f-44a1-a969-515a3151bdb3.png)

**Comment by beto-rodriguez** [comment]
Thanks for the issue and sorry for the late response.

Yes I agree the name could be shorter, it seems unnecessarily long that namespace for the library.

My idea with those namespaces is to keep the library detached from SkiaSharp, ([explained here](https://lvcharts.com/docs/WPF/2.0.0-beta.330/Overview.How%20it%20works)).

For now the library uses SkiaSharp to render the charts in any platform, but theoretically it should not be hard to build to consume `LiveChartsCore` from GDI+ or Maui Graphics for example.

**Comment by beto-rodriguez** [comment]
I will close this for now due Inactivity, let me know if there is any update on this.
