### ISSUE TITLE
Wrong layout in WinForms

### ISSUE THREAD

**Issue by ClubberLangG** [beto-rodriguez/LiveCharts2#57]
**Describe the bug**
When starting the sample, with the "Axes/DateTimeScaled", the set of dates are not displayed.
It works with WPF... but not with WinForms

**To Reproduce**
Start the WinForms sample and choose "Axes/DateTimeScaled"

**Screenshots**

![image](https://user-images.githubusercontent.com/67060390/121599469-5f92ae00-ca43-11eb-910c-b79dbad99e9d.png)

**Comment by ClubberLangG** [comment]
Noticed we do not see the horizontal axis

**Comment by ClubberLangG** [comment]
in the file src\skiasharp\LiveChartsCore.SkiaSharp.WinForms\Chart.cs, line 90.

Replace ResumeLayout(false) with ResumeLayout(true); !

**Comment by ClubberLangG** [comment]
Also, remove this:

AutoScaleDimensions = new SizeF(7F, 15F);
AutoScaleMode = AutoScaleMode.Font;

**Comment by Albert634515** [comment]
I have noticed the same behavior, but only if I set my screen to scale 125%.
Setting the axis position at AxisPosition.End (at the top), does make them visible.

**Comment by ClubberLangG** [comment]
Indeed, AxisPosition.End (at the top) make them visible, but it is harder to read the data this way. I really wish a way to display it on bottom :-(

**Comment by beto-rodriguez** [comment]
The issue should be fixed now with the previous commit, but I also see the issue @Albert634515 mentioned when an axis in the X axis has the `End` position.

**Comment by beto-rodriguez** [comment]
I will reopen this issue to track the issue mentioned above:

> I have noticed the same behavior, but only if I set my screen to scale 125%.
> Setting the axis position at AxisPosition.End (at the top), does make them visible.

**Comment by beto-rodriguez** [comment]
I am closing this issue, this issue seems to be gone in the current version of the library.
