### ISSUE TITLE
StackedRowSeries if all Values > 0  first Series hiding

### ISSUE THREAD

**Issue by SergeyVink** [beto-rodriguez/LiveCharts2#571]
**Describe the bug**
If we are set **Values > 1000**/  first Serie hids.
and if all StackedRowSeries.**Values  > 0** first Serie hids.

if  first StackedRowSeries have **Values<0** its good
**in 101 not hav problem**

**To Reproduce**
1.  in *\LiveCharts2\samples\ViewModelsSamples\StackedBars\Basic\ViewModel.cs  set 
     `using System.Collections.Generic;
      using CommunityToolkit.Mvvm.ComponentModel;
      using LiveChartsCore;
      using LiveChartsCore.Measure;
      using LiveChartsCore.SkiaSharpView;
      using LiveChartsCore.SkiaSharpView.Painting;
      using SkiaSharp;
      
      namespace ViewModelsSamples.StackedBars.Basic;
      
      [ObservableObject]
      public partial class ViewModel
      {
          public List<StackedRowSeries<int>> Series { get; set; } = new()
          {
              new StackedRowSeries<int>
              {
                  Values = new List<int> { 3000 },
                  Stroke = null,
                  DataLabelsPaint = new SolidColorPaint(new SKColor(45, 45, 45)),
                  DataLabelsSize = 14,
                  DataLabelsPosition = DataLabelsPosition.Middle
              },
              new StackedRowSeries<int>
              {
                  Values = new List<int> { 4000},
                  Stroke = null,
                  DataLabelsPaint = new SolidColorPaint(new SKColor(45, 45, 45)),
                  DataLabelsSize = 14,
                  DataLabelsPosition = DataLabelsPosition.Middle
              },
              new StackedRowSeries<int>
              {
                  Values = new List<int> { 2000},
                  Stroke = null,
                  DataLabelsPaint = new SolidColorPaint(new SKColor(45, 45, 45)),
                  DataLabelsSize = 14,
                  DataLabelsPosition = DataLabelsPosition.Middle
              }
          };
      }`
2. Bild
3. Open StackedBars\Basic in AvaloniaSamples

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/15277092/182828652-cf1fe26c-c6ca-4080-a975-da2327f15a90.png)

Desktop win10 .net6

**Comment by beto-rodriguez** [comment]
Hi and thanks for the report.

I am not sure about this one, the library auto scales the view so all the data is inside the plot, in this case the library decided to show the X axis from 3,000 to 9,000, this decision is not wrong.

Maybe for this specific case it seems wrong, but in my experience the behavior the library has now is a good default behavior.

Maybe in your case you need to force the limits of the axis so it always starts on 0.

```
axis.MinLimit = 0; // <- forces the axis to start on 0.
```

**Comment by SergeyVink** [comment]
> Maybe in your case you need to force the limits of the axis so it always starts on 0



> Maybe in your case you need to force the limits of the axis so it always starts on 0.
> 
> ```
> axis.MinLimit = 0; // <- forces the axis to start on 0.
> ```

Thanks! It works.
