### ISSUE TITLE
Text rendering not working in alpine docker container

### ISSUE THREAD

**Issue by Alumniminium** [beto-rodriguez/LiveCharts2#574]
**Describe the bug**
Text does not render inside a mcr.microsoft.com/dotnet/runtime:7.0-alpine container

**To Reproduce**
create a console application
dockerize it
save any graph as image from inside the docker container and it will not draw any text.

**Additional context**
.NET 7
LiveChartsCore.SkiaSharpView Version 2.0.0-beta.330
SkiaSharp.NativeAssets.Linux.NoDependencies Version 2.88.1-preview.91

**Comment by Alumniminium** [comment]
RUN apk add terminus-font ttf-inconsolata ttf-dejavu font-noto font-noto-cjk ttf-font-awesome font-noto-extra fontconfig
RUN fc-cache -f

that made text appear but the font is fucky, no idea how to override fonts, also my container is now >300mb

**Comment by beto-rodriguez** [comment]
Thanks for the report.

Adding the font to fix the issue makes sense, I have seen this issue also on other SkiaSharp dependent libraries, like this case: https://github.com/QuestPDF/QuestPDF/issues/31

**Comment by beto-rodriguez** [comment]
Closing this issue since there is not much we can do here.
