### ISSUE TITLE
EnableNullSplitting=false not working

### ISSUE THREAD

**Issue by scastria** [beto-rodriguez/LiveCharts2#578]
**Describe the bug**
My understanding is that when EnableNullSplitting=true, gaps in a LineSeries are made for null values.  That part works.  However, when EnableNullSplitting=false, I expect the point before the null and the point after the null to be connected to each other.  So, in other words, the LineSeries is connected across the null gap.  That is not working.  The null values are treated as 0 for a series of int? or as Jan 1 of year 0000 for a series of DateTimePoints.

**To Reproduce**
Use a LineSeries of:
```
series.Add(new LineSeries<int?>
{
    Values = new List<int?>
    {
        3,6,null,5,3,null,8,6
    },
    Fill = null,
    LineSmoothness = 0,
    GeometrySize = 1,
    EnableNullSplitting = false
});
```

**Expected behavior**
I expect value 6 to be connected to value 5 for the first null gap and value 3 to be connected to value 8 for the second null gap.

**Screenshots**

![Screen Shot 2022-08-10 at 12 25 20 AM](https://user-images.githubusercontent.com/4534494/183822377-b16be4a6-e182-411f-9b2a-8734260e516a.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - LiveCharts: 2.0.0-beta.330

**Additional context**

**Comment by beto-rodriguez** [comment]
Hi and thanks for the report!

This is now fixed with the referenced commit and will be included since the next version of the library.
