### ISSUE TITLE
Is it possible to produce Angular Gauge with v2?

### ISSUE THREAD

**Issue by azhali** [beto-rodriguez/LiveCharts2#58]
Is it possible to produce this example from v1 with v2?

https://lvcharts.net/App/examples/v1/Wpf/Angular%20Gauge

I need to it to go from -10 to 10
-10 to 0 needs to red 
0 to 10 needs to be green and arrow to show where the value is and showing labels with step size as 1

Any help to get that working would be great.

**Comment by azhali** [comment]
Please if you can advise on this, that would be great.

**Comment by beto-rodriguez** [comment]
It is not supported by now.

**Comment by azhali** [comment]
Ok thank you

**Comment by PatriQ94** [comment]
Is there perhaps any plans to support this? :) If not, is there a way to make colorful sections on the current gauges?

**Comment by CasperH2O** [comment]
Making great usage of LiveCharts v0 line and gauge in our open source application, we have an interactive configuration page for setting motion steering controls: https://www.youtube.com/watch?v=uTpIWsacB_M&t=3s

Would love to be able to upgrade to v2 when gauges are supported!

**Comment by beto-rodriguez** [comment]
This was finally implemented in #1158 and will be included in the next version of the library:

https://github.com/beto-rodriguez/LiveCharts2/blob/master/samples/WPFSample/Pies/AngularGauge/View.xaml
https://github.com/beto-rodriguez/LiveCharts2/blob/master/samples/ViewModelsSamples/Pies/AngularGauge/ViewModel.cs

**Comment by CasperH2O** [comment]
Thank you @beto-rodriguez ❤️

**Comment by beto-rodriguez** [comment]
This is now supported in beta.920, the docs in the website willbe updated soon.
