### ISSUE TITLE
Hidden axis breaks scaling

### ISSUE THREAD

**Issue by AsriFox** [beto-rodriguez/LiveCharts2#580]
**Describe the bug**
Applying `IsVisible = false` to an axis constructor makes the chart shrink.

**To Reproduce**
1. Create a ViewModel binding for axes:
```
public class ViewModel
{
	public Axis[] InvisibleAxis { get; set; } = new Axis[] {
		new Axis() { IsVisible = false }
	};
}
```
2. Create a CartesianChart in XAML:
```
<ContentView.BindingContext>
	<local:ViewModel />
</ContentView.BindingContext>

<lvc:CartesianChart
	x:Name="SoundChart"
	XAxes="{Binding InvisibleAxis}"
	YAxes="{Binding InvisibleAxis}"
	EasingFunction="{x:Null}"
	TooltipPosition="Hidden" />
```
3. Add a LineSeries:
```
SoundChart.Series = new ISeries[] {
		new LineSeries<double> {
			Values = new double[] { 0.0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0 },
			DataPadding = new LiveChartsCore.Drawing.LvcPoint(0, 0),
			Stroke = new SolidColorPaint(SkiaSharp.SKColors.Blue) { StrokeThickness = 1 },
			GeometryStroke = null,
			GeometryFill = null,
			Fill = null,
		}
	};
```
4. Run the app.

**Expected behavior**
The series should expand to control's bounds by default.

**Screenshots**
Expected result:
![AxisMadness_0](https://user-images.githubusercontent.com/91423563/184386208-e0fcaafc-82c9-4f83-8d06-40b94710f8b0.png)
Actual result:
![AxisMadness_1](https://user-images.githubusercontent.com/91423563/184386222-23ccc273-c897-4064-80e9-ac15551929a3.png)

**Desktop:**
 - OS: Windows 10
 - net6.0-windows10.0.19041.0
 - Microsoft.Windows.SDK.BuildTools (10.0.22000.194)
 - Microsoft.MAUI (6.0.486)
 - LiveChartsCore.SkiaSharpView.Maui (2.0.0-beta.350)

**Additional context**
I was able to achieve the correct result by setting visibility at runtime instead of a binding.

Changed XAML:
```
<lvc:CartesianChart
	x:Name="SoundChart"
	EasingFunction="{x:Null}"
	TooltipPosition="Hidden" />
```

Added to the view's constructor:
```
SoundChart.XAxes.First().IsVisible = false;
SoundChart.YAxes.First().IsVisible = false;
```

It's possible that the problem lies within `new Axis() { ... }`.

**Comment by beto-rodriguez** [comment]
Thanks for the report and the code!

Maybe this needs some docs, but the issue here is that you are sharing the same instance for the `X` and `Y` axes, just try to use a different instance, it will work fine, at least it worked for me.

Maybe this needs to be documented.

But for now just try:

```c#
public class ViewModel
{
	public Axis[] InvisibleAxisX { get; set; } = new Axis[] {
		new Axis() { IsVisible = false }
	};

        public Axis[] InvisibleAxisY { get; set; } = new Axis[] {
		new Axis() { IsVisible = false }
	};
}
```

```xml
<lvc:CartesianChart
    XAxes="{Binding InvisibleAxisX}"
    YAxes="{Binding InvisibleAxisY}" />
```

And it will work!
