### ISSUE TITLE
Legend cropped when series name is long

### ISSUE THREAD

**Issue by blackboxjt** [beto-rodriguez/LiveCharts2#582]
**Describe the bug**
Experience in PieChart, when series name is long, the legend cannot display the full width of text.
On v2.0.0 Beta.350 WinForm

**To Reproduce**
Try sample code below:
`
chartReviewPie.Series = Nothing
chartReviewPie.AutoSizeMode = AutoSizeMode.GrowAndShrink
chartReviewPie.LegendPosition = LegendPosition.Right

Dim pieSeries As New List(Of LiveChartsCore.ISeries)
Dim x = New With {.Name = "Project (ISO) - Documentation", .Value = 10}
Dim y = New With {.Name = "Admin (Team/Staff Meeting)", .Value = 2}
Dim z = New With {.Name = "Product (Internal Tools) - Enhancement", .Value = 6}
Dim xList As Object() = {x, y, z}

Dim abc As ISeries = New PieSeries(Of Double)
For Each obj As Object In xList
    pieSeries.Add(
        New PieSeries(Of Double) With {
            .Name = obj.Name,
            .Values = New List(Of Double) From {
                obj.Value
            },
            .DataLabelsPaint = New SolidColorPaint(SKColors.Black),
            .DataLabelsSize = 18,
            .DataLabelsPosition = LiveChartsCore.Measure.PolarLabelsPosition.Outer,
            .DataLabelsFormatter = Function(Point As Kernel.ChartPoint)
                                                    Return $"{Math.Round((Point.StackedValue.Share) * 100, 2)}% [ {Point.PrimaryValue.ToString("N2")} hrs]"
                                               End Function,
            .TooltipLabelFormatter = Function(Point As Kernel.ChartPoint)
                                                     Return $"{Point.Context.Series.Name} : {Math.Round((Point.StackedValue.Share) * 100, 2)}% [ {Point.PrimaryValue.ToString("N2")} hrs]"
                                                 End Function,
            .MaxOuterRadius = 0.5   'control if radius of circle use the canvas fully (0 to 1)
        }
    )
Next
chartReviewPie.Series = pieSeries
`

**Expected behavior**
Able to see the legend displayed without cropping of text

**Screenshots**
![image](https://user-images.githubusercontent.com/10876063/184617872-0a69b35a-a45d-4d26-9b50-3ad9cdf73d43.png)

**Comment by blackboxjt** [comment]
![image](https://user-images.githubusercontent.com/10876063/184618217-cfe44405-f9e0-4c36-9e6b-600dd87761a5.png)
Example when showing tooltip for full length of series name

**Comment by blackboxjt** [comment]
![image](https://user-images.githubusercontent.com/10876063/184830680-c96b6607-a77c-4a30-83a9-62ad243d3f70.png)
When the Legend Position is at the bottom, it also got cropped...

**Comment by beto-rodriguez** [comment]
Thanks for the issue!

This needs some time to get fixed.

**Comment by beto-rodriguez** [comment]
This is now fixed with https://github.com/beto-rodriguez/LiveCharts2/pull/768 and will be included in the next version of the library.
