### ISSUE TITLE
how design like these ?

### ISSUE THREAD

**Issue by lonelyxmas** [beto-rodriguez/LiveCharts2#585]
<lvc:CartesianChart
                                Grid.Row="2"
                                Margin="10,0,10,20"
                                DataTooltip="{x:Null}"
                                Hoverable="False">
                                <lvc:CartesianChart.Series>
                                    <lvc:LineSeries Stroke="White" Values="5,9,8,6,1,5,7,3,6,3" />
                                </lvc:CartesianChart.Series>
                            </lvc:CartesianChart>

**Comment by beto-rodriguez** [comment]
Hi

This is not supported for now, `v0` used a converter to map this syntax to a `ChartValues` instance.
