### ISSUE TITLE
Add theming docs or the included preview's theme styles

### ISSUE THREAD

**Issue by ymg2006** [beto-rodriguez/LiveCharts2#589]
Hello and thank you for this great Chart & Plot library.
I wanted to make an Avalonia app but based on modified styles I face some problems.
Without a button command, it is not changing the theme. For instance, Imagine a user component with a chart and a button, when a user clicks it executes the code below:
```
LiveCharts.Configure(settings => settings
  .AddDefaultMappers()
  .AddSkiaSharp()
  .AddDarkTheme());
```
for dark theme and 
```
LiveCharts.Configure(settings => settings
  .AddDefaultMappers()
  .AddSkiaSharp()
  .AddLightTheme());
```
for setting the dark theme.
The problem arises when these commands are being called by events (delegates) which are set to raise when the application theme is changed but they are not taking effect.
Another problem is that even the button command does not change the text color on the labels. So it would be nice if you include a theming and styling guide on the website or the included preview's theme styles and a how to set them with events.
I appreciate you.

**Comment by beto-rodriguez** [comment]
This will be added with the backers package, the web site article will be updated when ready.

**Comment by seikosantana** [comment]
Hi, I tried invoking the configure to AddDarkTheme on button click, but existing charts doest seem to react. Is it not meant to be used after the startup?
