### ISSUE TITLE
[Feature request] StepLine Series

### ISSUE THREAD

**Issue by LabuzzMichal** [beto-rodriguez/LiveCharts2#59]
Hi, is  LiveCharts2 going to support StepLine Series? I dont see it in a roadmap.
I would love to help with implementation if you are busy with more important stuff

**Comment by beto-rodriguez** [comment]
The idea is that v2 will have all the features v0 did. 

I would be happy to merge your PR if you build the step line series 😄, yesterday I just added the heat series, you can find an example in the commits I did yesterday.

**Comment by LabuzzMichal** [comment]
Ok great, then give me few days and we will see if I can be helpfull at all

**Comment by LabuzzMichal** [comment]
PR created: https://github.com/beto-rodriguez/LiveCharts2/pull/61
Please take a look once you have some time :)
