### ISSUE TITLE
Avalonia - 11.0.0-preview1

### ISSUE THREAD

**Issue by HobbesKo** [beto-rodriguez/LiveCharts2#593]
LiveCharts v2.0.0-beta.361 does not work with Avalonia-11.0.0-preview1 due to the following error:

`Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'Avalonia.Visuals, Version:0.10.0.0.`

Avalonia breaking changes are listed [here](https://github.com/AvaloniaUI/Avalonia/wiki/Breaking-Changes), one of which is `Avalonia.Visuals` being merged into `Avalonia.Base`.

Is there anything I can do to overcome the problem or do I need to wait for LiveCharts2 to become compatible with the latest Avalonia version?

**Comment by chenzanyu** [comment]
I had the same problem after updating Avalonia to the latest version

**Comment by beto-rodriguez** [comment]
Thanks for the update on the Avalonia new preview.

Now there is a branch that works in the newest Avalonia package.

https://github.com/beto-rodriguez/LiveCharts2/tree/avalonia-preview

I am not sure how to release this as a NuGet package, maybe for now the only alternative is to clone this repo and reference this branch in your project, let's wait for the Avalonia team to release a GA version.

**Comment by HobbesKo** [comment]
Thank you for the Avalonia-Preview branch.
All I have to do now is work out how to do what you suggested 🙂

**Comment by beto-rodriguez** [comment]
> I take it that it is actually not possible to publish a NuGet package for a preview release of an app?

It is just that I do not know how to name the version for this branch, `2.0.0-beta.400-preview.11` maybe?

**Comment by HobbesKo** [comment]
`2.0.0-beta.400-preview.11` seems appropriate. 😄 

However, if publishing a Nuget package just for this branch is going to cause issues, then I can wait.

**Comment by hahagu** [comment]
@beto-rodriguez
Should we be expecting a nuget package soon, or is the pull req. still in works?
Thanks.

**Comment by beto-rodriguez** [comment]
@hahagu it is published now.

The [11.0.0-preview1](https://www.nuget.org/packages/LiveChartsCore.SkiaSharpView.Avalonia/2.0.0-beta.500-11.0.0-preview1) package is for the Avalonia 11 preview, while the [2.0.0-beta.500](https://www.nuget.org/packages/LiveChartsCore.SkiaSharpView.Avalonia/2.0.0-beta.500) is for the GA version.

![image](https://user-images.githubusercontent.com/10853349/194463507-7c0d8024-c396-4d34-a86f-f7342303b09d.png)

I will keep this issue open, so others know what to do.

**Comment by hahagu** [comment]
@beto-rodriguez 
Thanks!

**Comment by HobbesKo** [comment]
Oh, cool, I have my charts back 😄 
Nice one. Thank you 👍
