### ISSUE TITLE
LiveChartsGeared activator not working

### ISSUE THREAD

**Issue by DerekLukas** [beto-rodriguez/LiveCharts2#60]
I am trying to activate my license in order to work with the WPF Geared package. My company purchased the 5 seat license pack and I am the only one so far to have problems when I try to get a valid activation key. To give some background I had previously activated a Geared trial when I was evaluating the software to see if we wanted to purchase it. 

The steps that I am taking to activate the license are: 
-Follow the invite link sent from the purchase account.
-Sign in and download the activator.
-Run the activator and it brings up a webpage that tells me that my code is invalid. There is no information as to why, the page just tells me to try again.
-Attempting to troubleshoot the problem I try copying the part of the URL that looks like a key (xxxx-xxxx...) and pasting it into the activator console. 
-I then try a similar thing with the invite code URL. Neither of these attempts work.

The other 2 people on my team had no issues activating their licenses when following these steps, one of them (like me) had previously activated a Geared trial before activating their license.

OS: Win10 pro
Version: 21H1
Build: 19043.1052
Browser: Mozilla FireFox 89.0

**Comment by beto-rodriguez** [comment]
Thank you so much for supporting the library!

I am sorry about that issue, please mail your private key to support@lvcharts.com, you will get your activation code there.

Here is the guide to activate your license:

https://lvcharts.net/licensing/howto

You will get instructions and help in that mail.

Sorry for that!

**Comment by DerekLukas** [comment]
Yes I've received your email, thank you!
