### ISSUE TITLE
Legend blinking under some conditions

### ISSUE THREAD

**Issue by pvalobra** [beto-rodriguez/LiveCharts2#601]
Hello,
Thank you for the nice library. I observed the following bug.

**Describe the bug**
The legend keeps blinking when in horizontal mode (Bottom or Top) if one of the series uses the property IsVisibleAtLegend false.

**To Reproduce**

1. Create a new WPF project.
2. Install LivechartsCoreSkiaSharpView.WPF (2.0.0-beta.361)
3. Create a very simple chart with 2 or more series.
4. Make one series IsVisibleAtLegend = false,
5. Set LegendPosition at Bottom or Top
6. Observe for a few seconds that the legend text and geometry are blinking
7. Set LegendPosition at Left or Right
8. Observe no blinking occurs

**Expected behavior**
Expect no blinking in all situation.

**Environment:**
 - OS: Windows
 - Net Core 6.0
 - WPF
 - LivechartsCoreSkiaSharpView.WPF (2.0.0-beta.361)

Thank you

**Comment by beto-rodriguez** [comment]
Thanks for the report, this is already fixed, current version (beta.400) has a bug to show legends, but the next release fixed both issues.
