### ISSUE TITLE
BLAZOR - lvc-tooltip outside lvc-container

### ISSUE THREAD

**Issue by bbo76** [beto-rodriguez/LiveCharts2#607]
**Describe the bug**
The lvc-tooltip-container appear outside of the lvc-container. It appear on the top 0 left 0 and it's above my menu button component.

**Expected behavior**
Tooltip must be in the lvc-container and not outside. Tooltip must appear only on the first mouse hover on the chart.

**Screenshots**
![image](https://user-images.githubusercontent.com/20109987/187857707-640f5a00-e081-4a7f-a3ce-887217573f0b.png)

I fixed my problem by setting the z-index of my button but I think it will be prettier to set the top and left of the tooltip by default to the lvc-container and not 0 0

**Comment by beto-rodriguez** [comment]
Thanks for the report, now the tooltip `display` is set to `none` when it is closed.

This fix will be included in the next version of the library.
