### ISSUE TITLE
Using LiveCharts 2 on a console app or on the server side link is broken.

### ISSUE THREAD

**Issue by bairog** [beto-rodriguez/LiveCharts2#617]
[README.md](https://github.com/beto-rodriguez/LiveCharts2#readme) contains the following info: 

_You can also use LiveCharts 2 on a console app or on the server side installing only the core packages, take a look at [this guide](https://lvcharts.com/docs/Uno/latest/samples.general.chartToImage#build-an-image-in-the-server-side-or-console-app)._

Link leads to a **Not Found** page (It seems that the article you are trying to reach in not available at the moment or was removed).

**Comment by beto-rodriguez** [comment]
Thanks! I updated the link

**Comment by tvert** [comment]
The link below is still (again?) broken:
https://livecharts.dev/docs/Uno/latest/samples.general.chartToImage#build-an-image-in-the-server-side-or-console-app
