### ISSUE TITLE
Can't set image background color for SK cartesian chart in b400

### ISSUE THREAD

**Issue by SteveDesmond-ca** [beto-rodriguez/LiveCharts2#618]
**Describe the bug**
Setting the background color of a Cartesian chart no longer outputs the correct color in a PNG image generated by SkiaSharp

**To Reproduce**
1. Create a new `SKCartesianChart` with a non-zero area the `Background` color set to anything other than `SKColor.Transparent`
2. Save the chart as a PNG image file
3. View the chart image

**Observed behavior**
Chart has a transparent background

**Expected behavior**
Chart has the specified background color

**Screenshots**
b400
![hammer](https://user-images.githubusercontent.com/195896/188648634-2f9d0c4b-5ac2-454f-b3a4-fff7122e9b42.png)

b361
![hammer](https://user-images.githubusercontent.com/195896/188648481-abb61bbb-a936-4c77-a92a-2fa99734c947.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: N/A

**Additional context**
This worked fine up through b361. The commit cef279c from last week looks pretty suspicious.

**Comment by beto-rodriguez** [comment]
Thanks for the report!

fixed with the referenced commit and will be included in the next version of the library.
