### ISSUE TITLE
Add ability to set and display chart title in image file output

### ISSUE THREAD

**Issue by SteveDesmond-ca** [beto-rodriguez/LiveCharts2#619]
**Is your feature request related to a problem? Please describe.**
When outputting a cartesian chart as an image file (via SkiaSharp) there is no easy/documented way to add a title to the chart.

**Describe the solution you'd like**
As a LiveChartsCore user, I want to add a title to my `SKCartesianChart`, so that viewers of the chart have a better context for what they're looking at.

**Describe alternatives you've considered**
Per #333, I tried to look up how to access the SK context from the chart, but couldn't find anything after a search of the docs.

**Additional context**
From my perspective as a dev, I'd love to have a `Title` property on the chart, just like `Legend`, but if the `Legend` were to have a `Title`, that would also suffice.

**Comment by beto-rodriguez** [comment]
Fixed with the referenced PR and will be included in the next version.
