### ISSUE TITLE
Issue with chart labels on pan and zoom

### ISSUE THREAD

**Issue by AnkitaPadma** [beto-rodriguez/LiveCharts2#62]
I 'm facing an issue in viewing the label list properly in x-axis while using livecharts in wpf. The label list is proper, and before setting I clear the axis too.

The code used is:

EMT_Chart.AxisX.Clear();

int stepSize = 1;

Axis xAxis = new Axis()
{
FontSize = 12,
Separator = new LiveCharts.Wpf.Separator { Step = stepSize, IsEnabled = false },
ShowLabels = true,
Labels = labelList,
LabelsRotation = -90.0
};
EMT_Chart.AxisX.Add(xAxis);

And xaml is as below:

<lvc:CartesianChart x:Name="EMT_Chart"
Series="{Binding Series}"
LegendLocation="Bottom"
Zoom="XY" Pan="XY"/>

Basically on zooming out, the x-axis labels (list of string) are coming in a cyclic fashion which isnt intended. And on zooming in the value and label alignment gets messed up.

Please suggest.

This is the plot without zoom or pan

![image](https://user-images.githubusercontent.com/23658195/122391095-4b453880-cf90-11eb-8193-8950543ba123.png)

On zooming out or panning to the left the plot x-axis labels starts duplicating in a cyclic fashion only on the start and the plot too doesn't look proper

![image](https://user-images.githubusercontent.com/23658195/122391132-55673700-cf90-11eb-9c5f-d3242bfd4825.png)

On zooming in or panning the plot x-axis labels and the values are not aligned

![image](https://user-images.githubusercontent.com/23658195/122391191-60ba6280-cf90-11eb-9df9-b7db613d616f.png)

**Comment by AnkitaPadma** [comment]
@beto-rodriguez  Please help me resolve the issue

**Comment by AnkitaPadma** [comment]
@btordz Please suggest how to resolve the issue

**Comment by AnkitaPadma** [comment]
@trympet @ghost1372 @jamsoft @Kalcey Could anyone of you assist. I had posted this issue in the older git repo of livecharts too and few days back I posted here. It would be really helpful if anyone of you could help me resolve the issue.

**Comment by beto-rodriguez** [comment]
This  issue belong to `v0` I am closing this for now.

**Comment by AnkitaPadma** [comment]
@beto-rodriguez  is the issue resolved in the latest version? How can I upgrade and migrate?

**Comment by beto-rodriguez** [comment]
@AnkitaPadma There is no out of the box conversion, but it works in a similar way, there are no huge differences.

I have added multiple samples to help with the migration:

**Comment by AnkitaPadma** [comment]
@beto-rodriguez Please let me know:-
1. Is the issue reported fixed in version 2?
2. I dont find the nuget package for version 2, when I searched today?

**Comment by beto-rodriguez** [comment]
> Is the reported issue fixed in version 2?

I hope so, but if you face an issue in v2 I will be able to fix it quickly.

> I dont find the nuget package for version 2, when I searched today! But the readme says its available from Skiasharp...By when will it be available?

It is available, just ensure to check the combo "Include prereleases" 

![image](https://user-images.githubusercontent.com/10853349/124925537-27d74180-dfc2-11eb-9e4a-475d63021ce0.png)

> The version 2 is still in beta stage, right. When is the final release expected?

The API will not change drastically now, you could use the beta version now, v2 has a lot of improvements.

**Comment by AnkitaPadma** [comment]
@beto-rodriguez  Hi I installed the beta release *.32

And tried out the below code, but the graph is not visible. What am I missing?
*.xaml

<Page x:Class="Test.LVC2"
      xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
      xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
      xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" 
      xmlns:d="http://schemas.microsoft.com/expression/blend/2008" 
      xmlns:local="clr-namespace:Test"
      xmlns:lvc2="clr-namespace:LiveChartsCore.SkiaSharpView.WPF;assembly=LiveChartsCore.SkiaSharpView.WPF"
      mc:Ignorable="d" 
      d:DesignHeight="450" d:DesignWidth="800"
      Title="LVC2">

    <Grid>
        <lvc2:CartesianChart Name="LVC2_Chart" Series="{Binding Series}"></lvc2:CartesianChart>
    </Grid>
</Page>

*.xaml.cx
using LiveChartsCore;
using LiveChartsCore.SkiaSharpView;

namespace Test
{
    /// <summary>
    /// Interaction logic for LVC2.xaml
    /// </summary>
    public partial class LVC2 : Page
    {
        public IEnumerable<ISeries> Series { get; set; } = new ObservableCollection<ISeries>
        {
            new LineSeries<double>
            {
                Values = new ObservableCollection<double> { 2, 1, 3, 5, 3, 4, 6 },
                Fill = null
            }
        };

        public LVC2()
        {
            InitializeComponent();
        }
    }
}

And from main window, on tab change event,  I do the following
if (LVC2Tab.IsSelected)
                ContentFrame.NavigationService.Navigate(new LVC2());
