### ISSUE TITLE
Can't hide legends for SK cartesian chart in b400

### ISSUE THREAD

**Issue by DreamPrism** [beto-rodriguez/LiveCharts2#620]
**Describe the bug**
when property `LegendPosition` of `SKCartesianChart` is set to `LegendPosition.Hidden`, the legend still appears

**To Reproduce**
1. Create a new `SKCartesianChart` with non-zero area
3. Set `LegendPosition` to `LegendPosition.Hidden`
4. Save the chart as a PNG file

**Observed behavior**
The legend still appears

**Expected behavior**
The legend is hidden

**Screenshots**
The chart image
![cartesianChart](https://user-images.githubusercontent.com/52944979/188763232-e6d3be51-52ba-4c3b-b131-daa838ba17da.png)

**Comment by beto-rodriguez** [comment]
Thanks for the report, this issue is fixed with the referenced commit and will be included in the next version of the library.
