### ISSUE TITLE
PieSeries is not hoverable even when property IsHoverable is set to true

### ISSUE THREAD

**Issue by PeterKisTelus** [beto-rodriguez/LiveCharts2#623]
**Describe the bug**
PieSeries is not hoverable even when property IsHoverable is set to true in WinUI3 (used LiveChartsCore.SkiaSharpView.WinUI 2.0.0-beta.400)

**To Reproduce**
1. Add PieChart control into app
2. Populate it with multiple PieSeries 
3. One of the series is not hoverable

**Expected behavior**
PieSeries is hoverable if property IsHoverable is set to true

**Comment by PeterKisTelus** [comment]
It seems that this issue occurs when PieChart.InitialRotation is set to other value that 0

**Comment by beto-rodriguez** [comment]
Thanks for the report, I was able to identify and fix the issue with a229add3f31a72d96827f3827e1a0a8132bd8976.

This will be included in the next version of the library.

**Comment by PeterKisTelus** [comment]
I have tested it on LiveChartsCore.SkiaSharpView.WinUI 2.0.0-beta.514 and it is not fixed at all. When a initialRotation is set e.g. to 270, then only 2 of 7 pie series are hoverable, so it is worst than before :(

**Comment by beto-rodriguez** [comment]
Thanks for the update, I'll take a look.

**Comment by beto-rodriguez** [comment]
This is now fixed, sorry about the previous attempt 😢, this fill will be included in the next version of the library.
