### ISSUE TITLE
PieChart control disappears if populated with single PieSeries

### ISSUE THREAD

**Issue by PeterKisTelus** [beto-rodriguez/LiveCharts2#624]
**Describe the bug**
PieChart control disappears if populated with single PieSeries in WinUI3 (used LiveChartsCore.SkiaSharpView.WinUI 2.0.0-beta.400)

**To Reproduce**
1. Add PieChart control into app
2. Populate it with single PieSeries 
3. After PieChart is fully rendered, it disappears

**Expected behavior**
PieChart control is visible when populated with single PieSeries

**Comment by PeterKisTelus** [comment]
It seems that this issue occurs when PieChart.InitialRotation is set to other value that 0

**Comment by jBijsterboschNL** [comment]
I'm having this exact same issue on, at least, Android as well! Removing the custom value of InitialRotation is a working work-around, but not ideal.

**Comment by beto-rodriguez** [comment]
Thanks for the report, this is fixes with the refenced commit and will be included in the next version of the library,
