### ISSUE TITLE
Multiple issue stacked columns

### ISSUE THREAD

**Issue by Albert634515** [beto-rodriguez/LiveCharts2#625]
**Describe the bug**
- Legend not showing correctly
- In last column only one part of the stack graph is visible, there are two bars bottom bar totally missing
   I think this is related to issue [https://github.com/beto-rodriguez/LiveCharts2/issues/571]
- Numbers is in graph not (all) visible
- x-axis seems to have gone missing

It looks like the graph tries to create some extra space/show the top graph in more detail, because they are all in the high levels.
Except now a part of the graph is missing.
This may also the problem that the labels which should show the value in the stacked bars is not visible. These are set to middle.
I think the middle of most bars is now outside the visible area of the graph.

Is it possible to:
- Fix this incorrect behavior and still retain the bottom being cut off (zoomed in chart)
- And/or optionally prevent this behavior of zooming in?

**To Reproduce**
To reproduce, I have added to the view used

To reproduce the behavior of the incorrect legend, move the mouse over the graph bars from right to left.
The right bar consist of two sub bars. It looks like the graph is not cleanup properly because the extra legend is still visible when you move the mouse over the other stacked bars with fewer bars.

![image](https://user-images.githubusercontent.com/85439711/189478155-abb860cc-0c40-46c8-bbe4-908a52cf07cd.png)

Screenshot of missing bottom bar:
![image](https://user-images.githubusercontent.com/85439711/189478202-a9fe0e87-9f8c-43bb-9c48-caa54f713581.png)

**Desktop (please complete the following information):**
 - Windows 11
 - LiveCharts 2.0 beta 400 (was already in previous version of livecharts 2.0)

**Additional context**
`    public class ViewModelStackedColumnSeries1Year
    {
        public IEnumerable<ISeries> Series { get; set; }

        public IEnumerable<Axis> XAxes { get; set; }

        public ViewModelStackedColumnSeries1Year()
        {
            var ob2list = new ObservableCollection<ISeries>();

            var cs = new StackedColumnSeries<DateTimePoint>
            {
                Name = "Test1",
                DataLabelsSize = 20,
                DataLabelsPaint = new SolidColorPaint(SKColors.Black),
                DataLabelsPosition = LiveChartsCore.Measure.DataLabelsPosition.Middle,
                Values = new ObservableCollection<DateTimePoint>
                    {
                        new DateTimePoint
                        {
                            DateTime = new DateTime(2018, 7, 1),
                            Value = 700
                        }
                    },
                StackGroup = 1
            };
            ob2list.Add(cs);

            cs = new StackedColumnSeries<DateTimePoint>
            {
                Name = "Test1",
                DataLabelsSize = 20,
                DataLabelsPosition = LiveChartsCore.Measure.DataLabelsPosition.Middle,
                DataLabelsPaint = new SolidColorPaint(SKColors.Black),
                Values = new ObservableCollection<DateTimePoint>
                    {
                        new DateTimePoint
                        {
                            DateTime = new DateTime(2019, 7, 1),
                            Value = 1107
                        }
                    },
                StackGroup = 1
            };
            ob2list.Add(cs);

            cs = new StackedColumnSeries<DateTimePoint>
            {
                Name = "Test1",
                DataLabelsSize = 20,
                DataLabelsPaint = new SolidColorPaint(SKColors.Black),
                DataLabelsPosition = LiveChartsCore.Measure.DataLabelsPosition.Middle,
                Values = new ObservableCollection<DateTimePoint>
                    {
                        new DateTimePoint
                        {
                            DateTime = new DateTime(2020, 7, 1),
                            Value = 940
                        }
                    },
                StackGroup = 2
            };
            ob2list.Add(cs);

            cs = new StackedColumnSeries<DateTimePoint>
            {
                Name = "Test1",
                DataLabelsSize = 20,
                DataLabelsPaint = new SolidColorPaint(SKColors.Black),
                DataLabelsPosition = LiveChartsCore.Measure.DataLabelsPosition.Middle,
                Values = new ObservableCollection<DateTimePoint>
                    {
                        new DateTimePoint
                        {
                            DateTime = new DateTime(2021, 7, 1),
                            Value = 1015
                        }
                    },
                StackGroup = 2
            };
            ob2list.Add(cs);

            cs = new StackedColumnSeries<DateTimePoint>
            {
                Name = "Test1",
                DataLabelsSize = 20,
                DataLabelsPaint = new SolidColorPaint(SKColors.Black),
                DataLabelsPosition = LiveChartsCore.Measure.DataLabelsPosition.Middle,
                Values = new ObservableCollection<DateTimePoint>
                    {
                        new DateTimePoint
                        {
                            DateTime = new DateTime(2022, 7, 1),
                            Value = 624
                        }
                    },
                StackGroup = 2
            };
            ob2list.Add(cs);

            cs = new StackedColumnSeries<DateTimePoint>
            {
                Name = "Test2",
                DataLabelsSize = 20,
                DataLabelsPaint = new SolidColorPaint(SKColors.Black),
                DataLabelsPosition = LiveChartsCore.Measure.DataLabelsPosition.Middle,
                Values = new ObservableCollection<DateTimePoint>
                    {
                        new DateTimePoint
                        {
                            DateTime = new DateTime(2022, 7, 1),
                            Value = 350
                        }
                    },
                StackGroup = 2
            };
            ob2list.Add(cs);

            // Add Year axis
            Series = new System.Collections.ObjectModel.ObservableCollection<ISeries>(ob2list);
            XAxes = new List<Axis>
            {
                new Axis
                {
                    Labeler = value => new DateTime((long) value).ToString("yyyy"),
                    LabelsRotation = 15,
                    Position = AxisPosition.Start,
                    Name = "Year",
                    UnitWidth = TimeSpan.FromDays(365.25).Ticks,
                    MinStep = TimeSpan.FromDays(365.5).Ticks
                }
            };
        }
    }`

**Comment by Albert634515** [comment]
Setting the MinLimit to zero doesn't work:
![image](https://user-images.githubusercontent.com/85439711/189496799-e9ef4fbd-7556-445a-ba0f-b5f69159a102.png)

And this should not been necessary, the library should handle this.

I changed the axis like this:
`new Axis
                {
                    Labeler = value => new DateTime((long) value).ToString("yyyy"),
                    LabelsRotation = 15,
                    Position = AxisPosition.Start,
                    Name = "Year",
                    UnitWidth = TimeSpan.FromDays(365.25).Ticks,
                    MinStep = TimeSpan.FromDays(365.5).Ticks,
                    MinLimit = 0
                }`

**Comment by Albert634515** [comment]
First issue regarding the tooltip has been resolved in the latest release.

**Comment by beto-rodriguez** [comment]
Most of the issues here must be solved.

If you keep facing issues with the separators/labels you can try to set your own separators:
https://github.com/beto-rodriguez/LiveCharts2/blob/master/samples/ViewModelsSamples/Axes/CustomSeparatorsInterval/ViewModel.cs
