### ISSUE TITLE
Error bar series in x- and y-direction

### ISSUE THREAD

**Issue by Crown0815** [beto-rodriguez/LiveCharts2#626]
**Is your feature request related to a problem? Please describe.**
We would like to utilize LiveCharts2 for a Scientific Plotting library. For scientific data, error bars are necessary to scrutinize the quality and meaningfulness of the data.

**Describe the solution you'd like**
It would be great to be able to add absolute errors as error bars to a plot. This type of requirement is typically implemented through a separate series that is laid below (or over) an existing line, scatter, or bar series. Here is an example from [Scottplot](https://scottplot.net/cookbook/4.1/category/plottable-error-bar/). 

**Describe alternatives you've considered**
A different library.

**Additional context**

- [Wikipedia - Error Bars](https://en.wikipedia.org/wiki/Error_bar)
- [Data Visualization Catalog - Error Bars](https://datavizcatalogue.com/methods/error_bars.html)

**Comment by beto-rodriguez** [comment]
This is now supported in beta.920:

https://github.com/beto-rodriguez/LiveCharts2/blob/master/samples/ViewModelsSamples/Error/Basic/ViewModel.cs
