### ISSUE TITLE
maximum zoom

### ISSUE THREAD

**Issue by Platonenkov** [beto-rodriguez/LiveCharts2#630]
how to set the maximum zoom?
so that the columns do not go far.

![image](https://user-images.githubusercontent.com/44946855/190844075-4a567263-c127-4833-85dc-cb8d19e4cec7.png)

ideally it should be like this
![image](https://user-images.githubusercontent.com/44946855/190844065-7a7004e8-6a9a-4466-bb01-77845278dbef.png)

**Comment by beto-rodriguez** [comment]
Thanks for the report. This is now fixed with the referenced commit and will be included in the next version of the library.

Axis will now have the `MinZoomDelta` property.

> Gets or sets the min zoom delta, the minimum difference between the max and min visible limits of the axis. default is null and null means that the library will calculate this value based on the current data.
