### ISSUE TITLE
Just upgraded VS2022 for Windows to 17.3.4 and LiveCharts2 Doesnt Work

### ISSUE THREAD

**Issue by danielcooper-hk** [beto-rodriguez/LiveCharts2#632]
I have a Maui LiveCharts2 project that is working fine.  Last night i updated VS2022 to 17.3.4 and today all the references to LiveChart classes were underlined in red.  I uninstalled LiveChartsCore.SkiaSharpView.Maui and tried to reinstall and now get the error NU1012. Platform version is not present for one or more target frameworks, even though they have specified a platform: net6.0-ios, net6.0-maccatalyst.

I've tried creating a new project and the same thing happens.  I've removed and reinstalled visual studio and same thing.

I am running primarily a test using windows 11 and am now stuck.  I was making some great progress and now i am totally stuck.

Any ideas what has gone wrong here?

**Comment by beto-rodriguez** [comment]
Hi

Try to restore the packages using the dotnet cli (`dotnet restore`), then try to compile your project (``dotnet build`), you will probably get a clue about what is wrong there.

**Comment by danielcooper-hk** [comment]
Thanks for such a quick reply.  It looks like the install of the latest version corrupted the maccatalyst and iOS sdk's.  maui-check failed to fix it but re-installing the latest preview version on top of the last release version fixed it.

Loving your work by the way.  The charts are amazing - adding a treemap would make this the only charting package I need!

**Comment by beto-rodriguez** [comment]
Glad to hear you fixed it!

Yeah treemaps  will be supported (not sure when) but the idea of v2 is to build a complete data visualization solution.
