### ISSUE TITLE
Install-Package LiveChartsCore.SkiaSharpView.WinForms gives error;  Install-Package : Unable to find package 'LiveChartsCore.SkiaSharpView.WinForms'

### ISSUE THREAD

**Issue by Lectere** [beto-rodriguez/LiveCharts2#633]
**Describe the bug**

Install-Package LiveChartsCore.SkiaSharpView.WinForms gives error;  Install-Package : Unable to find package 'LiveChartsCore.SkiaSharpView.WinForms'

**To Reproduce**
Follow this guide; https://lvcharts.com/docs/WinForms/2.0.0-beta.330/Overview.Installation

Install from NuGet
Now install [LiveCharts from NuGet](https://www.nuget.org/packages/LiveChartsCore.SkiaSharpView.WinForms). If you need more help to install a package from NuGet, please follow [this guide](https://docs.microsoft.com/en-us/nuget/consume-packages/install-use-packages-visual-studio).

Install-Package LiveChartsCore.SkiaSharpView.WinForms

After the package is installed you should see the LiveCharts controls in your toolbox, drag a new CartesianChart control from your toolbox to the Form1 class.

If the control does not appear in your toolbox, try to rebuild your project and look for it again.

**Expected behavior**
NuGet Package installed

**Screenshots**
PM> Install-Package LiveChartsCore.SkiaSharpView.WinForms
Install-Package : Unable to find package 'LiveChartsCore.SkiaSharpView.WinForms'
At line:1 char:1
+ Install-Package LiveChartsCore.SkiaSharpView.WinForms
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Time Elapsed: 00:00:01.2248623
PM>

**Comment by Lectere** [comment]
I found this works; 

Install-Package LiveChartsCore.SkiaSharpView.WinForms -Version 2.0.0-beta.400

**Comment by beto-rodriguez** [comment]
Nice! you could also use the `-IncludePrerelease` switch according to MS docs

**Comment by Lectere** [comment]
> Nice! you could also use the `-IncludePrerelease` switch according to MS docs

Would be nice to include a working solution in the documentation...  At the moment, when you follow the documentation, it gives an error message...
