### ISSUE TITLE
zooming .NET MAUI

### ISSUE THREAD

**Issue by Senso4sLab** [beto-rodriguez/LiveCharts2#635]
The zooming does not work when the .NET MAUI project is used. I tested on the Android platform.
I came across that this feature is not supported yet, is it true?

When the graph, the first time, is shown the tooltip does not work at first press. You have to tap on the graph a few times, then the tooltip usually shows.

**Comment by Senso4sLab** [comment]
I did some additional tests I found out that by changing MinLimit and MaxLimit values the graph is not updated. I have to double-click on the graph to force the axis to update. Is it possible programmatically force graph updating?

**Comment by beto-rodriguez** [comment]
Hi @Senso4sLab, zooming has some issues but sadly there is in our hands to fix that.

Take a look at https://github.com/dotnet/maui/issues/6553

**Comment by samosim** [comment]
Beto thanks for reply. let's start from the basics.  Please check attached images. In the first image x axes is not updated, when I just click on graph I get dates. The second problem is y axes, I do not know why steps are not linear. Third problem is not visible, but  when I click on point the tooltip does not show, I have to click  around the point and back on point.
![Screenshot_20221016_143731](https://user-images.githubusercontent.com/41702572/196037914-cfdcb1c1-9d75-4272-8852-14d4f4cb6950.jpg)
![Screenshot_20221016_143745](https://user-images.githubusercontent.com/41702572/196037916-7b4ab0dc-791c-4674-94e0-fa5d6bf07dd5.jpg)

**Comment by daltzctr** [comment]
Zooming and panning does seem to be completely broken in .NET MAUI targeting desktop/WinUI3. It seems to constantly think left-mouse is pressed, and panning does not seem to be functional at all. It "clips" back to position

**Comment by beto-rodriguez** [comment]
Zooming now works much better with a4045c633786918a2f9533bd9ba7d72637231eaf but I cannot find a way to improve zooming in desktop devices, I raised an issue to Maui:

https://github.com/dotnet/maui/issues/16130

**Comment by beto-rodriguez** [comment]
This is finally working properly on beta.950, it works on all the platforms properly, thanks for the report.
