### ISSUE TITLE
DataLabelFormatter Chinese garbled

### ISSUE THREAD

**Issue by uejar** [beto-rodriguez/LiveCharts2#636]
**Describe the bug**

PieChart's DataLabelFormatter Chinese garbled

**To Reproduce**

LiveChartsCore.SkiaSharpView.WPF  2.0.0-beta.400
```
_ReasonSeries.Add(new PieSeries<Reason>()
                        {
                            Values = new List<Reason>() { new Reason() { Name = name, Count = count, Precent = percent } },
                            Name = name,
                            DataLabelsPaint = new SolidColorPaint(SKColors.Black),
                            TooltipLabelFormatter = point => $"{point.Model.Name}, {point.PrimaryValue},{point.StackedValue?.Share:P2}",
                            DataLabelsFormatter = point => $"{point.Model.Name}, {point.PrimaryValue},{point.StackedValue?.Share:P2}",
                            DataLabelsPosition = LiveChartsCore.Measure.PolarLabelsPosition.Outer,
                            Mapping = (reason, point) =>
                            {
                                point.PrimaryValue = (float)reason.Count;
                               
                            }
                        });

```

**Expected behavior**

Data Label displays Chinese correctly

**Screenshots**

![image](https://user-images.githubusercontent.com/11648266/191645572-67cb518e-4822-4e05-8390-fd96ad2e0f33.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by uejar** [comment]
already solved
` DataLabelsPaint = new SolidColorPaint(SKColors.Black) {FontFamily= LiveChartsSkiaSharp.MatchChar('汉') },`

**Comment by beto-rodriguez** [comment]
Glad you found the solution!
