### ISSUE TITLE
Changing Axis color leave initial color visible on chart

### ISSUE THREAD

**Issue by rteuteu55** [beto-rodriguez/LiveCharts2#638]
**Describe the bug**
when an Axis color is changed the initial color of the Ticks and Subticks remain on the chart

**To Reproduce**
1. create a chart 
2. Set Axis color (Ticks and Subticks for example)
3. change color (Ticks and Subticks)

**Expected behavior**
I assume this initial color should not remain

**Screenshots**
![ColorChangeIssue](https://user-images.githubusercontent.com/1083543/191952451-e94b6079-353a-4ca9-a7a7-32b8c3fa80ed.gif)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Version [2.0.400 Beta]

**Comment by rteuteu55** [comment]
The button code in case it helps:

`private void button3_Click(object sender, EventArgs e)
        {
            SolidColorPaint colorTmp = new SolidColorPaint(colorList[random.Next(0, 14)]);
            (yAxis[0] as Axis).LabelsPaint = colorTmp;
            (yAxis[0] as Axis).TicksPaint = colorTmp;
            (yAxis[0] as Axis).SubticksPaint = colorTmp;
            (yAxis[0] as Axis).SeparatorsPaint = colorTmp;

            colorTmp = new SolidColorPaint(colorList[random.Next(0, 14)]);
            (yAxis[1] as Axis).LabelsPaint = colorTmp;
            (yAxis[1] as Axis).TicksPaint = colorTmp;
            (yAxis[1] as Axis).SubticksPaint = colorTmp;
            (yAxis[1] as Axis).SeparatorsPaint = colorTmp;

        }`

**Comment by beto-rodriguez** [comment]
Thanks for the report, this issue is fixed with the referenced commit and will be included in the next version of the library.
