### ISSUE TITLE
DrawTicksPath lost when when hiding an Axis

### ISSUE THREAD

**Issue by rteuteu55** [beto-rodriguez/LiveCharts2#639]
**Describe the bug**
DrawTicksPath is lost if the axis visibility is toggled 

**To Reproduce**
1. create a chart 
2. add an Axis with DrawTicksPath
3. toggle the Axis visibility twice

**Screenshots**
![DrawTicksPathIssue](https://user-images.githubusercontent.com/1083543/191960992-a91cc78b-3fae-4028-99d4-2a289ce41117.gif)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Version [400 Beta]

**Comment by rteuteu55** [comment]
Code of the btn if it helps:

```
        private void button2_Click(object sender, EventArgs e)
        {
            if (yAxis[0].IsVisible)
            {
                yAxis[0].IsVisible = false;
            }
            else
            {
                (yAxis[0] as Axis).DrawTicksPath = true;
                yAxis[0].IsVisible = true;
            }
        }
```

**Comment by beto-rodriguez** [comment]
Thanks for thew report, this issue is fixed with the referenced commit and will be included in the next version of the library.
