### ISSUE TITLE
Incorrect CandleSeries (and most probably others as well) due to precision loss in conversion from long to float

### ISSUE THREAD

**Issue by gegogabriel** [beto-rodriguez/LiveCharts2#64]
**Describe the bug**
Using the candleseries for displaying data with intervals smaller than ~90 minutes renders multiple candle sticks in the same position.

The reason for this is that ChartPoint uses for the SecondaryValue float. For this reason when converting the DateTime.Ticks(long) due to the precision loss the minutes are lost. (The conversion is done in LiveChartSettings.cs line 498)

**To Reproduce**
1. Go to the ViewModelsSamples -> Financial -> BasicCandleSticks 
2. Replace the existing values in the Series collection with the following:
            {
                    new FinancialPoint(new DateTime(2021, 1, 1, 10, 0, 0), 623, 500, 450, 400),
                    new FinancialPoint(new DateTime(2021, 1, 1, 11, 0, 0),624, 500, 450, 400),
                    new FinancialPoint(new DateTime(2021, 1, 1, 12, 0, 0), 625, 500, 450, 400),
                    new FinancialPoint(new DateTime(2021, 1, 1, 13, 0, 0), 626, 500, 450, 400),
           }
3. Change for the XAxis UnitWidth (UnitWidth = TimeSpan.FromHours(1).Ticks)
4. Start the Samples project
5. Go to the Financial Tab.

**Expected behavior**
4 different candlesticks rendered.

**Actual behavior**
2 candlesticks (acutally 4 but the first two are overlapping and the same for the last two)

**Screenshots**
![image](https://user-images.githubusercontent.com/9322765/123552075-29606880-d77d-11eb-9edd-270acd4aaeab.png)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Version [Latest master]
 - Platform [WPF]

**Additional context**
The actual issue is found at DataProvider.cs line 264 and 264. 
`                   var dx = Math.Abs(previous.SecondaryValue - point.SecondaryValue);
                    var dy = Math.Abs(previous.PrimaryValue - point.PrimaryValue);
                    if (dx < bounds.MinDeltaSecondary) bounds.MinDeltaSecondary = dx;
                    if (dy < bounds.MinDeltaPrimary) bounds.MinDeltaPrimary = dy;
`

At this point the DateTime.Ticks(long) has already been converted to float and some of its digits were lost.

How to validate this:
`(float)DateTime.Now.Ticks == (float)DateTime.Now.AddMinutes(10).Ticks` => True

**Comment by beto-rodriguez** [comment]
This should be fixed with the refenced commit, this fix is included since v2.0.beta.33.

Thanks for the report.
