### ISSUE TITLE
Some columns not drawn in 

### ISSUE THREAD

**Issue by NPadrutt** [beto-rodriguez/LiveCharts2#642]
**Describe the bug**
I noticed that not all columns are drawn once you go below 2 ColumnSeries with only one value in it.
Interesstingly the tooltip overlay is rendered correctly.

**To Reproduce**
Core for the Screenshow below:
```
        var statisticItems = await Mediator.Send(new GetCashFlowQuery { EndDate = EndDate, StartDate = StartDate });
        var columnSeries = new ColumnSeries<decimal>
        {
            Values = new[] { 2909m }
        };

        var columnSeries2 = new ColumnSeries<decimal>
        {
            Values = new[] { 1000m }
        };

        var columnSeries3 = new ColumnSeries<decimal>
        {
            Values = new[] { 5555.2m }
        };


        var columnSeries4 = new ColumnSeries<decimal>
        {
            Values = new[] { 5555.2m }
        };

        Series.Clear();
        Series.Add(columnSeries);
        Series.Add(columnSeries2);
        Series.Add(columnSeries3);
        Series.Add(columnSeries4);
```

**Expected behavior**
All Series are drawn correctly

**Screenshots**
![image](https://user-images.githubusercontent.com/1764367/192046626-820453ff-e751-40f2-b04f-a9017ecc30cf.png)

**Additional context**
This is only with the newest version (400) and worked correctly with 300.

**Comment by beto-rodriguez** [comment]
Thanks for the report, the refenced commit improves this behavior and this will be gone in the next version of the library.
