### ISSUE TITLE
How to draw a straightline

### ISSUE THREAD

**Issue by gegogabriel** [beto-rodriguez/LiveCharts2#65]
Is it possible to draw a line on a chart as it was possible in the first version? Or will it be in the near future?

With the first version I'm using the YAxis.

![image](https://user-images.githubusercontent.com/9322765/123701132-1bd4dc80-d86a-11eb-82fa-32ebf7e34a95.png)

**Comment by beto-rodriguez** [comment]
Sections can do it, for now they do not support labels:

https://github.com/beto-rodriguez/LiveCharts2/blob/master/samples/ViewModelsSamples/General/Sections/ViewModel.cs

**Comment by gegogabriel** [comment]
The missing labels is a deal breaker for my scenario. Is there any other feature planned for the near future that would give me an alternative? thanks
