### ISSUE TITLE
Do you have any plan to add the Section label??

### ISSUE THREAD

**Issue by hukjin** [beto-rodriguez/LiveCharts2#650]
I really wanna section's label.

is not enough to axis label.

Any plan??  really??

**Comment by beto-rodriguez** [comment]
This should be already supported with visual elements.

Add a section and also add a label as shown here: https://github.com/beto-rodriguez/LiveCharts2/releases/tag/v2.0.0-beta.400

Let me know if you faced any issue with the visual elements, I'll close this for now since this is already supported.
