### ISSUE TITLE
Is Avalonia.Diagnotics required in LiveChartsCore.SkiaSharp.Avalonia?

### ISSUE THREAD

**Issue by VMelnalksnis** [beto-rodriguez/LiveCharts2#655]
**Is your feature request related to a problem? Please describe.**
Right now `LiveChartsCore.SkiaSharp.Avalonia` references `Avalonia.Diagnostics`, which pulls in about 8 MB of additional transitive dependencies via `Microsoft.CSharp` and `Microsoft.CodeAnalysis.*`. The only reference to it that I can see is in the sample project. https://github.com/beto-rodriguez/LiveCharts2/blob/92578602760fa5089ff2f638e52b3508ce57c6b2/samples/AvaloniaSample/MainWindow.axaml.cs#L14

The project also builds without `Avalonia.Diagnostics`. Is there some other use of it that I'm missing, or can it be removed?

**Describe the solution you'd like**
`Avalonia.Diagnostics` is removed from `LiveChartsCore.SkiaSharp.Avalonia`.
https://github.com/beto-rodriguez/LiveCharts2/blob/868bad9993b0d0e4c4388229b7cfad15b05e3970/src/skiasharp/LiveChartsCore.SkiaSharp.Avalonia/LiveChartsCore.SkiaSharpView.Avalonia.csproj#L31

**Comment by beto-rodriguez** [comment]
You are right, that is not necessary, thanks for the report, this is fixed with the referenced commit, the next release will remove this unnecessary reference.
