### ISSUE TITLE
PieChart direction - Clockwise and Anti-Clockwise

### ISSUE THREAD

**Issue by tuyen-vuduc** [beto-rodriguez/LiveCharts2#656]
**Is your feature request related to a problem? Please describe.**
By default, PieChart is drawn in clockwise direction. I want it to be drawn in the opposite direction.

**Describe the solution you'd like**
I want it to be drawn in the opposite direction.

![image](https://user-images.githubusercontent.com/3112460/193474940-4e80781b-b7c0-4153-a1aa-d36cfd653c5d.png)

**Comment by beto-rodriguez** [comment]
This is a great feature, this was just implemented in the referenced PR and will be included in the next version of the library, using the `PieChart.IsClockwise` property.

Thanks for the report!
