### ISSUE TITLE
Render in a image file ?

### ISSUE THREAD

**Issue by ClubberLangG** [beto-rodriguez/LiveCharts2#66]
I wish to render my diagram into an image file, is it already possible?

**Comment by anthony-glenwright** [comment]
You could try this:
`public static void SaveAs(string filename, FrameworkElement element)
		{
			System.Drawing.Bitmap bmp = null;

			RenderTargetBitmap bmpTarget = new(
							(int)(element.ActualWidth),
							(int)(element.ActualHeight),
							75, 75, PixelFormats.Pbgra32);
			bmpTarget.Render(element);

			// Converts RenderTargetBitmap to bitmap.
			PngBitmapEncoder png = new();
			png.Frames.Add(BitmapFrame.Create(bmpTarget));

			using (MemoryStream memStream = new())
			{
				png.Save(memStream);
				bmp = new System.Drawing.Bitmap(memStream);
				png = null;
			}

			bmp.Save(filename, System.Drawing.Imaging.ImageFormat.Png);
		}`

**Comment by ClubberLangG** [comment]
Thanks

**Comment by beto-rodriguez** [comment]
Also see #16 

The solution by @anthony-glenwright works only for WPF.

#80 uses the SkiaShap API to render images, please lee #16 for more info
