### ISSUE TITLE
DateTime Axis Automatic Step is inconsistent when using labeler

### ISSUE THREAD

**Issue by pvalobra** [beto-rodriguez/LiveCharts2#663]
Hello,

**Describe the bug**
When using a DateTime series, the X Axis step grid separators are not always in a regular interval.
I narrowed it down to the use of the labeler when displaying only month/year
I am not entirely sure it's a bug but I was not expecting the labeler to have any effect on the step interval. I am expecting the interval to be constant for a given graph width in all cases once the step size has been calculated.
This was working properly in 2.0.0-beta.361

**To Reproduce**
1. Create a LineSeries with DateTimePoints
2. Add 10 points, 1 month apart each
3. Add a labeler to the XAxes that format to show only MM/YYYY
4. See vertical grid lines not using the same interval or some vertical grid lines are missing.

**Screenshots**
![image](https://user-images.githubusercontent.com/5199392/194471466-90765b7a-a81a-4b29-bad6-700d288b7df4.png)

**Expected behavior**
Constant step size for vertical grid lines. step size probably should only be affected by MinStep and Graph width.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Net Core 6.0
 - WPF
 - LivechartsCoreSkiaSharpView.WPF (2.0.0-beta.500)

**Additional context**
Please find the sample project that reproduces the issue.
Removing the labeler or labeling dd/MM/YYYY produce a correct grid 
[WpfApp1.zip](https://github.com/beto-rodriguez/LiveCharts2/files/9730823/WpfApp1.zip)

**Comment by beto-rodriguez** [comment]
Thanks again for the issue and the repo, this is fixed with the referenced commit and will be included in the next version of the library.

**Comment by pvalobra** [comment]
Hello,

thanks for always being responsive. I tested 2.0.0-beta.502 on the same sample and the grid is uniform but the labeler has no effect anymore

![image](https://user-images.githubusercontent.com/5199392/196603341-616e3ac4-b40d-46da-94d6-a490265f199b.png)

Has anything changed on how to use the labeler?

Thank you
Pascal

**Comment by beto-rodriguez** [comment]
My bad, fixed with 5c38ad2125960f2e61ce28c7419ff9441c2bbb0e

It is now fixed since beta.510 version (uploading)

**Comment by pvalobra** [comment]
Thank you for the quick fix! it works well in beta.512
