### ISSUE TITLE
charts frozen

### ISSUE THREAD

**Issue by sjs2118** [beto-rodriguez/LiveCharts2#667]
When I update thecharts  per 0.5second, I change x range , the charts frozen, app frozen. but 0.361 is ok

**Comment by beto-rodriguez** [comment]
hello, could you please share the steps to get this issue? please share your code

**Comment by sjs2118** [comment]
I do not know where is wrong, when I find the reason ,I will response you

**Comment by beto-rodriguez** [comment]
I will close this for now, feel free to reply or open a new issue when you have more information.
