### ISSUE TITLE
vlchatrs external class bug

### ISSUE THREAD

**Issue by sjs2118** [beto-rodriguez/LiveCharts2#668]
**Describe the bug**
 line can not be controled

**To Reproduce**
extern class member seirialine offen do not be scaled, and not be  controled, the line is a copy。

**Comment by beto-rodriguez** [comment]
Hello and thanks for the issue.

Can you please add more information about this issue, I require a `A clear and concise description of what the bug is` so I can reproduce and fix the issue you are facing.

**Comment by sjs97** [comment]
> Hello and thanks for the issue.
> 
> Can you please add more information about this issue, I require a `A clear and concise description of what the bug is` so I can reproduce and fix the issue you are facing.

hi beto, this is a example;

public class MyChart : CartesianChart
{
    LineSeries<DateTimePoint> s1=new LineSeries<DateTimePoint>();

    public MyChart()
    {
        List<ISeries> ss = new List<ISeries>();
        ss.Add(s1);
        this.Series = ss;
    }
}

somtimes,  the app can show two lines, one is s1 copy, the copy can not be zoomed and do not  be contrled.  howoever ,other one is normal.

**Comment by beto-rodriguez** [comment]
I am having troubles to reproduce this issue, this repo has a sample that uses the same series in 2 different charts, zooming ans panning works there, am I missing something?

https://github.com/beto-rodriguez/LiveCharts2/blob/master/samples/WPFSample/VisualTest/TwoChartsOneSeries/View.xaml
https://github.com/beto-rodriguez/LiveCharts2/blob/master/samples/ViewModelsSamples/VisualTest/TwoChartsOneSeries/ViewModel.cs

**Comment by sjs97** [comment]
I use code to zoom, not gestures。click button than change the x range,sometimes can reproduce this issue, but not always

在 2022-11-24 12:05:40，"Alberto Rodríguez" ***@***.***> 写道：


I am having troubles to reproduce this issue, this repo has a sample that uses the same series in 2 different charts, zooming ans panning works there, am I missing something?

https://github.com/beto-rodriguez/LiveCharts2/blob/master/samples/WPFSample/VisualTest/TwoChartsOneSeries/View.xaml
https://github.com/beto-rodriguez/LiveCharts2/blob/master/samples/ViewModelsSamples/VisualTest/TwoChartsOneSeries/ViewModel.cs

**Comment by sjs97** [comment]
in my app, all series are in one chart。I click butyon ,than change x axis min and max limit

在 2022-11-24 12:05:40，"Alberto Rodríguez" ***@***.***> 写道：


I am having troubles to reproduce this issue, this repo has a sample that uses the same series in 2 different charts, zooming ans panning works there, am I missing something?

https://github.com/beto-rodriguez/LiveCharts2/blob/master/samples/WPFSample/VisualTest/TwoChartsOneSeries/View.xaml
https://github.com/beto-rodriguez/LiveCharts2/blob/master/samples/ViewModelsSamples/VisualTest/TwoChartsOneSeries/ViewModel.cs
