### ISSUE TITLE
MAUI CandleSticksSeries BUG

### ISSUE THREAD

**Issue by sjs2118** [beto-rodriguez/LiveCharts2#669]
MAUI CandleSticksSeries BUG

CandlesticksSeries< FinancialPoint>   body is incorrect. 
I want to set stock kline,the upper pic is right,but lvcharts is the second pic

![4ee152f1e1765f49](https://user-images.githubusercontent.com/115332715/194744529-2e722e7a-18ad-4a77-aeba-ef080b0893e4.jpg)

**Comment by sjs2118** [comment]
I set upstroke and upfill thickness each other, but they are allways same style.

**Comment by beto-rodriguez** [comment]
Hello and thanks for the issue, can you please let me know your series data? so I can reproduce and verify the issue.

**Comment by sjs2118** [comment]
I test any data in maui,  all  are same result.
this is lvchart document simple data
![-669b23138079f6dd](https://user-images.githubusercontent.com/115332715/195618242-a713faf4-f2a8-4bfc-8119-dc6bc96f084b.png)
![-2ec13756ba024a07](https://user-images.githubusercontent.com/115332715/195618255-25ca6093-370b-4bec-91fb-444ed9bab06c.png)

**Comment by sjs2118** [comment]
hi beto, 
in 0.514,  has this promblem also

**Comment by sjs2118** [comment]
> Hello and thanks for the issue, can you please let me know your series data? so I can reproduce and verify the issue.
hi beto,
in 0.514, has this promblem also

**Comment by beto-rodriguez** [comment]
I am sorry I cannot understand what the issue is.

**Comment by sjs2118** [comment]
> I am sorry I cannot understand what the issue is.
the candlestick shuld have diffrent thickness  on both ends . but in maui,the thickness is same .

**Comment by sjs2118** [comment]
upfille thicknesis 1, upstrock thickness is 5, but in the maui, they are be showed with same thicknes 5

**Comment by beto-rodriguez** [comment]
After checking this out, it seems that this is the appropriate behavior, the `Stroke` uses the thickness set, while on the `Fill` property is ignored.
