### ISSUE TITLE
How to use ObservablePoint with int32

### ISSUE THREAD

**Issue by Albert634515** [beto-rodriguez/LiveCharts2#67]
How to use ObservablePoint with int32

I'm trying to create a graph with date per year.
I am currently using the ObservablePoint object. But this gives my x-axis values like 2018,5, 2019, 2019,5
How do I get these integers on my x-axis?

**Comment by beto-rodriguez** [comment]
Use the `MinStep` property in your axis:

https://github.com/beto-rodriguez/LiveCharts2/blob/master/docs/components/1.7.axes.md#minstep-property

**Comment by Albert634515** [comment]
Yes that works thanks
