### ISSUE TITLE
Is there a geared version for LiveCharts2? 

### ISSUE THREAD

**Issue by akshay-melapuram-ashok** [beto-rodriguez/LiveCharts2#674]
### Discussed in https://github.com/beto-rodriguez/LiveCharts2/discussions/103

<div type='discussions-op-text'>

<sup>Originally posted by **anivrutti** July 22, 2021</sup>
I want to use live chart geared WPF 
In live chart geared facing issue with zooming in line series
Raised issue @
https://github.com/Live-Charts/Live-Charts/issues/1129

![ZoomIssue](https://user-images.githubusercontent.com/46881696/126675909-8ee49efa-f1a2-409a-a9c6-feddc04c6673.png)

</div>

**Comment by beto-rodriguez** [comment]
Hello and thanks for your interest.

Yes, there is a high-performance package, and soon will be available for everyone, I will close this for now, you can find more info at #486.

**Comment by akshay-melapuram-ashok** [comment]
Hello,

Thank you for the reply.
