### ISSUE TITLE
Legend/tooltip is offset/cut for ScatterSeries

### ISSUE THREAD

**Issue by atlemann** [beto-rodriguez/LiveCharts2#677]
**Describe the bug**
I added a ScatterSeries and the legend/tooltip is not displayed correctly. 

**To Reproduce**
```csharp
public ISeries[] ChartSeries { get; }
...
...
ChartSeries = new ISeries[]
{
    new LineSeries<double>
    {
        Values = new double[] { 2, 1, 3, 5, 3, 4, 6 },
        Fill = null,
        Stroke = new SolidColorPaint(SKColors.CornflowerBlue, 2.0f),
        GeometrySize = 8.0
    },
    new LineSeries<double>
    {
        Values = new double[] { 2.5, 1.5, 3.5, 5.5, 3.5, 4.5, 6.5 },
        Fill = null,
        Stroke = new SolidColorPaint(SKColors.Coral, 2.0f),
        GeometrySize = 8.0
    },
    new ScatterSeries<double>()
    {
        Values = new double[] { 1.5, 2.5, 2.5, 4.5, 2.5, 3.5, 5.5 },
        Fill = new SolidColorPaint(SKColors.Teal),
        Stroke = new SolidColorPaint(SKColors.Teal, 2.0f),
        GeometrySize = 8.0
    }
};
```

```xaml
<avalonia:CartesianChart
    Grid.Row="2"
    Grid.Column="1"
    LegendPosition="Top"
    ZoomMode="Both"
    Series="{Binding ChartSeries}"/>
```

**Expected behavior**
Legend to look Ok

**Screenshots**
Legend is borked. The hover-toolip has the same problem.

![image](https://user-images.githubusercontent.com/16226914/194881989-d6cb463e-a29f-4d72-9a94-9155744ad85f.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04

**Additional context**
NuGet  [2.0.0-beta.501](https://www.nuget.org/packages/LiveChartsCore/2.0.0-beta.501)

**Comment by beto-rodriguez** [comment]
Hi and thanks for the report, this is fixed with https://github.com/beto-rodriguez/LiveCharts2/pull/768 and it will be included in the next version of the library.
