### ISSUE TITLE
Adding a series with an observable collection with DateTimePoint without data creates a mess in the graph

### ISSUE THREAD

**Issue by Albert634515** [beto-rodriguez/LiveCharts2#68]
Adding a series with an observable collection with DateTimePoint without data creates a mess in the graph

I have added three series.
Two with data, one without

Image with the three series:
![image](https://user-images.githubusercontent.com/85439711/124379311-89dc3200-dcb6-11eb-9fb6-50ea410df31e.png)

Image with the two correct series with data
![image](https://user-images.githubusercontent.com/85439711/124379362-d32c8180-dcb6-11eb-9174-19d0b482fcbd.png)

Code of series without data:
            cs = new ColumnSeries<DateTimePoint>
            {
                Name = "Serie3",
            };

**Comment by beto-rodriguez** [comment]
The referenced commit should fix this issue, thanks for the report, the fill will be included in the next version of the library.
