### ISSUE TITLE
Series events not triggered when TooltipPosition="Hidden"

### ISSUE THREAD

**Issue by atlemann** [beto-rodriguez/LiveCharts2#681]
**Describe the bug**
I need to be able to select points/lines in a chart, but it seems to not work when I hide the tooltips. And in my chart, the tooltips are just in the way, so I have to hide them.

**To Reproduce**

Set `TooltipPosition="Hidden"`

```xaml
<avalonia:CartesianChart
    Grid.Row="0"
    Grid.Column="1"
    Series="{Binding Points}"
    TooltipPosition="Hidden"
    />
```
```csharp
var paint = new SolidColorPaint(SKColors.Aqua, 2.0f);
var series = new LineSeries<ObservablePoint>()
{
    Name = name,
    Stroke = paint,
    Fill = null,
    GeometrySize = 8.0,
    GeometryFill = paint,
    GeometryStroke = paint,
    Values = values
};

series.ChartPointPointerDown += (chart, point) =>
{
    if (point.Visual is null) return;
    point.Visual.Geometry.Fill = new SolidColorPaint(SKColors.Red);
    chart.Invalidate(); // <- ensures the canvas is redrawn after we set the fill
};
series.ChartPointPointerHover += (chart, point) =>
{
    if (point.Visual is null) return;
    point.Visual.Geometry.Fill = new SolidColorPaint(SKColors.Yellow);
    chart.Invalidate();
};
series.ChartPointPointerHoverLost += (chart, point) =>
{
    if (point.Visual is null) return;
    point.Visual.Geometry.Fill = null;
    chart.Invalidate();
};
```

**Expected behavior**
The events to be fired

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04

**Additional context**
NuGet [2.0.0-beta.501](https://www.nuget.org/packages/LiveChartsCore/2.0.0-beta.501)

**Comment by scria1000** [comment]
As a workaround, setting the chart a blank `TooltipTemplate` like this:

```
<lvc:CartesianChart
    x:Name="chart1"
    <lvc:CartesianChart.TooltipTemplate>
        <DataTemplate />
    </lvc:CartesianChart.TooltipTemplate>
</lvc:CartesianChart>
```

Seems to achieve what is intended with `TooltipPosition="Hidden"`

**Comment by beto-rodriguez** [comment]
Thanks for the report, this is fixed with the referenced commit and will be included in the next version of the library,

**Comment by mabo0001** [comment]
series.ChartPointPointerHover is still not triggered
