### ISSUE TITLE
Box and Whisker Chart

### ISSUE THREAD

**Issue by girlpunk** [beto-rodriguez/LiveCharts2#684]
**Describe the solution you'd like**
Would be useful if LiveCharts could support box and whisker charts. For simplicity it may be easier to have the application rendering the graph handle min/max/avg calculation and outlier detection.

**Describe alternatives you've considered**
The existing "candlestick" chart provides similar output, and could likely be used as a basis. Additional values for upper/lower quartiles and median would need to be added in place of opening and closing values, and the date would need to be removed.

**Comment by Maryhuck** [comment]
You can call me or text me on my cell number 4248355559 and you can also WhatsApp me on ‪+1 (412) 283‑3062‬

**Comment by beto-rodriguez** [comment]
This is now supported in beta.920 https://github.com/beto-rodriguez/LiveCharts2/pull/1179:

https://github.com/beto-rodriguez/LiveCharts2/blob/master/samples/ViewModelsSamples/Box/Basic/ViewModel.cs
