### ISSUE TITLE
Maui Windows charts not displaying

### ISSUE THREAD

**Issue by DatBear** [beto-rodriguez/LiveCharts2#686]
**Describe the bug**
Running a Maui Windows app, displaying a basic line chart doesn't work. The line chart just doesn't show up at all for me.

**To Reproduce**
Run https://github.com/DatBear/MauiChartsTest on Windows. 

This is the base Maui template, adding the chart to MainPage.xaml, adding MainViewModel.cs, and adding .UseSkiaSharp(true) to MauiProgram.cs

**Expected behavior**
A basic line chart should show up.

**Screenshots**
![screenshot](https://i.imgur.com/q1pxWcO.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: LiveChartsCore.SkiaSharpView.Maui v2.0.0-beta.501, tried v2.0.0-beta.401 too.

**Additional context**
None?

**Comment by beto-rodriguez** [comment]
Hello and thanks for the repo and the issue!

I was able to make your sample work by changing your layout from:

```xml
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:lvc="clr-namespace:LiveChartsCore.SkiaSharpView.Maui;assembly=LiveChartsCore.SkiaSharpView.Maui"
             xmlns:mauiChartsTest="clr-namespace:MauiChartsTest"
             x:Class="MauiChartsTest.MainPage">
    <ContentPage.BindingContext>
        <mauiChartsTest:MainViewModel />
    </ContentPage.BindingContext>
    <ScrollView>
        <VerticalStackLayout Spacing="25" Padding="30,0" VerticalOptions="Center">
            <lvc:CartesianChart Series="{Binding Series}" Title="{Binding Title}" />
        </VerticalStackLayout>
    </ScrollView>
</ContentPage>
```

to:

```c#
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:lvc="clr-namespace:LiveChartsCore.SkiaSharpView.Maui;assembly=LiveChartsCore.SkiaSharpView.Maui"
             xmlns:mauiChartsTest="clr-namespace:MauiChartsTest"
             x:Class="MauiChartsTest.MainPage">
    <ContentPage.BindingContext>
        <mauiChartsTest:MainViewModel />
    </ContentPage.BindingContext>
    <lvc:CartesianChart Series="{Binding Series}" Title="{Binding Title}" />
</ContentPage>
```

In my understanding, this issue (it if is an issue) belongs to MAUI, I will close this for now since the chart renders, what is not working in your case is the layout above the chart.
