### ISSUE TITLE
Is it possible to get hashed background in columns or line fill

### ISSUE THREAD

**Issue by Albert634515** [beto-rodriguez/LiveCharts2#69]
Is it possible to get hashed background in columns or line fill
With hashed I mean non solid, like with lines or dottes but also with fill color.

**Comment by beto-rodriguez** [comment]
This can be done using the SkiaSharp API, for example:

https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/graphics/skiasharp/curves/effects#hatching-an-area

At this point the library does not provide a built-in solution for this, but it will in a future.
