### ISSUE TITLE
Horizontal- and VerticalAlignment for GeometryVisual

### ISSUE THREAD

**Issue by samirem** [beto-rodriguez/LiveCharts2#693]
For LabelVisuals, we have properties for Vertical- and HorizontalAlignment, but I cannot find how to achieve it for GeometryVisuals. It would come very handy in my case where I want to center a Geometry marker at certain points of interest in my charts
![image](https://user-images.githubusercontent.com/20268636/196249474-6497db50-f92d-42db-b454-47ffcfa0d9f0.png)

**Comment by beto-rodriguez** [comment]
This is already supported, you can set the `Translate` property to move the label from the original polistion.

**Comment by samirem** [comment]
Hi @beto-rodriguez!

Thanks for responding. As far as I can see, there is no `Translate` property on `GeometryVisual`. The alignment of the text label is fine, but not the `OvalGeometry` that I am using for the points

**Comment by beto-rodriguez** [comment]
You are right it was only implemented in the label visual, now all the visual elements also include this property, this change will be included in beta.900
