### ISSUE TITLE
我购买了LiveChrats.Geared个人版，然后通过下载激活器进行激活，我能看到激活已经成功了，但是我在运行系统时提示无法加载类型“LiveCharts.Definitions.Series.IGroupedStackedSeriesView”

### ISSUE THREAD

**Issue by xiaomumo** [beto-rodriguez/LiveCharts2#7]

**Comment by lihongfang16** [comment]
> _No description provided._

如果为了性能的话  可以尝试  scottplot

**Comment by beto-rodriguez** [comment]
@xiaomumo The stacked series are not fast in the geared version (v0). Take a look at the demo: 

https://github.com/Live-Charts/GearedExamples
