### ISSUE TITLE
Build error for BlazorWebAssembly target not building successefully with LVC lvc:CartesianChart controls used

### ISSUE THREAD

**Issue by Shattienator** [beto-rodriguez/LiveCharts2#703]
**Describe the bug**
WebAssembly target from Avalonia Xplat template not building 

**To Reproduce**
1. Create Avalonia Cross Platform Application (dotnet new avalonia.xplat)
2. Add LiveChartsCore.SkiaSharpView.Avalonia from NuGet
3. Create a View Model and Add the chart control to the UI as described in Installation and first chart for Avalonia
4. Build Solution. All projects will be built successful except Web one with following error: Parameter types of pinvoke callback method 'System.Int32 SetMinMaxSize(System.Void*, Avalonia.Native.Interop.AvnSize, Avalonia.Native.Interop.AvnSize)' needs to be blittable.	LV2BugTest.Web	C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.WebAssembly.Sdk\6.0.9\Sdk\WasmApp.Native.targets	244

**Expected behavior**
All build targets should work.

**Screenshots**
Nothing to screenshot - 

**Desktop (please complete the following information):**
 - Win10 with VS2022 17.4.0 Preview 4.0: [e.g. iOS]

**Additional context**
Desktop build runs like a charm. Webassembly target can not be built.
Encountered this error only with LiveCharts2. With many other packages all builds are successful.

**Comment by beto-rodriguez** [comment]
Hi and thanks for the report.

Sadly, I do not think that this issue belongs to LiveCharts, this could be an issue in Avalonia or SkiaSharp, I will take a look further and try to find what is wrong.

**Comment by beto-rodriguez** [comment]
Probably related to https://github.com/AvaloniaUI/Avalonia/discussions/9264.

According to that discussion, it seems that we need to remove the reference to `Avalonia.Desktop`, but it seems that there is also an issue on their side, I will keep an eye on this.

**Comment by beto-rodriguez** [comment]
This works properly now with Avalonia 11 and LiveCharts beta.810
