### ISSUE TITLE
How to apply themes?

### ISSUE THREAD

**Issue by Imadlekal** [beto-rodriguez/LiveCharts2#704]
I can see that we can apply either Light or Dark themes, but how about the styles in the demo? MaterialStripped, Dimmed, Function, and Slim? as shown here:

https://user-images.githubusercontent.com/10853349/124399763-41873900-dce3-11eb-937a-947d66d42597.gif

I'm using WPF.

**Comment by beto-rodriguez** [comment]
Themes are not available yet, there are a couple of issues that need to be fixed before that, I will close this for now, we can track this at #589
