### ISSUE TITLE
Setting Axis Color at Runtime

### ISSUE THREAD

**Issue by ajayre** [beto-rodriguez/LiveCharts2#706]
I can see in the examples how to set the NamePaint and LabelsPaint properties during axis declaration, but how I can I change the color during runtime after the axis has been declared? Here is my current cast and it doesn't give access to those properites.

`((CartesianChart<SkiaSharpDrawingContext>)Chart.CoreChart).YAxes[0]`

I've also tried this but still no access to the properties.

`(Axis<SkiaSharpDrawingContext, LabelGeometry, LineGeometry>)(((CartesianChart<SkiaSharpDrawingContext>)Chart.CoreChart).YAxes[0])`

I'm sure it's just a casting issue, but what is needed?

Thanks!

**Comment by beto-rodriguez** [comment]
This will probably be improved in a future version, for now cast it to `Axis`:

`(Axis)(((CartesianChart<SkiaSharpDrawingContext>)Chart.CoreChart).YAxes[0])`

**Comment by ajayre** [comment]
Works - many thanks!!
