### ISSUE TITLE
.Net FrameWork support

### ISSUE THREAD

**Issue by Oscaramr** [beto-rodriguez/LiveCharts2#71]
Dont know if im doing something wrong but i wanna use this for .net framework forms framework 4.7.2 i think if i am can someone guide me?

**Comment by Albert634515** [comment]
Check out this link: https://stackoverflow.com/questions/66227548/is-it-possible-to-use-a-net5-core-library-from-a-net-framework-app

**Comment by beto-rodriguez** [comment]
What is the error you are getting?

I am closing this for now, feel free to open a new issue that describes the error message you are getting.
