### ISSUE TITLE
Realtime plotting of 8 line series crashes with unhandled exception in KernelBase.dll

### ISSUE THREAD

**Issue by pablo-remy** [beto-rodriguez/LiveCharts2#715]
**Describe the bug**
I need to plot 8 line series in real time (data will be coming at a 10 Hz sampling rate from an external USB data logger). I built a simple app to test performance of LiveCharts2 to make sure it can handle the task but it's crashing every time with an unhandled exception in KernelBase.dll.

**To Reproduce**
My code is a modified version of the "automatic updates" sample code for WinUI found here (https://lvcharts.com/docs/WinUi/2.0.0-beta.330/samples.lines.autoupdate)
I simply modified it to have 8 line series, each with its own set of _observableValues and I set up a timer to run every 100 ms to call the AddItem function on all 8 line series
I'm attaching my MainWindow.xaml and MainWindow.xaml.cs files in case you want to reproduce the issue
[MainWindow.xaml.zip](https://github.com/beto-rodriguez/LiveCharts2/files/9863213/MainWindow.xaml.zip)

**Expected behavior**
When you press the "Start Timer" button the app should start plotting random data into 8 line series every 100ms and it should continue doing so indefinitely but instead it crashes after a while of running the timer. The crash seems to happen much sooner if the cursor is moved over the chart whereas it takes a lot longer if the cursor is left unmoved

**Screenshots**
I'm attaching screenshot of the error and I´ve made screen recordings that show the behavior which you can find via the links below
https://drive.google.com/file/d/1y-bufen3vjM-1MdeP5c2CV3utPd7RdYa/view?usp=sharing
https://drive.google.com/file/d/1-Su3lbHavKCTtcqb8RAwf8xGcLsh3G-y/view?usp=sharing

![Unhandled exception LiveCharts2](https://user-images.githubusercontent.com/116272162/197858554-8cf02ce3-7001-4fad-a490-8208dba88222.PNG)

**Desktop (please complete the following information):**
Windows 10 Pro + WinUI

**Comment by pablo-remy** [comment]
I've tried a few things to solve the issue but no luck so far. Here are some of the things I tried:

- Visual studio reported "kernelbase.pdb not found" and I read somewhere that enabling Microsoft or NuGet.org Symbol Servers might help with that (see screenshot). No luck 

![image](https://user-images.githubusercontent.com/116272162/198593822-65d327db-9aec-492e-8e3b-e29219824d3c.png)

- I tried simplifying things which I thought might be render-intensive. Most of these I've read that they shouldn't necessarily improve performance in LiveChart2 (as opposed to in LiveCharts 1). Nonetheless I tried these as a sanity check. None of these changed the outcome:

> EasingFunction="{x:Null}
> TooltipPosition="Hidden"
> LineSmoothness = 0                  
> GeometryFill = null,
> GeometryStroke = null,

- Finally I read on [this article](https://lvcharts.net/App/examples/v1/wpf/Performance%20Tips) about performance in the LiveCharts 1 library that it is not recommended to call the Add function too many times too frequently and instead it's better practice to call the AddRange function for better performance. I don't see the same warning in the LiveCharts2 documentation but nonetheless I checked to see if the AddRange function exists in LiveCharts2 but it doesn't seem to be there so in order to space out the calls to the Add function I tried adding a 20 ms delay between calling the Add function on my observable collections, but the result is the same.

I'm starting to lose hope and might need to look for another library for this project.

**Comment by pablo-remy** [comment]
I've tried a few things to solve the issue but no luck so far. Here are some of the things I tried:

Visual studio reported "kernelbase.pdb not found" and I read somewhere that enabling Microsoft or NuGet.org Symbol Servers might help with that (see screenshot). No luck
image

I tried simplifying things which I thought might be render-intensive. Most of these I've read that they shouldn't necessarily improve performance in LiveChart2 (as opposed to in LiveCharts 1). Nonetheless I tried these as a sanity check. None of these changed the outcome:
EasingFunction="{x:Null}
TooltipPosition="Hidden"
LineSmoothness = 0
GeometryFill = null,
GeometryStroke = null,

Finally I read on [this article](https://lvcharts.net/App/examples/v1/wpf/Performance%20Tips) about performance in the LiveCharts 1 library that it is not recommended to call the Add function too many times too frequently and instead it's better practice to call the AddRange function for better performance. I don't see the same warning in the LiveCharts2 documentation but nonetheless I checked to see if the AddRange function exists in LiveCharts2 but it doesn't seem to be there so in order to space out the calls to the Add function I tried adding a 20 ms delay between calling the Add function on my observable collections, but the result is the same.
I'm starting to lose hope and might need to look for another library for this project.

**Comment by pablo-remy** [comment]
I've tried a few things to solve the issue but no luck so far. Here are some of the things I tried:

- Visual studio reported "kernelbase.pdb not found" and I read somewhere that enabling Microsoft or NuGet.org Symbol Servers might help with that (see screenshot). No luck
![image](https://user-images.githubusercontent.com/116272162/198599420-b6e1a8de-d865-43db-b798-ebbfd1ab020c.png)

- I tried simplifying things which I thought might be render-intensive. Most of these I've read that they shouldn't necessarily improve performance in LiveChart2 (as opposed to in LiveCharts 1). Nonetheless I tried these as a sanity check. None of these changed the outcome:

> EasingFunction="{x:Null}
> TooltipPosition="Hidden"
> LineSmoothness = 0
> GeometryFill = null,
> GeometryStroke = null,


- Finally I read on [this article](https://lvcharts.net/App/examples/v1/wpf/Performance%20Tips) about performance in the LiveCharts 1 library that it is not recommended to call the Add function too many times too frequently and instead it's better practice to call the AddRange function for better performance. I don't see the same warning in the LiveCharts2 documentation but nonetheless I checked to see if the AddRange function exists in LiveCharts2 but it doesn't seem to be there so in order to space out the calls to the Add function I tried adding a 20 ms delay between calling the Add function on my observable collections, but the result is the same.

I'm starting to lose hope and might need to look for another library for this project.

**Comment by pablo-remy** [comment]
I see there is an UpdaterThrottler property which I suspect might help prevent these crashes, but as reported in [this issue ](https://github.com/beto-rodriguez/LiveCharts2/issues/699) #699  the UpdaterThrotter proerty throws XamlParseException so it's useless at the moment

**Comment by carraspe** [comment]
Tried a few more things and still no luck:

- Tried plotting dots instead of lines (still using lineSeries just tweaking stroke and stroke geometry properties). Same result

- Tried plotting scatterSeries instead of lineSeries. Same result

- I managed to get updaterTrhottler to work programmatically. Same result, even throttling down to super slow refresh rates like every 10 secs.

- I tried fixing the x and y axis ranges so nothing moves in the chart except for new points being added. Same result

- I tried adding data to my series using a separate thread. Same result.

- I tried running the app on another PC. Same general result it just seems to take a different amount of time before the crash happens 

Later on I'll see if I can prepare a reduced project I can share here to help debug the issue.

**Comment by pablo-remy** [comment]
Tried a few more things and still no luck:

- Tried plotting dots instead of lines (still using lineSeries just tweaking stroke and stroke geometry properties). Same result

- Tried plotting scatterSeries instead of lineSeries. Same result

- I managed to get updaterTrhottler to work programmatically. Same result, even throttling down to super slow refresh rates like every 10 secs.

- I tried fixing the x and y axis ranges so nothing moves in the chart except for new points being added. Same result

- I tried adding data to my series using a separate thread. Same result.

- I tried running the app on another PC. Same general result it just seems to take a different amount of time before the crash happens


Later on I'll see if I can prepare a reduced project I can share here to help debug the issue.

**Comment by pablo-remy** [comment]
**_UPDATE:_** It seems the situation has improved considerably simply by using `Microsoft.UI.Xaml.DispatcherTimer` instead of `System.Timers.Timer ` for adding data to all my lineSeries

I understand the DispatcherTimer runs on the UI thread whereas System.Timer runs on some other thread pool. I guess I might've been having a concurrency issue between the UI thread and whatever other thread my old System.Timer was using for adding data to the chart. It makes some sense that things are more stable if I'm adding data to my lineSeries from the UI thread itself instead. 

I'll continue working with this solution. However, I do hope the developer will comment on this. It would be nice to have some documentation with the recommended approach for using timers for adding data to the charts and how to manage threading in general. For example is it recommended to run the data updates on the UI thread or on another thread and use lock statements or some other technique for preventing concurrency issues?

**Comment by beto-rodriguez** [comment]
Hi Pablo, yes, the library has a couple of samples handling updates from multiple threads:

Take a look at the multithreading samples:

https://github.com/beto-rodriguez/LiveCharts2/tree/master/samples/ViewModelsSamples/General

And the winui views:

https://github.com/beto-rodriguez/LiveCharts2/blob/master/samples/WinUISample/WinUISample/General/MultiThreading2/View.xaml.cs

In general, the issue should be gone if your data changes always happen in the UI thread, or you provide a sync object for the library to handle that.

You can find more info at https://github.com/beto-rodriguez/LiveCharts2/issues/225#issuecomment-1012488255.
