### ISSUE TITLE
Chart, CartesianChart, IChartView, PieChart classes have a mis-spelled property "AutoUpdateEnaled"

### ISSUE THREAD

**Issue by anthony-glenwright** [beto-rodriguez/LiveCharts2#72]
**Describe the bug**
The Chart, CartesianChart, IChartView, PieChart classes have a property named "AutoUpdateEnaled", should be "AutoUpdateEnabled".

**Comment by beto-rodriguez** [comment]
Thanks for the report, the referenced commit fixes the typo.
