### ISSUE TITLE
WPF - Click and Zoom coexistence

### ISSUE THREAD

**Issue by krosthw** [beto-rodriguez/LiveCharts2#721]
**Is your feature request related to a problem? Please describe.**
If I click on a point in the chart, a function is called (it displays in another part of GUI more details about the points).
If the zoom (on x) is active, the chart flows as if I had dragged the point.
Is it possible to distinguish a simple click from a drag?

**Describe the solution you'd like**
decide the action based on the "point down" time. if time is "small", then consider a simple click, and not a drag.
Or the possibilty to configure left/right click with  custom action

**Comment by beto-rodriguez** [comment]
Hi and thanks for the report.

Are you using the `Series.DataPointerDown` event?

**Comment by krosthw** [comment]
(sorry for the delay in the response)

I'm using ```Series.ChartPointPointerDown```

**Comment by beto-rodriguez** [comment]
In a previous release (not documented) this was improved.

In a case like yours when we need customized interaction with the plot, probably the best alternative is to use the WPF events (Click or PointerDown), then in the click event you can ask the chart to look for the points at the click location.

You can find an example [here https://github.com/beto-rodriguez/LiveCharts2/blob/master/samples/WPFSample/Events/AddPointOnClick/View.xaml.cs#L19](https://github.com/beto-rodriguez/LiveCharts2/blob/dev/samples/WPFSample/Events/AddPointOnClick/View.xaml.cs#L19)

I think this should be enough to solve this issue, please feel free to reply if I missed something.
