### ISSUE TITLE
Only every other label shows in line chart X Axis

### ISSUE THREAD

**Issue by barrybriggs** [beto-rodriguez/LiveCharts2#726]
WPF, Windows 10.

Very simple line chart. Only "a", "c" and "e" show on x axis. 

I seem to remember seeing something about this in V1 but can't see the corresponding fix for V2. 

~~~
        public Axis[] XAxes { get; set; } =
        {
        new Axis
            {
            LabelsRotation = -90,
            Labels = new string [] { "a", "b", "c", "d", "e" },
            }
        };
~~~

**Comment by wdsjock** [comment]
Separator = new LiveCharts.Wpf.Separator
    {
        Step = 1,
    },

**Comment by barrybriggs** [comment]
Are you sure? I believe this is only for LiveCharts 1 not 2.

**Comment by barrybriggs** [comment]
But that was enough to help me find the solution which used 

```
            MinStep=1,
            ForceStepToMin=true
```
in the Axis definition.
