### ISSUE TITLE
Detecting mouse buttons for `ChartPointPointer` events

### ISSUE THREAD

**Issue by hahagu** [beto-rodriguez/LiveCharts2#727]
**Is your feature request related to a problem? Please describe.**
Using the current implementation of the aforementioned events, the event does not include `MouseEventArgs`.
Therefore, it is impossible to know whether a user pressed a data point or chart using the right or the left mouse button to click.
A use-case for this would be, for example, left click to add a point to a chart, and right click to remove a point.

**Describe the solution you'd like**
An implementation of  `MouseEventArgs` on the handlers of those methods would work.

**Describe alternatives you've considered**
Technically, a wrapper for the control containing the graph could be used to detect the mouse event, and pass it through down to the event handler.
Or, a `PointerPressed` method could be used for detecting and executing actions based on the `PointerPressedEventArgs` property.
However, this is an unconventional way of doing such thing, and would be an overcomplication of an otherwise simple task.

**Comment by hahagu** [comment]
Here is an implementation of the use-case provided using the alternative solution I have suggested.

```csharp
private void SeriesOnChartPointPointerHover(IChartView chart, ChartPoint<ObservablePoint, BezierPoint<CircleGeometry>, LabelGeometry> point)
{
    point.Visual!.Geometry.Fill = new SolidColorPaint(SKColors.Black);
    _selectedPoint = point.Model;
}

private void SeriesOnChartPointPointerHoverLost(IChartView chart, ChartPoint<ObservablePoint, BezierPoint<CircleGeometry>, LabelGeometry> point)
{
    point.Visual!.Geometry.Fill = new SolidColorPaint(SKColors.White);
    _selectedPoint = null;
}

private void ChartObject_OnPointerPressed(object? sender, PointerPressedEventArgs e)
{
    if (e.GetCurrentPoint(ChartObject).Properties.IsLeftButtonPressed)
    {
        Point pressedPoint = e.GetPosition(ChartObject);
        double[] scaledPoint = ChartObject.ScaleUIPoint(new LvcPoint((float)pressedPoint.X, (float)pressedPoint.Y));
        ObservablePoint addPoint = new(scaledPoint[0], scaledPoint[1]);

        // Check if addPoint is in range
        if (addPoint.Y > 100) addPoint.Y = 100;
        if (addPoint.Y < 0) addPoint.Y = 0;

        // Add point to corresponding 
        if (addPoint.X < _points.First().X || _points.Count == 0)
        {
            _points.Insert(0, addPoint);
        }
        else if (addPoint.X > _points.Last().X)
        {
            _points.Add(addPoint);
        }
        else
        {
            int index = _points.Last(x => x.X < addPoint.X).EntityIndex + 1;
            _points.Insert(index, addPoint);
        }
    } else if (e.GetCurrentPoint(ChartObject).Properties.IsRightButtonPressed)
    {
        if (_selectedPoint == null) return;
        _points.Remove(_selectedPoint);
    }
}
```

**Comment by beto-rodriguez** [comment]
This was improved in a previous release, please see #721, I think that alternative is flexible enough, let me know if I missed something or you think that is not a valid solution.
