### ISSUE TITLE
PieChart Title not showing

### ISSUE THREAD

**Issue by andrew-baylis** [beto-rodriguez/LiveCharts2#728]
**Describe the bug**
WPF - PieChart does not display the Title

**To Reproduce**
1. Create a PieChart and add a couple of series
2. Set the Title to something. For example
```
pieChart.Title = new LabelVisual()
{
    Text = "My pie chart title", 
    TextSize = 25, 
    Padding = new LiveChartsCore.Drawing.Padding(15), 
    Paint = new SolidColorPaint(SKColors.Green)
};
```
3. Run application
4. Pie chart is drawn properly, but the title does not show. Note that the same approach in a CartesianChart works fine.

**Expected behavior**
Title is centred above Pie

**Desktop (please complete the following information):**
 - OS: Windows 11
 - LiveCharts v2.0.0-beta.513

**Comment by beto-rodriguez** [comment]
Thanks for the report, this is fixed with the referenced commit and will be included in the next version of the library.
