### ISSUE TITLE
Tooltips - Winforms

### ISSUE THREAD

**Issue by devw4r** [beto-rodriguez/LiveCharts2#732]
**Describe the bug**
1- Unlike native tooltips, LiveCharts tooltip process is accessible through the task manager and task view (Alt-Tab). If for any reason the user decides to kill this or just close it, the whole parent application will crash.

2- Also, tooltips keep lingering on top of other applications even after its parent Form is minimized.

**To Reproduce**
1- Steps to reproduce the behavior:

1. Have the tooltip visible.
2. Close the tooltip window from TaskView:
3. Hover the chart again.

2- Steps to reproduce the behavior:

1. Have the tooltip visible.
2. Alt tab to another application making sure it ends up on top of the tooltip.
3. Minimize everything Wnd+D
4. Tooltip is there, on your empty desktop.

**Expected behavior**
1- I expect the library to have null checks for 'DefaultTooltip' and restore the closed tooltip instance instead of crashing.
2- I expect the tooltip to dissapear upon mouse leaving, parent form losing focus/minimized.

**Screenshots**
Case 1:

Close from TaskView.
![TaskView](https://user-images.githubusercontent.com/108442943/199367668-163a0d91-afb2-4216-ae05-c504cfe47b88.PNG)

After trying to hover the mouse on the chart.
![Ex](https://user-images.githubusercontent.com/108442943/199367653-c11270cf-19f0-4c4e-a008-f656c4b3d18b.PNG)

Case2:
Had the tooltip visible, alt tabbed to browser.
![LingeringTooltip0](https://user-images.githubusercontent.com/108442943/199367679-bc146540-18ed-40d5-8660-09e8d1f87c30.PNG)

Same but to Notepad++.
![LingeringTooltip1](https://user-images.githubusercontent.com/108442943/199367689-bc72838b-9097-4c36-b5df-1a75e8a330b7.PNG)

**Desktop (please complete the following information):**
- Windows 10
- Beta 514 from NuGet.

**Comment by devw4r** [comment]
> I think this is the same issue or related to #622

The second case (Lingering Tooltip) is.

**Comment by Fotrey** [comment]
winforms mdi , same issue like case1 , subwindow will crash and the tooltip is  invisible though I set its position

**Comment by beto-rodriguez** [comment]
Thanks for the report. This is already fixed with #768 and will be included in the next version of the library, #768 is a huge upgrade to tooltips in legends.
