### ISSUE TITLE
wrong behaviour of chart series events in MAUI version when used in windows

### ISSUE THREAD

**Issue by luigicasalegno** [beto-rodriguez/LiveCharts2#733]
I noticed that the events Series.ChartPointPointerDown behave the same way as ChartPointPointerHover in MAUI when used in windows.

**To Reproduce**
I tried your example Events and the bars never become yellow, but always red

**Expected behavior**
the same as in your example

**Desktop :**
Windows 10.0.19041.0

**Comment by beto-rodriguez** [comment]
Thanks for the report, this is already fixed and will be included in since version beta.850 (will publish soon)
