### ISSUE TITLE
Charts rendering issue - WPF 

### ISSUE THREAD

**Issue by EdenMeshulam28** [beto-rodriguez/LiveCharts2#734]
**Description**
In the WPFSample project the charts and their functions dose not render without resizing the window (shown in the screen-record).
Also when used LiveCharts2 as NuGet in WPF the same problem appeard.

**To Reproduce**
Used this repo and run the WPFSample project / new WPF application and did as described in the basic line chart documentation sample (https://lvcharts.com/docs/WPF/2.0.0-beta.330/samples.lines.basic). 

**Desktop:**
 - OS: win10
 - VS studio: 17.3.6 community / 17.1.3 Professional
 - .NET 6/5

https://user-images.githubusercontent.com/98810462/200157633-8cbe765c-d1b6-41f8-a4aa-7ec2e52a7da1.mp4

**Comment by beto-rodriguez** [comment]
is it possible that this issue is related to https://github.com/dotnet/wpf/issues/3817#?

Also probably related to: https://github.com/beto-rodriguez/LiveCharts2/issues/453

**Comment by EdenMeshulam28** [comment]
Issue is fixed with the solution described in #509 - intel graphics driver update.
@beto-rodriguez  Thx!

**Comment by tripleacoder** [comment]
I have the same issue on my Intel UHD 750 graphics card. 
It says the driver is already the latest version. Any ideas?
