### ISSUE TITLE
Winforms - Unable to change geomap background color

### ISSUE THREAD

**Issue by Andoo0** [beto-rodriguez/LiveCharts2#735]
**Describe the bug**
I am unable to change background color (GeoMap.BackColor) of GeoMap properly ----- Winforms

**Expected behavior**
I just want to change background color to black or transparent.

**Screenshots**
![screen](https://user-images.githubusercontent.com/101664057/200188213-fd5b132d-c3f6-4b6a-a8fc-796eb0e574eb.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Newest version of LiveCharts.Winforms

**Additional context**
Hello, I was trying to set background color of my geomap chart to black, but there are some problems.
Instead of changing the color to black, geomap changes the background color to 
![this](https://user-images.githubusercontent.com/101664057/200187988-84cab163-ea4e-4872-86e5-796ff795f25d.png)
I have also tried other colors but when I change the color to any other the color is again not accurate. (this is happening also when enabling the transparent option, the color again changes to (56, 74, 81).
I would be happy if there was any solution to change the background color to custom or at least to transparent.
Thanks for any help

**Comment by beto-rodriguez** [comment]
Hello, this is what I am doing, and it seems to work for me, am I missing something?

```c#
var chart = new GeoMap
{
    Series = new HeatLandSeries[]
    {
        new HeatLandSeries
        {
             Lands = new HeatLand[]
             {
                new HeatLand { Name = "bra", Value = 13 },
                new HeatLand { Name = "mex", Value = 10 },
                new HeatLand { Name = "arg", Value = 15 }
             },
             HeatMap = new[]
             {
                 new LvcColor(255, 0, 0),
                 new LvcColor(0, 0, 255)
             }
        }
    },
    MapProjection = LiveChartsCore.Geo.MapProjection.Mercator,
    Stroke = new SolidColorPaint(SKColors.Blue) { StrokeThickness = 2 },
    Fill = new SolidColorPaint(SKColors.Gray),
    BackColor = System.Drawing.Color.Black,
};
```

![image](https://user-images.githubusercontent.com/10853349/203871798-b03a5cae-6bb7-4ca4-963f-204c5a2aa6ec.png)

**Comment by H1-N1** [comment]
> Hello, this is what I am doing, and it seems to work for me, am I missing something?
> 
> ```cs
> var chart = new GeoMap
> {
>     Series = new HeatLandSeries[]
>     {
>         new HeatLandSeries
>         {
>              Lands = new HeatLand[]
>              {
>                 new HeatLand { Name = "bra", Value = 13 },
>                 new HeatLand { Name = "mex", Value = 10 },
>                 new HeatLand { Name = "arg", Value = 15 }
>              },
>              HeatMap = new[]
>              {
>                  new LvcColor(255, 0, 0),
>                  new LvcColor(0, 0, 255)
>              }
>         }
>     },
>     MapProjection = LiveChartsCore.Geo.MapProjection.Mercator,
>     Stroke = new SolidColorPaint(SKColors.Blue) { StrokeThickness = 2 },
>     Fill = new SolidColorPaint(SKColors.Gray),
>     BackColor = System.Drawing.Color.Black,
> };
> ```
> 
> ![image](https://user-images.githubusercontent.com/10853349/203871798-b03a5cae-6bb7-4ca4-963f-204c5a2aa6ec.png)

hi beto .
i hope you inswer my question
can we set heat color to over 100 value
a color for each range of value 0 to 200 ,200 to 400 ...
