### ISSUE TITLE
CartesianChart has drawing error

### ISSUE THREAD

**Issue by qz347655378** [beto-rodriguez/LiveCharts2#736]
https://user-images.githubusercontent.com/54021540/200452745-1e4ac9a0-2b90-4249-8de9-2fb0270d7b4d.mp4

![image](https://user-images.githubusercontent.com/54021540/200452796-b435b53b-32a4-45db-88bd-03913efc6293.png)

the component is **CartesianChart**

OS:Android

DevFramework:Xamarin.From

**Comment by beto-rodriguez** [comment]
Hi and thanks for the report!

Can I please get more details about the data you are trying to plot? how can I get this issue?

**Comment by qz347655378** [comment]
I use two ObservableValue arrays to save data, and add data to the two arrays at the same time, one of which adds data, and the other adds a data with a value of 0

**Comment by beto-rodriguez** [comment]
Thanks for the reply, I am not able to reproduce this issue, can you please share a minimal reproducible example so I can work on this issue?

**Comment by qz347655378** [comment]
https://user-images.githubusercontent.com/54021540/204128824-b7e12d28-9516-4ac4-bdc4-edb090296aff.mp4

`  
  public class MainPageViewModel : BindableBase
    {
        public MainPageViewModel()
        {
            PressSeries = new ObservableCollection<ISeries>
            {
                new LineSeries<ObservableValue>
                {
                    Values = PressChartSource,
                    Fill = null,
                    GeometrySize = 0,
                    LineSmoothness = 0.1,
                    Stroke = new SolidColorPaint(SKColor.Parse("4BC95F"),4)

                }
            };


            BlowSeries = new ObservableCollection<ISeries>
            {
                new LineSeries<ObservableValue>
                {
                    Values = BlowChartSource,
                    Fill = null,
                    GeometrySize = 0,
                    LineSmoothness = 0.1,
                    Stroke = new SolidColorPaint(SKColor.Parse("4BC95F"),4)

                }
            };


            StartCommand = new DelegateCommand(() =>
            {
                if (_timer == null)
                {
                    _timer = new Timer(150);
                    _timer.AutoReset = true;
                    _timer.Elapsed += OnAddData;
                    _timer.Start();
                }
            });

            StopCommand = new DelegateCommand(() =>
            {
                if (_timer != null)
                {
                    _timer.Stop();
                    _timer.Dispose();
                    _timer = null;
                }
            });

        }

        private int _index = 0;

        private readonly Random _random = new Random();

        private readonly ObservableValue _defaultValue = new ObservableValue(0);


        private void OnAddData(object sender, ElapsedEventArgs e)
        {

            if (_index <= 20)
            {
                PressChartSource.Add(new ObservableValue(_random.Next(0, 100)));
                BlowChartSource.Add(_defaultValue);

            }
            else
            {
                BlowChartSource.Add(new ObservableValue(_random.Next(0, 100)));
                PressChartSource.Add(_defaultValue);
            }

            _index++;

            if (_index >= 30)
            {
                _index = 0;
            }

            if (PressChartSource.Count >= 50)
            {
                PressChartSource.RemoveAt(0);
            }

            if (BlowChartSource.Count >= 30)
            {
                BlowChartSource.RemoveAt(0);
            }

        }


        public ObservableCollection<ObservableValue> PressChartSource { get; set; } = new()
        {
           new (0),
           new (0),
           new (0),
           new (0),
           new (0),
        };


        public ObservableCollection<ObservableValue> BlowChartSource { get; set; } = new()
        {
            new (0),
            new (0),
            new (0),
            new (0),
            new (0),
        };

        public DelegateCommand StartCommand { get; }

        public DelegateCommand StopCommand { get; }

        private Timer _timer;




        /// <summary>
        /// 按压数据
        /// </summary>
        public ObservableCollection<ISeries> PressSeries { get; set; }

        /// <summary>
        /// 吹气数据
        /// </summary>
        public ObservableCollection<ISeries> BlowSeries { get; set; }


        private Axis[] _yAxes =  {
            new () {
                IsInverted = true,
                LabelsPaint = new SolidColorPaint(SKColors.White)
            }
        };

        private Axis[] _blowYAxes =  {
            new () {

                LabelsPaint = new SolidColorPaint(SKColors.White)

            }
        };



        /// <summary>
        /// Y轴设置
        /// </summary>
        public Axis[] YAxes
        {
            get => _yAxes;
            set => SetProperty(ref _yAxes, value);
        }

        /// <summary>
        /// Blow Y轴设置
        /// </summary>
        public Axis[] BlowYAxes
        {
            get => _blowYAxes;
            set => SetProperty(ref _blowYAxes, value);
        }




    }`


The above is my ViewModel code, sorry I don't know how to use markdown。
Below is the code for ContentView。
I used prism as mvvm framework。

![QQ截图20221127175010](https://user-images.githubusercontent.com/54021540/204129022-ec59f6b9-dcdd-4bfb-8ea7-425f5c000f15.png)

**Comment by qz347655378** [comment]
Should be my problem, when I use 
`PressChartSource.Add(new ObservableValue(0))`
When replacing 
`PressChartSource.Add(_defaultValue)`
 the problem didn't work again
