### ISSUE TITLE
Memory leaks using CartesianChart 

### ISSUE THREAD

**Issue by mohelwazer** [beto-rodriguez/LiveCharts2#737]
using a simple CartesianChart leads to a consistent memory leak with WPF/C# and .NET6

1. Add a CartesianChart into a grid within a UserControl
2. bind chart's Series prop with an ObservableCollection<ISeries> type property within ViewModel
3. A button to navigate to another empty view
4. Navigate back to CartesianChart view

**Property within the ViewModel**

`public ObservableCollection<ISeries> Readings => new ObservableCollection<ISeries>
            {
                new LineSeries<double>
                {
                    Values = new double[] { 2, 1, 3, 5, 3, 4, 6 },
                    Fill = null
                }
            };`

**Xaml**

`<lvc:CartesianChart
            Series="{Binding Readings}"/>`

![image](https://user-images.githubusercontent.com/27537723/200739048-4e2ae1ac-a375-4915-9d6b-6ebfb1978afa.png)

**Comment by beto-rodriguez** [comment]
Hi

Does your ViewModel implements INotifyPropertyChanged? there is a known bug/issue that could cause memory leaks when the VM does not implement that interface.

https://michaelscodingspot.com/ways-to-cause-memory-leaks-in-dotnet/#:~:text=WPF%20Bindings%20can%20actually%20cause,a%20memory%20leak%20(explanation).

**Comment by mohelwazer** [comment]
The ViewModel is driving from custom ViewModelBase. ViewModelBase Implements INotifyPropertyChanged and IDisposable interfaces

**Comment by beto-rodriguez** [comment]
Strange, it does not happen in this repo, are there any steps to reproduce the issue?

**Comment by mohelwazer** [comment]
Sorry for the delay. I'm running more investigation regarding this problem to be sure your recommendations is in place correctly. I will revert back with the repo or closing of issue.

**Comment by mohelwazer** [comment]
@beto-rodriguez  Sorry for my very late reply. After a very careful consideration I believe that my concerns was due to other memory leaks on my code base. I will close this issue. On a side note LiveCharts2 is a great addition to the .net community, thanks for your hard work on it.

Thanks!

**Comment by beto-rodriguez** [comment]
Glad to read that! thanks for taking your time investigating the issue.
