### ISSUE TITLE
Chart loses focus after zooming

### ISSUE THREAD

**Issue by ajayre** [beto-rodriguez/LiveCharts2#742]
I use the MouseMove event to show the user the current X/Y of the mouse pointer (and some other things). I have X-axis zoom enabled. If I zoom using my mouse wheel then the MouseMove event stops firing at the end of the zoom.

It seems that zooming the chart causes the chart control to lose the focus. However I can still move the pointer over the chart without clicking on it and it still zooms with the mouse wheel.

How can I detect the end of zoom and re-focus the chart?

WinForms, CartesianChart

Thanks, Andy

**Comment by ajayre** [comment]
I managed to solve this by commented out

`Capture = true;`

in CartesianChart.OnMouseWheel. As far as I can tell zoom still works fine without the mouse capture. I didn't need zoom when the pointer was outside of the chart control anyway.

**Comment by beto-rodriguez** [comment]
That capture should be already removed in the master branch, where is your fork at?

**Comment by beto-rodriguez** [comment]
I am closing this, notice that this issue is already fixed in the last release.
