### ISSUE TITLE
Need help with WPF CandlestickSeries

### ISSUE THREAD

**Issue by DanielVampire** [beto-rodriguez/LiveCharts2#743]
Hi, i have question. I try to create candle chart with many point ~300.000. Created ISeries[] and add CandlestickSeries<FinancialPoint> with my points. Bind this ISeries to CartesianChart.Series. Also add zoom by X and crosshair.

When the graph appears, I get about 1-3 fps. I would like to know if the data should be submitted in some other way, or is this number of points too large?

Through the profiler I received the following data - long delay on SkElement
<img width="849" alt="image" src="https://user-images.githubusercontent.com/22197122/201324625-c093d31f-acd3-4714-9c82-fe174ed3fe32.png">

**Comment by beto-rodriguez** [comment]
Hello, this is an expected result, the library will have a high-performance package, but it is not public yet.

For more info see #486
