### ISSUE TITLE
LegendPosition interferes RightClick zoom

### ISSUE THREAD

**Issue by EniacMlezi** [beto-rodriguez/LiveCharts2#747]
**Describe the bug**
When enabling the Legend, something happens to the DrawMargin variables that gives rightclick zooming an offset. See what happens when Legend is Enabled vs Disabled: When Enabled, the zoomingsection box starts drawing with an initial height (about the height of the legend)

**To Reproduce**
1. In Lines/Zoom example, set zoom mode to both and enable legend position top
2. Use right click zoom on graph in example

**Expected behavior**
zoomingsection to NOT start drawing with an initial height

**Screenshots**
![ezgif-3-2f969e6d9d](https://user-images.githubusercontent.com/15785664/201336837-78cbb51c-4c22-4514-aa46-eed7fa88f42c.gif)

**Comment by beto-rodriguez** [comment]
This was fixed in https://github.com/beto-rodriguez/LiveCharts2/pull/1021  thanks for the report!
