### ISSUE TITLE
WPF throws "Exception: core not set yet" When using UpdaterThrottler property

### ISSUE THREAD

**Issue by EricEzaM** [beto-rodriguez/LiveCharts2#750]
**Describe the bug**
Crash when using UpdateThrottler

**To Reproduce**
Clone LiveCharts repo
Edit `samples/WPFSample/Scatter/Basic/View.xaml` and use 
```xml
<lvc:CartesianChart Series="{Binding Series}" UpdaterThrottler="00:00:01"></lvc:CartesianChart>
```
Run WPF sample
Go to scatter/basic
Application crashes

**Expected behavior**
No Crash

**Desktop (please complete the following information):**
WIN 10

**Comment by EricEzaM** [comment]
Does UpdateThrottler even work? I can't see it being used anywhere and it does not seem to do anything when I set it in a `Loaded` event handler.

**Comment by beto-rodriguez** [comment]
Thanks for the report, this is already fixed and will be included in the next version of the library, see #699 for more info.

**Comment by EricEzaM** [comment]
Oops, sorry I didnt see that issue!
