### ISSUE TITLE
Stuck when using custom font (TypeFace) in Linux

### ISSUE THREAD

**Issue by bsdayo** [beto-rodriguez/LiveCharts2#751]
**Describe the bug**
I'm rendering a cartesian chart in a console application, and setting custom font to the axis like this:
```csharp
var yAxes = new[]
{
    new Axis
    {
        LabelsPaint = new SolidColorPaint(SKColors.Black)
        {
            SKTypeface = SKTypeface.FromFile("fonts/TitilliumWeb-Regular.ttf")
        },
        TextSize = 40,
    }
};

chart.YAxes = yAxes;
```

The program got stuck when I called these methods:
```csharp
chart.GetImage()
// or
chart.SaveImage("chart.png")
```

But after I commented these line:
```csharp
// LabelsPaint = new SolidColorPaint(SKColors.Black)
// {
//     SKTypeface = SKTypeface.FromFile("fonts/TitilliumWeb-Regular.ttf")
// },
```
The application will render it successfully, and won't stuck again.

But this issue will not perform in Windows, as I set custom font then it will not get any problem.

**Expected behavior**
The application will not stuck in rendering chart, when a custom font is set.

**Environment**
 - OS: Arch Linux
 - .NET version: 7.0.100
 - LiveChartsCore.SkiaSharpView version: 2.0.0-beta.516

**Additional context**
The newest version of package `SkiaSharp.NativeAssets.Linux.NoDependencies` (2.88.3) is installed.

**Comment by beto-rodriguez** [comment]
There must be something missing on the SkiaSharp side, sadly it is not in the hands of this library to fix this.

I will close this for now, but we can probably find a solution for this in the SkiaSharp repo.
