### ISSUE TITLE
Label on XAxis for DateTime Point series not displayed properly

### ISSUE THREAD

**Issue by emanuelevaini** [beto-rodriguez/LiveCharts2#752]
**Describe the bug**
I have DateTime data that I want to show using a lineSeries.
I tried adapting the example on site [LINK](https://lvcharts.com/docs/Maui/2.0.0-beta.330/samples.axes.dateTimeScaled) but it seems Xaxis only shows datetime in numerical format.

**To Reproduce**
Try to adapt the cited example on data every 5 minutes

**Expected behavior**
I'd like to see time in HH:mm:ss formato on axis X

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/60423698/201971912-7903c5df-0ebb-41a1-a3fa-64c5af1679ef.jpg)

**Additional context**
I am using Visual Studio 2022 with .Net Maui

**Comment by Albert634515** [comment]
How does your axis label look like?
In WinForms I use something like this:
`      var xaxes = new List<Axis>
            {
                new Axis
                {
                    Labeler = value => new DateTime((long) value).ToString("dd/MM/yyyy"),
                    LabelsRotation = 15,
                    Position = AxisPosition.Start,
                    MinStep = TimeSpan.FromDays(value).Ticks,
                    UnitWidth = TimeSpan.FromDays(value).Ticks
                }
            };`

**Comment by VainiEmanuele** [comment]
Thanks @Albert634515!
I reviewed my code and found a trivial double designation for Axis... and obviously one was incorrect!
Therefore my code is now perfectly working.

In XAML:

` <lvc:CartesianChart Grid.Row="1" Margin="0"  HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand" HeightRequest="200"
                Series="{Binding PointSeries}"     XAxes="{Binding XAxes}">`
 

Where:
` public Axis[] XAxes { get; set; } =
        {
        new Axis
        {
             Labeler = value =>  new DateTime((long) value).ToString("T"),
            LabelsRotation = 15,
            UnitWidth = TimeSpan.FromMinutes(1).Ticks, 
            MinStep = TimeSpan.FromMinutes(1).Ticks,           
        }

public ISeries[] PointSeries { get; set; } =
  {
        new LineSeries<DateTimePoint>
        {
              TooltipLabelFormatter = (chartPoint) =>
                $"{new DateTime((long) chartPoint.SecondaryValue):HH:mm:ss}: {chartPoint.PrimaryValue}",

_[Values are added runtime]_         
 Fill=new SolidColorPaint(SKColors.Transparent),
            Stroke=new SolidColorPaint(SKColors.IndianRed){ StrokeThickness = 5 } ,
            GeometryStroke=new SolidColorPaint(SKColors.IndianRed),
            GeometryFill=new SolidColorPaint(SKColors.IndianRed) `
