### ISSUE TITLE
Y Axis label on stacked chart with value of -100M (-1e8) displays as "-100000000000000 μ"

### ISSUE THREAD

**Issue by EdGuiness** [beto-rodriguez/LiveCharts2#754]
**Describe the bug**
I have a stacked bar chart with large positive and negative values (range +/- 100B) and I find that when a value crosses a threshold of -100M (-1e8 or -100000000) the default labels on the Y-Axis show as "-100000000000000 μ"

**To Reproduce**

Here's the simplest code that shows the problem.

It's a dotnet 5 aspnet web app using prerelease livecharts packages.

```csharp
// ------------  Program.cs
var builder = WebApplication.CreateBuilder(args);
builder.Services.AddMvc();
builder.Services.AddControllers();
var app = builder.Build();
app.MapDefaultControllerRoute();
app.Run();

// ------------ HomeController.cs
using LiveChartsCore;
using LiveChartsCore.SkiaSharpView;
using LiveChartsCore.SkiaSharpView.SKCharts;
using Microsoft.AspNetCore.Mvc;
using SkiaSharp;

public class HomeController : ControllerBase
{
    [Route("/")]
    public FileStreamResult StackedBarChart()
    {
        var chart = new SKCartesianChart
        {
            Series = new List<ISeries>
            {
                new StackedColumnSeries<decimal> {Values = new [] {1e8m}},
                new StackedColumnSeries<decimal> {Values = new [] {-1e8m}},
            }
        };

        return
            new FileStreamResult(chart.GetImage().Encode(SKEncodedImageFormat.Png, 100).AsStream(), "image/png");
    }
}
```

**Expected behavior**
The Y axis labels for the large negative values should be consistent with the positive values, "100M" and "-100M" instead of "100M" and "-100000000000000 μ"

**Screenshots**
![image](https://user-images.githubusercontent.com/979705/202141520-cd84c24a-32af-4d0c-9329-92081c435657.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Edge
 - Version: 107.0.1418.42 (Official build) (64-bit)

**Comment by beto-rodriguez** [comment]
This is fixed and will be included in the next version of the library, thanks for the report!
