### ISSUE TITLE
Very simple CartesianChart hangs an entire WinForms application

### ISSUE THREAD

**Issue by rafabernal** [beto-rodriguez/LiveCharts2#755]
**Describe the bug**
I have found a very simple Series data that, when applied to a CartesianChart and let the user make a few zoom-in/zoom-out, the entire application got freezed.
The bug only applies when "cartesianChart.ZoomMode" is set to "ZoomAndPanMode.X". If the property is set to "ZoomAndPanMode.Both" it works fine.
Find attached a Visual Studio solution with the source code ready to reproduce the bug.

**To Reproduce**
1. Start demo app using Visual Studio 2022
2. Click 'Fill chart' button
3. Make a few zoom-in/pan/zoom-out with the mouse
4. Application should got freeze on this point
5. Try again, but selecting ZoomAndPanMode.Both. Now it should works OK.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - .NET 4.6.2 and 6.0

(thanks for this chart library! It's really the best charting package for WPF/WinForms)

![image](https://user-images.githubusercontent.com/22178264/202183670-1334e96f-ee89-40db-a388-21d326dad082.png)
[LiveCharts2_BugHang.zip](https://github.com/beto-rodriguez/LiveCharts2/files/10021755/LiveCharts2_BugHang.zip)

**Comment by dvpot** [comment]
To avoid creating new questions, I'll add mine here as my question is similar to this one.

Application hangs with zero values using DateTimePoint series - found this bug in my application during tests.

How you can reproduce such a bug:
1. Take an example from here: https://lvcharts.com/docs/WPF/2.0.0-beta.330/samples.axes.dateTimeScaled
2. Add new points with value = 0 at the end, beginning or middle (about 10 of them).
3. Add to XAML ZoomMode="X".
4. Start the project and zoom in the area where the values are 0.

Result - the application is frozen, no errors appear, the application process is loaded to about 35%.

What could be the problem, I do not understand?
But this only happens with values "0" at the end, beginning or in the middle of the graph.

**Comment by dongyi-cai-windsab** [comment]
Same issue here.

Using .NET Framework 4.6.2. Similar data as described. But I'm using ` ZoomMode="X"` instead of ZoomAndPanMode.X

**Comment by beto-rodriguez** [comment]
Thanks for the sample and the feedback!

I was able to identify the issue, this is fixed with the referenced commit and will be included in the next version of the library (beta 700).
