### ISSUE TITLE
Not Supported displaying Korean character.

### ISSUE THREAD

**Issue by kimbominsn** [beto-rodriguez/LiveCharts2#758]
**Describe the bug**
I'm trying to use gauge3 piechart.
But some characters are cracked.
Korean characters Like "시간", "주", .. etc 

**To Reproduce**
1. Go to '...' : https://lvcharts.com/docs/winforms/2.0.0-beta.330/samples.pies.gauge3
 -> Exactly same code but this part below.
[ObservableObject]
public partial class ViewModel
{
    public IEnumerable<ISeries> Series { get; set; }
        = new GaugeBuilder()
        .WithLabelsSize(20)
        .WithLabelsPosition(PolarLabelsPosition.Start)
        .WithLabelFormatter(point => $"{point.PrimaryValue}시간 {point.Context.Series.Name}")
        .WithInnerRadius(20)
        .WithOffsetRadius(8)
        .WithBackgroundInnerRadius(20)

        .AddValue(4, "이동시간")
        .AddValue(11, "수확시간")

        .BuildSeries();
}
3. Build and run
4. See error : the character "시간", "이동시간", "수확시간" shown with rectangles..

**Expected behavior**
Expected : 4시간 이동시간 , 11시간 수확시간

**Screenshots**
![image](https://user-images.githubusercontent.com/99714036/202604812-ec06a543-1df8-492e-83f8-78b63bf9279c.png)

**Desktop (please complete the following information):**
 - OS: windows10
 - Version [e.g. 22] : 21H2

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Asyvix** [comment]
아마 폰트의 CJK지원이 안되어서로 예상됩니다. CustomFont로 한국어 폰트를 이용하여 테스트가 필요할듯합니다.

i guess font not support cjk by default. i think need test again with cjk supported fonts.

**Comment by beto-rodriguez** [comment]
This should be supported, please see https://lvcharts.com/docs/WinForms/2.0.0-beta.330/samples.axes.labelsFormat2

**Comment by kimbominsn** [comment]
> This should be supported, please see https://lvcharts.com/docs/WinForms/2.0.0-beta.330/samples.axes.labelsFormat2

Thanks for reply.
I saw the page about fontfamily, but still don't know how to apply it on GaugeBuilder().
Can you give me sample code ? Sorry for bothering you.

**Comment by beto-rodriguez** [comment]
This should make the trick:

```c#
new GaugeBuilder()
        .WithMaxColumnWidth(30)
        .AddValue(
            new(30),
            "Series Name",
            new SolidColorPaint(SKColors.Red),
            new SolidColorPaint
            {
                Color = SKColors.Black,
                SKTypeface = SKFontManager.Default.MatchCharacter('시')
            })
        .BuildSeries();
```

I think this needs a better way to do it.

**Comment by kimbominsn** [comment]
> It works well.
Thanks for your help.
