### ISSUE TITLE
Uno.WinUi, iOS and MacCatalyst: Glitched rendering of CartesianChart

### ISSUE THREAD

**Issue by baskren** [beto-rodriguez/LiveCharts2#759]
### Description 
LiveChartsCore.SkiaSharpView.Uno.WinUI, Version="2.0.0-beta.516"
On iOS and MacCatalyst, when adding points to a Cartesian Chart, it appears that canvas is not cleared between animation passes.

### Steps to reproduce
1. Download the following demo project
        [UnoLiveCharts.zip](https://github.com/beto-rodriguez/LiveCharts2/files/10050503/UnoLiveCharts.zip)

2. Build, deploy and run the above project to either iOS or MacCatalyst

### Expected behavior
Canvas should be cleared between each animation frame

#### iOS
https://user-images.githubusercontent.com/2528888/202921479-95f82a08-abd7-4d3e-8a50-f68fc0760d24.mov

#### MacCatalyst
https://user-images.githubusercontent.com/2528888/202921549-0c1bd87f-5a30-44d4-afa4-e3d861e9b912.mov

### Desktop (please complete the following information):
 - OS: MacOS 
 - Device: 2019 16" MacBook Pro
 - Version : Ventura 13.0.1 (22A400)

### Smartphone (please complete the following information):
 - Device: iPhone 14
 - OS: iOS 16.1

**Comment by beto-rodriguez** [comment]
Hello

I will close this issue, we can track this at https://github.com/beto-rodriguez/LiveCharts2/issues/1512, this is also reported in the Uno repo.
