### ISSUE TITLE
Permanent hang/freeze when using DateTimePoint data and only plotting one datapoint WPF

### ISSUE THREAD

**Issue by EricEzaM** [beto-rodriguez/LiveCharts2#763]
**Describe the bug**
Permanent application hang, appears to trigger when plotting a chart using DateTimePoint data and having only one datapoint.

**To Reproduce**
1. Using the LiveCharts sample...
2. Run and Navigate to `Axes/DateTimeScaled` - note how the chart displays / no hang.
3. Close app
4. Open `samples/ViewModelsSamples/Axes/DateTimeScaled/ViewModel.cs` in editor.
5. Comment out or remove all values **except one** 
6. Open the view for Axis/DateTimeScaled - remove axis binding
7. Run the app and navigate to `Axes/DateTimeScaled` - no chart appears, application is now permanently hung/frozen.

**Expected behavior**
No hang
Note this does **not** occur when using the basic line chart with only one point.

**Desktop (please complete the following information):**
WIN 10, WPF

**Additional context**
I attached dotTrace during the hang, and this is the callstack/tree
![image](https://user-images.githubusercontent.com/41730826/203176949-e4bf0f52-6af5-4517-8ee7-c87535ff1b96.png)

**Comment by EricEzaM** [comment]
It appears setting `UnitWidth` to a non-default value resolves this issue.

**Comment by beto-rodriguez** [comment]
Fixed with the referenced commits and will be included in the next version (beta 700) Thanks for the report.
