### ISSUE TITLE
Tooltip display position bug in chart between 0 and 1

### ISSUE THREAD

**Issue by powerpdw** [beto-rodriguez/LiveCharts2#764]
**Describe the bug**
When axis range is 0~1, tooltip display position is wrong.

**To Reproduce**
1. Project: ViewModelsSamples, In VisualStudio
2. Open Scatter-Basic-ViewModel.cs
3. Modify the point values as shown below.
<img width="355" alt="image" src="https://user-images.githubusercontent.com/51893532/203191157-cbd524dd-ee0c-4d07-ab16-ef221813620d.png">
4. Build and Execute WinUISample.exe
5. When you select the Scatter-Basic chart, you can see that the location of the tooltip is wrong.

**Expected behavior**
The tooltip should be displayed near the point

**Screenshots**
<img width="490" alt="image" src="https://user-images.githubusercontent.com/51893532/203190392-40271b1c-b77d-4762-b5e0-90a5952b8d3b.png">

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser : Not used. It's WinUI3 Environment

**Additional context**
I modified the code temporarily as follows. I hope it's useful.
Project: LiveChartCore
File: ScatterSeries.cs
Method: public override void Measure(Chart<TDrawingContext> chart)

```
//Changes to correct problems where tooltips are not displayed properly in a range of less than 1
//uwx = uwx < gs ? gs : uwx;
//uwy = uwy < gs ? gs : uwy;
uwx = (uwx > 1) ? (gs + 2) : (uwx < gs ? gs : uwx);
uwy = (uwy > 1) ? (gs + 2) : (uwy < gs ? gs : uwy);

```

**Comment by beto-rodriguez** [comment]
This was fixed with https://github.com/beto-rodriguez/LiveCharts2/pull/1028

![tt](https://github.com/beto-rodriguez/LiveCharts2/assets/10853349/971ea779-7504-47bd-be5f-969bfacf347a)

Thanks for the report!
