### ISSUE TITLE
Stacked bar chart becomes a line when using the Axis IsInverted property

### ISSUE THREAD

**Issue by kojima-imamura** [beto-rodriguez/LiveCharts2#769]
When I use StackedRowSeries and set [IsInverted = true] on the axis labels, the display is strange.

![image](https://user-images.githubusercontent.com/118875864/203480503-b8d0027a-ab5a-4eae-8d0c-85854d4fe69c.png)

![image](https://user-images.githubusercontent.com/118875864/203480408-b4b153d9-018a-44fb-af03-704c2c007ce9.png)

Setting [Padding = 0] and [MaxBarWidth = double.PositiveInfinity] has no effect.

**Comment by kojima-imamura** [comment]
WPF Default Sample
![image](https://user-images.githubusercontent.com/118875864/204469635-1bd28594-5bec-4c8f-9880-f284caaf2be5.png)

Using the IsInverted option.

![image](https://user-images.githubusercontent.com/118875864/204468711-99e8b3bf-277b-46b9-9313-4aca62c11b93.png)

.\LiveCharts2-master\samples\WPFSample\StackedBars\Basic\View.xaml
Edit Code
`<lvc:CartesianChart Series="{Binding Series}">` 
-->`<lvc:CartesianChart Series="{Binding Series}" XAxes="{Binding XAxis}">`

.\LiveCharts2-master\samples\ViewModelsSamples\StackedBars\Basic\ViewModel.cs
Add Code
`    public Axis[] XAxis { get; set; } =
    {
        new Axis
        {
            IsInverted = true
        }
    };`

**Comment by beto-rodriguez** [comment]
Thanks for the report, fixed with the referenced commit and will be included since beta 700.
