### ISSUE TITLE
.NET Maui (7.0)  - IOS 

### ISSUE THREAD

**Issue by biromatik** [beto-rodriguez/LiveCharts2#770]
**Describe the bug**
Default instalation guide (https://lvcharts.com/docs/maui/2.0.0-beta.330/Overview.Installation) throws following error when app is loaded.

Problem is on IOS. On android is OK.

`System.TypeInitializationException: 'The type initializer for 'SkiaSharp.SKObject' threw an exception.'`

We are using:
VS 2022 - 17.4.1
MAUI .NET 7.0

**To Reproduce**
Follow steps from link.

**Desktop (please complete the following information):**
 - OS: [iOS]

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone13]
 - OS: [e.g. iOS16]

**Comment by beto-rodriguez** [comment]
Thanks for the issue, I am closing this, we can track this issue at #800

**Comment by canperk** [comment]
You mentioned 2 issues each other and closed both of them :)

**Comment by beto-rodriguez** [comment]
No I did not.
