### ISSUE TITLE
WPF: Changes on InnerRadius of PieChart affect position of labels

### ISSUE THREAD

**Issue by riccardo-pizzuti** [beto-rodriguez/LiveCharts2#771]
**Describe the bug**
If a pie chart is transformed to a doughnut chart by increasing the InnerRadius from 0 to e.g. 50 the labels (DataLabelsPosition = PolarLabelsPosition.Outer) also move away from the outer radius of the chart and are no longer visible in the chart area.

**To Reproduce**
1. Create WPF application with a pie chart and add a set of values
2. Add some labels with content and set the property DataLabelsPosition to value PolarLabelsPosition.Outer
3. Start your application to ensure that the pie chart fits into your chart area (see e.g. attached screenshot of pie chart)
4. Stop your application
5. Set the property InnerRadius of your chart to e.g. 50 and run the application again
6. The labels of the displayed doughtnut chart have increased their distance and are only partially visible (see e.g. attached screenshot of doughnut chart)

**Expected behavior**
Changes of the InnerRadius have no impact on the positions of the labels and do not move them away from the chart.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/118933349/203632495-aefcac26-7649-44a2-8d57-069c64f83c16.png)
![grafik](https://user-images.githubusercontent.com/118933349/203632523-2548b8ec-adf7-44fa-9801-bf2cc141ffcc.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 22H2
 - Browser: NA --> WPF on desktop
 - Version: LiveChartsCore.SkiaSharpView.WPF 2.0.0-beta.516

**Comment by beto-rodriguez** [comment]
Thanks for the report, this is fixed with the referenced commit and will be included since version beta 700.
