### ISSUE TITLE
LegendTemplate MAUI compile error missing Property Name

### ISSUE THREAD

**Issue by pocki** [beto-rodriguez/LiveCharts2#772]
**Describe the bug**
.NET MAUI Compile error XFC0045	Binding: Property "Name" not found on "MyProject.ViewModels.MyViewModel".
When using LegentTemplate in CartesianChart.

**To Reproduce**
1. Add CartesianChart in XAML
2. Add LegendTemplate like in the same or [original](https://github.com/beto-rodriguez/LiveCharts2/blob/acb5a24dca791161dc28b97e4632e92725bd5eb1/src/skiasharp/LiveChartsCore.SkiaSharpView.Maui/DefaultLegend.xaml#L25)
3. Build fail because on Name (in Label Text) is not found in ViewModel, but should be from Legend

**Expected behavior**
Compile successfully and show Series Name in Legend

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Android]

**Smartphone (please complete the following information):**
 - Device: [e.g. Android Emulator]
 - OS: [e.g. Android 9.0]

**Additional context**
.NET MAUI with .NET7 
LiveChartsCore.SkiaSharpView.Maui v2.0.0-beta.516

**Comment by beto-rodriguez** [comment]
This changed in the latest version will update docs in few hours, meanwhile you can get more info about this at https://github.com/beto-rodriguez/LiveCharts2/issues/816#issuecomment-1348759920.
