### ISSUE TITLE
Multi Labels will diplay when assigning values to the Series more than once.

### ISSUE THREAD

**Issue by alexly2048** [beto-rodriguez/LiveCharts2#774]
**Describe the bug**
The PieChart property Series is binging to one property, when I using GaugeBuilder class to creating one new series and assign this to the property, then the Labe in the PieChart will display the labels as many as the times I set value to the property.

**To Reproduce**
1. Create one view instance, the view has one property Series which type is ObservableCollection<PieSeries<LiveChartsCore.Defaults.ObservableValue>>.
2. Binding view to DataContext:  DataContext = view;
3. In the load event method, building series by using GaugeBuilder
```
     var series = new GaugeBuilder()
                           .WithLabelsPosition(LiveChartsCore.Measure.PolarLabelsPosition.ChartCenter)
                           .WithLabelsSize(20)
                           .WithLabelFormatter(point => { return string.Format("{0}%", point.PrimaryValue); })
                           .WithInnerRadius(40)
                           .WithBackgroundInnerRadius(40)
                           .AddValue(10)
                           .BuildSeries();
```
4. Setting Series with new series.
```
view.Series = new ObservableCollection<PieSeries<LiveChartsCore.Defaults.ObservableValue>>(series);
```
5. When I open the chart control instance again, the labels in the chart will display many times. In my project, the control that hold the chart is singleton instance.
6. The binding code as following:
```
<lv:PieChart
                Name="test"
                Series="{Binding SeriesData}"
                Total="{Binding GaugeTotal}"
                InitialRotation="-90">
            </lv:PieChart>
```
**Expected behavior**
The lable in the chart should only display once.

**Screenshots**
![1](https://user-images.githubusercontent.com/16357510/203922649-dff438a9-d45f-4514-9eb0-f189c5741508.png)

**Comment by beto-rodriguez** [comment]
I am not completely sure if this is a LiveCharts issue, it seems that your data is a singleton, but your view creates multiple instances using the same data? am I correct?

Could you please provide a small repository or test project where I can see what you are trying to do?

**Comment by beto-rodriguez** [comment]
I will close this for now, please feel free to add more information when you find evidence that the issue belongs to LiveCharts.
