### ISSUE TITLE
ISeries does not implement "Tag"

### ISSUE THREAD

**Issue by Tremlton** [beto-rodriguez/LiveCharts2#775]
**Is your feature request related to a problem? Please describe.**
I have a custom Visibility Toggle for my Chart but its hard to compare the Tag to my Toggle.
RowSeries, LineSeries, ColumnSeries, etc. all of those have the Tag Property

I currently do it like this
![image](https://user-images.githubusercontent.com/85153099/204011189-60b288b3-de2e-46ca-8025-60f7985cdf7a.png)

**Describe the solution you'd like**
Can the Tag be implemented inside of ISeries?

**Comment by beto-rodriguez** [comment]
Yes, this is by design, for now the `ISeries` type does not include the `Tag` property, please cast it to the type of your series, or hold a reference to the actual type.
