### ISSUE TITLE
CandleStick series interpolating DateTime values on the XAxis

### ISSUE THREAD

**Issue by polymorphicshade** [beto-rodriguez/LiveCharts2#778]
I noticed the CandleStick series is inserting blank days in my data (daily candlesticks):
![image](https://user-images.githubusercontent.com/32504507/204111988-bce0f365-fb1f-44b9-8362-ef2865a92251.png)

The chart displays days on the XAxis where no data exists. I'm assuming this is because it is filling in missing days.

My data has no missing or NULL values, but it does skip days (i.e. weekends, since I'm pulling in NASDAQ stock data).

How could I configure my chart to hide or collapse missing XAxis data points on the chart?

**Comment by tretom2121** [comment]
Just a thought to this topic:
Plotly.Blazor has a concept of RangeBreaks on the X axis.
I found it quite good.
It's something like:
                    RangeBreaks = new List<RangeBreak>()
                    {
                        new RangeBreak()
                        {
                            Pattern = PatternEnum.DayOfWeek,
                            Bounds = new List<object> { 6, 1}
                        },
                        new RangeBreak()
                        {
                            Pattern = PatternEnum.Hour,
                            Bounds = new List<object> { 21, 7}
                        },
                    }

Something like this would be great. It's more flexible than an On/Off gaps.

**Comment by beto-rodriguez** [comment]
A couple of versions ago I added the `FinancialPointI` class, with this object is easier to achieve this, here is an example:

https://github.com/beto-rodriguez/LiveCharts2/blob/dev/samples/ViewModelsSamples/Financial/BasicCandlesticks/ViewModel.cs

The next docs version in the web site will include this example by default.
