### ISSUE TITLE
Tooltip problem

### ISSUE THREAD

**Issue by alexachso** [beto-rodriguez/LiveCharts2#781]
**Describe the bug**
The tooltip does not work as intended.

**To Reproduce**
Create any cartesian chart with a simple series. 
Hover the mouse over the points in the chart. The first point it renders will show the correct Y value but if you hover the mouse to another point the Y value stays the same in the tooltip.

**Expected behavior**
The Y value in the tooltip should change.

**Screenshots**

https://user-images.githubusercontent.com/12586000/204292430-7828e754-aa55-4376-ba5d-7bd1b5b3372b.mp4

https://user-images.githubusercontent.com/12586000/204292437-8e6e8acd-c16e-4a7d-9139-4452582cc09f.mp4

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
livecharts2 version beta.601

**Comment by beto-rodriguez** [comment]
🤔 this was a big one, I just published `beta.602` with a fix for this issue, thanks for the report!

**Comment by alexachso** [comment]
No worries, Thank you for all that you are doing!
