### ISSUE TITLE
Default update throttling behavior changed

### ISSUE THREAD

**Issue by pkindruk** [beto-rodriguez/LiveCharts2#786]
Fix for #699 changed sets default value for `IChartView.UpdaterThrottler` to `TimeSpan.Zero`. Previously `ActionThrottler.ThrottlerTimeSpan` default value was `TimeSpan.FromMilliseconds(50)`.

This behavior can be potentially breaking for consumers who used library as is without trying to specify it explicitly. For me it introduced app freeze for a long time in common usecases of my app.

**Comment by beto-rodriguez** [comment]
Fixed with #787
