### ISSUE TITLE
LiveChartsCore.SkiaSharpView.Blazor: zh-CN content becomes squares

### ISSUE THREAD

**Issue by LeaFrock** [beto-rodriguez/LiveCharts2#793]
**Describe the bug**

First of all, I've seen the previous issues #140 #347 #636 . The solutions of them do not work for me (which make me 😕 & 😞 ).

I have a hosted blazor wasm project (ASP.NET Core 6) which uses livechart2 and runs on CentOS. 

The first version of `LiveChartsCore.SkiaSharpView.Blazor` I used is `2.0.0-beta.513`.

### Bug 1: About Legends

The chart looks like the image below,

![1669876422788](https://user-images.githubusercontent.com/20787265/204982281-57639eb5-4f47-4758-81c6-613a7d060119.png)

When the lib version is <= `2.0.0-beta.516`, the Chinese chars are shown well in the legends. But after `2.0.0-beta.600`, they become squares.

### Bug 2: About Axis Name Paint

This bug exists for all versions since `beta.513`. When I'm trying to use Chinese as the axis name, 

```csharp

        public Axis[] XAxes { get; set; } = new Axis[]
        {
            new Axis
            {
                Name = "日期",
                Labels = Array.Empty<string>(),
                LabelsRotation = 60,
                NamePaint = new SolidColorPaint()
                {
                    Color= SKColors.Black,
                    SKTypeface = SKFontManager.Default.MatchCharacter('汉')，// Solution 1
                    // SKTypeface = SKTypeface.FromFamilyName("Microsoft YaHei UI")，// Solution 2
                    // FontFamily = "Microsoft YaHei UI" // Solution 3
                }
            }
        };

```

All the three solutions do not work and the browser console shows `System.DllNotFoundException: libHarfBuzzSharp` exceptions like below,

![1669877807495](https://user-images.githubusercontent.com/20787265/204986153-431600d0-2698-4103-90ae-565736a7a1c2.png)

**To Reproduce**

All related code of the project are limited to the basic usage of `CartesianChart`.

The only difference is that I want to take Chinese characters as the legend and axis name.

**Expected behavior**

Show zh-CN characters correctly.

**Desktop (please complete the following information):**
 - OS: [Win10 22H2]
 - Browser [Edge 107.0.1418.62]
 - Version [2.0.0-beta.603]

**Comment by zylalx1** [comment]
Same problem (Bug 1) and solved. 
The method of setting FontFamily has changed. In previous versions you set LegendFontFamily and TooltipFontFamily, but these properties have been removed in beta.600. 

Try this:
`
MyChart.LegendTextPaint = new SolidColorPaint { Color = SKColor.Parse("FF000000"), FontFamily = "Microsoft YaHei UI" };
MyChart.TooltipTextPaint = new SolidColorPaint { Color = SKColor.Parse("FF000000"), FontFamily = "Microsoft YaHei UI" };
`

**Comment by LeaFrock** [comment]
@zylalx1 Thanks for your comment. If so, that's a break change because the legend used to work well even though you don't clarify `LegendTextPaint` at all before `beta.600`.

```html
<CartesianChart 
                        Series="ChartViewModel.Series"
                        XAxes="ChartViewModel.XAxes"
                        YAxes="ChartViewModel.YAxes"
                        LegendPosition="LiveChartsCore.Measure.LegendPosition.Right" />
```

Also, once I take your suggestion, the bug 2 appears again. It seems the native `.dll` does not support broswer, at least I don't find it in the published `runtime/browser` file (but do find in `runtime/win-x64`).

![1669945686384](https://user-images.githubusercontent.com/20787265/205196241-571839bb-f6dd-4248-9598-7013dd70164b.png)

**Comment by beto-rodriguez** [comment]
Yes, the API changed to what @zylalx1 mentioned, the docs will be updated soon.

I also get the error message in the WASM sample even when trying your suggestion @zylalx1, need to investigate this further.

You can see the error here: https://blazor-livecharts.controli.app/Axes/LabelsFormat2

**Comment by MithrilMan** [comment]
FYI I fixed the issue of missing DLL (on my Blazor WASM project) by dong this:

I've added an explicit reference to
`<PackageReference Include="HarfBuzzSharp.NativeAssets.WebAssembly" Version="2.8.2.3" />`

I've added an explicit NativeFileReference
```
<ItemGroup>
      <NativeFileReference Include="$(HarfBuzzSharpStaticLibraryPath)\2.0.23\*.a" />
   </ItemGroup>
```

info source: https://github.com/mono/SkiaSharp/issues/1725#issuecomment-988044531

**Comment by beto-rodriguez** [comment]
Yes @MithrilMan that seems to fix the issue, I was able to make this work with #848. I will explain that in the docs in the next version of the library.

[This](https://github.com/beto-rodriguez/LiveCharts2/blob/337a17a2cb2d68b1fd027ef21df3af70d992a7cf/samples/BlazorSample/Pages/Axes/LabelsFormat2.razor) is how to setup things in the next version of the library, HarfBuzz must be explicitly included (SkiaSharp bug?)

```
<ItemGroup>
    <NativeFileReference Include="$(HarfBuzzSharpStaticLibraryPath)\2.0.23\*.a" />
 </ItemGroup>
```
