### ISSUE TITLE
SKCartesianChart: Bad calculation of ScaleDataToPixels in some cases

### ISSUE THREAD

**Issue by dlucazeau** [beto-rodriguez/LiveCharts2#795]
I use the two libraries mentioned in the Desktop part to build charts and embed them in mails.
I already have several operational ones. I'm doing a console program to develop this new graph.
I thank you for all your work on which I build mine. 

**Bug Description**
The pixel coordinates of the origin (0,0), computed with the ScaleDataToPixels() method of SKCartesianChart are good if the legend is placed on the right or on the bottom. But they are not good if the legend is placed on the top or on the left.
The images are based on the same code, only the location of the legend changes from one image to another.
I use the coordinates of the origin to draw my circle reference lines.

**To Reproduce**
The main code used is attached.

**Expected Behavior**
The calculation done by ScaleDataToPixels should be correct regardless of the location of the legend.

**Screenshots**
![image](https://user-images.githubusercontent.com/4538922/205071478-443e3e65-b96d-4036-8e54-d439508c94a7.png)
![image](https://user-images.githubusercontent.com/4538922/205071837-684f25c1-23aa-4364-83ec-caa15625a0f2.png)
![image](https://user-images.githubusercontent.com/4538922/205071919-9fc8f480-0417-45b0-a671-87efdd1ba08d.png)
![image](https://user-images.githubusercontent.com/4538922/205071967-02e7daa6-67e4-4c94-8f9e-848b83acc41b.png)

and hidden :
![image](https://user-images.githubusercontent.com/4538922/205072033-b18024c0-1be7-4f38-9cd3-b02f85c89d90.png)

**Desktop:**
 - OS: Windows 10
 - Browser No browser, it's a console application with a SaveImage()
 - Version LiveCharts.Core@0.9.8 & SkiaSharp@2.88.3

[sample-code.txt](https://github.com/beto-rodriguez/LiveCharts2/files/10133139/sample-code.txt)

**Comment by beto-rodriguez** [comment]
This is now fixed and this case was added to test, thanks for the report, it will be included in the next version of the library.
