### ISSUE TITLE
Chart legend layout properties Xamarin Forms (layout issues)

### ISSUE THREAD

**Issue by vadimffe** [beto-rodriguez/LiveCharts2#796]
**Describe the bug**
I have just recently tried to update to the recent version (2.0.0-beta.603) and it looks like there are has been some breaking changes. Previously I have used:
`LegendBackground="Transparent" LegendTextBrush="White" LegendFontSize="15"`

Currently there are new properties: 
`LegendBackgroundPaint="Transparent" LegendTextPaint="White" LegendTextSize="15"`

with `typeof(IPaint<SkiaSharpDrawingContext>)`. I have not been following all the changelogs recently. Can you update documentation at some point on how to apply layout properties for Legend as current ones seems to be outdated after recent changes? 

Also I have noticed that there are some layout issues appeared at least for CartesianChart with Legends in Xamarin Forms. Chart is too close to Legend and there is no any gap in between. There are probably many things in development, so I will not push any pull requests with edits.

**Screenshots**
Red dot on the right
![Screenshot_20221201-212549](https://user-images.githubusercontent.com/72302395/205152709-8d9802c8-988b-4aa9-9983-4701a54213ac.jpg)

**Desktop (please complete the following information):**
 - OS: Xamarin

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy Tab A

**Comment by beto-rodriguez** [comment]
Sorry about the braking change without docs, you can find more info about this here: https://github.com/beto-rodriguez/LiveCharts2/issues/816#issuecomment-1348759920 the docs will be updated in a few hours, feel free to reply if that does not fix the issue.
