### ISSUE TITLE
Performance issues with DateTimePoint

### ISSUE THREAD

**Issue by qz347655378** [beto-rodriguez/LiveCharts2#797]
I'm using a DateTimePoint to plot the graph in real time with a write interval of 30 milliseconds, which triggers 'Collection was modified; enumeration operation may not execute.'. I want to know how to use DateTimePoint correctly, what is the appropriate time interval

**Comment by pkindruk** [comment]
Hard to say without code sample. But usually such exceptions occur in concurrent scenarios. Check that you update your collection to GUI thread. I assume that you update collection from background thread, while chart is calculating frame.

**Comment by qz347655378** [comment]
Thank you very much, I used the method you provided to solve the problem
