### ISSUE TITLE
How could I run the WPF demo?

### ISSUE THREAD

**Issue by kenllSean** [beto-rodriguez/LiveCharts2#8]
Hi, it,s amazing! I'v clone the code alread but I can't run it. 
My IDE is vs2019 and .net 5.

**Comment by beto-rodriguez** [comment]
Hi

Try to rigth click in the solutiuon

![image](https://user-images.githubusercontent.com/10853349/112408858-25383100-8cde-11eb-9efb-ed1b723c4537.png)

then Properties

Then select the WPF sample as your startup project and run it

![image](https://user-images.githubusercontent.com/10853349/112408954-46991d00-8cde-11eb-9a30-23e64ded854b.png)
