### ISSUE TITLE
Uno Error with LiveChartsCore.SkiaSharpView.Uno.WinUI 2.0.0-beta.603

### ISSUE THREAD

**Issue by wuweisin** [beto-rodriguez/LiveCharts2#801]
Dear Sir, 

When I use UnoPlatform with "LiveChartsCore.SkiaSharpView.Uno.WinUI 2.0.0-beta.603" in WASM mode, 

it will show error:
![圖片](https://user-images.githubusercontent.com/45276164/205551136-617b95b6-bff0-4b92-96c8-26494f127f1e.png)

the full log file attach as file：[msbuild.log](https://github.com/beto-rodriguez/LiveCharts2/files/10150703/msbuild.log)

please help me to deal this problem, thanks a lot！

**Comment by wuweisin** [comment]
Dear Sir,

I solve this problem after downgrading "Uno.Wasm.Bootstrap" and "Uno.Wasm.Bootstrap.DevServer"'s  version from 7.0 to 3.3.1。

Uno.Wasm.Bootstrap 7.X will use EMSDK 3.1.12 , is not compatible with Live Chart.

Thanks for you help.

**Comment by beto-rodriguez** [comment]
Thanks for the feedback, I will take a look into this!

**Comment by beto-rodriguez** [comment]
This is fixes in the latest Uno NuGet package, thanks for the report!
