### ISSUE TITLE
Spelling error in docs

### ISSUE THREAD

**Issue by Albert634515** [beto-rodriguez/LiveCharts2#813]
Spelling error in docs.
See link: https://lvcharts.com/docs/WinForms/2.0.0-beta.330/samples.stackedBars.groups
It says as title: Gruped And Stacked Bars, I think that should be: 'Grouped And Stacked Bars'

**Comment by beto-rodriguez** [comment]
This is fixed now, thanks for the report!

Notice it is not fixed in the link you shared, beta 330, but it is fixed since beta 700 version of the docs.
