### ISSUE TITLE
Chartesian Chart LegendFont and TooltipFont are no longer available in beta .603

### ISSUE THREAD

**Issue by AhmadKelany** [beto-rodriguez/LiveCharts2#816]
**Describe the bug**
Previously I could set the TooltipFont and the LegendFont on the chart, which allowed displaying Arabic text correctly,
now these two properties are not available, and the chart uses the default font which displays Arabic letters incorrectly.

**To Reproduce**
On any chart try setting the TooltipFont or the LegendFont properties, both are not available.

**Expected behavior**
We should have a way of setting the font for the tooltip and the legend.

**Comment by Kevin-Seiden** [comment]
Based on commit history the Tooltip customization was moved from WPF to the Skia back end so you will have to redevelop that portion.  Unfortunately, the guides haven't been updated yet.  IF you are customizing the tooltip, I recommend not updating until the guides are updated.  This is one of those things you just have to accept when choosing to use a beta.

**Comment by pkindruk** [comment]
@AhmadKelany have you tried setting `LegendTextPaint` and `TooltipTextPaint`? `IPaint` has `FontFamily` which should be give similar results.

**Comment by beto-rodriguez** [comment]
The site now has docs for beta 700. The library now also draws and animates tooltips and legends, thus now we need to use LiveCharts objects ad motioned above, sorry about the braking change!
