### ISSUE TITLE
Performance issues - candlestick chart is very slow

### ISSUE THREAD

**Issue by pavlexander** [beto-rodriguez/LiveCharts2#817]
**Describe the bug**
I am trying out this library by drawing candlestick charts and comparing the performance to other solutions. However, it's hard to use this library as **it becomes nearly unusable with 50k worth of data points..** (with animations OFF) Other libraries could handle 100k points kind of fine.. I was wondering if I am doing something wrong, or is there a bug that makes it behave some painfully slow in comparison?

**To Reproduce**
The source code is at: https://github.com/pavlexander/plot_test
basically I am plotting 50k to 100k candles like so:
```
            var candles = GetCanles();
            var plottableCandles = LCConverter.ConvertToPlottalble(candles);

            var form = new LCChartForm();
            var plot = form.MainPlot;
            form.Show();

            LiveChartsCore.SkiaSharpView.Axis[] axis = {
                new LiveChartsCore.SkiaSharpView.Axis
                {
                    LabelsRotation = 45,
                    Labeler = value => new DateTime((long)value).ToString("yyyy MMM dd HH mm"),
                    UnitWidth = TimeSpan.FromMinutes(1).Ticks,
                }
            };

            plot.XAxes = axis;
            plot.Series = new ISeries[]
            {
                plottableCandles
            };
```

**Expected behavior**
The zoom is fast.
The mouse drag on chart is fast.

**Actual behavior**
Everything is slow..

**Screenshots**
Here is the video proof instead
![Animation11](https://user-images.githubusercontent.com/20644772/207057940-9ba9435a-f203-46ad-acba-2227b60ec1c2.gif)

**Desktop:**
 - OS: Win10x64
 - LiveCharts version: `LiveChartsCore.SkiaSharpView.WinForms` `2.0.0-beta.603`
 - I am using the `WinForms` version of the library

**Additional context**

First of all, if you want to take testing to the **extreme** you could try increasing the data point count to 100k, 200k or max 500k. Default is 50k.

![image](https://user-images.githubusercontent.com/20644772/207059545-cd8d4e61-f21b-430c-a4d3-f8c382b09363.png)

**Additionally** I would really like to know answers to some additional questions, if you would be so kind to answer in this "bug" report.. (**preferably, but not mandatory** :) )

1. Is it possible to reset the view after zooming? Like "double click to reset" functionality or something similar? Currently after zooming-in I have no idea how to reset the view..

2. Could you look into adding the "right-mouse-click-hold zoom" option? (for reference please check the ScottPlot in my repo example)

![image](https://user-images.githubusercontent.com/20644772/207058924-0dcbbf54-b965-4f22-85af-0f361c4f26be.png)

![Animation12](https://user-images.githubusercontent.com/20644772/207061526-70fd2f9b-15ca-42a6-baab-ea669dc74f73.gif)

3. Is there a way to disable "series hover label" when hovering on candle data points on chart?

![image](https://user-images.githubusercontent.com/20644772/207060896-e199e372-e1f3-4d4b-8cf3-7cbec6072e90.png)

**Comment by beto-rodriguez** [comment]
The high-performance package is not ready yet, you can learn more about it here:

https://github.com/beto-rodriguez/LiveCharts2/releases/tag/v2.0.0-beta.350

**Comment by pavlexander** [comment]
@beto-rodriguez do you have an estimate for this package release date?

Looks very promising! Looking forward to it :)
