### ISSUE TITLE
Crash when closing MAUI app

### ISSUE THREAD

**Issue by feal87** [beto-rodriguez/LiveCharts2#828]
**Describe the bug**
I use charts in various pages of my application, they work perfectly. Except when I close the application right after interacting with the graph (even merely going over it with the mouse) they make the app crash with some native crash.
I tried to find if there was something to properly dispose the object, but everything seems to indicate it should do that automatically so I'm a bit puzzled.

**Expected behavior**
Close gracefully

**Screenshots**
![2022-12-19 03_39_53-Scegli debugger JIT](https://user-images.githubusercontent.com/26706898/208313773-02c2b451-bed6-458c-8fde-b971658afc6b.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by pkindruk** [comment]
Is there any errors in Event Viewer -> Windows Logs -> Application? Usually when .NET apps crash there are 2 events. An error which tells that app crashed and another error with details about .NET Runtime exception. Would be nice to see both of them, to at least confirm that error relates to library.

Also you didn't mention LiveCharts version you are using.

**Comment by beto-rodriguez** [comment]
Thanks for the issue, please let us know how we can reproduce the issue.

I will close this for now, feel free to add more details or reply here to @pkindruk then we can try to help you better
