### ISSUE TITLE
Default legend doesn't wrap children correctly

### ISSUE THREAD

**Issue by EricRosenfeld1** [beto-rodriguez/LiveCharts2#832]
<lvc:PieChart Margin="5"
                      Grid.Row="1"
                      x:Name="chart"
                      Grid.RowSpan="4"                   
                      Series="{Binding Series}"
                      LegendPosition="Bottom" />

![image](https://user-images.githubusercontent.com/46537274/208448053-2c8becc3-7282-4679-8927-03e7f4d1d0a1.png)

**Comment by beto-rodriguez** [comment]
Thanks for the report, yes, this is not supported by now, a work around at the moment is to place the legend at the left or right.

**Comment by kbegiedza** [comment]
Do we have any ETA on this @beto-rodriguez ?
For my use case left / right didn't solve issue.

**Comment by beto-rodriguez** [comment]
It is published now.
