### ISSUE TITLE
Problems with legend after Update from beta.501 to beta.700

### ISSUE THREAD

**Issue by Stefan69** [beto-rodriguez/LiveCharts2#833]
Windows 10 21H2
Library: net462 WPF application

Hi Alberto,

in advance, super great library, I love it! Thank you for developing and sharing it!

Today I was adding a feature to one of our tools and therefore I did an update of the NuGet-packages. I notices some changes in formating, but everything looks good except these two points (Please look at the attached videos):
1. The horizontal space between the vertical axis and the legend is gone. Is this a bug or do I have to add some (new) settings to define the size of the space?
2. When hiding a series (I do this via calling LineSeries<TModel>.IsVisible) the legend is not refreshed completely and the text-parts of the legend are missing. In case I would change anything after (f.e. the window size) a refresh would show the legend again. 

old: beta.501
https://user-images.githubusercontent.com/6460492/208472071-1ca63e82-61e8-4794-9923-eedb9885af42.mp4

new: beta.700
https://user-images.githubusercontent.com/6460492/208472114-06518ce5-377d-4329-afd7-c63e46dc2875.mp4

Kind regards
Stefan

**Comment by beto-rodriguez** [comment]
This is already working in the latest release, thanks for the report.
