### ISSUE TITLE
Tooltip displays bi-directional text (e.g.: Arabic and English text in the same string) incorrectly in beta 700. (WinForms)

### ISSUE THREAD

**Issue by AhmadKelany** [beto-rodriguez/LiveCharts2#834]
**Describe the bug**
**In beta 516, the numbers is displayed correctly:**

The Tooltip font is set like this:
`chart.TooltipFont = Font("Noto Naskh Arabic", 14, FontStyle.Regular);`

![image](https://user-images.githubusercontent.com/12924528/208660075-7bb22026-b462-4199-8e34-2135ad90a08b.png)
---------------------------------------------------------------
**In beta 700:**

The Tooltip Font is set like this:
```
chart.TooltipTextPaint = new SolidColorPaint()
        {
            Color = new SKColor(50, 50, 50),
            SKTypeface = SKTypeface.FromFamilyName("Noto Naskh Arabic"),

        };
```

![image](https://user-images.githubusercontent.com/12924528/208659256-6fa1a37e-be39-47b4-9777-f9c950fa9b60.png)

--------------------------------------

The correct number is : **_5105.68_** , formatted should be: **_5,105.68_**

The Tooltip formatter used in both cases:

    `public static Func<ChartPoint<decimal, DoughnutGeometry, LabelGeometry>, string> PieTooltipFormatter => arg => arg.Model.ToString("N2") + " " + arg.Context.Series.Name;`

If the text is in English, the numbers are displayed correctly:

![image](https://user-images.githubusercontent.com/12924528/208662056-4149523d-00a9-4049-944e-42c4d0dcb792.png)

**_More Info:_**
When the first character is English letter, the whole string is displayed left-to-right even the Arabic part.
When the first character is Arabic letter, or a number then Arabic text, the whole string is displayed right-to-left even the numbers.. e.g. one hundred will be displayed: 001

**To Reproduce**
Assign any Arabic text with number to the tooltip

**Expected behavior**
Should display the numbers correctly.

(Platform = WinForms)

**Comment by AhmadKelany** [comment]
Some investigation led me to the following hypothesis:
-SkiaSharp doesn't handle bi-directional text correctly, it requires HarfBuzz library to do that.
-LiveCharts removed the handling of the text rendering from the frameworks (which could handle bi-directional text) to rely instead on SkiaSharp (which couldn't, without additional use of other library).

I hope this helps, and thanks for your great efforts.

**Comment by AbdullahUlber** [comment]
HarfBuzz is not the culprit here. Its documentation mentions explicitly that HarfBuzz is not concerned with bidirectionality and that it is the caller's responsibility to segment the text into "into runs that have a uniform set of properties", in particular "the same **direction**, script tag, and language tag".
It appears that LiveCharts does not perform any such segmentation.

References:
- https://harfbuzz.github.io/what-harfbuzz-doesnt-do.html
- https://harfbuzz.github.io/text-runs.html

**Comment by beto-rodriguez** [comment]
I think I already got this in the referenced PR, I also inverted the tooltip direction, this is the result:

![v](https://github.com/beto-rodriguez/LiveCharts2/assets/10853349/c5a73707-4927-46ca-b78c-2fd38d2f73e4)

Does that look good? (I need help here; I am not familiar with Arabic 😢)

in the next version of the library we will:

```c#
LiveCharts.Configure(config => config
  .HasGlobalSKTypeface(SKTypeface.FromFamilyName("Noto Naskh Arabic"))
  .UseRightToLeftSettings());
```

**Comment by AhmadKelany** [comment]
> Does that look good? (I need help here; I am not familiar with Arabic 😢)

Thanks for your amazing work,
Yes, this looks great. 👌

**Comment by beto-rodriguez** [comment]
This is already included in beta.900, thanks for the report.
