### ISSUE TITLE
A better zooming functionality

### ISSUE THREAD

**Issue by pavlexander** [beto-rodriguez/LiveCharts2#837]
**Is your feature request related to a problem? Please describe.**
Can't zoom out

**Describe the solution you'd like**
Could you look into adding the "right-mouse-click-hold zoom" option? (for reference please check the ScottPlot in my repo example)
https://github.com/pavlexander/plot_test

![image](https://user-images.githubusercontent.com/20644772/207058924-0dcbbf54-b965-4f22-85af-0f361c4f26be.png)

![Animation12](https://user-images.githubusercontent.com/20644772/207061526-70fd2f9b-15ca-42a6-baab-ea669dc74f73.gif)

You could control the scaling of the X and Y axis at the same time using the right mouse button. 

**Describe alternatives you've considered**
I was looking into "double click to reset" functionality or something similar, but unfortunately, currently, after zooming-in I have no idea how to reset the view.. So, even if there is a way that I am not aware of - I think it would be nice to have the right mouse button used as a zoom in-out option.

**Additional context**
-

**Comment by beto-rodriguez** [comment]
Hello, LiveCharts has a different behavior than other charting libraries, and it is actually really flexible, you can always  control the zooming manually for more info check the [docs](https://lvcharts.com/docs/WPF/2.0.0-beta.700/CartesianChart.Cartesian%20chart%20control#zooming-and-panning) or this [sample](https://lvcharts.com/docs/WPF/2.0.0-beta.700/samples.axes.paging). 

> Can't zoom out

All you have to do is use the mouse wheel to zoom in/out, in touch devices you can just pinch the screen to get the desired zoom level.

> Could you look into adding the "right-mouse-click-hold zoom" option

We have a "section" [zooming mode](https://github.com/beto-rodriguez/LiveCharts2/releases/tag/2.0.0-beta.361), probably this is more user friendly than the alternative you suggested.

> I was looking into "double click to reset" functionality or something similar

It is supper ready to implement, just set the axis limits to `null` as [stated in the docs](https://lvcharts.com/docs/WPF/2.0.0-beta.700/CartesianChart.Cartesian%20chart%20control#clearing-the-current-zooming-or-panning).

I think this is not an issue, we maybe just need better docs on this, I will keep an eye on that.
