### ISSUE TITLE
Tooltip dispapears too quickly 

### ISSUE THREAD

**Issue by msmw13** [beto-rodriguez/LiveCharts2#840]
**Describe the bug**
The tooltip dispapears too quickly to see the content clearly.

**To Reproduce**
1. Click on 'lvc:CartesianChart'
2. See error

**Expected behavior**
The tooltip disappears within 1 second.

**Screenshots**

https://user-images.githubusercontent.com/115437516/209141209-9832c272-0eef-449b-863c-de126b283e53.mp4

![image](https://user-images.githubusercontent.com/115437516/209144356-4380df03-831d-42fa-94b9-df527317460e.png)

**Smartphone (please complete the following information):**
 - Device: [HUAWEI P30 Pro]
 - OS: [Android 10]

**Comment by beto-rodriguez** [comment]
Tooltips had a lot of fixes in beta.800, this should behave much better, thanks for the report, feel free to open a new issue if you are not satisfied with the current behavior.

**Comment by GamiDroid** [comment]
I still have the same issue. I have a Blazor WASM application with is using version 2.0.0-rc5.4 of LiveChartsCore.SkiaSharpView.Blazor. 
When I click on the the chart a tooltip is not showing at all. On mouse hover works. But the application is mostly using on touch devices.

Do I need to add to the chart to make it work?
