### ISSUE TITLE
StepLine legend text disappears

### ISSUE THREAD

**Issue by kojima-imamura** [beto-rodriguez/LiveCharts2#845]
After using the legend in 'StepLine' and pressing 'Add Series', if you press 'Remove Series', the legend text disappears.

Version in which the problem occurred
 --> beta.700

Add Series
![image](https://user-images.githubusercontent.com/118875864/209300769-c1f61063-9ac7-43e4-80a6-264d24c4e494.png)

Remove Series
![image](https://user-images.githubusercontent.com/118875864/209301445-a137ad9e-600a-4f63-a20d-51780e83d2f0.png)

.\LiveCharts2-master\samples\WPFSample\StepLines\AutoUpdate\View.xaml
Edit Code
<lvc:CartesianChart Grid.Row="1" Series="{Binding Series}">
  --> <lvc:CartesianChart Grid.Row="1" Series="{Binding Series}" LegendPosition="Bottom">

**Comment by mjanulaitis** [comment]
This bug also occurs when clearing the series collection then re-assigning it with a new collection.  This is a critical defect when refreshing data that includes a variant result set of series.

**Comment by network-interface-controller** [comment]
Same effect as in #833

**Comment by beto-rodriguez** [comment]
This is already fixed, it will be included in the next version of the library. Thanks for the report..

**Comment by mjanulaitis** [comment]
@beto-rodriguez Thank you.  I will pull the latest code and apply to my branch.
