### ISSUE TITLE
Task.Delay()....Bug

### ISSUE THREAD

**Issue by TherdDB** [beto-rodriguez/LiveCharts2#846]
// value length = 500 ..
        var value = str.Split("^");
        foreach (var item in value)
        {
            // this Delay
            // F5  running DeBug is OK.
            // But  running  /bin/Debug(Release)/app.exe  is too slow,  and  slowly more then that!      
            //   case 1:   TimeSpan.FromMicroseconds  < 1000 
            //   case 2:   TimeSpan.FromMicroseconds  > 1000 

            await Task.Delay(TimeSpan.FromMicroseconds(1000));
            _observableValues.RemoveAt(0);
            _observableValues.Add(new(Convert.ToInt32(item)));
        }

I'm doing a ECG waveform test. 

First, I need the animation when adding data.

One sencond have 500 waveform data add  inside, and ensure thread safety.

But I don't know how to do concurrent processing and ensure thread safety.

So I want to control the time of adding data within 1 second.

I can provide waveform data.
But I need a master to save me!!

**Comment by beto-rodriguez** [comment]
Hi, the library is thread safe, but you must also ensure that your code also is.

Take a look at the following comment: https://github.com/beto-rodriguez/LiveCharts2/issues/225#issuecomment-1012488255


There you can find a solution for your problem.
