### ISSUE TITLE
Solution not building VS2022 

### ISSUE THREAD

**Issue by VikingExplorer** [beto-rodriguez/LiveCharts2#850]
**Describe the bug**
Microsoft Visual Studio Community 2022 (64-bit) - Current
Version 17.4.3

**To Reproduce**
1. clone from LiveCharts2
2. build

**Expected behavior**
Expect it to build out of the box

4>C:\Program Files\dotnet\sdk\7.0.101\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(1220,3): error MSB4019: The imported project "C:\Program Files\dotnet\sdk\7.0.101\Sdks\Microsoft.NET.Sdk\13.0.2032\targets\Xamarin.Shared.Sdk.MultiTarget.targets" was not found. Confirm that the expression in the Import declaration ";..\13.0.2032\targets\Xamarin.Shared.Sdk.MultiTarget.targets" is correct, and that the file exists on disk.
4>Done building project "LiveChartsCore.SkiaSharpView.Uno.WinUI.csproj" -- FAILED.
6>C:\Program Files\dotnet\sdk\7.0.101\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(1220,3): error MSB4019: The imported project "C:\Program Files\dotnet\sdk\7.0.101\Sdks\Microsoft.NET.Sdk\13.0.2032\targets\Xamarin.Shared.Sdk.MultiTarget.targets" was not found. Confirm that the expression in the Import declaration ";..\13.0.2032\targets\Xamarin.Shared.Sdk.MultiTarget.targets" is correct, and that the file exists on disk.
6>Done building project "LiveChartsCore.SkiaSharpView.Uno.csproj" -- FAILED.
11>LiveChartsCore.SkiaSharpView.WinForms -> C:\Users\gunna\source\repos\LiveCharts2\src\skiasharp\LiveChartsCore.SkiaSharp.WinForms\bin\Debug\net462\LiveChartsCore.SkiaSharpView.WinForms.dll
11>Done building project "LiveChartsCore.SkiaSharpView.WinForms.csproj".
14>C:\Users\gunna\source\repos\LiveCharts2\src\skiasharp\LiveChartsCore.SkiaSharp.WPF\Themes\Generic.xaml(44,22): error MC3074: The tag 'SKElement' does not exist in XML namespace 'clr-namespace:SkiaSharp.Views.WPF;assembly=SkiaSharp.Views.WPF'. Line 44 Position 22.
14>Done building project "LiveChartsCore.SkiaSharpView.WPF.csproj" -- FAILED.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10

**Smartphone (please complete the following information):**

**Additional context**

**Comment by alexachso** [comment]
Hi, I have also some problems building the repository projects. I have the same environment as VikingExplorer but as soon as I try to build the LiveChartsCore projects (because any other project won't build because they miss the LiveChartsCore.dll) I get this error instead. 
![image](https://user-images.githubusercontent.com/12586000/210556392-cdc5e6c0-0195-4708-ae21-580806c7d65c.png)

I need a key to build this repository?

**Comment by beto-rodriguez** [comment]
Hi and thanks for the issue.

The repo compiles properly, notice that the error you are getting is related with Uno Platform @VikingExplorer, if you have never built a Uno Platform project, then there are a few steps you must follow, please check the Uno Docs to get started with it, you can also remove the Uno projects from your local solution.

@alexachso this issue only happens in release mode.
