### ISSUE TITLE
Pie Chart Observable not updating in .700 

### ISSUE THREAD

**Issue by rpascalegh** [beto-rodriguez/LiveCharts2#858]
**Describe the bug**
When Series is updated in pie chart, chart does not update anymore.  The Bar charts works as expected and still updates correctly.  
This worked correctly in .400 and when rolled back to .603 works correclty.  Chart updates data and changes pie sizes and values is the expected(this works correctly in older verions) Tested Android and IOS both same issue, but works on .603.

**To Reproduce**
xaml code
<lvc:PieChart 
                     Series="{Binding Chart1.Series}"
                     HeightRequest="{Binding ChartHightRequest}"   
                     LegendBackgroundPaint="{Binding LegendColor}"
                     LegendTextSize="{Binding LegendFontSizeLg}"
                     LegendPosition="{Binding LegendPosition}"
                     AnimationsSpeed="{Binding AnimationsSpeed}"
                     EasingFunction="{Binding Easing}">
                </lvc:PieChart>

MVVM code
 for (int i = 0; i < report.xvalues.Count; i++)
                            {
                                Chart1.Series[i].Values = new List<double> { report.posted[i] };
                                Chart1.Series[i].Name = report.xvalues[i].PadRight(5, ' ')+"\n" + Math.Round(report.posted[i] / 1000000, 3).ToString();
                            }

**Expected behavior**
When data is updated pie chart should update and draw new pie chart with udpated data

**Screenshots**
NA

**Desktop (please complete the following information):**
VS 2022 on Win 10 

**Smartphone (please complete the following information):**
Tested on
Android S21 samsung 
IOS Apple 
IOS IPAD  softward ver 15.6   IPAD 6th gen 
**Additional context**

**Comment by bruxe0000** [comment]
I have the same issue. But in my case, version .603 didn't help.
My package is LiveChartsCore.SkiaSharpView.Avalonia, Version=2.0.0-beta.701

**Comment by rpascalegh** [comment]
I haven't seen any updates yet.  I am still using version
livechartscor.skiasharpview.maui 2.00.-beta.400

This seems to be the only one that works correctly.  When I try higher
versions, the Pie charts wont change/redraw when the observable data is
updated. The line charts do work correctly in higher versions. Hoping for
an update.

**Comment by bruxe0000** [comment]
Hi, I find a solution for this issue, which is "LiveChartsCore.Defaults.ObservableValue".
I bind an "ObservableCollection<ObservableValue>" variable to the "Values" of the PieSeries, then I only need to update the variable.
And voila, it works like a charm! 😄
I'm still using 2.0.0-beta.701.

**Comment by bruxe0000** [comment]
Hi @rpascalegh, this is the code is my ViewModel:

` public class ChartViewModel : BindableBase
{
        private IEnumerable<ISeries> _acceptedDefectiveSeries;

        public IEnumerable<ISeries> AcceptedDefectiveSeries
        {
            get { return _acceptedDefectiveSeries; }
            set { SetProperty(ref _acceptedDefectiveSeries, value); }
        }

        private readonly ObservableCollection<ObservableValue> _observableAcceptiveValues;
        private readonly ObservableCollection<ObservableValue> _observableDefectiveValues;
        
         public ChartViewModel ()
        {
             AcceptedDefectiveSeries = new List<ISeries>
            {
                // Defective
                new PieSeries<ObservableValue>
                {
                    Name = "Defective",
                    Values = _observableDefectiveValues,
                    Fill = new SolidColorPaint(skRed),
                    InnerRadius = 40,
                    IsHoverable = false
                },
                // Accepted
                new PieSeries<ObservableValue>
                {
                    Name = "Accepted",
                    Values = _observableAcceptiveValues,
                    Fill = new SolidColorPaint(skBlue),
                    InnerRadius = 40,
                    IsHoverable = false
                },
            };
        }

        public void Update(Services.AcceptDeffectInfo defectInfo)
        {
            _observableDefectiveValues.First().Value = defectInfo.DeffectiveQuanity;
            _observableAcceptiveValues.First().Value = defectInfo.AcceptiveQuanity;
        }
} `

**Comment by rpascalegh** [comment]
Thanks I will take a look.

**Comment by rpascalegh** [comment]
Looks like documents are updated.  See https://lvcharts.com/docs/Maui/2.0.0-beta.700/PieChart.Pie%20series#name-property

Updated my model to using a observerable collection and its working.

**Comment by rpascalegh** [comment]
New issue.  The charge updates when I change the values, but the legend name wont update.   I trying to display a name with current value.  Example   house = 10.   When I update the pie values, 10 to 20 the  pie updates, the values in the pop up when you press a pie sectionupdate, but the legend name stays the same.

**Comment by rpascalegh** [comment]
Resolved with oberervalbe collection change
