### ISSUE TITLE
How to show separators on logarithmic axis 

### ISSUE THREAD

**Issue by pschimmel** [beto-rodriguez/LiveCharts2#86]
Hi!
I'm trying to convert some WPF charts from version 0.9.7 to version 2. One of my charts has a logarithmic scaling on both the X and Y axis.

I found two issues while doing that.
1. I could not find a way to add a label to the axis itself (like the E and N in the previous version)
2. In version 2, it will only show the main separators.

I basically followed the code example from version 2 to create the Can you give me a hint how to accomplish that? 

Chart in 2.0.0, beta 17:
![image](https://user-images.githubusercontent.com/9028723/125307973-d36cf280-e330-11eb-8cd2-57e10da3aa85.png)

Same chart in 0.9.7:
![image](https://user-images.githubusercontent.com/9028723/125307913-c4864000-e330-11eb-91c8-2aeccf9da144.png)

**Comment by beto-rodriguez** [comment]
This is finally implemented with the referenced commit and will be included in the next version of the library, thanks for the report!
