### ISSUE TITLE
StackedArea Hides LineSeries

### ISSUE THREAD

**Issue by mjanulaitis** [beto-rodriguez/LiveCharts2#862]
**Describe the bug**
I have a chart with two StackedAreaSeries and two LineSeries.  The stacked area series have data such as free disk space and used disk space for a total of the total disk space.  I now append two LineSeries, one for a warning threshold and the other for a critical threshold. If I use a solid fill on the StackedAreaSeries the line Series are covered up.  If I use an alpha fill on the StackedAreaSeries, I can see the LineSeries however the alpha fill is drawn on top of the line series.  

**Expected behavior**
Each series in the collection should always draw on top of the previous series. 

**Desktop (please complete the following information):**
 - Windows 10

**Comment by beto-rodriguez** [comment]
At this point `StackedArea` use a high z-index, a work around for now is to set a high z-index for the line series (greater than 1000), this is [documented at the source code](https://github.com/beto-rodriguez/LiveCharts2/blob/master/src/LiveChartsCore/LineSeries.cs#L142) and might be improved in a future.
