### ISSUE TITLE
Tooltip does not remain open while actively adding data to the series.

### ISSUE THREAD

**Issue by Kevin-Seiden** [beto-rodriguez/LiveCharts2#869]
**Describe the bug**
In a Cartesian chart where data is being continually added to the series in WPF, the tooltip closes each time the series updates.  This is new to beta 700.

**To Reproduce**
1. Create a chart where data is added to the series frequently (In my use I add data at about 10Hz)
2. Hover the mouse over the series to produce the tooltip.
3. The tooltip will close or blink/flash repeatedly (due to small mouse movement) making it unreadable.
4.  This happens when using a custom tooltip according to the guides or using the default tooltip.

**Expected behavior**
In previous versions the tooltip would remain open as the series was updated.  The tooltip should only close if the mouse moves or the data point under the mouse changes, not when new data is added to the series.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Beta 700
 - WPF

**Comment by beto-rodriguez** [comment]
This now works properly and will be included in the next version of the library.

![ggg](https://github.com/beto-rodriguez/LiveCharts2/assets/10853349/ea7efe08-a137-4592-8782-fa68e4606f2d)

Thanks for the report.
