### ISSUE TITLE
EnableNullSplitting and LineSmoothness ignored in beta 2.0.0.beta-700 (blazor wasm)

### ISSUE THREAD

**Issue by MithrilMan** [beto-rodriguez/LiveCharts2#871]
Hello, I'm testing the library on a Blazor WASM project (Net 7.0) and I'm creating a Series like this

```
Series.Add(new LineSeries<DateTimePoint>
            {
               Name = serie.Label,
               Values = serie.ChartSeriesValues.Select(v => new DateTimePoint(v.EventDate, v.Value)),
               Stroke = new SolidColorPaint(SKColor.Parse(serie.Color)) { StrokeThickness = 1 },
               Fill = null,
               GeometryFill = null,
               GeometryStroke = null,
               EnableNullSplitting = true,
               LineSmoothness = 0
            });
```

No matter if I change EnableNullSplitting, the chart is always like this
![image](https://user-images.githubusercontent.com/5107375/210838108-10275340-1acd-492e-aeb9-14e5c6d409a7.png)

Also the X scale doesn't print datetime labels

Thanks and kudos for the effort

**Comment by MithrilMan** [comment]
Update again:
found the big problem on my side (that even caused the chart to lag on a beefy PC)
It was caused by my expression to generate points...

`Values = serie.ChartSeriesValues.Select(v => new DateTimePoint(v.EventDate, v.Value)),`

Here I was setting to the LineSerie.Values property an IEnumerable!!!!
I realized it when I added a Console.WriteLine instruction into the setter and I found it was called at each interaction with the chart (mouse move, etc...) so basically it was re-generating the list everytime because inside the library it isn't converted into a ToList of any sort but used as it is, an IEnumerable, so by nature (LINQ) my LINQ expression was executed continuously....

As soon as I added a ToList at the end now I have tooltip and chart is smooth...

Well, I leave this issue for people having kind of similar problem and maybe could be added in an infobox in the documentation to prevent easy-to-do errors like this.

Btw this wouldn't be a production code on my side, I was just playing with the chart and just shot myself in the foot

**Comment by beto-rodriguez** [comment]
Glad to read you found a solution for most of your issues.

About IEnumerable, yes this needs docs or to actually work with Enumerables, I will keep that in mind.
Also the referenced commit simplifies the library initialization and actually makes think optional.

Thank for the report.
