### ISSUE TITLE
Disabling hover animation and piechart moving.

### ISSUE THREAD

**Issue by SCLD-JMcCoard** [beto-rodriguez/LiveCharts2#872]
### Discussed in https://github.com/beto-rodriguez/LiveCharts2/discussions/854

<div type='discussions-op-text'>

<sup>Originally posted by **SCLD-JMcCoard** December 28, 2022</sup>
We upgraded from 2.0.0-beta.101 to 2.0.0-beta.700 to resolve issues where the doughnut had a gap at 0 and 100%, but now we are seeing hover animations which was previously disabled.

Our chart code from 101:
<lvc:PieChart Grid.Row="0" Height="200" Width="200"  TooltipPosition="Hidden" Series="{Binding Series}" Total="{Binding TotalProcessedControlsCount}" InitialRotation="-90"/>

We've tried setting EasingFunction to {x:Null} and AnimationsSpeed to 0.

<lvc:PieChart Grid.Row="0" EasingFunction="{x:Null}" AnimationsSpeed="0" Height="200" Width="200"  TooltipPosition="Hidden" Series="{Binding Series}" Total="{Binding TotalProcessedControlsCount}" InitialRotation="-90"/>

The doughnut graphic still moves.
![image](https://user-images.githubusercontent.com/70153610/209857421-dd122288-21b8-4d8e-aa81-13aa4c9cfec0.png)
![image](https://user-images.githubusercontent.com/70153610/209857507-7e5c66c1-adbc-48d9-971c-44e8a61bcb14.png)
</div>

**Comment by beto-rodriguez** [comment]
Hi and thanks for the report, the library calls this property "Pushout". There is a [small note in the docs](https://lvcharts.com/docs/WPF/2.0.0-beta.710/PieChart.Pie%20series#pushout-property) that mentions this behavior.

This should make the trick:

`series.HoverPushout = 0;`

Sorry about the late response, and thanks again for the report! feel free to let me know if you face any other issue.

**Comment by SCLD-JMcCoard** [comment]
Thank you. This resolves my question.
