### ISSUE TITLE
Allow shared axis to have visibility based on rules and share crosshair

### ISSUE THREAD

**Issue by MithrilMan** [beto-rodriguez/LiveCharts2#875]
Blazor beta-700

I'm using Shared axis and I did this
![image](https://user-images.githubusercontent.com/5107375/210922627-f1d51b3a-0d59-418f-9851-a13b35af4bb5.png)

X Axes are synchronized, the problem is that I'd like to hide the X ases of smaller digital charts to don't have to waste space, also I'd need to share the crosshair among these different charts

**Comment by beto-rodriguez** [comment]
To Hide the `XAxis` Labels, just do: `chart.XAxes = new[] { new Axis { IsVisible = false } };`

About sharing the crosshair, that is not supported yet, but we can track that at #876.

Thanks for the report, I will close this for now.
