### ISSUE TITLE
Show geometry for points displayed on tooltip

### ISSUE THREAD

**Issue by MithrilMan** [beto-rodriguez/LiveCharts2#879]
**Is your feature request related to a problem? Please describe.**
I don't want to display geometry for my series point so I set GeometryStroke/Fill to null, but I want to show geometry for points that are displayed into the tooltip
In this GIF you can see that when I hover over some points, they are displayed on tooltip but there isn't any clue about where the point lies.
I don't want to use CrosshairSnapEnabled but just have some geometry displayed for these points
![chart-issue](https://user-images.githubusercontent.com/5107375/211204167-07ba0ffd-52c8-4239-9431-7702699132d4.gif)

**Describe the solution you'd like**
I'd like to have a Series property to set which geometry to display on points displayed by Tooltip, e.g.
I see ISeries has a ActivePoints property (undocumented and probably actually unused) so assuming it (will) keep a list of the points "activated by the tooltip", I think properties like
```
myLineSeries.ActivePointGeometryStroke
myLineSeries.ActivePointGeometryFill
myLineSeries.ActivePointGeometrySize
```
that can be used to customize the geometry of these points would be useful.

**Additional context**
Based on current Blazor WASM beta-700 version

**Comment by beto-rodriguez** [comment]
Hi and thanks for the report(s)

This seems interesting, I think we can do more in cases like this where the geometry is `null`, maybe only display a line instead?

I will keep this open so we can think in a good way to solve this, your alternative to add new properties seems like a good option.

**Comment by beto-rodriguez** [comment]
There is now an example on how to achieve this, we can create a custom tooltip and set the geometry to anything we need, you can take a look at the custom tooltips or legends samples in the site and the repo.
