### ISSUE TITLE
Issue with rendering the graph

### ISSUE THREAD

**Issue by DevHasher** [beto-rodriguez/LiveCharts2#88]
@beto-rodriguez  Hi I installed the beta release 2.0.0-beta.32

And tried out the below code, but the graph is not visible. What am I missing?
*.xaml

```
<Page x:Class="Test.LVC2"
      xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
      xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
      xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" 
      xmlns:d="http://schemas.microsoft.com/expression/blend/2008" 
      xmlns:local="clr-namespace:Test"
      xmlns:lvc2="clr-namespace:LiveChartsCore.SkiaSharpView.WPF;assembly=LiveChartsCore.SkiaSharpView.WPF"
      mc:Ignorable="d" 
      d:DesignHeight="450" d:DesignWidth="800"
      Title="LVC2">

    <Grid>
        <lvc2:CartesianChart Name="LVC2_Chart" Series="{Binding Series}"></lvc2:CartesianChart>
    </Grid>
</Page>
```

*.xaml.cs
```
using LiveChartsCore;
using LiveChartsCore.SkiaSharpView;

namespace Test
{
    public partial class LVC2 : Page
    {
        public IEnumerable<ISeries> Series ;

        public LVC2()
        {
            InitializeComponent();
            Series= new ObservableCollection<ISeries>
            {
                new LineSeries<double>
                {
                    Values = new ObservableCollection<double> { 2, 1, 3, 5, 3, 4, 6 },
                    Fill = null
                }
            }
        }
    }
}
```

And from main window, on tab change event,  I do the following
```
if (LVC2Tab.IsSelected)
       ContentFrame.NavigationService.Navigate(new LVC2());
```

**Comment by LabuzzMichal** [comment]
You are not setting datacontext for your binding as far as I see

**Comment by DevHasher** [comment]
@LabuzzMichal 

I had tried it, but the graph still doesnt show up.
Below is the code for reference with datacontext:-

 ```
public partial class LVC2 : Page
    {
        public IEnumerable<ISeries> Series;

        public LVC2()
        {
            InitializeComponent();

            LineSeries<double> l1 = new LineSeries<double>
            {
                Values = new ObservableCollection<double> { 2, 1, 3, 5, 3, 4, 6 },
                Fill = null
            };
            ColumnSeries<double> c1 = new ColumnSeries<double>
            {
                Values = new ObservableCollection<double> { 2, 5, 4, -2, 4, -3, 5 }
            };
            Series = new ObservableCollection<ISeries> {l1,c1};

            DataContext = this;
        }
```

**Comment by LabuzzMichal** [comment]
It seems fine. You need to have a problem in other part of code. Share full project zipped if you need further assistance

**Comment by Bartos-Pol** [comment]
Hi i have a little problem with the chart rendering, its only show half the chart
![image](https://user-images.githubusercontent.com/44208326/126118717-1be73c8f-bba9-43fa-b1a0-94df2e620b57.png)

**Comment by LabuzzMichal** [comment]
@Bartos-Pol  I dont think its related to @DevHasher problem. Create separate issue with more details. Without code no one could help you

**Comment by Bartos-Pol** [comment]
> @Bartos-Pol I dont think its related to @DevHasher problem. Create separate issue with more details. Without code no one could help you

OK, Thank you

**Comment by DevHasher** [comment]
@LabuzzMichal I can share the source code, but I m unable to upload the zip here.
Could you share a mail address.. or link where I can upload the project.

**Comment by LabuzzMichal** [comment]
@DevHasher Delete binaries and unrelevant part of code

**Comment by DevHasher** [comment]
@LabuzzMichal  without the binaries only it was 210 mb..
I m sharing now without the packages
[Test.zip](https://github.com/beto-rodriguez/LiveCharts2/files/6854697/Test.zip)
For packages installed please refer the below image

![image](https://user-images.githubusercontent.com/23658195/126471686-302d4cd5-5b9b-4370-aee3-6bcd066b272a.png)

**Comment by LabuzzMichal** [comment]
Ohhh ok I see It. At first I didnt pay attention to your Series field. And thats the reason. Its a field but need to be property!
Here you can find more information about difference between fields and properties: [LINK](https://www.differencebetween.com/difference-between-field-and-vs-property-in-c/)

Just to be clear: Its not at all related to LiveCharts library. Its related to C#, WPF and its binding mechanism. Basically if you want binding to work you need to use property instead of a field. So instead of:

`public IEnumerable<ISeries> Series;`

it should rather be:

`public IEnumerable<ISeries> Series {get; set;}`

Then everything works fine :)
However you can still have it working with a field but then you need to use reference to control. Example below:

```
<Page x:Class="Test.LVC2"
      xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
      xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
      xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" 
      xmlns:d="http://schemas.microsoft.com/expression/blend/2008" 
      xmlns:local="clr-namespace:Test"
      xmlns:lvc2="clr-namespace:LiveChartsCore.SkiaSharpView.WPF;assembly=LiveChartsCore.SkiaSharpView.WPF"
      mc:Ignorable="d" 
      d:DesignHeight="450" d:DesignWidth="800"
      Title="LVC2">

    <Grid>
        <lvc2:CartesianChart Name="LVC2_Chart"></lvc2:CartesianChart>
    </Grid>
</Page>
```


```
   public partial class LVC2 : Page
   {
       public IEnumerable<ISeries> Series;

       public LVC2()
       {
           InitializeComponent();
           Series= new ObservableCollection<ISeries>
           {
               new LineSeries<double>
               {
                   Values = new ObservableCollection<double> { 2, 1, 3, 5, 3, 4, 6 },
                   Fill = null
               }
           };
           LVC2_Chart.Series = Series;
       }
   }
```


BTW: sometimes binding might be tricky but Visual Studio introduced nice feature helping people get around it.
![image](https://user-images.githubusercontent.com/17740334/126476591-d259a9a1-a48a-4e57-96c9-de2585ec8c70.png)
This red icon at the top of the imega tells you that you have a problem with binding somewhere. Just click it to ge more information.

Good luck!

**Comment by DevHasher** [comment]
@LabuzzMichal  Thanks a lot.. it was really tricky to identify that bit. Couldn't even imagine the cause. Thanks again!

**Comment by DevHasher** [comment]
I m trying shared X axis, and the selection doesnt seem proper
Setting on xaml
![image](https://user-images.githubusercontent.com/23658195/126638099-b663cb14-726d-4865-836b-fbb6369a0e2a.png)
And Shared X axis definition
 SharedXAxis = new Axis[] 
            {
                new Axis
                {
                    Labels = labelList,
                    LabelsRotation = -90
                }
            };
below is the image reference.

Correct selection as axis is shared
![image](https://user-images.githubusercontent.com/23658195/126637871-47387d76-49c4-4dcd-a7f5-0fcd0e22d683.png)
Incorrect selection even though axis is shared
![image](https://user-images.githubusercontent.com/23658195/126638030-69e5aea3-bef7-4591-840c-fa4c2d1bee08.png)

Do I need to add any other setting?

**Comment by LabuzzMichal** [comment]
Hi @DevHasher,

It is not related to your initial issue and its not right place to ask about it. Issues are there not only to help you but also to help other people facing the same problem. Asking about many different things in one issue is not right way to go :)

If you think its a bug please create another issue and dont forget to fill all information in template.

Otherwise if you just want to ask please move your comment somewhere there: https://github.com/beto-rodriguez/LiveCharts2/discussions

**Comment by DevHasher** [comment]
> Hi @DevHasher,
> 
> It is not related to your initial issue and its not right place to ask about it. Issues are there not only to help you but also to help other people facing the same problem. Asking about many different things in one issue is not right way to go :)
> 
> If you think its a bug please create another issue and dont forget to fill all information in template.
> 
> Otherwise if you just want to ask please move your comment somewhere there: https://github.com/beto-rodriguez/LiveCharts2/discussions

Ok, I have created a new thread -[https://github.com/beto-rodriguez/LiveCharts2/issues/100]
