### ISSUE TITLE
Expose MiniatureShapeSize property on ISeries interface (pull request available)

### ISSUE THREAD

**Issue by MithrilMan** [beto-rodriguez/LiveCharts2#881]
**Is your feature request related to a problem? Please describe.**
There is no an easy way to customize legend minuature even if everything is set up to allow such customization:
Series class, that's the base class used for every series, has a MiniatureShapeSize that's used to display the legend (and on tooltip also)

Having it exposed by ISeries interface would allow us to customize the size (that's often enough to not have a custom legend/tooltip) in an easy way

**Describe the solution you'd like**
Just declare the property in the ISeries interface is enough
see https://github.com/beto-rodriguez/LiveCharts2/pull/880
On the pull request I've added a screenshot and a snippet to show the result of the change

**Describe alternatives you've considered**
Would be better to have specific Series property to setup geometry for legend and tooltip, not just the minuature size.

Note that having full geometry support to custom aspect of legend and tooltip would be a better choice but if you want to have developers implement custom labels/legends and not support any custom shape out of the box, exposing at least this property could be a good tradeoff

**Comment by beto-rodriguez** [comment]
Fixed in #880, thanks for the issue and PR.
