### ISSUE TITLE
Inclusion of methods "Add()" and "AddRange()" to List of Class object presents in LiveCharts2

### ISSUE THREAD

**Issue by luissiqmaia** [beto-rodriguez/LiveCharts2#884]
Some array like "ISeries[]" or "Axis[]" or "VisualElements" don't have the method "Add()" and "AddRange()". Please, will be utils use these methods!

I use the Windows Forms.

**Comment by beto-rodriguez** [comment]
Hi!

The [Axes](https://github.com/beto-rodriguez/LiveCharts2/blob/master/src/skiasharp/LiveChartsCore.SkiaSharpView.WinUI/CartesianChart.xaml.cs#L422),  [Series](https://github.com/beto-rodriguez/LiveCharts2/blob/master/src/skiasharp/LiveChartsCore.SkiaSharpView.WinUI/CartesianChart.xaml.cs#L415) and [Visual elements](https://github.com/beto-rodriguez/LiveCharts2/blob/master/src/skiasharp/LiveChartsCore.SkiaSharpView.WinUI/CartesianChart.xaml.cs#L443) are of type `IEnumerable`.

This means that you can bind `Lists` or `ObservableCollection` instances to these properties and you will get the `Add` method.

For the special case of the `Add Range` there are more things to discuss, but I think that that is not related with the nature of this issue, we can discuss that in a new one.
