### ISSUE TITLE
System.ArgumentOutOfRangeException while using Date Time Scale chart

### ISSUE THREAD

**Issue by vadimffe** [beto-rodriguez/LiveCharts2#888]
**Describe the bug**
I am testing Date Time Scale chart (https://lvcharts.com/docs/Maui/2.0.0-beta.700/samples.axes.dateTimeScaled ) and my current implementation with latest update (2.0.0-beta.700) is throwing exception if my data model does not have any values (=empty). 

![image](https://user-images.githubusercontent.com/72302395/212545628-f74d7ca5-bb22-44ab-b9f8-1e2a04596f7a.png)

```
System.ArgumentOutOfRangeException
  HResult=0x80131502
  Message=Ticks must be between DateTime.MinValue.Ticks and DateTime.MaxValue.Ticks. Arg_ParamName_Name
  Source=System.Private.CoreLib
  StackTrace:
   at System.DateTime.ThrowTicksOutOfRange()
   at System.DateTime..ctor(Int64 ticks)
   at .ViewModels.HomeViewModel.<>c.<.ctor>b__0_5(Double value) in C:\...\ViewModels\HomeViewModel.cs:line 435
   at LiveChartsCore.Axis`3.TryGetLabelOrLogError(Func`2 labeler, Double value)
```
Previously I was using version 513 and it was not throwing any exception with exactly the same setup. Should this be handled by library or user itself?

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 2.0.0-beta.700
 - NET MAUI NET 7

**Comment by vadimffe** [comment]
I have not checked all the recent updates. However it looks like at some point after 2.0.0-beta.700 this issue has been resolved as cloning current version of repo and referencing it in my solution, I am not getting this error anymore. Would appreciate updating packages more frequently.

**Comment by vadimffe** [comment]
With an update to `<PackageReference Include="LiveChartsCore.SkiaSharpView.Maui" Version="2.0.0-beta.701" />` issue is still present.

**Comment by beto-rodriguez** [comment]
Thanks for the report, we can track this at #898
