### ISSUE TITLE
Scaling gets weird after adding Cartesian chart control to the Winform. 

### ISSUE THREAD

**Issue by davlovsky** [beto-rodriguez/LiveCharts2#89]
I'm trying to add the Cartesian chart control to a WinForm application. It adds fine, but when I go to run the project in VS2019, the scaling is off...smaller. It looks "WPF-y". I'm guessing that it is because the WInForm controls are based on the WPF controls? Is there a way to fix this, and preserve the original, WinForm scaling?

**Comment by beto-rodriguez** [comment]
please add an image, the controls are not based on wpf in v2

**Comment by davlovsky** [comment]
![Normal](https://user-images.githubusercontent.com/33270296/125891808-43f72863-fc1b-4a8c-bfb2-11638cc45c41.PNG)
![Skewed](https://user-images.githubusercontent.com/33270296/125891810-03ce310e-e733-4572-85a2-fe1cd9a8907d.PNG)

I added the LiveCharts, LiveCharts.WPF, and the LiveCharts.Winform NUGET packages. Am I on version 1?

**Comment by davlovsky** [comment]
Yeah, I was on V1. I must have missed the line on your main github page for the link to the beta NUGET package. My bad.
