### ISSUE TITLE
WPF DEMO of multi-threading  MAKE UI non-interactive

### ISSUE THREAD

**Issue by heartacker** [beto-rodriguez/LiveCharts2#892]
**Describe the bug**

**To Reproduce**
![image](https://user-images.githubusercontent.com/1876302/212650920-54e7e7fd-b31b-423a-a4b9-9057216544c8.png)

**Expected behavior**
UI of WPF can be interactive
**Screenshots**

**Additional context**
UI of WPF is non-interactive

**Comment by beto-rodriguez** [comment]
I will close this because we need more info to track this. feel free to reply here or open a new issue if you found more info about this case.
