### ISSUE TITLE
High resolution heatmap -- is it possible?

### ISSUE THREAD

**Issue by sleytus2** [beto-rodriguez/LiveCharts2#894]
Newbie here...

We are using LiveCharts in an Avalonia project that acquires and displays RF spectrum data. So far it works great and suits our purpose. I am currently attempting to create a high resolution heatmap and I think I'm close -- except there are gaps of white space between the cells. Is there a way to remove the space between the colored cells? I've attached an image to show what I mean.

Thanks...

![LiveCharts-Heatmap](https://user-images.githubusercontent.com/98443960/212879287-1f7aac9a-2340-4fa5-93aa-a66dbf353814.png)

**Comment by sleytus2** [comment]
I found it -- set PointPadding to '0'...

![LiveCharts-Heatmap-2](https://user-images.githubusercontent.com/98443960/212879455-112d50d1-91cc-4e3e-8875-55a6f4c05a05.png)

**Comment by beto-rodriguez** [comment]
Glad to read that you found a solution!
