### ISSUE TITLE
"System.Exception: Failed to run emscripten." when trying to build Uno.Wasm.

### ISSUE THREAD

**Issue by smischke** [beto-rodriguez/LiveCharts2#899]
I'm trying to build an Uno project with platforms Mobile, Skia.Gtk, Wasm and Windows which all use the package "LiveChartsCore.SkiaSharpView.Uno.WinUI" version 2.0.0-beta.700. My OS is Windows 10 22H2 and my IDE is Visual Studio 2022 v17.4.4 using the extension "Uno Platform Solution Template" v4.6.39.33. Target is .net 6.0.

Building the Uno.Wasm project fails with error "System.Exception: Failed to run emscripten.". I can see that emscripten is pulled from git and stored in "c:\Users\user\.uno\emsdk\emsdk-3.1.12\emsdk\" and there is a file "c:\Users\user\.uno\emsdk\emsdk-3.1.12\.uno-install-done" which contains '"installed" \r\n'. Some ninja task is running before the build fails. 

The exact error is: 
`System.Exception: Failed to run emscripten. More details are available in diagnostics logging mode or using the MSBuild /bl switch, see https://aka.platform.uno/msbuild-troubleshoot.
   bei Uno.Wasm.Bootstrap.ShellTask_vf9d4b1283d9a104e712cab3038c84f1737222b98.RunPackager() in D:\a\1\s\src\Uno.Wasm.Bootstrap\ShellTask.cs:Zeile 718.
   bei Uno.Wasm.Bootstrap.ShellTask_vf9d4b1283d9a104e712cab3038c84f1737222b98.Execute() in D:\a\1\s\src\Uno.Wasm.Bootstrap\ShellTask.cs:Zeile 255.`

Using msbuild /bl doesn't show more information. There's also a warning "NU1504: Duplicate 'PackageReference' items found. Remove the duplicate items or use the Update functionality to ensure a consistent restore behavior. The duplicate 'PackageReference' items are: Microsoft.Windows.Compatibility 6.0.0, Microsoft.Windows.Compatibility 5.0.0." although there is only one PackageReference in the project file.

1. Open Visual Studio 2022 v17.4.4
2. Create a new "Uno Platform App" using the extension "Uno Platform Solution Template" v4.6.39.33
3. Install the NuGet package "LiveChartsCore.SkiaSharpView.Uno.WinUI" version 2.0.0-beta.700 to all uno platforms
4. Build the solution

**Comment by rabejens** [comment]
You must also explicitly add a dependency to `SkiaSharp.Views.Uni.WinUI` version 2.88.3. The Nuget package transitively adds version 2.88.2 which is incompatible with the current version of Uno.

**Comment by smischke** [comment]
> 

Now the project builds, thanks a lot!
