### ISSUE TITLE
LiveCharts.Geared已经激活了，为何系统中还是无法运行，还是会出现LiveCharts错误

### ISSUE THREAD

**Issue by xiaomumo** [beto-rodriguez/LiveCharts2#9]

**Comment by lihongfang16** [comment]
代码发上来瞅瞅呗

**Comment by xiaomumo** [comment]
> 代码发上来瞅瞅呗
这个跟代码没有关系，因为我第一版本已经投入使用当中了，然后通过这个代码拉取的一个副本在其他机器上运行就会出现这个错误

**Comment by xiaomumo** [comment]
> 代码发上来瞅瞅呗
{"未能从程序集“LiveCharts, Version=0.9.7.0, Culture=neutral, PublicKeyToken=0bc1f845d1ebb8df”中加载类型“LiveCharts.Definitions.Series.IGroupedStackedSeriesView”。":"LiveCharts.Definitions.Series.IGroupedStackedSeriesView"}
这个就是错误描述

**Comment by beto-rodriguez** [comment]
@xiaomumo please stop spamming messages in both repositories, feel free to send an email to support@lvcharts.net to continue with this conversation.
