### ISSUE TITLE
Provide a means to enumerate the default colors

### ISSUE THREAD

**Issue by rabejens** [beto-rodriguez/LiveCharts2#903]
I am trying to create a `LineSeries` in my view model. Currently I have something like this:

```csharp
            yield return new LineSeries<(double x, double y)> {
                LineSmoothness = 0,
                Name = ...,
                Values = EnumeratePoints(),
                Mapping = (p, cp) => {
                    cp.PrimaryValue = p.y;
                    cp.SecondaryValue = p.x;
                }
            };
```

When I set `Fill` to `null`, the lines disappear. When I set `Stroke` to a `new SolidColorPaint(SKColor.Empty, 1)` my line width is 1 as I want it, but it is very faint. When I set the Alpha channel of the color to 255, the line becomes black.

What I basically want to achieve:

- Draw solid lines with a thickness of 1
- No fill
- No geometry stroke/fill

I discovered that when setting `Fill`, `GeometryStroke` and `GeometryFill` to `null`, I almost get there, but I explicitly have to specify a color, so I have to maintain my own list with all colors I want somewhere and cycle through it. It would be nice if there was a static list somewhere that contains all the default colors.

**Comment by rabejens** [comment]
Follow up: I extracted the colors by creating a dummy plot with 1000 lines, attaching an event handler to the `UpdateFinished` properties and enumerated the distinct colors. Here is what I found out:

```csharp
public static class DefaultColors {

    public static IReadOnlyList<SKColor> Colors { get; } = new SKColor[] {
        new SKColor(33, 150, 243, 255),
        new SKColor(244, 67, 54, 255),
        new SKColor(139, 195, 74, 255),
        new SKColor(0, 188, 212, 255),
        new SKColor(63, 81, 181, 255),
        new SKColor(255, 193, 7, 255),
        new SKColor(0, 150, 136, 255),
        new SKColor(233, 30, 99, 255),
        new SKColor(96, 125, 139, 255)
    }.ToImmutableArray();
}
```

**Comment by beto-rodriguez** [comment]
This is not documented properly yet because in general themes are not. You can find the colors here:

https://github.com/beto-rodriguez/LiveCharts2/blob/master/src/LiveChartsCore/Themes/ColorPalletes.cs

The default color set is [material500](https://github.com/beto-rodriguez/LiveCharts2/blob/master/src/skiasharp/LiveChartsCore.SkiaSharp/ThemesExtensions.cs#L56).

I think this is enough in your case, this will have better docs in the future, let me know if you can not solve your issue with this or face any new issue.

**Comment by seikosantana** [comment]
Is there a way to override only stroke thickness but stick to default colors for each created series?
