### ISSUE TITLE
Basic Gauge Negative Values

### ISSUE THREAD

**Issue by RobertoGFilho** [beto-rodriguez/LiveCharts2#907]
Hi there,

I'm wonking with negative values on basic gauge, then it seems it's not ok , see:

![image](https://user-images.githubusercontent.com/68563526/215363553-9548c275-4007-4fec-bbae-a9e9cc717c83.png)

**Comment by ragiovan** [comment]
I second this. It would be nice to have even a simple workaround so a negative value is a valid value.

**Comment by beto-rodriguez** [comment]
Hi, this is interesting.

I think that the best solution here is just to plot the absolute value, and then just format the label to add the negatives. I need some feel free to add any thoughts.

**Comment by beto-rodriguez** [comment]
@ragiovan why the down vote? isn.t that a simple workaround?

**Comment by ragiovan** [comment]
For a simple implementation it's a simple workaround.

The higher you go in an negative value generally the larger that is. However, taking the absolute value of a negative value will produce the opposite effect (the larger the negative, the larger the positive). This then requires some mapping solution to map small negative values to a large positive and a large negative to a small positive.

Not to mention having to put a negative value at some random location on the screen that has to be relative to the gauge at all times, but also needs to scale as the size of the gauge dynamically scaling.

The workaround is a horrible solution. Ask me how I know.

**Comment by beto-rodriguez** [comment]
Thanks for sharing your thoughts, that helps a lot.

**Comment by beto-rodriguez** [comment]
This Will be supported int the next version of the library (beta.920).

Thanks for thew report, since the next version we can speficy the gauge range using the `MaxValue` and `MinValue` properties, sample [here](https://github.com/beto-rodriguez/LiveCharts2/blob/master/samples/WPFSample/Pies/Gauge1/View.xaml).
