### ISSUE TITLE
[WPF] MarginFrame is displayed above Sections

### ISSUE THREAD

**Issue by LabuzzMichal** [beto-rodriguez/LiveCharts2#91]
**Describe the bug**
MarginFrame is displayed above Sections causing sections to dissappear if MarginFrame is filled with some color

**To Reproduce**
1. Create CartesianChart with DrawMarginFrame and Sections defined
2. Set Fill property on DrawMarginFrame
3. Set at least one Section
4. Section is not visible

**Expected behavior**
MarginFrame should be layered below sections and sections should respect MarginFrame stroke thickness

**Desktop (please complete the following information):**
 - OS: Windows 10
 - WPF
 - Beta 32

**Additional context**
As a workaround it is possible to set Sections Zindex

**Comment by beto-rodriguez** [comment]
This should be fixed with the refenced commit, this fix is included since `v2.0.beta.33`.

Thanks for the report.
