### ISSUE TITLE
How to upgrade v0 library?

### ISSUE THREAD

**Issue by HJLeeProject** [beto-rodriguez/LiveCharts2#910]
There is a library that I bought a year or two ago.

Maybe ver0 library.

How to upgrade v0 to v2 library?

When using the V0 library, the 'https://lvcharts.net/Licensing/License404' site appears.

I would like to resolve this issue.

**Comment by beto-rodriguez** [comment]
For now, you can contact me to `rodriguezo.alberto@gmail.com` and I will be happy to assist you and generate an activation code for you.

Yes, there is going to be a migration license to v2, this version is much more solid and extremely much performant, the final release of v2 should be available in November of this year.

I will close this for now, but you will receive a notification to your email once v2 is available and you can migrate.

Thanks for your comprehension and do not hesitate to mail me!
