### ISSUE TITLE
ToolTip and Legend GeometryStrokes and GeometryFill not updating correctly in b701

### ISSUE THREAD

**Issue by danielgruethling** [beto-rodriguez/LiveCharts2#913]
**Describe the bug**
I have used XAML binding to bind a ColorPicker to a property which changes Stroke, GeometryStroke and GeometryFill when the selected color changes. The Stroke and Geometry properties for my LineSeries update properly but the GeometryStroke and GeometryFill presented in the ToolTip and Legend do not.
The legend updates once I make the LineSeries invisible for some time and turn it back to visible. The ToolTip does not update at all.

**To Reproduce**
1. Compile the included project.  [LVC_Testproject.zip](https://github.com/beto-rodriguez/LiveCharts2/files/10544604/LVC_Testproject.zip)
2. Start the application.
3. Change the color from the ColorPicker.
4. See behaviour described above.

**Expected behavior**
ToolTip and Legend geometries should update properly like the LineSeries does.

**Screenshots**

Application start:
![grafik](https://user-images.githubusercontent.com/31628469/215716968-f1ea73fb-a1c2-4121-8a2a-eec55016cb50.png)

Change color and observe only line color changes:
![grafik](https://user-images.githubusercontent.com/31628469/215717105-3b58a46e-2c23-4be2-90a5-9c63557e0192.png)

Make series invisible:
![grafik](https://user-images.githubusercontent.com/31628469/215717172-c3f4da72-b1a7-46e8-a410-8d603c3ab0fc.png)

Make it visible again and observe Legend updated but ToolTip did not:
![grafik](https://user-images.githubusercontent.com/31628469/215717318-c30a623b-dd76-44a8-8ab6-82cd751a32d6.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser N/A
 - Version b701 for WinUI3

**Smartphone (please complete the following information):**
 - Device: N/A
 - OS: N/A
 - Browser N/A
 - Version N/A

**Additional context**
This used to work back in b516 iirc. This broke with a lot of other things in b700. I'll probably have to roll back to an older version because so many things are currently broken.

**Comment by danielgruethling** [comment]
Issue can be reproduced in b710 as well.

**Comment by rocinn** [comment]
> Thanks for the report and the sample., it seems that this issue is already fixed in the current dev branch, this will be fixed in the next version of the library, I will close this for now, thanks again! ![sss](https://private-user-images.githubusercontent.com/10853349/243896455-32e50e46-6720-4bdc-a5d5-3914a1df2e54.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0NDYyNzYsIm5iZiI6MTcyODQ0NTk3NiwicGF0aCI6Ii8xMDg1MzM0OS8yNDM4OTY0NTUtMzJlNTBlNDYtNjcyMC00YmRjLWE1ZDUtMzkxNGExZGYyZTU0LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA5VDAzNTI1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlYWZjMTViZGNlMmQ3NjdmZmQ3NDIyZjY0N2VkODFjNGQ3YzhkNWYzZTE3MzM1NzQ1YjVlZmI2MzE4N2FmZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.3gl6vLNzMDLmQE91tZ_de7AotovEoeVmpBJyjNod1OA) [ ![sss](https://private-user-images.githubusercontent.com/10853349/243896455-32e50e46-6720-4bdc-a5d5-3914a1df2e54.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0NDYyNzYsIm5iZiI6MTcyODQ0NTk3NiwicGF0aCI6Ii8xMDg1MzM0OS8yNDM4OTY0NTUtMzJlNTBlNDYtNjcyMC00YmRjLWE1ZDUtMzkxNGExZGYyZTU0LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA5VDAzNTI1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlYWZjMTViZGNlMmQ3NjdmZmQ3NDIyZjY0N2VkODFjNGQ3YzhkNWYzZTE3MzM1NzQ1YjVlZmI2MzE4N2FmZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.3gl6vLNzMDLmQE91tZ_de7AotovEoeVmpBJyjNod1OA) ](https://private-user-images.githubusercontent.com/10853349/243896455-32e50e46-6720-4bdc-a5d5-3914a1df2e54.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0NDYyNzYsIm5iZiI6MTcyODQ0NTk3NiwicGF0aCI6Ii8xMDg1MzM0OS8yNDM4OTY0NTUtMzJlNTBlNDYtNjcyMC00YmRjLWE1ZDUtMzkxNGExZGYyZTU0LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA5VDAzNTI1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlYWZjMTViZGNlMmQ3NjdmZmQ3NDIyZjY0N2VkODFjNGQ3YzhkNWYzZTE3MzM1NzQ1YjVlZmI2MzE4N2FmZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.3gl6vLNzMDLmQE91tZ_de7AotovEoeVmpBJyjNod1OA) [ ](https://private-user-images.githubusercontent.com/10853349/243896455-32e50e46-6720-4bdc-a5d5-3914a1df2e54.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0NDYyNzYsIm5iZiI6MTcyODQ0NTk3NiwicGF0aCI6Ii8xMDg1MzM0OS8yNDM4OTY0NTUtMzJlNTBlNDYtNjcyMC00YmRjLWE1ZDUtMzkxNGExZGYyZTU0LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA5VDAzNTI1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlYWZjMTViZGNlMmQ3NjdmZmQ3NDIyZjY0N2VkODFjNGQ3YzhkNWYzZTE3MzM1NzQ1YjVlZmI2MzE4N2FmZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.3gl6vLNzMDLmQE91tZ_de7AotovEoeVmpBJyjNod1OA)

Which version has fixed this issue? I am currently using LiveChartsCore.SkiaSharpView.Avalonia version 2.0.0-rc3, and I am still experiencing this problem.

**Comment by beto-rodriguez** [comment]
See https://github.com/beto-rodriguez/LiveCharts2/discussions/1427 for the answer.

**Comment by rocinn** [comment]
> > Thanks for the report and the sample., it seems that this issue is already fixed in the current dev branch, this will be fixed in the next version of the library, I will close this for now, thanks again!
> 
> Which version has fixed this issue? I am currently using LiveChartsCore.SkiaSharpView.Avalonia version 2.0.0-rc3, and I am still experiencing this problem.
> 
see https://github.com/beto-rodriguez/LiveCharts2/discussions/1632
