### ISSUE TITLE
[BUG]Error when using avalonia version in wasm mode

### ISSUE THREAD

**Issue by charleypeng** [beto-rodriguez/LiveCharts2#914]
I use avalonia  in my project and livecharts2 , in desktop mode it worked fine but in wasm web mode it went wrong.

[error info]
Parameter types of pinvoke callback method 'System.Int32 SetMinMaxSize(System.Void*, Avalonia.Native.Interop.AvnSize, Avalonia.Native.Interop.AvnSize)' needs to be blittable.	xxx.Web	C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.WebAssembly.Sdk\7.0.0\Sdk\WasmApp.Native.targets	292	

[version]
avalonia:11.0-preview4
dotnet sdk:7.0
livecharts:2.0.0-beta.700-11.0.0-preview4
vs2022:17.4.1
windows10

**Comment by beto-rodriguez** [comment]
Thanks for the report, we can track this issue at #914
