### ISSUE TITLE
Setting minimun bars padding

### ISSUE THREAD

**Issue by Amir0715** [beto-rodriguez/LiveCharts2#915]
Hi, It's possible set minimum distance between columns in Chart? 

I wont get like this:
![изображение](https://user-images.githubusercontent.com/45153320/215789011-d7eea295-e82c-4213-8610-236ee9b8dfc0.png)

**Comment by beto-rodriguez** [comment]
This can be done by setting the ` MaxBarWidth` to `double.PositiveInfinity`.

https://github.com/beto-rodriguez/LiveCharts2/blob/master/samples/ViewModelsSamples/Bars/Spacing/ViewModel.cs

Adn the result:

![image](https://github.com/beto-rodriguez/LiveCharts2/assets/10853349/6b7134f2-06c4-4bae-939d-c1011073d1d1)
