### ISSUE TITLE
Uno documentation page not working

### ISSUE THREAD

**Issue by baskren** [beto-rodriguez/LiveCharts2#917]
**Describe the bug**
UNO version of the documentation page is not working
https://lvcharts.com/docs/unowinui/2.0.0-beta.700/gallery

**To Reproduce**
1. Go to [Uno Documentation Page](https://lvcharts.com/docs/unowinui/2.0.0-beta.700/gallery)
2. Compare to the MAUI page: https://lvcharts.com/docs/maui/2.0.0-beta.700/gallery

**Expected behavior**
UNO page should be as good as MAUI page

**Screenshots**
UNO PAGE:
<img width="982" alt="image" src="https://user-images.githubusercontent.com/2528888/216076736-00dc155f-3229-4207-990d-8f5742994335.png">

MAUI PAGE:
<img width="982" alt="image" src="https://user-images.githubusercontent.com/2528888/216076807-e7784ba0-b0e5-403f-9dac-f97ff02f1546.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Safari
 - Version 16.3 (18614.4.6.1.5)

**Comment by sasakrsmanovic** [comment]
@baskren Is this the page you were looking for https://lvcharts.com/docs/uno/2.0.0-beta.700/gallery

**Comment by sasakrsmanovic** [comment]
I see what you mean - if accessed from the LiveCharts website, the link takes you to the place you are pointing to 
![image](https://user-images.githubusercontent.com/33944563/220692138-82d96a48-1bc4-487a-8d47-78523557c64b.png)

**Comment by baskren** [comment]
Yes!  Thanks!

**Comment by baskren** [comment]
Sorry I wasn’t so clear. Thank you for taking the time to figure it out.

**Comment by beto-rodriguez** [comment]
This is already fixed and updated to the latest Uno version, sorry about that!
