### ISSUE TITLE
Axis title/description

### ISSUE THREAD

**Issue by rgomez90** [beto-rodriguez/LiveCharts2#92]
**Is your feature request related to a problem? Please describe.**
There is no option to show axes titles/names. Every correct chart should have descriptions for the axes.

**Describe the solution you'd like**
An option to show a text (maybe also custom control) as axis name/title.

**Describe alternatives you've considered**
The only option now would be to have the axis title/description implemented "externally" via UI Control.

**Comment by beto-rodriguez** [comment]
This should be fixed with the refenced commit, this fix is included since `v2.0.beta.33`.

Thanks for the report.
