### ISSUE TITLE
Chinese cannot be displayed in WPF application.Version [2.0.0-beta.701]

### ISSUE THREAD

**Issue by 2270969436** [beto-rodriguez/LiveCharts2#922]
**Chinese cannot be displayed in WPF application**. Version [2.0.0-beta.701](https://www.nuget.org/packages/LiveChartsCore.SkiaSharpView.WPF/2.0.0-beta.701)
![屏幕截图_20230205_203136](https://user-images.githubusercontent.com/45121491/216818919-c0976838-6d85-490d-979f-b11089e7ccbc.png)

**Chinese can be displayed in WPF application**. Version [2.0.0-beta.516](https://www.nuget.org/packages/LiveChartsCore.SkiaSharpView.WPF/2.0.0-beta.516)
![屏幕截图_20230205_203813](https://user-images.githubusercontent.com/45121491/216819112-cc03eddf-a5d3-4afe-bc67-1d155a158e6d.png)

**Comment by TewQ** [comment]
Bind `TooltipTextPaint` Attribute in XAML.
```
<wpf:CartesianChart
    TooltipTextPaint="{Binding UiItem.SolidPaint}">
</wpf:CartesianChart>
```

then,  set `SolidPaint` Attribute in Model Class.
```
private SolidColorPaint mSolidPaint = new SolidColorPaint
{
    Color = SKColors.Black,
    SKTypeface = SKFontManager.Default.MatchCharacter('汉'),
    FontFamily = "Microsoft YaHei"
};

/// <summary>
/// 颜色
/// </summary>
public SolidColorPaint SolidPaint
{
    get => mSolidPaint;
    set
    {
        mSolidPaint = value;
        RaisePropertyChanged(() => SolidPaint);
    }
}
```

**Comment by 2270969436** [comment]
您好，您的邮件已收到。我会尽快给您回复。

**Comment by beto-rodriguez** [comment]
Please follow what @TewQ told you, this will be improvend in future versions.

**Comment by 2270969436** [comment]
您好，您的邮件已收到。我会尽快给您回复。
