### ISSUE TITLE
Can't use LiveCharts2 with Avalonia preview5

### ISSUE THREAD

**Issue by kikipoulet** [beto-rodriguez/LiveCharts2#925]
Using LiveCharts with Avalonia preview5 throws this error : 

System.TypeInitializationException: The type initializer for 'LiveChartsCore.SkiaSharpView.Avalonia.CartesianChart' threw an exception.
 ---> System.MissingMethodException: Method not found: 'Avalonia.StyledProperty`1<!!1> Avalonia.AvaloniaProperty.Register(System.String, !!1, Boolean, Avalonia.Data.BindingMode, System.Func`2<!!1,Boolean>, System.Func`3<Avalonia.IAvaloniaObject,!!1,!!1>, System.Action`2<Avalonia.IAvaloniaObject,Boolean>)'.
   at LiveChartsCore.SkiaSharpView.Avalonia.CartesianChart..cctor()
   --- End of inner exception stack trace ---
   at LiveChartsCore.SkiaSharpView.Avalonia.CartesianChart.!XamlIlPopulateTrampoline(CartesianChart)
   at LiveChartsCore.SkiaSharpView.Avalonia.CartesianChart.InitializeComponent()
   at LiveChartsCore.SkiaSharpView.Avalonia.CartesianChart..ctor()

EDIT : Guess it's already done, just need the nuget package then [56b838c](https://github.com/beto-rodriguez/LiveCharts2/pull/924/commits/56b838cf8839981d1b4c469946b1529f2d3300ec)

**Comment by KindOfGod** [comment]
I have the same problem.

**Comment by l3roit** [comment]
Same here

**Comment by DirkKramer** [comment]
Just checked, new nuget for Avalonia preview 5 is available.

**Comment by beto-rodriguez** [comment]
This is already published.
