### ISSUE TITLE
Graph freezes with new remote desktop connection

### ISSUE THREAD

**Issue by mcipjvw** [beto-rodriguez/LiveCharts2#926]
Hi, I am using a virtual machine with an app using WPF LiveCharts 0.9.7. Everything is just fine until the remote desktop session is closed and opened again. The graph stops adding new datapoints and its size is not correct as well. The app uses MVVM.
Any ideas? 
Cheers
Mart

**Comment by beto-rodriguez** [comment]
Hello, this issue belongs to live charts 0 it seems that we need more information to help you, please identify the issue clearly, it seems that there are multiple reasons that could cause that, it is not clear if LiveCharts causes the issue.  Feel free to open a new ticket if you found evidence that the library is causing the issue!

**Comment by mingpepe** [comment]
I encountered the same issue. It only happened when the value was added from a background thread.
```
SeriesCollection = new SeriesCollection
{
    new LineSeries
    {
        Title = "Demo Line",
        Values = new ChartValues<double>()
    }
};

// It works even after a Remote Desktop connection or disconnection
timer = new DispatcherTimer
{
    Interval = TimeSpan.FromSeconds(1)
};
timer.Tick += (s, e) =>
{
    SeriesCollection[0].Values.Add(_random.Next(0, 100));
};
timer.Start();

// It works under normal conditions, but fails to update the chart after a Remote Desktop connection or disconnection.
Task.Run(() =>
{
    while (true)
    {
        SeriesCollection[0].Values.Add(_random.Next(0, 100));
        Thread.Sleep(1000);
    }
});
```
So you can dispatch the work to the UI thread, or you can detect session change events.
```
SystemEvents.SessionSwitch += (s, e) =>
{
    if (e.Reason == SessionSwitchReason.SessionLock)
    {
        dispatcherToUi = true;
    }
    else if (e.Reason == SessionSwitchReason.SessionUnlock)
    {
        dispatcherToUi = false;
    }
};
```

Before the RemoteConnect event fires, the SessionLock event is triggered.
