### ISSUE TITLE
Customizable Legend

### ISSUE THREAD

**Issue by Ethilyk** [beto-rodriguez/LiveCharts2#927]
**Is your feature request related to a problem? Please describe.**
The current legend only shows the name and a sketch. I see there is a way to add a custom legend but I didn't find any way to add Events on it.

**Describe the solution you'd like**
A way to add events such as OnHover and OnClick on the legend to add interactability allowing us to hide series on click or highlight series on hover

Also, I didn't see a way of adding new components on the legends, it could be interesting to add labels on the legend for PieSeries to show the percentage of the series.

To further customize the legends, maybe we could add a .xaml as a view for the legend.

If those features are already available, is it possible to have documentations on those because as of today the custom legends docs isn't really exhaustive it could help if the documentation had more examples of things we could customize.

**Comment by beto-rodriguez** [comment]
This is partially implemented already, I missed the `OnHover` behaviour, but we can now subscribe to the pointer down event:

https://livecharts.dev/docs/WPF/2.0.0-beta.950/samples.general.customLegends

**Comment by beto-rodriguez** [comment]
This is fully supported since old versions of the library, the VisualElement class provides the `PointerDown` event, and legends in the latest versions use visual elements to display the miniature and the series name.

I know a sample is missing, but I will close this for now since this should be already working.
