### ISSUE TITLE
How to create grouped nested bar chart?

### ISSUE THREAD

**Issue by polliniafc** [beto-rodriguez/LiveCharts2#929]
### Discussed in https://github.com/beto-rodriguez/LiveCharts2/discussions/919

<div type='discussions-op-text'>

<sup>Originally posted by **polliniafc** February  2, 2023</sup>
Is it possible to create a chart like this with LiveCharts2? Thanks!

![image](https://user-images.githubusercontent.com/44291425/216310081-c2a87da3-1e10-45d5-9b34-4c739ab832d5.png)
</div>

**Comment by beto-rodriguez** [comment]
Hi, yes this should be possible, please take a look at:

https://github.com/beto-rodriguez/LiveCharts2/blob/master/samples/ViewModelsSamples/Bars/Layered/ViewModel.cs

And produces the next result:

![image](https://github.com/beto-rodriguez/LiveCharts2/assets/10853349/6593670b-45fd-4091-912b-f63c27387520)
