### ISSUE TITLE
[WPF] Error in generate LineSeries 

### ISSUE THREAD

**Issue by Bartos-Pol** [beto-rodriguez/LiveCharts2#93]
Hi i have a little problem with the chart rendering, in second Series show only show half the chart.
Code:

               IEnumerable<ISeries> panel_Zlecenia_Spedycja = new ObservableCollection<ISeries>
                {
                    new LineSeries<decimal>
                    {
                        Values =  zlecenia_Euro.Select(z=>z.Zysk),
                        Name =  "Zysk EURO ",
                        TooltipLabelFormatter = (chartPoint) => $"{chartPoint.Context.Series.Name}: {chartPoint.PrimaryValue}",
                        DataLabelsFormatter = (point) => point.PrimaryValue.ToString("C2")
                    },
                    new LineSeries<decimal>
                    {
                        Values =  zlecenia_Pln.Select(z=>z.Zysk),
                        Name =  "Zysk PLN ",
                    DataLabelsFormatter = (point) => point.PrimaryValue.ToString("C2") }
                };
                List<Axis> series_XAxes = new()
                {
                    new Axis
                    {
                        // Use the labels property to define named labels.
                        Labels = zlecenia_Euro.Select(x => x.Data.ToShortDateString()).ToList(),
                        LabelsRotation = 0,
                        MinStep = 1,
                        ShowSeparatorLines = true,
                        Position = LiveChartsCore.Measure.AxisPosition.Start
                    }
                };
                mw.Panel_LVC.DataContext = panel_Zlecenia_Spedycja;
                mw.Panel_LVC.Series = panel_Zlecenia_Spedycja;
                mw.Panel_LVC.XAxes = series_XAxes;

![126118717-1be73c8f-bba9-43fa-b1a0-94df2e620b57](https://user-images.githubusercontent.com/44208326/126138092-6db51c6b-49f8-455f-be9f-1c19304979b6.png)

**Comment by LabuzzMichal** [comment]
Hi @Bartos-Pol . In feature please use template while creating new issue. It should be fully reproducible - otherwise its really difficult to say what is wrong with your code. I suspect its related to your data. Are you sure that collections zlecenia_Pln and zlecenia_Euro have the same length ? If so please provide values for these collections so that someone can check it

**Comment by Bartos-Pol** [comment]
Hi sorry, I will use a template next time. 
The data is now shown, even the tooltip shows the correct value

![Bez tytułu](https://user-images.githubusercontent.com/44208326/126142591-baea0b19-27f5-4854-b2dd-1c1fb754ffd6.png)
