### ISSUE TITLE
Add support for .NET7 native AOT

### ISSUE THREAD

**Issue by laolarou726** [beto-rodriguez/LiveCharts2#930]
It will be awesome to have AOT publish enabled while using Livecharts2! It has many performance benefits and size improvements.

**Comment by charleypeng** [comment]
[https://github.com/charleypeng/Cagaya_Radar/tree/main/aot/Cagaya](https://github.com/charleypeng/Cagaya_Radar/tree/main/aot/Cagaya)

**Comment by beto-rodriguez** [comment]
AOT compilation is moving a lot in dotnet, I think it will work much better at a point, I do not think there is much LiveCharts can do here, we are just a math library, we calculate and animate shapes, then SkiaSharp and the framework (avalonia) render everything in the UI.

**Comment by beto-rodriguez** [comment]
AOT compilation is moving a lot in dotnet, I think it will work much better at a point, I do not think there is much LiveCharts can do here, we are just a math library, we calculate and animate shapes, then SkiaSharp and the framework (avalonia) render everything in the UI.
