### ISSUE TITLE
Seems incorrect encoding for Chinese

### ISSUE THREAD

**Issue by GF-Huang** [beto-rodriguez/LiveCharts2#931]
**Describe the bug**
I run the example from: https://lvcharts.com/docs/WPF/2.0.0-beta.700/samples.financial.basicCandlesticks

I got this:

![image](https://user-images.githubusercontent.com/4510984/218447793-c3bc7685-61fc-4474-9bd2-607adf97626a.png)

**To Reproduce**
Just run the example at other environments except English.

**Expected behavior**
The boxes above should be `月` in Chinese.

**Desktop (please complete the following information):**
 - OS: `Win11 22H2`
 - .NET: `7`
 - Version: `2.0.0-beta.701`

**Comment by torum** [comment]
I can confirm this with my app as well. Adding `new CultureInfo("ja-Jp")` did not help. Probably a font issue...

**Comment by seishinkouki** [comment]
This bug can be reproduced on .NET6  2.0.0-beta.701, And I found that someone had reported this before, refer to https://github.com/beto-rodriguez/LiveCharts2/issues/268
![image](https://user-images.githubusercontent.com/8842321/223445660-befcf333-1443-4728-bddf-1d7976b4dfa9.png)

**Comment by WZheng1126** [comment]
use 2.0.0-beta.516

**Comment by wwusq** [comment]
我现在也遇到这个问题，请问你怎么解决这个问题

**Comment by WZheng1126** [comment]
使用&nbsp;2.0.0-beta.516 版本




316052115
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "beto-rodriguez/LiveCharts2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月16日(星期四) 晚上7:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [beto-rodriguez/LiveCharts2] Seems incorrect encoding for Chinese (Issue #931)





 
我现在也遇到这个问题，请问你怎么解决这个问题

**Comment by tankvn** [comment]
If you want use Chinese/Japanese in Legends, then you can set font **"MS Gothic"** for `LegendTextPaint`

```xaml
<lvc:CartesianChart
	Series="{Binding Series}"
	LegendTextPaint="{Binding LegendTextPaint}"
</lvc:CartesianChart>
```

```cs
public SolidColorPaint LegendTextPaint { get; set; } = new SolidColorPaint
{
	Color = new SKColor(50, 50, 50),
	SKTypeface = SKTypeface.FromFamilyName("MS Gothic")
};
```

**Comment by tankvn** [comment]
If you want use Chinese/Japanese in **XAxes**, then you can set font "MS Gothic" for `LabelsPaint`

```
public Axis[] XAxes { get; set; } =
{
	new Axis
	{
		LabelsRotation = -40,
		Labeler = value => new DateTime((long)value).ToString("yyyy年MM月dd日HH:mm:ss"),
		LabelsPaint = new SolidColorPaint
		{
			Color = new SKColor(50, 50, 50),
			SKTypeface = SKTypeface.FromFamilyName("MS Gothic")
		},
		UnitWidth = TimeSpan.FromDays(1).Ticks
	}
};
```

**Comment by calmsboy** [comment]
private const string _fontFamliy = "Microsoft YaHei";
/// <summary>
    /// 用于解决中文乱码
    /// </summary>
    public SolidColorPaint LegendTextPaint { get; set; } = new SolidColorPaint
    {
        Color = new SKColor(50, 50, 50),
        SKTypeface = SKTypeface.FromFamilyName(_fontFamliy)
    };

**Comment by calmsboy** [comment]
可以用这种方法，亲测有效
 `
    private const string _fontFamliy = "Microsoft YaHei";
    /// <summary>
    /// 用于解决中文乱码
    /// </summary>
    public SolidColorPaint LegendTextPaint { get; set; } = new SolidColorPaint
    {
        Color = new SKColor(50, 50, 50),
        SKTypeface = SKTypeface.FromFamilyName(_fontFamliy)
    };

`

**Comment by beto-rodriguez** [comment]
The repo now contains docs for this and soon will be uploaded to the web site, please feel free to check this repo, the idea is to configure the library when the app starts, here is an example:

https://github.com/beto-rodriguez/LiveCharts2/blob/master/samples/WPFSample/App.xaml.cs#L33

**Comment by wangdaojun1985** [comment]
> The repo now contains docs for this and soon will be uploaded to the web site, please feel free to check this repo, the idea is to configure the library when the app starts, here is an example:
> 
> https://github.com/beto-rodriguez/LiveCharts2/blob/master/samples/WPFSample/App.xaml.cs#L33

hi, it doesn't seem to work in version 2.0.0-beta.950.
winforms
![123](https://github.com/beto-rodriguez/LiveCharts2/assets/87227314/38098670-df2a-4976-bb66-7b25711946db)

**Comment by zhaokuohaha** [comment]
@beto-rodriguez Is there any way to set fonts in global 🤣

**Comment by CareyYang** [comment]
Now,I tried many times, adding the following code to the App class in App.xaml.cs
```
protected override void OnStartup(StartupEventArgs e)
{
	base.OnStartup(e);
	LiveChartsSettings settings = new LiveChartsSettings();
	settings.HasGlobalSKTypeface(SKFontManager.Default.MatchCharacter('汉')); 
}
```
and it's worked.
