### ISSUE TITLE
WPF Event VisualElementsPointerDown have no data in VisualElements args

### ISSUE THREAD

**Issue by Esgire** [beto-rodriguez/LiveCharts2#937]
### On event VisualElementsPointerDown have no data in argument property VisualElements. 
I use a VisualElements collection for adding an alement LabelVisual. When I click on LabelVisual firing event VisualElementsPointerDown, but arguments property VisualElements still empty.

Version **514** was OK, but after updating to version **701** i cant get current LabelVisual for editing.

![obrazek](https://user-images.githubusercontent.com/72521301/219661528-e97580bf-c3e6-4245-9630-d0b39ede5bbb.png)

**Comment by beto-rodriguez** [comment]
Thanks for the report, this was fixed with 7b0ca97bc23e69fcc2623274802cd33cd4fa003f and will be included in the next version of 
 the library.
