### ISSUE TITLE
Issue with using LiveCharts2 with dynamically compiled code

### ISSUE THREAD

**Issue by ZjzMisaka** [beto-rodriguez/LiveCharts2#942]
I am trying to use LiveCharts2 to generate chart images by dynamically compiling code using Roslyn. Instead of using NuGet packages, I am using the DLL files directly, which include LiveChartsCore.dll, LiveChartsCore.SkiaSharpView.dll, and SkiaSharp.dll.

However, when I run the code, I get the following error:
"The type initializer for 'SkiaSharp.SKImageInfo' threw an exception."
at SkiaSharp.SKImageInfo..ctor(Int32 width, Int32 height)
at LiveChartsCore.SkiaSharpView.SKCharts.InMemorySkiaSharpChart.GetImage()
at LiveChartsCore.SkiaSharpView.SKCharts.InMemorySkiaSharpChart.SaveImage(String path, SKEncodedImageFormat format, Int32 quality)
at AnalyzeCode.Analyze.RunBeforeAnalyzeSheet(Param param, Object& globalObject, List`1 allFilePathList, Boolean isExecuteInSequence)

I also tried referencing HarfBuzzSharp.dll and SkiaSharp.HarfBuzz.dll, but the error persists. The code works fine when using NuGet packages, so I am unsure why this error is occurring when using the DLLs directly.

Here is the sample code that I am using:

```
using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using LiveChartsCore.SkiaSharpView.SKCharts;
using LiveChartsCore.SkiaSharpView;
using LiveChartsCore.SkiaSharpView.Painting;
using SkiaSharp;

......

            SKCartesianChart ch = new SKCartesianChart();
            List<LineSeries<double>> lineSeriesList = new List<LineSeries<double>>();
            LineSeries<double> lineSeries1 = new LineSeries<double>{
                Values = new double[] { 1, 1, 2, 3 ,5 },
                Stroke = new SolidColorPaint(SKColors.Blue) { StrokeThickness = 4 }, // mark
                Fill = null,
                GeometryFill = null,
                GeometryStroke = null
            };
            LineSeries<double> lineSeries2 = new LineSeries<double>{
                Values = new double[] { 2, 1, 4, 6 ,1 },
                Stroke = new SolidColorPaint(SKColors.Blue) { StrokeThickness = 4 }, // mark
                Fill = null,
                GeometryFill = null,
                GeometryStroke = null
            };
            lineSeriesList.Add(lineSeries1);
            lineSeriesList.Add(lineSeries2);
            ch.Series = lineSeriesList;
            ch.SaveImage("CartesianImageFromControl.png");
```

Can you please help me understand why this error is occurring and how I can resolve it?

**Comment by beto-rodriguez** [comment]
I am afraid that this issue belongs to SkiaSharp, there is not much we can do here :(
