### ISSUE TITLE
Issue of LineSeries with DateTimePoint

### ISSUE THREAD

**Issue by morriskimweco** [beto-rodriguez/LiveCharts2#948]
Chart is not displayed as I expected. The value of XAxis is displayed as one point.
For example, I added several DateTimePoints to ObservableCollection<DateTimePoint>.
However, CartesianChart displayed the DateTime of the Points as same.
Below is screenshot and code.

<img width="600" alt="image" src="https://user-images.githubusercontent.com/126845653/222628678-68714f4f-f70c-4c73-995e-4a233cab39f1.png">

using LiveChartsCore;
using LiveChartsCore.Defaults;
using LiveChartsCore.SkiaSharpView;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Threading;

namespace Livecharts2Test
{
    class MainWindowViewmodel
    {

        public ObservableCollection<DateTimePoint> DateTimePoints { get; set; }

        public List<ISeries> Series { get; set; }

        public Axis[] XAxes { get; set; } =
        {
            new Axis
            {
                Labeler = value => new DateTime((long) value).ToString("yyyy MM dd"),
                LabelsRotation = 80,
    
                // when using a date time type, let the library know your unit 
                UnitWidth = TimeSpan.FromDays(1).Ticks, 
    
                // if the difference between our points is in hours then we would:
                // UnitWidth = TimeSpan.FromHours(1).Ticks,
    
                // since all the months and years have a different number of days
                // we can use the average, it would not cause any visible error in the user interface
                // Months: TimeSpan.FromDays(30.4375).Ticks
                // Years: TimeSpan.FromDays(365.25).Ticks
    
                // The MinStep property forces the separator to be greater than 1 day.
                MinStep = TimeSpan.FromDays(1).Ticks
            }
        };

        public MainWindowViewmodel()
        {
            DateTimePoints = new ObservableCollection<DateTimePoint>()
                {
                new DateTimePoint(new DateTime(2021, 1, 1), 3),
                // notice we are missing the day new DateTime(2021, 1, 2)
                new DateTimePoint(new DateTime(2021, 1, 3), 6),
                new DateTimePoint(new DateTime(2021, 1, 4), 5),
                new DateTimePoint(new DateTime(2021, 1, 5), 3),
                new DateTimePoint(new DateTime(2021, 1, 6), 5),
                new DateTimePoint(new DateTime(2021, 1, 7), 8),
                new DateTimePoint(new DateTime(2021, 1, 8), 6)
            };
            var lineSeries = new LineSeries<DateTimePoint>()
            {
                Values = DateTimePoints
            };

            Series = new List<ISeries>();
            Series.Add(lineSeries);

            DateTime timeStamp = DateTime.Now;

            DateTimePoints.Add(new DateTimePoint(timeStamp, 1));
            return;

            timeStamp.AddSeconds(100);
            DateTimePoints.Add(new DateTimePoint(timeStamp, 2));
            timeStamp.AddYears(100);
            DateTimePoints.Add(new DateTimePoint(timeStamp, 3));

        }
    }
}

 - OS: Windows 11
 - Version: Latest (22H2, OS Build 22621.1344)

Could I know how to add DateTimePoint without problem of chart display?

**Comment by ParkhutRoman** [comment]
try set in CartesianChart.XAxes Labeler and MaxLimit

**Comment by mark-monteiro** [comment]
This looks like it is rendering as expected. You've added several points in 2021 which all appear bunched together and a single point in 2023 which appears separated by a year from the other points.

**Comment by beto-rodriguez** [comment]
Hello it seems that the plot is correct. both previous comments are right, it seems that the error that you first points have a distance of about 1 year to the last point.

Please feel free to reply if you think we misunderstood the issue, thanks for the report!
