### ISSUE TITLE
The Tooltip is not displayed completely, and the part that extends beyond the control is not displayed

### ISSUE THREAD

**Issue by xwang-888** [beto-rodriguez/LiveCharts2#949]
![image](https://user-images.githubusercontent.com/56998197/223334229-161b96f3-5408-424c-9c94-22db9df5753b.png)
The Tooltip is not displayed completely, and the part that extends beyond the control is not displayed。

**Comment by beto-rodriguez** [comment]
Hi and thanks for the report, yes, there were some changes in the previous releases that caused this.

I will close this for now we can track this issue at #912, please feel free to add any additional info or thoughts there, this issue will now be referenced there.
