### ISSUE TITLE
about geomap

### ISSUE THREAD

**Issue by ChenGuyu** [beto-rodriguez/LiveCharts2#951]
Taiwan is an integral part of China, is Taiwan an independent country in GeoMap?I like this control very much，It is not right to treat Taiwan as an independent country

**Comment by RianQuenlin** [comment]
How terrible is the education in your country that you don't know your own country's geography?

**Comment by ChenGuyu** [comment]
> How terrible is the education in your country that you don't know your own country's geography?

So, what is the geography you learned from your country?

**Comment by RianQuenlin** [comment]
I don't answer questions from Nazis.

**Comment by ChenGuyu** [comment]
> 

Me too, you Nazi Bitch

**Comment by ChenGuyu** [comment]
> I don't answer questions from Nazis.

me too，you nazi btich

**Comment by beto-rodriguez** [comment]
Any map provided in this library and the information that it contains comes from public databases, this is something that is out of the hands of the library.

You can also always build your own map (it will be documented in a future version), but for now all the maps do not belong to the library but to public databases where I do not have any opinion or power to change the maps.

I also invite you to respect the [code of conduct](https://github.com/beto-rodriguez/LiveCharts2/blob/master/CODE_OF_CONDUCT.md) in this library, we are here only to code and build cool stuff!
