### ISSUE TITLE
Change of Visibility of RectangularSection not updating chart

### ISSUE THREAD

**Issue by daniellorencik** [beto-rodriguez/LiveCharts2#958]
**Describe the bug**
Changing the IsVisible property of RectangularSection will not update visibility of section in chart in LiveChartsCore.SkiaSharpView.WPF version 2.0.0-beta701 

Works in LiveChartsCore.SkiaSharpView.WPF version 2.0.0-beta603

**To Reproduce**
CheckBox in UI (.Net 6 WPF app) sets the value of IsVisible property for RectangularSection. 
Property value is changed, but the RectangularSection stays visible (or invisible) until chart area update (resize window, resize of the chart area).

**Expected behavior**
Rectangular section visible or not after changing visibility.

**Desktop (please complete the following information):**
 - OS: Win11 Arm
 - Visual Studio Code

**Comment by beto-rodriguez** [comment]
mm strange...

I am not sure if `2.0.0-beta701` had a specific issue, but this seems to be working in the dev branch, please update to `2.0.0-beta800` and the issue should be gone (should be available on NuGet soon).
