### ISSUE TITLE
Bug with zoom out in line series chart

### ISSUE THREAD

**Issue by CMOSLouis** [beto-rodriguez/LiveCharts2#960]
Creating a line series chart with zoom mode to both axes, if you want keep your graphics delimitted of 0 to 100 in x axe and 0 to 10 in y axe, its works until apply zoom in e after, zoom out. Make the test using samples with half values of  Y range and you will see your graphics will lose itself.

Bellow following a example with range in X axe of 0 to 100 and Y axe of -2.5 to 2.5, and with half values in relation to Y axe:

![image](https://user-images.githubusercontent.com/126483692/225723933-c670eb99-c20c-40a7-8bf1-a653c8db3f06.png)

 But, when I scroll the mouse in zoom out mode or when I make zoom in following zoom out, happens this:

![image](https://user-images.githubusercontent.com/126483692/225724468-7b597267-d312-4019-888a-6a207e4beaec.png)

So as, you cannot go back to view in the range defined (0 to 100 for X axe and -2.5 to 2.5 in Y axe).

I am using Windwos Forms to create a real application to analyze electrocardiogram. Thus, the user must be allowed to zoom in on both axes, but when zooming out, the graph must be returned until the aforementioned standard limits are established.

Please, help us.

**Comment by CMOSLouis** [comment]
To help, I noticed that the X axe adjust correctly with aplying zoom in and out. It seems that is aplying a zoom with factor 0,05 of range the axe. In this case, so as Y Axe do not following the zoom in this conditions mentioned above, I believe that is missing applying this factor to Y Axe in zoom out, when the Zoom Mode choosed is equal to Both.

**Comment by CMOSLouis** [comment]
Following my code used to resolve the problem when the developer want keep the graphic delimited by range values:

`public void OnXAxePropertyChanged(object sender, PropertyChangedEventArgs e)
        {
            if (EnableRenderXAxe)
            {
                return;
            }

            EnableRenderXAxe = true;

            try
            {
                var xAxe = sender as ICartesianAxis;

                var min = xAxe.MinLimit;
                var max = xAxe.MaxLimit;

                if (e.PropertyName is nameof(xAxe.MinLimit))
                {
                    if (min < MinLimitXAxe)
                    {
                        xAxe.MinLimit = MinLimitXAxe;
                    }
                }

                if (e.PropertyName is nameof(xAxe.MaxLimit))
                {
                    if (MaxLimitXAxe < max)
                    {
                        xAxe.MaxLimit = MaxLimitXAxe;
                    }
                }
            }
            catch (Exception) { }
            finally
            {
                EnableRenderXAxe = false;
            }
        }`

**Comment by beto-rodriguez** [comment]
Actually, now that I am reading this issue again, there is a way to do that.

Just handle the limits, similar to what you did, but I think this is simpler (probably did not worked property in an older version):

````c#
 public ICartesianAxis[] X { get; set; }
 public ICartesianAxis[] Y { get; set; }

 public ViewModel()
 {
     var x = new Axis
     {
         MinLimit = 0,
         MaxLimit = 99
     };
     x.PropertyChanged += OnXAxisChanged;
     X = [x];

     var y = new Axis
     {
         MinLimit = -1500,
         MaxLimit = 1500
     };

     y.PropertyChanged += OnYAxisChanged;
     Y = [y];
 }

 private int _minX = 0;
 private int _maxX = 99;

 private void OnXAxisChanged(object? sender, PropertyChangedEventArgs e)
 {
     if (e.PropertyName == nameof(Axis.MinLimit) && X[0].MinLimit < _minX)
         X[0].MinLimit = _minX;

     if (e.PropertyName == nameof(Axis.MaxLimit) && X[0].MaxLimit > _maxX)
         X[0].MaxLimit = _maxX;
 }

 private int _minY = -1500;
 private int _maxY = 1500;

 private void OnYAxisChanged(object? sender, PropertyChangedEventArgs e)
 {
     if (e.PropertyName == nameof(Axis.MinLimit) && Y[0].MinLimit < _minY)
         Y[0].MinLimit = _minY;

     if (e.PropertyName == nameof(Axis.MaxLimit) && Y[0].MaxLimit > _maxY)
         Y[0].MaxLimit = _maxY;
 }
```

I will close this for now, since this seems to solve the issue.
