### ISSUE TITLE
Chart SaveImage no Margin

### ISSUE THREAD

**Issue by Tremlton** [beto-rodriguez/LiveCharts2#964]
**Describe the bug**
The SaveImage() function does not consider the DrawMargin when rendering the image.

**To Reproduce**
Set a Drawin Margin in Xaml and SaveImage()

**Expected behavior**
How it should look like (With Margin on auto)
![image](https://user-images.githubusercontent.com/85153099/226967171-26ff74d3-b2ca-4001-a2d6-faaa892db085.png)

Here is the a screenshot with Margin(0,0,0,0)
![image](https://user-images.githubusercontent.com/85153099/226966137-01b945b1-4862-4a94-b677-a3ac1a23e2ff.png)
But it still prints it like the first image

**Comment by beto-rodriguez** [comment]
Thanks for the report! this is fixed with the referenced commit and will be included in the next version of the library.
