### ISSUE TITLE
RectangularSection properties lost notify update

### ISSUE THREAD

**Issue by a44281071** [beto-rodriguez/LiveCharts2#970]
**Describe the bug**
update RectangularSection lost update in ui, it didn't work.
Xi
Xj
Yi
Yj
[2.0.0-beta.603] works, but [2.0.0-beta.700] have bug.

**To Reproduce**
``` csharp
// bind section
CartesianChart.Sections.Add(rectSection);

// change xj/yj on button click.
rectSection.Xj = 10;
rectSection.Yj = 10;

// ui no changes.
```

**Expected behavior**
ui will change rectSection display size.
But it doesn't work. nothing happends.

**Platform**
Windows10
WPF target.

**Comment by jspfister-sep** [comment]
I have noticed this bug as well.

**Comment by beto-rodriguez** [comment]
Thanks for the report! probably also related to #958, I quote myself:

> I am not sure if 2.0.0-beta701 had a specific issue, but this seems to be working in the dev branch, please update to 2.0.0-beta800 and the issue should be gone (should be available on NuGet soon).
