### ISSUE TITLE
Can't build example code from Installation guide 

### ISSUE THREAD

**Issue by SergeyKopylov** [beto-rodriguez/LiveCharts2#977]
On the installation guide, under chapter "Configure themes and mappers (Optional)" placed code example with type <City>, which is not written in this example. So, because of this I can't build this example.

[https://lvcharts.com/docs/WPF/2.0.0-beta.700/Overview.Installation#configure-themes-and-mappers-optional
](https://lvcharts.com/docs/WPF/2.0.0-beta.700/Overview.Installation#configure-themes-and-mappers-optional)

![image](https://user-images.githubusercontent.com/35231813/230548219-d5b18a59-fff4-4564-8933-84252981f5ef.png)

**Desktop:**
 - OS: Win10 21H2
 - VisualStudio 2022, .NET6.0

**Comment by calmsboy** [comment]
Try to create the City class

**Comment by SergeyKopylov** [comment]
Yes, I can create the City class, but it would be better to place this City class on the example page "Installation and first chart" for the next users.

**Comment by beto-rodriguez** [comment]
Thanks for feedback @SergeyKopylov, this will be updated in a future version of the docs.
