### ISSUE TITLE
XAxes Binding Issue - WinUI

### ISSUE THREAD

**Issue by wadeamaral** [beto-rodriguez/LiveCharts2#980]
Binding for XAxis on CartesianChart does not work for WinUI Application. I followed the steps based on the documentation but am getting the following error:

`Invalid binding assignment : Cannot directly bind type 'System.Collections.ObjectModel.ObservableCollection(LiveChartsCore.SkiaSharpView.Axis)' to 'System.Collections.Generic.IEnumerable(LiveChartsCore.Kernel.Sketches.ICartesianAxis)'. Use a cast, converter or function binding to change the type`

**Comment by andrette** [comment]
Same here. Using Binding or x:bind gives same result. @wadeamaral Have you found solution?

**Comment by wadeamaral** [comment]
@andrette bind to ICartesianAxis instead of XAxis and it should work.

**Comment by beto-rodriguez** [comment]
This needs better docs, will keep this open to improve that.

**Comment by andrette** [comment]
@wadeamaral thank you for your help!
@beto-rodriguez Just want to thank you for great library. I just started exploring it in depth and I'm impressed. I was looking for flexible charting library for WinUI and here it is.

**Comment by beto-rodriguez** [comment]
I will close this for now, we can track this at #720.
