### ISSUE TITLE
Is not work with avalonia preview 6

### ISSUE THREAD

**Issue by qfmee** [beto-rodriguez/LiveCharts2#981]
Error：
System.TypeInitializationException: The type initializer for 'LiveChartsCore.SkiaSharpView.Avalonia.CartesianChart' threw an exception.
 ---> System.MissingMethodException: Method not found: 'Avalonia.StyledProperty`1<!!1> Avalonia.AvaloniaProperty.Register(System.String, !!1, Boolean, Avalonia.Data.BindingMode, System.Func`2<!!1,Boolean>, System.Func`3<Avalonia.AvaloniaObject,!!1,!!1>, System.Action`2<Avalonia.AvaloniaObject,Boolean>)'.
   at LiveChartsCore.SkiaSharpView.Avalonia.CartesianChart..cctor()
   --- End of inner exception stack trace ---
   at LiveChartsCore.SkiaSharpView.Avalonia.CartesianChart.!XamlIlPopulateTrampoline(CartesianChart )
   at LiveChartsCore.SkiaSharpView.Avalonia.CartesianChart..ctor()

**Comment by DJVova** [comment]
On MAUI NET.8 Preview also not work on Android, on Windows works without problems.

**Comment by BHaesen** [comment]
Doesn't work on Avalonia preview 7 with .NET 7 either.
System.TypeInitializationException: 'The type initializer for 'LiveChartsCore.SkiaSharpView.Avalonia.CartesianChart' threw an exception.'
MissingMethodException: Method not found: 'Avalonia.StyledProperty`1<!!1> Avalonia.AvaloniaProperty.Register(System.String, !!1, Boolean, Avalonia.Data.BindingMode, System.Func`2<!!1,Boolean>, System.Func`3<Avalonia.AvaloniaObject,!!1,!!1>, System.Action`2<Avalonia.AvaloniaObject,Boolean>)'.

**Comment by beto-rodriguez** [comment]
There is already a package for preview 7 on NuGet now!
