### ISSUE TITLE
WPF - diagram is not rendered in the XAML designer

### ISSUE THREAD

**Issue by expirius** [beto-rodriguez/LiveCharts2#993]
**Describe the bug**
I immediately apologize for a possibly stupid question, I have not encountered this before.

Everything works fine when compiling, but the diagram is not rendered in the XAML designer. I rummaged through everything, I didn't find a solution, is it really impossible to circumvent this limitation and you need to run the project every time?

**Screenshots**
![image](https://user-images.githubusercontent.com/76265796/235157364-3fa9b6f8-94f5-44f7-94ce-d3eaa449231b.png)
![image](https://user-images.githubusercontent.com/76265796/235159523-f1caaea0-db66-4b6f-bba9-e001c15164da.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro
 - Version 22h2

**Comment by beto-rodriguez** [comment]
Hi, a designer view is not implemented yet, there are limitation out of the hands of this library that complicate this, in a future version we should add at least an image, so the designer is more useful!

**Comment by TheXtremeKing** [comment]
I've been trying to get the designer working as well for the last couple of hours lol. But it's simply not supported, good to know!

**Comment by tinovasq** [comment]
I've just stumbled upon this as well, are the external factors still too big to handle?

**Comment by beto-rodriguez** [comment]
@tinovasq hot reload is now supported, but designer is not due skia sharp limitations, it just randomly skips the draw in the designer for no apparent reason.


Why wasn't this a priority, because there were no xaml series or axes  in the library, but now they do, check rc-6 release notes for more info.
