### ISSUE TITLE
Custom DataLabel

### ISSUE THREAD

**Issue by Enigmatrix** [beto-rodriguez/LiveCharts2#995]
**Is your feature request related to a problem? Please describe.**
I would like a way to create a per-data point DataLabel that isn't just text. I know there are some ways of doing this e.g. custom LabelGeometry for a Series, but there is not way to pass the point itself to them, only a string.

**Describe the solution you'd like**
The `ILabelGeometry<TDrawingContext>` having a `object DataPoint` property. This is likely fine since the default implementor, `LabelGeometry`, won't use it, but it will allow those wanting to customize their derived LabelGeometry with something more than just a string to base their OnDraw on. They can cast it to the expected type accordingly.

**Describe alternatives you've considered**
The other option would be having this `DataPoint` property be of a generic type (so modify ILabelGeometry<TDrawingContext> to ILabelGeometry<TModel, TDrawingContext>). It might not be so bad, especially since for `PieSeries<TModel, TVisual, TLabel>`, the constraint for `TLabel` can be `where TLabel: ILabelGeometry<TModel, TDrawingContext>, class` instead of the current `where TLabel: ILabelGeometry<TDrawingContext>, class`. Or we can use `ChartPoint` for `DataPoint` as well.

**Additional context**
Trying to create a custom PieChart similar to [LiveCharts v1](https://github.com/Live-Charts/Live-Charts/issues/414)

**Comment by beto-rodriguez** [comment]
There is finally an example to fix this:

https://github.com/beto-rodriguez/LiveCharts2/blob/dev/samples/ViewModelsSamples/Pies/Icons/ViewModel.cs

I will close this for now, since this is actually supported in older versions of the library, this sample will be in the website soon.

Thanks for the report.
