### ISSUE TITLE
Not working with .net 7 winui 3 TemplateStudio

### ISSUE THREAD

**Issue by IM-001** [beto-rodriguez/LiveCharts2#996]
Hi!

  I cannot install livecharts 2 with templateStudio for winui 3.  I tried different livecharts 2 versions and none seem to work.

  Do you have an idea when livecharts 2 will be compatible with .net 7 winui 3 templateStudio please?  It looks amazing and would be perfect for my project.

  Thank you!

**Comment by beto-rodriguez** [comment]
mm strange, there is a sample working in this reposotoru using WindowsSDK (WinUI3), but I am not sure if there are extra steps to make it work with templateStudio.
